import {test,expect} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fixture} from './villegram-fixture.mjs';
// Private phone recordings are supplied locally, never checked into Git or deployed.
const lab=process.env.VILLE_PHONE_AUDIO_DIR;
test('phone recordings: real upload, cleanup, A/B, undo/redo, save, preview and export',async({page},info)=>{
 test.skip(!lab,'Set VILLE_PHONE_AUDIO_DIR to locally prepared phone recordings');test.setTimeout(90000);
 const errors=[];page.on('console',m=>{if(m.type()==='warning')console.log(m.text())});page.on('pageerror',e=>errors.push(e.message));const saved=await fixture(page);await page.locator('#vg-new').click();
 await page.locator('#vg-upload').setInputFiles([lab+'/20261009_114718-browser.mp4',lab+'/20261009_114542-browser.mp4']);await expect(page.locator('.vg-media-strip [data-select]')).toHaveCount(2,{timeout:20000});
 await page.locator('#vg-timeline-open').click();const d=page.locator('.vg-timeline-dialog');await d.locator('[data-tl-feelings]').click();await expect(d.locator('.vg-tl-status')).toContainText('Feelings pronto',{timeout:25000});
 for(let i=0;i<2;i++){await d.locator('[data-tl-original="'+i+'"]').click();await d.locator('[data-tl-cleanup=strong]').click();await d.locator('[data-tl-undo]').click();await expect(d.locator('[data-tl-cleanup=gentle]')).toHaveAttribute('aria-pressed','true');await d.locator('[data-tl-redo]').click();await expect(d.locator('[data-tl-cleanup=strong]')).toHaveAttribute('aria-pressed','true');await d.locator('[data-tl-treatment=false]').click();await d.locator('[data-tl-treatment=true]').click();}
 await d.locator('[data-tl-seek]').fill('0');await d.locator('[data-tl-play]').click();await expect.poll(()=>d.locator('.vg-tl-preview video').first().evaluate(v=>v.currentTime)).toBeGreaterThan(.4);await expect(d.locator('.vg-tl-status')).not.toContainText('indisponível');await d.locator('[data-tl-play]').click();
 await d.screenshot({path:lab+'/interface-'+info.project.name+'.png'});await d.locator('[data-tl-close]').click();await page.locator('#vg-step-next').click();await page.getByText('Descrição e título da publicação',{exact:true}).click();await page.locator('[name=title]').fill('Detalhes do nosso dia');await page.locator('[name=caption]').fill('Sons e pequenos momentos no Ville.');await page.locator('#vg-step-next').click();await page.locator('[name=draft]').click();await expect.poll(()=>saved.length).toBe(1);expect(saved[0].publication.media.every(m=>m.audio_treatment.version===2&&m.audio_treatment.cleanup==='strong')).toBe(true);
 await page.locator('#vg-timeline-open').click();await d.locator('[data-tl-original="1"]').click();await expect(d.locator('[data-tl-cleanup=strong]')).toHaveAttribute('aria-pressed','true');await d.locator('[data-tl-close]').click();await page.locator('#vg-preview').click();await expect(page.locator('#villegram .vg-timeline-player')).toBeVisible();await page.locator('#villegram [data-action=sound]').click();await expect.poll(()=>page.locator('#villegram video').first().evaluate(v=>v.currentTime)).toBeGreaterThan(.3);
 const rendered=await page.evaluate(async()=>{const F=window.VillegramFeelings,media=window.__qaLastPreview.media,items=[];for(const m of media){const c=new AudioContext({sampleRate:48000}),buffer=await c.decodeAudioData(await (await fetch(m.url)).arrayBuffer());const before=await F.measure(buffer),variants={};for(const mode of ['gentle','strong']){const off=new OfflineAudioContext(2,buffer.length,buffer.sampleRate);await F.prepare(off);const source=off.createBufferSource();source.buffer=buffer;const graph=F.graph(off,source,off.destination,{...m,audio_treatment:{...m.audio_treatment,cleanup:mode}});source.start();const out=await off.startRendering(),after=await F.measure(out);variants[mode]={rmsDb:after.rmsDb,peakDb:after.peakDb,pcm:Array.from({length:out.length*2},(_,i)=>out.getChannelData(i%2)[Math.floor(i/2)])};graph.disconnect();}items.push({profile:m.audio_treatment,sampleRate:buffer.sampleRate,before:{rmsDb:before.rmsDb,peakDb:before.peakDb},variants});await c.close();}
 const blob=await window.VillegramTimeline.exportSequence(media);return {items,export:Array.from(new Uint8Array(await blob.arrayBuffer()))};});
 await mkdir(lab,{recursive:true});for(const [i,item] of rendered.items.entries()){for(const [mode,v] of Object.entries(item.variants)){expect(v.peakDb).toBeLessThan(0);expect(v.rmsDb).toBeLessThan(item.before.rmsDb);await writeFile(lab+'/phone-'+(i+1)+'-'+mode+'.f32',Buffer.from(new Float32Array(v.pcm).buffer));delete v.pcm;}}await writeFile(lab+'/analysis-'+info.project.name+'.json',JSON.stringify(rendered.items,null,2));await writeFile(lab+'/feelings-'+info.project.name+'-export.mp4',Buffer.from(rendered.export));expect(errors).toEqual([]);
});
