import {test,expect} from '@playwright/test';import {spawnSync} from 'node:child_process';import {writeFile} from 'node:fs/promises';import {fixture} from './villegram-fixture.mjs';
test.beforeAll(()=>{const r=spawnSync('ffmpeg',['-v','error','-y','-loop','1','-i','assets/01-cantinho-cafe-opt-w640.webp','-f','lavfi','-i','sine=frequency=330:sample_rate=44100','-t','8','-vf','scale=320:480:force_original_aspect_ratio=increase,crop=320:480','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac','-shortest','/tmp/ville-feelings-fixture.mp4']);expect(r.status,r.stderr.toString()).toBe(0)});
test('mixed timeline stays available, edits seconds and audio, reorders and persists the draft',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const saved=await fixture(page,{mixed:true});await page.locator('#vg-timeline-open').click();const d=page.locator('.vg-timeline-dialog');await expect(d).toBeVisible();await expect(d.locator('[data-tl-scene]')).toHaveCount(7);
 await d.locator('[data-tl-field=clip_duration]').fill('2');await d.locator('[data-tl-field=clip_duration]').press('Tab');await d.locator('[data-tl-search]').fill('café');await expect(d.locator('[data-tl-sound]')).toHaveCount(1);await d.locator('[data-tl-sound=coffee]').click();await d.locator('[data-tl-sound-field=offset]').fill('0.5');await d.locator('[data-tl-sound-field=offset]').press('Tab');await d.locator('[data-tl-field=transition]').selectOption('cut');
 await d.locator('[data-tl-scene="1"]').click();await d.locator('[data-tl-field=trim_start]').fill('1');await d.locator('[data-tl-field=trim_start]').press('Tab');await d.locator('[data-tl-field=trim_end]').fill('4');await d.locator('[data-tl-field=trim_end]').press('Tab');await d.locator('[data-tl-field=transition]').selectOption('slide');
 await d.locator('[data-tl-play]').click();await expect.poll(()=>d.locator('.vg-tl-preview video').evaluate(v=>v.currentTime)).toBeGreaterThan(1.2);await expect(d.locator('.vg-tl-preview video')).toHaveJSProperty('muted',false);await d.locator('[data-tl-play]').click();await d.screenshot({path:'/tmp/ville-feelings-'+info.project.name+'-timeline.png'});
 await d.locator('[data-tl-move="1"]').click();await d.locator('[data-tl-close]').click();await page.locator('#vg-step-next').click();await expect(page.locator('#vg-timeline-open')).toBeVisible();await page.locator('#vg-timeline-open').click();await expect(d.locator('[data-tl-field=trim_start]')).toHaveValue('1');await d.locator('[data-tl-close]').click();await page.locator('#vg-step-next').click();await expect(page.locator('#vg-timeline-open')).toBeVisible();await page.locator('[name=draft]').click();await expect.poll(()=>saved.length).toBe(1);
 const media=saved[0].publication.media;expect(media).toHaveLength(7);expect(media[0].clip_duration).toBe(2);expect(media[0].sound.offset).toBe(.5);expect(media[0].transition).toBe('cut');expect(media[2].kind).toBe('video');expect(media[2].trim_start).toBe(1);expect(media[2].trim_end).toBe(4);expect(media[2].transition).toBe('slide');expect(errors).toEqual([]);
});
test('Feelings runs the real local classifier, keeps existing sound, supports undo',async({page},info)=>{
 test.setTimeout(90000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,{mixed:true});await page.locator('#vg-timeline-open').click();const d=page.locator('.vg-timeline-dialog');await d.locator('[data-tl-sound=rain]').click();await d.locator('[data-tl-feelings]').click();await expect(d.locator('.vg-tl-status')).toContainText('Feelings pronto',{timeout:60000});await expect(d.locator('[data-tl-undo]')).toBeVisible();await expect(d.locator('[data-tl-sound=rain]')).toHaveAttribute('aria-pressed','true');expect(await page.evaluate(()=>window.tf.memory().numTensors)).toBeLessThan(200);
 await d.screenshot({path:'/tmp/ville-feelings-'+info.project.name+'-automatic.png'});await d.locator('[data-tl-undo]').click();await expect(d.locator('.vg-tl-status')).toHaveText('Montagem automática desfeita.');await expect(d.locator('[data-tl-sound=rain]')).toHaveAttribute('aria-pressed','true');expect(errors).toEqual([]);
});
test('public mixed preview changes scenes, pauses sound and exports a playable MP4 with both media types',async({page},info)=>{
 test.setTimeout(90000);const saved=await fixture(page,{mixed:true});await page.locator('#vg-timeline-open').click();const d=page.locator('.vg-timeline-dialog');for(let i=0;i<7;i++){await d.locator('[data-tl-scene="'+i+'"]').click();if(i===1){await d.locator('[data-tl-field=trim_end]').fill('1');await d.locator('[data-tl-field=trim_end]').press('Tab')}else{await d.locator('[data-tl-field=clip_duration]').fill('1');await d.locator('[data-tl-field=clip_duration]').press('Tab')}}await d.locator('[data-tl-scene="0"]').click();await d.locator('[data-tl-sound=coffee]').click();await d.locator('[data-tl-close]').click();await page.locator('#vg-step-next').click();await page.locator('#vg-step-next').click();await page.locator('#vg-preview').click();await expect(page.locator('#villegram .vg-timeline-player')).toBeVisible();await expect(page.locator('#villegram .vg-sequence-scene')).toHaveCount(7);await page.locator('#villegram [data-action=sound]').click();await expect.poll(()=>page.locator('#villegram .vg-sequence-scene.is-visible').evaluate(e=>e.querySelector('video')!==null)).toBe(true);await page.locator('#villegram [data-action=pause]').click();const at=await page.locator('#villegram video').evaluate(v=>v.currentTime);await page.waitForTimeout(300);expect(await page.locator('#villegram video').evaluate(v=>v.currentTime)).toBeCloseTo(at,1);
 const result=await page.evaluate(async()=>{const media=window.__qaLastPreview.media;const blob=await window.VillegramTimeline.exportSequence(media,{guest:true});const url=URL.createObjectURL(blob),v=document.createElement('video');v.muted=true;v.src=url;await new Promise((resolve,reject)=>{v.onloadedmetadata=resolve;v.onerror=reject});const duration=v.duration;v.src='';URL.revokeObjectURL(url);return {type:blob.type,bytes:blob.size,duration,data:Array.from(new Uint8Array(await blob.arrayBuffer()))}});expect(result.type).toBe('video/mp4');expect(result.bytes).toBeGreaterThan(5000);expect(result.duration).toBeGreaterThanOrEqual(6.7);expect(result.duration).toBeLessThan(8.5);expect(saved).toHaveLength(0);const artifact='/tmp/ville-feelings-'+info.project.name+'-export.mp4';await writeFile(artifact,Buffer.from(result.data));const probe=spawnSync('ffprobe',['-v','error','-show_entries','stream=codec_name,codec_type','-of','json',artifact]);expect(probe.status,probe.stderr.toString()).toBe(0);const streams=JSON.parse(probe.stdout.toString()).streams;expect(streams.some(s=>s.codec_type==='video')).toBe(true);expect(streams.some(s=>s.codec_type==='audio')).toBe(true);for(const at of [0,1.2]){const audio=spawnSync('ffmpeg',['-v','info','-ss',String(at),'-t','0.6','-i',artifact,'-vn','-af','volumedetect','-f','null','-']);expect(audio.status,audio.stderr.toString()).toBe(0);const level=Number(audio.stderr.toString().match(/mean_volume: ([\d.-]+) dB/)?.[1]);expect(level).toBeGreaterThan(-60);}
});

test('failed visual analysis preserves the manual timeline and chosen sound',async({page})=>{
 const saved=await fixture(page);await page.route('**/assets/feelings/model.json',r=>r.abort());await page.locator('#vg-timeline-open').click();const d=page.locator('.vg-timeline-dialog');await d.locator('[data-tl-field=clip_duration]').fill('2');await d.locator('[data-tl-field=clip_duration]').press('Tab');await d.locator('[data-tl-sound=coffee]').click();await d.locator('[data-tl-feelings]').click();await expect(d.locator('.vg-tl-status')).toContainText('A montagem foi preservada',{timeout:30000});await expect(d.locator('[data-tl-field=clip_duration]')).toHaveValue('2');await expect(d.locator('[data-tl-sound=coffee]')).toHaveAttribute('aria-pressed','true');await expect(d.locator('[data-tl-undo]')).toBeHidden();await d.locator('[data-tl-close]').click();await page.locator('#vg-step-next').click();await page.locator('#vg-step-next').click();await page.locator('[name=draft]').click();await expect.poll(()=>saved.length).toBe(1);expect(saved[0].publication.media[0].clip_duration).toBe(2);expect(saved[0].publication.media[0].sound.id).toBe('coffee');expect(saved[0].publication.media[0].mode).toBeUndefined();
});
