import {test,expect} from '@playwright/test';import {fixture} from './villegram-fixture.mjs';
test('upload eight mixed files, long hold reorder, zoom, scroll, cancel and resume',async({page},info)=>{
 test.setTimeout(60000);const saved=await fixture(page);await page.locator('#vg-new').click();await page.locator('#vg-upload').setInputFiles(['/tmp/ville-feelings-fixture.mp4','/tmp/ville-feelings-fixture.mp4',...Array(6).fill('assets/01-cantinho-cafe-opt-w640.webp')]);await expect(page.locator('.vg-media-strip [data-select]')).toHaveCount(8,{timeout:25000});expect(saved.uploads.size).toBe(10);
 await expect(page.locator('.vg-feelings-quick')).toBeVisible();await page.locator('#vg-timeline-open').click();const d=page.locator('.vg-timeline-dialog');await d.locator('[data-tl-scene="0"]').click();await d.locator('[data-tl-zoom-out]').click();const width=await d.locator('[data-tl-clip="0"]').evaluate(e=>e.getBoundingClientRect().width);await d.locator('[data-tl-zoom-in]').click();expect(await d.locator('[data-tl-clip="0"]').evaluate(e=>e.getBoundingClientRect().width)).toBeGreaterThan(width);
 const c=d.locator('[data-tl-scene="0"]');await c.scrollIntoViewIfNeeded();const r=await c.boundingBox();await page.mouse.move(Math.max(25,r.x+20),r.y+20);await page.mouse.down();await page.waitForTimeout(450);await expect(d.locator('.dragging')).toBeVisible();await page.mouse.move((await d.locator('.vg-tl-rail').boundingBox()).x+(await d.locator('.vg-tl-rail').boundingBox()).width-20,r.y+20,{steps:8});await page.waitForTimeout(450);await page.mouse.up();await page.waitForTimeout(400);await expect(d.locator('[data-tl-undo]')).toBeEnabled();await d.locator('[data-tl-undo]').click();
 await d.locator('[data-tl-seek]').fill('20');await expect(d.locator('[data-tl-time]')).toContainText('0:20.0');await d.locator('[data-tl-scene="7"]').click();await expect(d.locator('[data-tl-scene="7"]')).toHaveAttribute('aria-pressed','true');
 // Freeze only analysis, not the player's media elements. Cancel before any decisions commit.
 await page.evaluate(()=>{window.__oldCompose=window.VillegramFeelings.compose;window.VillegramFeelings.compose=(media,{signal,onProgress})=>new Promise((resolve,reject)=>{onProgress(0,8,.5);signal.addEventListener('abort',()=>reject(new DOMException('Cancelado','AbortError')),{once:true});});});
 await d.locator('[data-tl-feelings]').click();await expect(d.locator('progress')).toBeVisible();await d.locator('[data-tl-cancel]').click();await expect(d.locator('.vg-tl-status')).toContainText('cancelado');await page.evaluate(()=>window.VillegramFeelings.compose=window.__oldCompose);await d.locator('[data-tl-feelings]').click();await expect(d.locator('.vg-tl-status')).toContainText('Feelings pronto',{timeout:20000});await expect(d.locator('.vg-tl-preview')).toBeVisible();
});
test('natural sounds and very different levels use the same offline graph without clipping or noise boost',async({page})=>{
 await fixture(page);const report=await page.evaluate(async()=>{const F=window.VillegramFeelings,results=[];for(const name of ['rain','fire','pour']){const context=new AudioContext(),data=await (await fetch('assets/feelings/'+name+'.mp3')).arrayBuffer(),buffer=await context.decodeAudioData(data);const a=await F.measure(buffer),profile=F.profile(a),off=new OfflineAudioContext(buffer.numberOfChannels,buffer.length,buffer.sampleRate),source=off.createBufferSource();source.buffer=buffer;await F.prepare(off);const graph=F.graph(off,source,off.destination,{audio_treatment:profile});graph.volume(1);source.start();const out=await off.startRendering(),after=await F.measure(out);results.push({name,profile,peak:after.peakDb,rmsBefore:a.rmsDb,rmsAfter:after.rmsDb});await context.close();}return results;});for(const r of report){expect(r.peak,r.name).toBeLessThan(0);expect(r.rmsAfter-r.rmsBefore,r.name).toBeLessThanOrEqual(Math.max(0,r.profile.gain_db)+.3);expect(r.profile.status).toBe('ready');}console.log(JSON.stringify(report.map(({profile,...r})=>({...r,gain:profile.gain_db,hum:profile.hum_hz}))));
});
test('touch pinch enlarges the timeline; preview allows vertical page scrolling',async({page},info)=>{
 if(info.project.name!=='mobile')test.skip();await fixture(page,{mixed:true,eight:true});const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:2});
 const preview=page.locator('#vg-composer-screen');await preview.scrollIntoViewIfNeeded();const box=await preview.boundingBox(),before=await page.evaluate(()=>scrollY);const x=Math.max(30,box.x+box.width*.55),y=Math.min(650,Math.max(280,box.y+box.height*.6));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x,y}]});for(let i=1;i<=5;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x,y:y-i*35}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>page.evaluate(()=>scrollY)).not.toBe(before);
 await page.locator('#vg-timeline-open').click();const d=page.locator('.vg-timeline-dialog');await d.locator('.vg-tl-rail').scrollIntoViewIfNeeded();const rail=await d.locator('.vg-tl-rail').boundingBox(),height=rail.y+65;const width=await d.locator('[data-tl-clip="0"]').evaluate(e=>e.getBoundingClientRect().width);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:200,y:height},{id:2,x:280,y:height}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{id:1,x:170,y:height},{id:2,x:310,y:height}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(()=>d.locator('[data-tl-clip="0"]').evaluate(e=>e.getBoundingClientRect().width)).toBeGreaterThan(width*1.2);
});
test('export cancellation rejects a partial recording',async({page})=>{
 await fixture(page,{mixed:true});const result=await page.evaluate(async()=>{const controller=new AbortController(),m={kind:'photo',url:'assets/01-cantinho-cafe-opt-w640.webp',clip_duration:10,transition:'fade'};setTimeout(()=>controller.abort(),800);try{await window.VillegramTimeline.exportSequence([m],{signal:controller.signal});return 'unexpected_success'}catch(e){return e.name}});expect(result).toBe('AbortError');
});

test('blocked cleanup keeps preview original and rejects export instead of changing its sound',async({page})=>{
 await fixture(page,{mixed:true});const result=await page.evaluate(async()=>{const F=window.VillegramFeelings,ctx=new AudioContext(),buffer=await ctx.decodeAudioData(await(await fetch('/qa-video.mp4')).arrayBuffer()),profile=F.profile(await F.measure(buffer));await ctx.close();const media=[{kind:'video',url:'/qa-video.mp4',duration:8,audio_treatment:profile}],host=document.createElement('div'),messages=[];document.body.append(host);F.prepare=async()=>{throw Error('module_blocked')};const player=window.VillegramTimeline.player({host,media,onError:s=>messages.push(s)});await player.setSound(true);const muted=player.elements[0].muted;player.destroy();host.remove();try{await window.VillegramTimeline.exportSequence(media);return {messages,muted,exported:true}}catch(e){return {messages,muted,error:e.message}}});expect(result.muted).toBe(false);expect(result.messages[0]).toContain('original');expect(result.error).toBe('module_blocked');expect(result.exported).toBeUndefined();
});
