import {test,expect} from '@playwright/test';
import {spawnSync} from 'node:child_process';
import {writeFile} from 'node:fs/promises';
import {fixture} from './villegram-fixture.mjs';

const open=async page=>{await page.locator('#vg-timeline-open').click();const d=page.locator('.vg-timeline-dialog');await expect(d).toBeVisible();return d;};
async function drag(page,locator,delta){await locator.scrollIntoViewIfNeeded();await page.waitForTimeout(150);const r=await locator.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x+r.width/2+delta,r.y+r.height/2,{steps:10});await page.mouse.up();await page.waitForTimeout(400);}
test('eight-media visual timeline: trim, reorder, undo redo, original treatment, persistence and reopen',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const saved=await fixture(page,{mixed:true,eight:true});const d=await open(page);await expect(d.locator('[data-tl-scene]')).toHaveCount(8);
 await drag(page,d.locator('[data-tl-handle=end][data-kind=scene]'),-90);
 await expect(d.locator('[data-tl-undo]')).toBeEnabled();await d.locator('[data-tl-undo]').click();await d.locator('[data-tl-redo]').click();
 await d.locator('[data-tl-scene="1"]').click();await drag(page,d.locator('[data-tl-handle=start][data-kind=scene]'),36);
 await d.locator('[data-tl-feelings]').click();await expect(d.locator('.vg-tl-status')).toContainText('Feelings pronto',{timeout:30000});await d.locator('[data-tl-original="1"]').click();await expect(d.locator('[data-tl-treatment=true]')).toBeVisible();await d.locator('[data-tl-treatment=false]').click();await d.locator('[data-tl-treatment=true]').click();
 await d.locator('[data-tl-play]').click();await expect.poll(()=>d.locator('.vg-tl-preview video').evaluate(v=>v.currentTime)).toBeGreaterThan(1.2);await d.locator('[data-tl-play]').click();
 await d.locator('[data-tl-transition="1"]').click();await d.locator('[data-tl-transition-value=cut]').click();await d.locator('[data-tl-scene="1"]').click();await d.locator('[data-tl-move="1"]').click();
 await d.locator('[data-tl-undo]').click();await d.locator('[data-tl-redo]').click();
 await d.screenshot({path:'/tmp/feelings2-'+info.project.name+'.png'});await d.locator('[data-tl-close]').click();await page.locator('#vg-step-next').click();await expect(page.locator('#vg-timeline-open')).toBeVisible();await page.locator('#vg-step-next').click();await expect(page.locator('#vg-timeline-open')).toBeVisible();await page.locator('[name=draft]').click();await expect.poll(()=>saved.length).toBe(1);
 const media=saved[0].publication.media;expect(media).toHaveLength(8);expect(media[2].kind).toBe('video');expect(media[2].trim_start).toBeGreaterThan(.7);expect(media[2].audio_treatment.version).toBe(1);expect(media[2].transition).toBe('cut');expect(media[2].sound).toBeUndefined();
 await page.locator('#vg-timeline-open').click();await d.locator('[data-tl-original="2"]').click();await expect(d.locator('[data-tl-treatment=true]')).toHaveAttribute('aria-pressed','true');expect(errors).toEqual([]);
});
test('audio option waveform, positioning, transitions, feed and playable MP4 export',async({page},info)=>{
 test.setTimeout(90000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await fixture(page,{mixed:true});const d=await open(page);
 // Shorten through accessible handles; the same mutation path serves keyboard and pointer.
 for(let i=0;i<7;i++){await d.locator('[data-tl-scene="'+i+'"]').click();const h=d.locator('[data-tl-handle=end][data-kind=scene]');await h.focus();for(let j=0;j<(i===1?70:55);j++)await page.keyboard.press('ArrowLeft');}
 await d.locator('[data-tl-scene="0"]').click();await d.locator('[data-tl-library]').click();await d.locator('[data-tl-search]').fill('café');await d.locator('[data-tl-sound=coffee]').click();await expect(d.locator('.vg-tl-added .vg-tl-wave')).toBeVisible();await d.locator('[data-tl-close]').click();await page.locator('#vg-step-next').click();await page.locator('#vg-step-next').click();await page.locator('#vg-preview').click();await expect(page.locator('#villegram .vg-timeline-player')).toBeVisible();await page.locator('#villegram [data-action=sound]').click();await expect.poll(()=>page.locator('#villegram .vg-sequence-scene.is-visible').evaluate(e=>e.querySelector('video')!==null)).toBe(true);await page.locator('#villegram [data-action=pause]').click();const at=await page.locator('#villegram video').evaluate(v=>v.currentTime);await page.waitForTimeout(300);expect(await page.locator('#villegram video').evaluate(v=>v.currentTime)).toBeCloseTo(at,1);
 const result=await page.evaluate(async()=>{const blob=await window.VillegramTimeline.exportSequence(window.__qaLastPreview.media);return {type:blob.type,data:Array.from(new Uint8Array(await blob.arrayBuffer()))}});expect(result.type).toBe('video/mp4');const artifact='/tmp/feelings2-'+info.project.name+'-export.mp4';await writeFile(artifact,Buffer.from(result.data));const probe=spawnSync('ffprobe',['-v','error','-show_entries','format=duration:stream=codec_name,codec_type','-of','json',artifact]);expect(probe.status).toBe(0);const meta=JSON.parse(probe.stdout);expect(meta.streams.some(s=>s.codec_type==='audio')).toBe(true);expect(Number(meta.format.duration)).toBeGreaterThan(6.5);expect(Number(meta.format.duration)).toBeLessThan(9);expect(errors).toEqual([]);
});
test('cancellation and failed audio leave originals intact; no heavy model download',async({page})=>{
 const requests=[];page.on('request',r=>requests.push(r.url()));const saved=await fixture(page,{mixed:true});await page.route('**/qa-video.mp4',r=>r.abort());const d=await open(page);await d.locator('[data-tl-feelings]').click();await expect(d.locator('.vg-tl-status')).toContainText('original preservado',{timeout:30000});expect(requests.some(u=>/tf.min|model.json|weights.bin/.test(u))).toBe(false);
 await d.locator('[data-tl-close]').click();await page.locator('#vg-step-next').click();await page.locator('#vg-step-next').click();await page.locator('[name=draft]').click();await expect.poll(()=>saved.length).toBe(1);expect(saved[0].publication.media[1].audio_treatment).toBeUndefined();
});
