(()=>{
const C=window.CHALEZINHO_CONFIG;
const sb=window.supabase.createClient(C.supabaseUrl,C.supabaseKey);
window.ChalezinhoAuth={sb};
const qs=new URLSearchParams(location.search),mode=qs.get("mode")||"login",ret=qs.get("return")||"conta.html";
const by=id=>document.getElementById(id), msg=(t,ok=false)=>{const e=by("auth-message");if(e){e.textContent=t;e.className="auth-message "+(ok?"ok":"error")}};
const panes={login:by("pane-login"),signup:by("pane-signup"),recover:by("pane-recover"),reset:by("pane-reset")};
function show(name){Object.values(panes).forEach(x=>x&&(x.hidden=true));if(panes[name])panes[name].hidden=false;document.querySelectorAll("[data-auth-mode]").forEach(b=>b.classList.toggle("active",b.dataset.authMode===name))}
document.querySelectorAll("[data-auth-mode]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.authMode)));
show(mode);
by("login-form")?.addEventListener("submit",async e=>{e.preventDefault();msg("Entrando...");
 const {error}=await sb.auth.signInWithPassword({email:by("login-email").value.trim(),password:by("login-password").value});
 if(error)return msg(error.message);location.href=ret;
});
by("signup-form")?.addEventListener("submit",async e=>{e.preventDefault();msg("Criando sua conta...");
 const email=by("signup-email").value.trim(),password=by("signup-password").value,name=by("signup-name").value.trim(),phone=by("signup-phone").value.trim();
 if(password.length<8)return msg("Use uma senha com pelo menos 8 caracteres.");
 const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name,phone},emailRedirectTo:location.origin+"/auth.html?mode=login"}});
 if(error)return msg(error.message);
 msg(data.session?"Conta criada.":"Conta criada. Confira seu e-mail para confirmar antes de entrar.",true);
});
by("recover-form")?.addEventListener("submit",async e=>{e.preventDefault();msg("Enviando instruções...");
 const {error}=await sb.auth.resetPasswordForEmail(by("recover-email").value.trim(),{redirectTo:location.origin+"/auth.html?mode=reset"});
 if(error)return msg(error.message);msg("Se o e-mail estiver cadastrado, enviaremos o link de recuperação.",true);
});
by("reset-form")?.addEventListener("submit",async e=>{e.preventDefault();const p=by("reset-password").value;if(p.length<8)return msg("Use pelo menos 8 caracteres.");
 const {error}=await sb.auth.updateUser({password:p});if(error)return msg(error.message);msg("Senha alterada. Você já pode continuar.",true);setTimeout(()=>location.href=ret,800);
});
sb.auth.getSession().then(({data})=>{if(data.session&&mode==="login")location.href=ret});
})();