(()=>{
const C=window.CHALEZINHO_CONFIG,sb=window.supabase.createClient(C.supabaseUrl,C.supabaseKey),DEV_BASE="https://chalezinho-ville-git-desenvolvimento-roldneicosta-4140.vercel.app";
window.ChalezinhoAuth={sb};
let anonymousId="";
try{anonymousId=localStorage.getItem("chalezinho_anon_id")||crypto.randomUUID();localStorage.setItem("chalezinho_anon_id",anonymousId)}
catch{anonymousId=crypto.randomUUID()}
function track(event_name,metadata={}){fetch(C.bookingEngine+"?action=track",{method:"POST",headers:{"Content-Type":"application/json","X-Chalezinho-Env":"development"},body:JSON.stringify({action:"track",event_name,anonymous_id:anonymousId,metadata})}).catch(()=>{})}
const qs=new URLSearchParams(location.search),mode=qs.get("mode")||"login",ret=qs.get("return")||"conta.html";
const safeReturn=v=>{try{const u=new URL(v,location.origin);return u.origin===location.origin?(u.pathname+u.search+u.hash).replace(/^\//,""):"conta.html"}catch{return "conta.html"}};
const returnTarget=safeReturn(ret),by=id=>document.getElementById(id),msg=(t,ok=false)=>{const e=by("auth-message");if(e){e.textContent=t;e.className="auth-message "+(ok?"ok":"error")}};
const authMessage=(error,context="")=>{const code=String(error?.code||"").toLowerCase(),raw=String(error?.message||"").toLowerCase();if(code.includes("invalid_credentials")||raw.includes("invalid login credentials"))return "E-mail ou senha incorretos.";if(code.includes("email_not_confirmed")||raw.includes("email not confirmed"))return "Confirme seu e-mail antes de entrar.";if(code.includes("user_already_exists")||raw.includes("already registered"))return "Este e-mail já possui uma conta. Entre ou recupere sua senha.";if(code.includes("over_email_send_rate_limit")||raw.includes("rate limit"))return "Muitas tentativas em pouco tempo. Aguarde alguns minutos e tente novamente.";if(code.includes("weak_password"))return "Não foi possível usar essa senha. Escolha outra com pelo menos 8 caracteres.";return context==="recover"?"Não foi possível enviar as instruções agora. Tente novamente.":"Não foi possível concluir esta ação agora. Tente novamente.";};
const panes={login:by("pane-login"),signup:by("pane-signup"),recover:by("pane-recover"),reset:by("pane-reset"),identify:by("pane-identify")};
function show(name){Object.values(panes).forEach(x=>x&&(x.hidden=true));if(panes[name])panes[name].hidden=false;document.querySelectorAll("[data-auth-mode]").forEach(b=>b.classList.toggle("active",b.dataset.authMode===name))}
document.querySelectorAll("[data-auth-mode]").forEach(b=>b.addEventListener("click",()=>show(b.dataset.authMode)));show(mode);

by("pane-login")?.addEventListener("submit",async e=>{e.preventDefault();msg("Entrando…");track("login_started",{source:"auth_page"});const {error}=await sb.auth.signInWithPassword({email:by("login-email").value.trim(),password:by("login-password").value});if(error)return msg(authMessage(error,"login"));location.href=returnTarget});
const digits=v=>String(v||"").replace(/\D/g,"");
function validCpf(v){const s=digits(v);if(s.length!==11||/^(\d)\1{10}$/.test(s))return false;for(let n=9;n<11;n++){const sum=[...s.slice(0,n)].reduce((a,x,i)=>a+Number(x)*(n+1-i),0),check=(sum*10)%11;if(Number(s[n])!==(check===10?0:check))return false}return true}
by("signup-document-type")?.addEventListener("change",()=>{const passport=by("signup-document-type").value==="passport";by("signup-country-label").hidden=!passport;by("signup-country").required=passport;by("signup-document-number").inputMode=passport?"text":"numeric";by("signup-document-number").placeholder=passport?"Número do passaporte":"000.000.000-00"});
by("identity-type")?.addEventListener("change",()=>{const passport=by("identity-type").value==="passport";by("identity-country-label").hidden=!passport;by("identity-country").required=passport;by("identity-number").inputMode=passport?"text":"numeric";by("identity-number").placeholder=passport?"Número do passaporte":"000.000.000-00"});
by("pane-identify")?.addEventListener("submit",async e=>{e.preventDefault();const {data:{session}}=await sb.auth.getSession();if(!session)return msg("Entre na sua conta antes de salvar o documento.");const documentType=by("identity-type").value,documentNumber=documentType==="cpf"?digits(by("identity-number").value):by("identity-number").value.trim().toUpperCase().replace(/[ -]/g,""),issuingCountry=documentType==="cpf"?"BR":by("identity-country").value.trim().toUpperCase();if(documentType==="cpf"&&!validCpf(documentNumber))return msg("Confira os dígitos do CPF.");if(documentType==="passport"&&(!/^[A-Z0-9]{5,20}$/.test(documentNumber)||!/^[A-Z]{2}$/.test(issuingCountry)))return msg("Confira passaporte e país emissor.");msg("Salvando sua identificação…");try{const r=await fetch(C.bookingEngine+"?action=complete_identity",{method:"POST",headers:{"Content-Type":"application/json","X-Chalezinho-Env":"development",Authorization:"Bearer "+session.access_token},body:JSON.stringify({document_type:documentType,document_number:documentNumber,issuing_country:issuingCountry})});const d=await r.json();if(!r.ok){msg(d.error==="identity_conflict"?"Este documento já está vinculado a outra conta. Entre na conta original ou fale com o atendimento.":"Não foi possível salvar a identificação. Verifique os dados e tente novamente.");return}location.href=returnTarget}catch{msg("Não foi possível salvar agora. Tente novamente.")}});
by("pane-signup")?.addEventListener("submit",async e=>{e.preventDefault();msg("Criando sua conta…");const email=by("signup-email").value.trim(),password=by("signup-password").value,name=by("signup-name").value.trim(),phone=by("signup-phone").value.trim();if(password.length<8)return msg("Use uma senha com pelo menos 8 caracteres.");
 const documentType=by("signup-document-type").value,documentNumber=(documentType==="cpf"?digits(by("signup-document-number").value):by("signup-document-number").value.trim().toUpperCase().replace(/[ -]/g,"")),issuingCountry=documentType==="passport"?by("signup-country").value.trim().toUpperCase():"BR";
 if(documentType==="cpf"&&!validCpf(documentNumber))return msg("Confira os dígitos do CPF.");
 if(documentType==="passport"&&(!/^[A-Z0-9]{5,20}$/.test(documentNumber)||!/^[A-Z]{2}$/.test(issuingCountry)))return msg("Confira o número do passaporte e o código de duas letras do país emissor.");
 const callback=DEV_BASE+"/auth-callback.html?next="+encodeURIComponent(returnTarget);
 const {data,error}=await sb.auth.signUp({email,password,options:{data:{full_name:name,phone,document_type:documentType,document_number:documentNumber,issuing_country:issuingCountry},emailRedirectTo:callback}});
 if(error)return msg(authMessage(error,"signup"));track("account_signup_submitted",{source:"auth_page",email_confirmation_required:!data.session});msg(data.session?"Conta criada.":"Se este e-mail ainda não estiver cadastrado, enviaremos um link de confirmação. Se você já tem conta, entre ou recupere a senha.",true);
});
by("pane-recover")?.addEventListener("submit",async e=>{e.preventDefault();msg("Enviando instruções…");const callback=DEV_BASE+"/auth-callback.html?next="+encodeURIComponent("auth.html?mode=reset&return="+encodeURIComponent(returnTarget));const {error}=await sb.auth.resetPasswordForEmail(by("recover-email").value.trim(),{redirectTo:callback});if(error)return msg(authMessage(error,"recover"));msg("Se o e-mail estiver cadastrado, enviaremos o link de recuperação.",true)});
by("pane-reset")?.addEventListener("submit",async e=>{e.preventDefault();const p=by("reset-password").value;if(p.length<8)return msg("Use pelo menos 8 caracteres.");const {error}=await sb.auth.updateUser({password:p});if(error)return msg(authMessage(error,"reset"));msg("Senha alterada.",true);setTimeout(()=>location.href=returnTarget,700)});
sb.auth.getSession().then(({data})=>{if(data.session&&mode==="login")location.href=returnTarget;if(!data.session&&mode==="identify")show("login")});
})();
