(()=>{
 const C=window.CHALEZINHO_CONFIG,sb=window.supabase.createClient(C.supabaseUrl,C.supabaseKey,C.authOptions),$=s=>document.querySelector(s),{esc,components,label,issues}=window.VilleOffers;
 let replacements=[],vg={photos:[],audio:null},session,data,properties,current,photos=[],draftId=crypto.randomUUID();
 async function api(body){const r=await fetch(C.bookingEngine,{method:'POST',headers:{'Content-Type':'application/json','X-Chalezinho-Env':'development',Authorization:'Bearer '+session.access_token},body:JSON.stringify({action:'stay_offer_action',...body})});const d=await r.json();if(!r.ok||!d.ok)throw Object.assign(Error(d.error),{data:d});return d}
 async function load(id=null){data=await api({operation:'list'});const r=await fetch(C.bookingEngine+'?action=property_media');properties=(await r.json()).properties;$('#offer-picker').innerHTML='<option value="">Nova estadia completa</option>'+data.offers.map(o=>`<option value="${o.id}">${esc(o.name)} · ${o.status==='active'?'Ativa':'Pausada'}</option>`).join('');select(id)}
 function select(id){current=data.offers.find(o=>o.id===id)||null;draftId=current?.id||crypto.randomUUID();photos=[...(current?.media||[])];$('#offer-picker').value=current?.id||'';
 for(const [key,field,fallback] of [['name','name',''],['description','description',''],['status','status','paused'],['min','min_nights',1],['max','max_nights',''],['start','start_date',''],['end','end_date','']])$('#offer-'+key).value=current?.[field]??fallback;
 const merchandising=current?.showcase||{};$('#vg-celebrations').checked=merchandising.celebrations===true;$('#vg-celebration-discount').checked=merchandising.celebration_discount===true;$('#vg-holidays').value=(merchandising.holidays||[]).join('\n');$('#offer-showcase-enabled').checked=merchandising.enabled===true;const durations=(merchandising.nights||[2,3]).join(',');const menu=$('#offer-showcase-nights');if(![...menu.options].some(o=>o.value===durations))menu.add(new Option(durations.split(',').join(' e ')+' noites',durations));menu.value=durations;$('#offer-showcase-horizon').value=merchandising.horizon_days||60;
 $('#offer-discount').value=(current?.discount_bps??500)/100;$('#offer-discount-enabled').checked=current?.discount_enabled!==false;
 $('#offer-properties').innerHTML=properties.map(p=>`<label><input type="checkbox" value="${p.id}" ${current?.property_ids.includes(p.id)?'checked':''}> ${esc(p.name)}</label>`).join('');
 $('#offer-packages').innerHTML=data.products.filter(p=>p.status!=='archived').map(p=>`<label><input type="checkbox" value="${p.id}" ${current?.product_ids.includes(p.id)?'checked':''}> <span>${esc(p.name)} · ${(p.price_cents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}${p.status!=='active'?' · pausado':''}</span></label>`).join('');
 replacements=[];vg=structuredClone(current?.villegram||{photos:[],audio:null});vg.photos ||= [];$('#vg-title').value=vg.title||'';$('#vg-motion').value=vg.motion||'gentle';$('#vg-audio-origin').value=vg.audio?.origin||'';$('#vg-audio-license').value=vg.audio?.license||'';$('#vg-audio-status').textContent=vg.audio?'Trilha cadastrada.':'Síntese original, opcional.';$('#vg-property').innerHTML=properties.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');renderVG();
 $('#offer-message').textContent='';$('#offer-preview').hidden=true;renderPhotos();
 }
 function values(){return {id:current?.id,updated_at:current?.updated_at,name:$('#offer-name').value.trim(),description:$('#offer-description').value.trim(),status:$('#offer-status').value,property_ids:[...$('#offer-properties').querySelectorAll('input:checked')].map(x=>Number(x.value)),product_ids:[...$('#offer-packages').querySelectorAll('input:checked')].map(x=>x.value),discount_bps:Math.round(Number($('#offer-discount').value)*100),discount_enabled:$('#offer-discount-enabled').checked,min_nights:Number($('#offer-min').value),max_nights:$('#offer-max').value?Number($('#offer-max').value):null,start_date:$('#offer-start').value||null,end_date:$('#offer-end').value||null,media:photos,media_replacements:replacements,villegram:{...vg,title:$('#vg-title').value,motion:$('#vg-motion').value,audio:vg.audio?{...vg.audio,origin:$('#vg-audio-origin').value,license:$('#vg-audio-license').value}:null},showcase:{celebrations:$('#vg-celebrations').checked,celebration_discount:$('#vg-celebration-discount').checked,holidays:$('#vg-holidays').value.split(/\s+/).filter(Boolean),enabled:$('#offer-showcase-enabled').checked,nights:$('#offer-showcase-nights').value.split(',').map(Number),horizon_days:Number($('#offer-showcase-horizon').value)}}}
 async function preview(){const d=await api({...values(),operation:'preview'}),box=$('#offer-preview');box.hidden=false;box.innerHTML=`<h2>${esc(d.offer.name)}</h2><p>${esc(d.offer.description)}</p><ul>${d.packages.flatMap(components).map(c=>`<li>${esc(label(c))}</li>`).join('')}</ul><p>${d.offer.discount_enabled?d.offer.discount_bps/100+'% de desconto':'Desconto desativado'} · ${d.offer.min_nights} noite(s) ou mais${d.offer.max_nights?' · até '+d.offer.max_nights+' noites':''}</p><p>${d.offer.showcase.enabled?'Vitrine ativa: '+d.offer.showcase.nights.join(' e ')+' noites nos próximos '+d.offer.showcase.horizon_days+' dias. Somente noites de segunda a quinta disponíveis.':'Vitrine de dias de semana desativada.'}</p><p>O preço será consultado para as datas escolhidas.</p>${d.issues.length?`<p class="offer-field-error">${d.issues.map(x=>esc(issues[x]||x)).join('. ')}.</p>`:'<p>Configuração pronta. Datas, antecedência e capacidade serão conferidas na reserva.</p>'}`;const button=document.createElement('button');button.type='button';button.textContent='Assistir à prévia do Villegram';button.onclick=async()=>{const prop=properties.find(p=>d.offer.property_ids.includes(p.id));const card={preview:true,offer_id:d.offer.id||'preview',property_id:prop.id,property_code:prop.code,property_name:prop.name,nights:d.offer.min_nights,guests:2,experiences:d.packages.map(p=>({components:components(p)})),rate_name:'Condições confirmadas na consulta'};await window.Villegram.configure([card],[{...d.offer,id:card.offer_id}]);window.Villegram.open(card)};box.append(button);return d}
 function renderPhotos(){$('#offer-photos').innerHTML=photos.map((url,i)=>`<figure class="simple-photo"><img src="${esc(url)}" alt="Foto da oferta"><button type="button" data-remove="${i}" aria-label="Remover foto">×</button></figure>`).join('');$('#offer-photos').querySelectorAll('button').forEach(b=>b.onclick=()=>{photos.splice(Number(b.dataset.remove),1);renderPhotos()})}
 async function uploadVG(blob){const path='offers/'+draftId+'/'+crypto.randomUUID()+'.webp';const r=await sb.storage.from('experience-media').upload(path,blob,{contentType:'image/webp'});if(r.error)throw r.error;return sb.storage.from('experience-media').getPublicUrl(path).data.publicUrl}
 function renderVG(){const property=properties.find(p=>p.id===Number($('#vg-property').value));$('#vg-gallery').innerHTML=(property?.gallery||[]).map((m,i)=>`<button type="button" data-gallery="${i}">Adicionar foto ${i+1}</button>`).join('');$('#vg-gallery').querySelectorAll('button').forEach(b=>b.onclick=()=>{const m=property.gallery[Number(b.dataset.gallery)];vg.photos.push({property_id:property.id,url:typeof m==='string'?m:m.url,alt:typeof m==='string'?property.name:m.alt});renderVG()});$('#vg-photos').innerHTML=vg.photos.map((p,i)=>`<div class="villegram-admin-media"><img src="${esc(p.url)}" alt="${esc(p.alt)}"><span>${esc(properties.find(x=>x.id===p.property_id)?.name)}</span><button type="button" data-edit="${i}">Girar / enquadrar</button><button type="button" data-up="${i}" ${i?'':'disabled'}>↑</button><button type="button" data-delete="${i}">Remover</button></div>`).join('');$('#vg-photos').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{vg.photos.splice(Number(b.dataset.delete),1);renderVG()});$('#vg-photos').querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.up);[vg.photos[i-1],vg.photos[i]]=[vg.photos[i],vg.photos[i-1]];renderVG()});$('#vg-photos').querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const i=Number(b.dataset.edit),r=await fetch(vg.photos[i].url),blob=await window.VillegramMedia.editor(await r.blob());if(blob){const old=vg.photos[i].url;vg.photos[i].url=await uploadVG(blob);replacements.push({old,url:vg.photos[i].url});renderVG()}}catch{$('#offer-message').textContent='Não foi possível editar a foto.'}finally{b.disabled=false}})}
 const message=e=>e.message==='offer_not_ready'?(e.data.issues||[]).map(x=>issues[x]||x).join('. '):({offer_conflict:'Esta oferta foi alterada por outra pessoa. Atualize antes de salvar.',invalid_offer:'Preencha nome, descrição, imóveis, pacotes e duração válidos.',invalid_offer_period:'Confira o período da oferta.',invalid_showcase:'Confira as durações e o horizonte da vitrine (14 a 90 dias).'}[e.message]||issues[e.message]||'Não foi possível salvar. Confira os campos e tente novamente.');
 async function boot(){session=(await sb.auth.getSession()).data.session;if(!session){location.href='auth.html?mode=login&return=estadias-admin.html';return}try{await load()}catch(e){$('#offer-message').textContent=message(e);return}
 $('#offer-picker').onchange=e=>select(e.target.value);$('#new-offer').onclick=()=>select(null);$('#offer-preview-button').onclick=async()=>{try{await preview()}catch(e){$('#offer-message').textContent=message(e)}};
 $('#offer-form').onsubmit=async e=>{e.preventDefault();const b=$('#offer-save');b.disabled=true;try{const p=await preview();if(p.issues.length&&values().status==='active')throw Object.assign(Error('offer_not_ready'),{data:p});const d=await api({...values(),operation:'save'});await load(d.offer.id);$('#offer-message').textContent='Estadia completa salva. '+(d.offer.status==='active'?'A versão atual já está disponível para novas consultas.':'Ela permanece pausada.')}catch(e){$('#offer-message').textContent=message(e)}finally{b.disabled=false}};
 $('#vg-property').onchange=renderVG;
 $('#vg-upload').onchange=async e=>{const file=e.target.files[0];try{if(!file||file.size>10485760)throw Error('invalid_photo');const blob=await window.VillegramMedia.editor(file);if(blob){vg.photos.push({url:await uploadVG(blob),property_id:Number($('#vg-property').value),alt:properties.find(p=>p.id===Number($('#vg-property').value)).name});renderVG()}}catch{$('#offer-message').textContent='Não foi possível preparar a foto.'}e.target.value=''};
 $('#vg-audio-file').onchange=async e=>{try{const file=e.target.files[0];if(!file||file.size>10485760||!['audio/mpeg','audio/mp4','audio/ogg','audio/wav'].includes(file.type))throw Error('invalid_audio');const path=draftId+'/'+crypto.randomUUID()+'.'+file.name.split('.').pop().toLowerCase();const r=await sb.storage.from('villegram-audio').upload(path,file);if(r.error)throw r.error;vg.audio={url:sb.storage.from('villegram-audio').getPublicUrl(path).data.publicUrl};$('#vg-audio-status').textContent='Arquivo enviado. Registre origem e licença antes de salvar.'}catch{$('#vg-audio-status').textContent='Use MP3, M4A, OGG ou WAV de até 10 MB.'}e.target.value=''};
 $('#vg-audio-remove').onclick=()=>{vg.audio=null;$('#vg-audio-status').textContent='Síntese original.'};
 $('#vg-comments-load').onclick=async()=>{if(!current)return;const r=await fetch(C.bookingEngine,{method:'POST',headers:{'Content-Type':'application/json','X-Chalezinho-Env':'development',Authorization:'Bearer '+session.access_token},body:JSON.stringify({action:'villegram',offer_id:current.id})});const d=await r.json();$('#vg-comments-admin').innerHTML=d.ok?d.comments.map(c=>`<article><strong>${esc(c.display_name)}</strong><p>${esc(c.body)}</p><button type="button" data-remove-comment="${c.id}">Remover comentário</button></article>`).join('')||'Nenhum comentário.':'Não foi possível carregar.';$('#vg-comments-admin').querySelectorAll('button').forEach(b=>b.onclick=async()=>{b.disabled=true;const r=await fetch(C.bookingEngine,{method:'POST',headers:{'Content-Type':'application/json','X-Chalezinho-Env':'development',Authorization:'Bearer '+session.access_token},body:JSON.stringify({action:'villegram',operation:'remove',offer_id:current.id,comment_id:b.dataset.removeComment})});if(r.ok)$('#vg-comments-load').click();else b.disabled=false})};
 $('#offer-photo-upload').onchange=async e=>{try{for(const file of e.target.files){if(file.size>10*1024*1024||!['image/jpeg','image/png','image/webp','image/avif'].includes(file.type))throw Error('invalid_photo');const path='offers/'+draftId+'/'+crypto.randomUUID()+'.webp';const {error}=await sb.storage.from('experience-media').upload(path,await window.VillegramMedia.transform(file),{contentType:'image/webp'});if(error)throw error;photos.push(sb.storage.from('experience-media').getPublicUrl(path).data.publicUrl)}renderPhotos()}catch{$('#offer-message').textContent='Não foi possível enviar a foto. Use JPG, PNG, WebP ou AVIF de até 10 MB.'}e.target.value=''};
 }
 boot();
})();
