window.ListingEditor={
 async open({property,host,api,onBack,onSaved}){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let p=property;
 const show=()=>{host.innerHTML=`<button type="button" id="listing-back">← Voltar</button><h2>${esc(p.name)}</h2><p>Escolha o que deseja editar.</p><div class="workspace-cards"><button data-section="space"><strong>Título e descrição</strong><span>${esc(p.tagline||'Apresente seu imóvel')}</span></button><button data-section="amenities"><strong>Comodidades</strong><span>${(p.features?.amenities||[]).length} itens cadastrados · Wi-Fi, cozinha, lazer e mais</span></button></div><p id="listing-message" role="status"></p>`;host.querySelector('#listing-back').onclick=onBack;host.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>edit(b.dataset.section))};
 const edit=section=>{
 const common=['Wi-Fi','Ar-condicionado','Cozinha equipada','Estacionamento','Piscina privativa','Piscina aquecida','Hidromassagem','Spa aquecido','Aceita pets','Roupa de cama','Toalhas','Televisão','Fogueira','Rede','Varanda'];
 const current=VilleAmenities.list(p.features),extra=current.filter(x=>!common.includes(x));
 host.innerHTML=`<button type="button" id="listing-back">← ${esc(p.name)}</button><h2>${section==='space'?'Título e descrição':'Comodidades'}</h2><form id="listing-form" class="workspace-form">${section==='space'?`<label>Título<input name="name" required minlength="2" maxlength="160" value="${esc(p.name)}"></label><label>Chamada curta<input name="tagline" maxlength="240" value="${esc(p.tagline)}"></label><label>Descrição<textarea name="summary" maxlength="3000" rows="7">${esc(p.summary)}</textarea></label>`:`<p>Marque apenas o que este imóvel oferece.</p><div class="amenity-options">${common.map(x=>`<label><input type="checkbox" name="amenity" value="${esc(x)}" ${current.includes(x)?'checked':''}>${esc(x)}</label>`).join('')}</div><label>Outras comodidades (uma por linha)<textarea name="extra" rows="5">${esc(extra.join('\n'))}</textarea></label>`}<p role="status" id="listing-message"></p><button type="submit" class="workspace-primary">Salvar alterações</button></form>`;
 host.querySelector('#listing-back').onclick=show;
 let selected=VilleAmenities.highlights(p.features),categories={...(p.features?.amenity_categories||{})};
 if(section==='amenities'){
  const f=host.querySelector('form'),settings=document.createElement('div');settings.className='amenity-settings';f.insertBefore(settings,f.querySelector('#listing-message'));
  const items=()=>[...new Set([...f.querySelectorAll('[name=amenity]:checked')].map(x=>x.value).concat(f.elements.extra.value.split('\n').map(x=>x.trim()).filter(Boolean)))];
  const refresh=()=>{const all=items();selected=selected.filter(x=>all.includes(x));settings.innerHTML='<h3>Destaques na página do imóvel</h3><p>Escolha até 8 comodidades. A posição 1 aparece primeiro. Deixe vazias as posições que não quiser usar.</p>'+Array.from({length:8},(_,i)=>`<label>${i+1}º destaque<select data-highlight="${i}"><option value="">Sem destaque</option>${all.map(x=>`<option value="${esc(x)}" ${selected[i]===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`).join('')+'<button type="button" id="suggest-highlights">Usar destaques sugeridos</button><h3>Categorias</h3>'+all.map((x,i)=>`<label class="amenity-category-row">${esc(x)}<select data-category="${i}">${VilleAmenities.categories.map(c=>`<option ${c===(categories[x]||VilleAmenities.category(x))?'selected':''}>${esc(c)}</option>`).join('')}</select></label>`).join('');
   settings.querySelectorAll('[data-highlight]').forEach(el=>el.onchange=()=>{const chosen=el.value,i=Number(el.dataset.highlight);selected=Array.from({length:8},(_,j)=>j===i?chosen:(selected[j]===chosen?'':selected[j]||''));refresh()});
   settings.querySelectorAll('[data-category]').forEach(el=>el.onchange=()=>categories[all[Number(el.dataset.category)]]=el.value);
   settings.querySelector('#suggest-highlights').onclick=()=>{selected=VilleAmenities.defaults(all);refresh()};
  };f.querySelectorAll('[name=amenity]').forEach(el=>el.addEventListener('change',refresh));f.elements.extra.addEventListener('change',refresh);refresh();
 }
 host.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('[type=submit]'),m=host.querySelector('#listing-message');b.disabled=true;m.textContent='Salvando…';try{const payload=section==='space'?Object.fromEntries(new FormData(f)):{amenities:[...f.querySelectorAll('[name=amenity]:checked')].map(x=>x.value).concat(f.elements.extra.value.split('\n').map(x=>x.trim()).filter(Boolean))};if(section==='amenities'){payload.amenity_highlights=selected.filter(x=>x&&payload.amenities.includes(x));payload.amenity_categories=Object.fromEntries(payload.amenities.map(x=>[x,categories[x]||VilleAmenities.category(x)]))}await api({action:'listings',operation:'save',property_id:p.id,updated_at:p.updated_at,section,...payload});await onSaved();}catch(err){m.textContent=err.message==='listing_conflict'?'O imóvel mudou em outra tela. Volte e abra novamente para atualizar.':'Não foi possível salvar. Confira os campos e seu acesso.';b.disabled=false}};
 };show();
 }
};
