(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n))),color=v=>/^#[\da-f]{6}$/i.test(v)?v:'#ffffff';
 function markup(layers=[]){return '<div class="vg-text-stage">'+layers.slice(0,5).map(t=>'<span class="vg-text-sticker" style="left:'+clamp(t.x??50,5,95)+'%;top:'+clamp(t.y??30,5,95)+'%;font-size:'+clamp(t.size??6,3,9)+'cqw;color:'+color(t.color)+';background:'+(t.background==='transparent'?'transparent':color(t.background||'#17130f'))+'">'+esc(t.text)+'</span>').join('')+'</div>'}
 function editor({screen,getMedia,onChange,isBusy}){
  const stage=document.createElement('div'),tools=document.createElement('div');stage.className='vg-text-stage vg-text-edit-stage';tools.className='vg-text-tools';tools.innerHTML='<button type="button" aria-label="Adicionar texto sobre a cena">Aa <span>Texto</span></button>';screen.append(stage,tools);let active=-1,editing=false;
  const list=()=>getMedia()?.text_layers||[];
  function confine(node,t){const r=stage.getBoundingClientRect(),b=node.getBoundingClientRect();if(!r.width||!r.height)return;t.x=clamp(t.x,Math.max(5,Math.min(50,b.width/r.width*50)),Math.min(95,Math.max(50,100-b.width/r.width*50)));t.y=clamp(t.y,Math.max(5,Math.min(50,b.height/r.height*50)),Math.min(95,Math.max(50,100-b.height/r.height*50)));node.style.left=t.x+'%';node.style.top=t.y+'%';}
  function paint(node,t){node.textContent=t.text||'Seu texto';Object.assign(node.style,{left:t.x+'%',top:t.y+'%',fontSize:t.size+'cqw',color:t.color,background:t.background});confine(node,t)}
  function render(){tools.hidden=!getMedia();stage.innerHTML='';list().forEach((t,i)=>{const b=document.createElement('button');b.type='button';b.className='vg-text-sticker';b.setAttribute('aria-label','Editar texto: '+t.text);stage.append(b);paint(b,t);let start=null,moved=false;b.onpointerdown=e=>{if(isBusy()||editing||e.button>0)return;e.preventDefault();e.stopPropagation();active=i;moved=false;const r=stage.getBoundingClientRect();start={x:e.clientX,y:e.clientY,tx:t.x,ty:t.y,w:r.width,h:r.height};b.setPointerCapture?.(e.pointerId)};b.onpointermove=e=>{if(!start)return;e.preventDefault();e.stopPropagation();const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.hypot(dx,dy)>4)moved=true;if(!moved)return;t.x=clamp(start.tx+dx/start.w*100,5,95);t.y=clamp(start.ty+dy/start.h*100,5,95);paint(b,t)};b.onpointerup=e=>{if(!start)return;e.stopPropagation();start=null;if(moved)onChange();};b.onpointercancel=()=>{start=null};b.onclick=()=>{if(moved){moved=false;return}open(i)};b.onkeydown=e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();e.stopPropagation();if(e.key==='ArrowLeft')t.x-=2;if(e.key==='ArrowRight')t.x+=2;if(e.key==='ArrowUp')t.y-=2;if(e.key==='ArrowDown')t.y+=2;paint(b,t);onChange()};});}
  function open(index){if(isBusy()||editing||!getMedia())return;active=index;editing=true;const item=list()[index],original={...item};const panel=document.createElement('div');panel.className='vg-text-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','Editar texto na cena');panel.innerHTML='<label class="sr-only" for="vg-text-value">Texto sobre a cena</label><textarea id="vg-text-value" maxlength="280" rows="4" placeholder="Escreva seu momento…"></textarea><div class="vg-text-palette"><label>Texto<input type="color" data-color></label><label>Fundo<input type="color" data-background></label><label><input type="checkbox" data-transparent> Transparente</label></div><div class="vg-text-size"><button type="button" data-size="-1" aria-label="Diminuir texto">A−</button><button type="button" data-size="1" aria-label="Aumentar texto">A+</button><button type="button" data-delete>Excluir texto</button></div><div class="vg-text-done"><button type="button" data-cancel>Cancelar</button><button type="button" data-done>Concluir</button></div><small>Depois de concluir, arraste o texto na foto para posicionar.</small>';screen.append(panel);const textarea=panel.querySelector('textarea'),fg=panel.querySelector('[data-color]'),bg=panel.querySelector('[data-background]'),transparent=panel.querySelector('[data-transparent]');textarea.value=item.text;fg.value=item.color;bg.value=item.background==='transparent'?'#17130f':item.background;transparent.checked=item.background==='transparent';bg.disabled=transparent.checked;const update=()=>{item.text=textarea.value;item.color=fg.value;item.background=transparent.checked?'transparent':bg.value;bg.disabled=transparent.checked;const node=stage.children[active];paint(node,item)};for(const n of [textarea,fg,bg,transparent])n.addEventListener('input',update);panel.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{item.size=clamp(item.size+Number(b.dataset.size)*.5,3,9);update()});
   const finish=kind=>{if(kind==='cancel')Object.assign(item,original);if(kind==='delete'||!item.text.trim())getMedia().text_layers.splice(index,1);panel.remove();editing=false;render();onChange();tools.querySelector('button').focus()};panel.querySelector('[data-cancel]').onclick=()=>finish('cancel');panel.querySelector('[data-delete]').onclick=()=>finish('delete');panel.querySelector('[data-done]').onclick=()=>finish('done');panel.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();finish('cancel')}if(e.key==='Tab'){const focusable=[...panel.querySelectorAll('textarea,input,button')].filter(n=>!n.disabled),first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};textarea.focus();
  }
  tools.querySelector('button').onclick=()=>{if(isBusy()||editing)return;const m=getMedia();if(!m)return;m.text_layers ||= [];if(m.text_layers.length>=5){open(0);return}m.text_layers.push({text:'',x:50,y:30,size:6,color:'#ffffff',background:'transparent'});render();open(m.text_layers.length-1)};
  return {render,isEditing:()=>editing};
 }
 window.VillegramText={markup,editor};
})();
