(()=>{
 const filters={original:{label:'Original',css:'none'},warm:{label:'Aconchego',css:'sepia(.18) saturate(1.12) brightness(1.04)'},soft:{label:'Suave',css:'saturate(.8) contrast(.92) brightness(1.08)'},gold:{label:'Dourado',css:'sepia(.3) saturate(1.15) contrast(1.05)'},mono:{label:'P&B',css:'grayscale(1) contrast(1.08)'}};
 const modes={original:{label:'Original',duration:6500,description:'Enquadramento livre'},breathe:{label:'Respirar',duration:8000,description:'Tela cheia · dissolve suave · zoom entra e sai'},pulse:{label:'Pulso',duration:3200,description:'Tela cheia · corte rápido · zoom alternado'},cinema:{label:'Cinema',duration:6000,description:'Moldura vertical · transição lateral · movimento amplo'}};
 const templates=modes;
 const css=m=>filters[m?.filter||'original']?.css||'none';
 function applyTemplate(m,key){if(!modes[key])return;m.mode=key;}
 function controls(host,getMedia,changed,locked=()=>false,getCollection=()=>[getMedia()]){
 const svg=p=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+p+'</svg>';
 const glyphs={filter:'<circle cx="9" cy="9" r="5"/><circle cx="15" cy="9" r="5"/><circle cx="12" cy="15" r="5"/>',effect:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>',speed:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',original:'<circle cx="12" cy="12" r="8"/><path d="m6 6 12 12"/>',warm:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',soft:'<path d="M16 3a9 9 0 1 0 5 14A9 9 0 0 1 16 3Z"/>',gold:'<path d="m12 3 9 9-9 9-9-9Z"/>',mono:'<circle cx="12" cy="12" r="9"/><path d="M12 3v18"/>',breathe:'<path d="M3 9h12a3 3 0 1 0-3-3M3 13h16a3 3 0 1 1-3 3M3 17h7"/>',pulse:'<path d="M2 12h5l3-8 4 16 3-8h5"/>',cinema:'<rect x="3" y="4" width="18" height="16" rx="3"/><path d="M7 4v16m10-16v16M3 9h4m-4 6h4m10-6h4m-4 6h4"/>'};
 host.innerHTML='<button type="button" class="vg-wheel-launch" data-effects-toggle aria-label="Abrir filtros e efeitos" aria-expanded="false">'+svg(glyphs.effect)+'</button><div class="vg-wheel" hidden><div class="vg-wheel-outer" role="group" aria-label="Categorias de edição"></div><div class="vg-wheel-inner" role="group" aria-label="Opções"></div><button type="button" class="vg-wheel-close" aria-label="Fechar roleta">'+svg('<path d="m6 6 12 12M18 6 6 18"/>')+'</button><span class="vg-wheel-feedback" role="status" aria-live="polite"></span></div>';
 const wheel=host.querySelector('.vg-wheel'),launch=host.querySelector('[data-effects-toggle]');let active='filter',labelTimer;
 function place(button,index,count,radius){const angle=(-165+150*(count===1?.5:index/(count-1)))*Math.PI/180;button.style.left='calc(50% + '+Math.cos(angle)*radius+'px)';button.style.bottom=(22-Math.sin(angle)*radius)+'px';}
 function label(text){const node=host.querySelector('.vg-wheel-feedback');node.textContent=text;clearTimeout(labelTimer);labelTimer=setTimeout(()=>node.textContent='',1400)}
 function draw(){const m=getMedia();if(!m)return;const categories=m.kind==='video'?[['filter','Filtros'],['speed','Velocidade']]:[['filter','Filtros'],['effect','Efeitos']];if(!categories.some(c=>c[0]===active))active='filter';const outer=host.querySelector('.vg-wheel-outer');outer.innerHTML='';categories.forEach(([key,name],i)=>{const button=document.createElement('button');button.type='button';button.dataset.effectsTab=key;button.setAttribute('aria-label',name);button.setAttribute('aria-pressed',String(active===key));button.innerHTML=svg(glyphs[key]);place(button,i,categories.length,120);button.onclick=()=>{active=key;draw();label(name)};outer.append(button)});
 const items=active==='filter'?Object.entries(filters).map(([k,v])=>[k,v.label,(m.filter||'original')===k]):active==='effect'?Object.entries(modes).map(([k,v])=>[k,v.label,(m.mode||'original')===k]):[.5,.75,1].map(v=>[String(v),v===1?'Normal':String(v).replace('.',',')+'×',(m.speed||1)===v]);const inner=host.querySelector('.vg-wheel-inner');inner.innerHTML='';items.forEach(([key,name,selected],i)=>{const button=document.createElement('button');button.type='button';button.dataset[active==='filter'?'filter':active==='effect'?'template':'speed']=key;button.setAttribute('aria-label',name);button.title=name;button.setAttribute('aria-pressed',String(selected));button.innerHTML=active==='speed'?'<span>'+name+'</span>':svg(glyphs[key]||glyphs.effect);if(active==='filter')button.style.setProperty('--vg-wheel-color',({warm:'#b78354',soft:'#959ca6',gold:'#bc9a48',mono:'#dddddd',original:'#353538'})[key]);place(button,i,items.length,70);button.disabled=locked();button.onclick=()=>{if(locked())return;if(active==='filter')m.filter=key;else if(active==='speed')m.speed=Number(key);else getCollection().forEach(item=>applyTemplate(item,key));changed();draw();label(name)};inner.append(button)});}
 function open(){if(locked()||!getMedia())return;wheel.hidden=false;launch.setAttribute('aria-expanded','true');draw();}
 function close(){wheel.hidden=true;launch.setAttribute('aria-expanded','false');}
 launch.onclick=()=>wheel.hidden?open():close();host.querySelector('.vg-wheel-close').onclick=()=>{close();launch.focus()};host.onkeydown=e=>{if(e.key==='Escape'){close();launch.focus()}};
 return {open,close,render(){host.hidden=!getMedia();if(!getMedia())close();else if(!wheel.hidden)draw()}};
 }
 // Share frame: only authored layers, media framing and a discreet brand handle.
 function watermark(layers=[]){const corners=[{x:6,y:90},{x:72,y:90},{x:6,y:10},{x:72,y:10}];return corners.find(c=>!layers.some(t=>Math.abs(t.y-c.y)<14&&Math.abs(t.x-(c.x+11))<32))||null;}
 function geometry(m,sw,sh,w,h){const scale=(m.fit==='contain'?Math.min:Math.max)(w/sw,h/sh)*(m.zoom||1),dw=sw*scale,dh=sh*scale;return {x:(w-dw)*(m.position_x??50)/100+w*(m.offset_x||0)/100,y:(h-dh)*(m.position??50)/100+h*(m.offset_y||0)/100,w:dw,h:dh};}
 function draw(ctx,source,m,layers){const w=ctx.canvas.width,h=ctx.canvas.height;ctx.fillStyle='#17130f';ctx.fillRect(0,0,w,h);const g=geometry(m,source.videoWidth||source.naturalWidth,source.videoHeight||source.naturalHeight,w,h);ctx.save();ctx.filter=css(m);ctx.drawImage(source,g.x,g.y,g.w,g.h);ctx.restore();
 for(const t of layers){const size=t.size*w/100,chars=[];const font=v=>(v.italic?'italic ':'')+(v.bold===false?'400 ':'600 ')+size+'px "DM Sans",sans-serif';for(const part of new Intl.Segmenter('pt-BR',{granularity:'grapheme'}).segment(t.text)){const i=part.index,c=part.segment,style={...t};for(const r of t.runs||[])if(i>=r.start&&i<r.end)Object.assign(style,r);ctx.font=font(style);chars.push({c,style,width:ctx.measureText(c).width,index:i});}
 const lines=[[]];let length=0;for(const ch of chars){if(ch.c==='\n'){lines.push([]);length=0;continue}if(length+ch.width>w*.9&&lines.at(-1).length){lines.push([]);length=0}lines.at(-1).push(ch);length+=ch.width;}
 let y=t.y*h/100-lines.length*size*.625;ctx.textBaseline='top';for(const line of lines){const total=line.reduce((a,c)=>a+c.width,0);let x=t.x*w/100-total/2;for(const ch of line){ctx.font=font(ch.style);if(ch.style.background!=='transparent'){ctx.fillStyle=ch.style.background||'#17130f';ctx.fillRect(x-1,y-2,ch.width+2,size*1.25)}ctx.fillStyle=ch.style.color||'#fff';ctx.fillText(ch.c,x,y);if(ch.style.strike){ctx.fillRect(x,y+size*.55,ch.width,Math.max(1,size/18))}x+=ch.width;}y+=size*1.25;}}
 const mark=watermark(layers);if(mark){ctx.font='500 18px "DM Sans",sans-serif';ctx.fillStyle='#ffffff';ctx.shadowColor='#000';ctx.shadowBlur=4;ctx.fillText('@chalezinhoville',mark.x*w/100,mark.y*h/100);ctx.shadowBlur=0;}
 }
 async function exportMedia(blob,m,{guest=true,progress=()=>{},signal}={}){
 const canvas=document.createElement('canvas');canvas.width=720;canvas.height=1280;const ctx=canvas.getContext('2d');if(!ctx)throw Error('export_unavailable');const layers=guest?(m.text_layers||[]):[],url=URL.createObjectURL(blob);let source,stream,recorder,audioContext,frame,timeout;
 const check=()=>{if(signal?.aborted)throw new DOMException('Cancelado','AbortError')};
 try{check();await document.fonts?.ready;
 source=document.createElement(m.kind==='video'?'video':'img');if(m.kind==='video'){source.playsInline=true;source.preload='auto';source.style.cssText='position:fixed;left:-2px;bottom:0;width:1px;height:1px;opacity:.01;pointer-events:none';document.body.append(source)}
 await new Promise((resolve,reject)=>{timeout=setTimeout(()=>reject(Error('media_timeout')),20000);source.addEventListener(m.kind==='video'?'loadeddata':'load',resolve,{once:true});source.addEventListener('error',()=>reject(Error('media_unavailable')),{once:true});source.src=url});clearTimeout(timeout);check();draw(ctx,source,m,layers);
 if(m.kind!=='video')return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('export_unavailable')),'image/jpeg',.92));
 if(!window.MediaRecorder||!canvas.captureStream)throw Error('export_unavailable');
 // MP4 is required for the Instagram export; never silently discard the edits.
 const mime=['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4'].find(v=>MediaRecorder.isTypeSupported(v));if(!mime)throw Error('mp4_unavailable');
 source.playbackRate=m.speed||1;source.preservesPitch=true;stream=canvas.captureStream(30);
 const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('audio_unavailable');audioContext=new AC();const audioSource=audioContext.createMediaElementSource(source),dest=audioContext.createMediaStreamDestination();audioSource.connect(dest);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));await audioContext.resume();
 const chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:4000000});
 return await new Promise((resolve,reject)=>{const stopError=e=>{if(recorder.state!=='inactive')recorder.stop();reject(e)};const abort=()=>stopError(new DOMException('Cancelado','AbortError'));signal?.addEventListener('abort',abort,{once:true});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=()=>stopError(Error('export_failed'));recorder.onstop=()=>{signal?.removeEventListener('abort',abort);const result=new Blob(chunks,{type:'video/mp4'});result.size?resolve(result):reject(Error('export_failed'))};source.onended=()=>recorder.stop();source.onerror=()=>stopError(Error('export_failed'));timeout=setTimeout(()=>stopError(Error('export_timeout')),(source.duration/(m.speed||1)+20)*1000);
 const paint=()=>{if(recorder.state==='inactive')return;draw(ctx,source,m,layers);progress(Math.min(99,Math.round(source.currentTime/source.duration*100)));frame=requestAnimationFrame(paint)};recorder.start(1000);source.play().then(paint).catch(stopError);});
 }finally{clearTimeout(timeout);cancelAnimationFrame(frame);source?.pause?.();source?.remove();stream?.getTracks().forEach(t=>t.stop());if(recorder&&recorder.state!=='inactive')recorder.stop();await audioContext?.close();URL.revokeObjectURL(url);}
 }
 window.VillegramEffects={filters,modes,templates,css,applyTemplate,controls,geometry,watermark,exportMedia};
})();
