(()=>{
 const C=window.CHALEZINHO_CONFIG,sb=window.supabase.createClient(C.supabaseUrl,C.supabaseKey,C.authOptions),$=s=>document.querySelector(s),f=$('#vg-post-form'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={property:'Chalé',experience:'Experiência',offer:'Estadia pronta',trust:'Dúvidas e confiança'},states={draft:'Rascunho',published:'Publicada',archived:'Arquivada',pending_review:'Aguardando aprovação'};
 let data,current=null,media=[],cover=0,uploading=false,pendingUpload=null,session;
 async function api(body){const fresh=await sb.auth.getSession();session=fresh.data.session;if(!session)throw Error('authentication_required');const r=await fetch(C.supabaseUrl+'/functions/v1/villegram-content',{method:'POST',headers:{'Content-Type':'application/json','X-Chalezinho-Env':'development',Authorization:'Bearer '+session.access_token},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error);return d;}
 const message=e=>({edit_conflict:'Outra pessoa alterou esta publicação. Reabra a versão atual antes de salvar.',link_required:'Vincule o chalé, a experiência ou a estadia correspondente ao tipo.',invalid_action:'A ação principal precisa do vínculo correspondente.',link_unavailable:'O vínculo está indisponível. Salve como rascunho ou escolha outra opção.',invalid_publication:'Informe título, legenda e pelo menos uma mídia válida.',invalid_media_owner:'Esta mídia não pertence ao autor. Envie sua própria mídia.',media_upload_incomplete:'A mídia ainda não terminou de carregar.',authentication_required:'Sua sessão expirou. Entre novamente.'}[e.message]||'Não foi possível concluir. '+(e.message==='service_unavailable'?'O serviço está indisponível; tente novamente.':e.message));
 async function load(){data=await api({operation:'admin_list'});$('#vg-admin-root').hidden=false;$('#vg-admin-message').textContent='';renderList();links();automation();library();if(!current)edit();await report();}
 function links(){for(const [name,rows] of [['property_id',data.properties],['experience_id',data.products],['offer_id',data.offers]]){const selected=f.elements[name].value;f.elements[name].innerHTML='<option value="">Sem vínculo</option>'+rows.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join('');f.elements[name].value=selected;}}
 function renderList(){const filter=$('#vg-filter').value;$('#vg-post-list').innerHTML=data.publications.filter(p=>filter==='all'||p.status===filter).map(p=>`<article class="vg-post-card">${p.media[p.cover_index]?.poster||p.media[p.cover_index]?.url?`<img src="${esc(p.media[p.cover_index].poster||p.media[p.cover_index].url)}" alt="Capa de ${esc(p.title)}">`:''}<h3>${esc(p.title)}</h3><p>${labels[p.type]} · ${states[p.status]}${p.featured?' · Destaque':''}</p><p>${p.source==='automatic'?'Gerada automaticamente':'Equipe'} · ordem ${p.display_order}</p><button type="button" data-edit="${p.id}">Editar</button></article>`).join('')||'<p>Nenhuma publicação nesta seleção.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));}
 function edit(id){if(uploading)return;pendingUpload=null;$('#vg-upload-retry').hidden=true;current=data.publications.find(p=>p.id===id)||null;media=current?current.media.map(m=>({...m})):[];cover=current?.cover_index||0;$('#vg-editor-title').textContent=current?'Editar publicação':'Nova publicação';for(const key of ['type','property_id','experience_id','offer_id','title','caption','cta','display_order'])f.elements[key].value=current?.[key]??({type:'property',cta:'property',display_order:0}[key]||'');f.elements.featured.checked=!!current?.featured;f.elements.expires_at.value=current?.expires_at?new Date(Date.parse(current.expires_at)-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):'';$('#vg-archive').hidden=!current||current.status==='archived';$('#vg-editor-message').textContent='';renderMedia();if(id)f.scrollIntoView({block:'start',behavior:'smooth'});}
 function library(){const photos=data.properties.flatMap(p=>(p.gallery?.length?p.gallery:[p.cover_image]).filter(Boolean).map(m=>({url:typeof m==='string'?m:m.url,name:p.name}))).concat(data.products.flatMap(p=>(p.experience_media||[]).map(m=>({url:m.media_url,name:p.name}))));$('#vg-library-photos').innerHTML=photos.map((p,i)=>'<button type="button" data-photo="'+i+'" aria-label="Adicionar foto de '+esc(p.name)+'"><img src="'+esc(p.url)+'" alt="'+esc(p.name)+'"></button>').join('');$('#vg-library-photos').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(media.length>=8||media.some(m=>m.kind==='video')){$('#vg-editor-message').textContent='Use até 8 fotos, ou apenas um vídeo.';return}const p=photos[Number(b.dataset.photo)];media.push({kind:'photo',url:p.url,fit:'contain',position:50,alt:p.name});renderMedia()});}
 function renderMedia(){if(!media.length){$('#vg-media-list').innerHTML='<p>Adicione uma mídia para visualizar.</p>';return}$('#vg-media-list').innerHTML=media.map((m,i)=>`<article class="vg-media-card">${m.kind==='video'?`<video src="${esc(m.url)}" poster="${esc(m.poster||'')}" controls muted playsinline></video>`:`<img src="${esc(m.url)}" alt="${esc(m.alt||'Mídia selecionada')}">`}<p>${i===cover?'Capa · ':''}${m.kind==='video'?'Vídeo':'Foto '+(i+1)}</p><button type="button" data-cover="${i}">Usar como capa</button>${i?`<button type="button" data-up="${i}">Mover antes</button>`:''}<button type="button" data-remove="${i}">Remover</button><label>Enquadramento<select data-fit="${i}"><option value="contain" ${m.fit!=='cover'?'selected':''}>Cena inteira</option><option value="cover" ${m.fit==='cover'?'selected':''}>Preencher vertical (confira o corte)</option></select></label><label>Posição da cena<input data-position="${i}" type="range" min="0" max="100" value="${m.position||50}"></label>${m.kind==='video'?`<label>Escolher instante da capa<input data-poster="${i}" type="range" min="0" max="${Math.max(0,m.duration-.1)}" step="0.1" value="0"></label><button type="button" data-poster-save="${i}">Usar este instante como capa</button>`:''}</article>`).join('');
  $('#vg-media-list').querySelectorAll('[data-cover]').forEach(b=>b.onclick=()=>{cover=Number(b.dataset.cover);renderMedia()});$('#vg-media-list').querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.up);[media[i-1],media[i]]=[media[i],media[i-1]];if(cover===i)cover--;else if(cover===i-1)cover++;renderMedia()});$('#vg-media-list').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.remove);media.splice(i,1);cover=Math.max(0,Math.min(cover-(i<cover?1:0),media.length-1));renderMedia()});$('#vg-media-list').querySelectorAll('[data-fit]').forEach(b=>b.onchange=()=>{media[Number(b.dataset.fit)].fit=b.value});$('#vg-media-list').querySelectorAll('[data-position]').forEach(b=>b.oninput=()=>{media[Number(b.dataset.position)].position=Number(b.value)});
  $('#vg-media-list').querySelectorAll('[data-poster]').forEach(b=>b.oninput=()=>{b.closest('article').querySelector('video').currentTime=Number(b.value)});$('#vg-media-list').querySelectorAll('[data-poster-save]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const i=Number(b.dataset.posterSave),blob=await window.VillegramUpload.poster(b.closest('article').querySelector('video'),Number(b.closest('article').querySelector('[data-poster]').value)),path=session.user.id+'/'+crypto.randomUUID()+'.webp';await window.VillegramUpload.upload(sb,blob,path);media[i].poster_path=path;media[i].poster=URL.createObjectURL(blob);renderMedia()}catch(e){$('#vg-editor-message').textContent=message(e)}finally{b.disabled=false}});
 }
 function payload(status){return {type:f.elements.type.value,title:f.elements.title.value,caption:f.elements.caption.value,media,cover_index:cover,property_id:f.elements.property_id.value||null,experience_id:f.elements.experience_id.value||null,offer_id:f.elements.offer_id.value||null,cta:f.elements.cta.value,display_order:Number(f.elements.display_order.value),featured:f.elements.featured.checked,status,published_at:current?.published_at||null,expires_at:f.elements.expires_at.value?new Date(f.elements.expires_at.value).toISOString():null};}
 async function save(status){if(uploading){$('#vg-editor-message').textContent='Espere o upload terminar.';return}const buttons=[...f.querySelectorAll('.vg-editor-actions button')];buttons.forEach(b=>b.disabled=true);try{const r=await api({operation:'save',id:current?.id,updated_at:current?.updated_at,publication:payload(status)});current=r.publication;data.publications=data.publications.filter(p=>p.id!==current.id).concat(current).sort((a,b)=>a.display_order-b.display_order);renderList();edit(current.id);$('#vg-editor-message').textContent=status==='published'?'Publicação disponível no Villegram.':status==='archived'?'Publicação arquivada.':'Rascunho salvo.'}catch(e){$('#vg-editor-message').textContent=message(e)}finally{buttons.forEach(b=>b.disabled=false)}}
 async function uploadFiles(files){if(!files?.length||uploading)return;uploading=true;$('#vg-upload-retry').hidden=true;$('#vg-upload-progress').hidden=false;$('#vg-upload-progress').value=0;$('#vg-upload-status').textContent='Preparando mídia…';try{
  for(const file of files){if(file.type.startsWith('video/')){if(files.length!==1||media.length)throw Error('Um vídeo deve ser publicado sozinho. Remova as fotos antes de enviar.');const inspected=await window.VillegramUpload.inspect(file),poster=await window.VillegramUpload.poster(inspected.video),path=session.user.id+'/'+crypto.randomUUID()+(file.type==='video/mp4'?'.mp4':'.webm'),poster_path=session.user.id+'/'+crypto.randomUUID()+'.webp';pendingUpload={file,path,poster,poster_path,info:{kind:'video',fit:'contain',position:50,duration:inspected.video.duration,bytes:file.size,alt:f.elements.title.value||'Vídeo do Chalezinho Ville',url:inspected.url,poster:URL.createObjectURL(poster)}};}
   else{if(media.length>=8||media.some(m=>m.kind==='video')||file.size>10*1024*1024)throw Error('Use até 8 fotos de no máximo 10 MB cada.');const blob=await window.VillegramMedia.editor(file);if(!blob)continue;pendingUpload={file:blob,path:session.user.id+'/'+crypto.randomUUID()+'.webp',info:{kind:'photo',fit:'contain',position:50,alt:f.elements.title.value||'Foto do Chalezinho Ville',url:URL.createObjectURL(blob)}};}
   await finishUpload();
  }$('#vg-upload-status').textContent='Mídia pronta. Confira o enquadramento e a capa antes de publicar.';
 }catch(e){$('#vg-upload-status').textContent=e.message;$('#vg-upload-retry').hidden=!pendingUpload;}finally{uploading=false;$('#vg-upload').value=''}}
 async function finishUpload(){const u=pendingUpload;if(!u)return;$('#vg-upload-status').textContent='Enviando mídia…';if(!u.fileUploaded){await window.VillegramUpload.upload(sb,u.file,u.path,n=>{$('#vg-upload-progress').value=n});u.fileUploaded=true;}if(u.poster)await window.VillegramUpload.upload(sb,u.poster,u.poster_path);media.push({...u.info,path:u.path,...(u.poster_path?{poster_path:u.poster_path}:{})});pendingUpload=null;renderMedia();}
 async function preview(){if(uploading)return;if(!f.reportValidity())return;$('#vg-editor-message').textContent='Preparando prévia…';try{const r=await api({operation:'preview',id:current?.id,publication:payload('draft')}),p=r.publication,property=r.properties.find(x=>x.id===p.property_id),product=r.products.find(x=>x.id===p.experience_id);const card={preview:true,publication:p,publication_id:p.id,property_id:property?.id,property_name:property?.name||'Chalezinho Ville',property_code:property?.code,property_url:window.VillegramContent.propertyURL(property),product,experiences:[],guests:2};window.Villegram.configurePublications([card],r.offers,r.properties);window.Villegram.open(card);$('#vg-editor-message').textContent='';}catch(e){$('#vg-editor-message').textContent=message(e)}}
 function automation(){const a=$('#vg-automation-form'),s=data.settings;a.elements.enabled.checked=s.enabled;a.elements.auto_publish.value=String(s.auto_publish);a.elements.frequency_hours.value=s.frequency_hours;a.elements.max_offers.value=s.max_offers;$('#vg-templates').innerHTML=Object.entries(s.templates).map(([type,t])=>`<fieldset data-template="${type}"><legend>${labels[type]}</legend><label class="vg-check"><input data-enabled type="checkbox" ${t.enabled?'checked':''}> Gerar este tipo</label><label>Título<input data-title value="${esc(t.title)}" maxlength="140" required></label><label>Legenda<textarea data-caption maxlength="3000" required>${esc(t.caption)}</textarea></label><label>Movimento<select data-motion>${['gentle','slow','romantic'].map(m=>'<option value="'+m+'" '+(m===t.motion?'selected':'')+'>'+({gentle:'Suave',slow:'Lento',romantic:'Romântico'}[m])+'</option>').join('')}</select></label></fieldset>`).join('');}
 async function report(){const node=$('#vg-report-data');node.textContent='Consultando resultados…';try{const d=await api({operation:'report',days:Number($('#vg-report-days').value)});node.innerHTML='<div class="vg-report-scroll"><table><thead><tr><th>Publicação</th><th>Visualizações</th><th>Visitantes</th><th>Sessões</th><th>Interesse</th><th>Cliques</th><th>Consultas de datas</th><th>Intenção de reserva</th><th>Reservas iniciadas</th><th>Reservas pagas</th></tr></thead><tbody>'+d.rows.map(r=>'<tr><th>'+esc(r.title)+'</th>'+['views','visitors','sessions','interest','clicks','date_queries','reservation_intent','reservations_started','reservations_paid'].map(k=>'<td>'+r[k]+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}catch(e){node.textContent='Não foi possível consultar as métricas. Os valores não foram tratados como zero.'}}
 async function boot(){const r=await sb.auth.getSession();session=r.data.session;if(!session){location.href='auth.html?mode=login&return=villegram-admin.html';return}try{await load()}catch(e){$('#vg-admin-message').textContent=message(e)}}
 $('#vg-new').onclick=()=>edit();$('#vg-filter').onchange=renderList;$('#vg-upload').onchange=e=>uploadFiles([...e.target.files]);$('#vg-upload-retry').onclick=async()=>{uploading=true;try{await finishUpload();$('#vg-upload-retry').hidden=true;$('#vg-upload-status').textContent='Upload concluído.'}catch(e){$('#vg-upload-status').textContent=e.message}finally{uploading=false}};f.onsubmit=e=>{e.preventDefault();save(e.submitter?.name==='published'?'published':'draft')};f.elements.type.onchange=()=>{f.elements.cta.value=({property:'property',experience:'experience',offer:'offer',trust:'dates'})[f.elements.type.value]};$('#vg-archive').onclick=()=>save('archived');$('#vg-preview').onclick=preview;$('#vg-report-days').onchange=report;
 $('#vg-automation-form').onsubmit=async e=>{e.preventDefault();const a=e.currentTarget,templates={};a.querySelectorAll('[data-template]').forEach(n=>templates[n.dataset.template]={enabled:n.querySelector('[data-enabled]').checked,title:n.querySelector('[data-title]').value,caption:n.querySelector('[data-caption]').value,motion:n.querySelector('[data-motion]').value});try{const d=await api({operation:'save_settings',updated_at:data.settings.updated_at,settings:{enabled:a.elements.enabled.checked,auto_publish:a.elements.auto_publish.value==='true',frequency_hours:Number(a.elements.frequency_hours.value),max_offers:Number(a.elements.max_offers.value),templates}});data.settings=d.settings;$('#vg-automation-message').textContent='Configuração salva. Os modelos valem para os novos conteúdos.'}catch(e){$('#vg-automation-message').textContent=message(e)}};
 $('#vg-generate').onclick=async()=>{const b=$('#vg-generate');b.disabled=true;try{const d=await api({operation:'generate'});$('#vg-automation-message').textContent=d.created+' nova(s) publicação(ões). Conteúdos existentes foram preservados.';await load()}catch(e){$('#vg-automation-message').textContent=message(e)}finally{b.disabled=false}};boot();
})();
