(()=>{
 const C=window.CHALEZINHO_CONFIG,sb=window.supabase.createClient(C.supabaseUrl,C.supabaseKey,C.authOptions),$=s=>document.querySelector(s),f=$('#vg-post-form'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={property:'Chalé',experience:'Experiência',offer:'Estadia pronta',trust:'Dúvidas e confiança'},states={draft:'Rascunho',published:'Publicada',archived:'Arquivada',pending_review:'Aguardando aprovação'};
 let data,current=null,media=[],cover=0,uploading=false,pendingUpload=null,session,step=0,selected=0,saving=false,stayQuote=null,stayVersion=0,stayTimer=null,dragCancel=null,suppressMediaClickUntil=0;

 const money=c=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const fixedStay=()=>f.elements.cta.value==='offer'&&f.elements.stay_fixed.checked;
 const stayValues=()=>({check_in:f.elements.stay_check_in.value,check_out:f.elements.stay_check_out.value,guests:Number(f.elements.stay_guests.value),rate_code:f.elements.stay_rate_code.value});
 function invalidateStay(){++stayVersion;clearTimeout(stayTimer);stayQuote=null;$('#vg-stay-rates').innerHTML='';$('#vg-stay-message').textContent='';updateComposition();if(fixedStay())stayTimer=setTimeout(()=>consultStay(),450);}
 function renderStayRates(){const rates=stayQuote?.rate_options||[];$('#vg-stay-rates').innerHTML=rates.map(r=>'<button type="button" class="vg-stay-rate" data-stay-rate="'+esc(r.code)+'" aria-pressed="'+(r.code===f.elements.stay_rate_code.value)+'"><span>'+esc(r.name)+'</span><strong>'+money(r.total_amount_cents)+'</strong><span>Hospedagem '+money(r.accommodation_amount_cents)+' · limpeza '+money(r.cleaning_fee_cents)+' · pacote '+money(r.experience_amount_cents||0)+'</span><small>'+(r.code===f.elements.stay_rate_code.value?'Tarifa apresentada no reel':'Escolher esta tarifa para apresentar')+'</small></button>').join('');$('#vg-stay-rates').querySelectorAll('[data-stay-rate]').forEach(b=>b.onclick=()=>{f.elements.stay_rate_code.value=b.dataset.stayRate;renderStayRates();updateComposition()});}
 async function consultStay(){clearTimeout(stayTimer);if(!fixedStay())return;const values=stayValues();if(!f.elements.property_id.value||!values.check_in||!values.check_out||values.check_out<=values.check_in){$('#vg-stay-message').textContent='Escolha chalé, entrada e saída para consultar.';return}const version=++stayVersion;stayQuote=null;renderStayRates();updateComposition();$('#vg-stay-message').textContent='Consultando calendário e preço atual…';try{const r=await fetch(C.bookingEngine,{method:'POST',headers:{'Content-Type':'application/json','X-Chalezinho-Env':'development'},body:JSON.stringify({action:'villegram_quote',property_id:Number(f.elements.property_id.value),offer_id:f.elements.offer_id.value||null,...values}),signal:AbortSignal.timeout(30000)}),d=await r.json();if(version!==stayVersion)return;if(!r.ok||!d.ok)throw Error(d.error);stayQuote=d;renderStayRates();updateComposition();$('#vg-stay-message').textContent='Preços completos consultados agora. Escolha a tarifa que será apresentada. O hóspede confirma sua tarifa na revisão.'}catch(e){if(version!==stayVersion)return;stayQuote=null;renderStayRates();updateComposition();$('#vg-stay-message').textContent='Não foi possível calcular estes dias. '+(e.message==='dates_unavailable'?'Chalé indisponível nessas datas.':e.message?.startsWith('minimum_stay')?'Confira o mínimo de noites.':message(e))}}
 function moveMedia(from,to){if(from===to||from<0||to<0||to>=media.length||uploading||saving)return;const chosen=media[selected],cap=media[cover];media.splice(to,0,media.splice(from,1)[0]);selected=media.indexOf(chosen);cover=media.indexOf(cap);renderMedia();$('#vg-reorder-status').textContent='Foto movida para a posição '+(to+1)+'. A capa foi preservada.';$('#vg-media-list [data-select="'+to+'"]').focus();}
 function enableReordering(){
 const strip=$('.vg-media-strip');if(!strip||media.length<2)return;
 const marker=document.createElement('span');marker.className='vg-insertion-marker';marker.hidden=true;marker.setAttribute('aria-hidden','true');strip.append(marker);
 strip.addEventListener('click',e=>{if(Date.now()<suppressMediaClickUntil){e.preventDefault();e.stopImmediatePropagation()}},true);
 const buttons=[...strip.querySelectorAll('[data-select]')];let positions=[];const rectFor=n=>positions[buttons.indexOf(n)]||n.getBoundingClientRect();
 buttons.forEach(b=>{let timer=null,active=false,slot=Number(b.dataset.select),origin=null,ghost=null,grab=null,scrollFrame=0,lastPoint=null;
 const clear=()=>{clearTimeout(timer);cancelAnimationFrame(scrollFrame);ghost?.remove();ghost=null;marker.hidden=true;buttons.forEach(n=>{n.classList.remove('vg-dragging');n.style.transform=''});active=false;dragCancel=null};
 const indicate=x=>{const rect=strip.getBoundingClientRect();slot=buttons.findIndex(n=>{const r=rectFor(n);return x<r.left-strip.scrollLeft+r.width/2});if(slot<0)slot=buttons.length;const edge=slot===buttons.length?rectFor(buttons.at(-1)).right-strip.scrollLeft+4:rectFor(buttons[slot]).left-strip.scrollLeft-4;marker.style.left=(edge-rect.left+strip.scrollLeft)+'px';marker.hidden=false;buttons.forEach((n,i)=>{n.style.transform=n===b?'':(i>=slot?'translateX(8px)':'translateX(-8px)')});$('#vg-reorder-status').textContent='Solte na posição '+(slot>Number(b.dataset.select)?slot:slot+1)+'.'};
 b.onpointerdown=e=>{if(e.button!==undefined&&e.button!==0||uploading||saving)return;dragCancel?.();origin={x:e.clientX,y:e.clientY};positions=buttons.map(n=>{const r=n.getBoundingClientRect();return {left:r.left+strip.scrollLeft,right:r.right+strip.scrollLeft,width:r.width}});timer=setTimeout(()=>{active=true;const r=b.getBoundingClientRect();grab={x:e.clientX-r.left,y:e.clientY-r.top};ghost=b.cloneNode(true);ghost.removeAttribute('data-select');ghost.removeAttribute('id');ghost.tabIndex=-1;ghost.setAttribute('aria-hidden','true');ghost.className='vg-drag-ghost';ghost.style.width=r.width+'px';ghost.style.height=r.height+'px';document.body.append(ghost);lastPoint={x:e.clientX,y:e.clientY};ghost.style.transform='translate3d('+(e.clientX-grab.x)+'px,'+(e.clientY-grab.y-14)+'px,0) scale(1.1)';b.classList.add('vg-dragging');b.setPointerCapture?.(e.pointerId);indicate(e.clientX);const scroll=()=>{if(!active)return;const r=strip.getBoundingClientRect(),speed=lastPoint.x<r.left+28?-5:lastPoint.x>r.right-28?5:0;if(speed){strip.scrollLeft=clamp(strip.scrollLeft+speed,0,Math.max(0,strip.scrollWidth-strip.clientWidth));indicate(lastPoint.x)}scrollFrame=requestAnimationFrame(scroll)};scrollFrame=requestAnimationFrame(scroll)},320);dragCancel=clear};
 b.onpointermove=e=>{if(!active){if(origin&&Math.hypot(e.clientX-origin.x,e.clientY-origin.y)>8)clear();return}e.preventDefault();lastPoint={x:e.clientX,y:e.clientY};ghost.style.transform='translate3d('+(e.clientX-grab.x)+'px,'+(e.clientY-grab.y-14)+'px,0) scale(1.1)';indicate(e.clientX)};
 b.onpointerup=()=>{const from=Number(b.dataset.select),drop=active,to=slot>from?slot-1:slot;clear();if(drop){suppressMediaClickUntil=Date.now()+450;moveMedia(from,to)}};b.onpointercancel=clear;b.onlostpointercapture=clear;b.oncontextmenu=e=>e.preventDefault();
 b.onkeydown=e=>{if(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();moveMedia(Number(b.dataset.select),Number(b.dataset.select)+(e.key==='ArrowLeft'?-1:1))}};
 });
 }
 const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
 let cancelSceneGesture=()=>{};
 function sceneGeometry(){const scene=$('#vg-composer-visual').firstElementChild,m=media[selected],r=$('#vg-composer-visual').getBoundingClientRect();if(!scene||!m||!r.width||!r.height)return null;const w=scene.naturalWidth||scene.videoWidth,h=scene.naturalHeight||scene.videoHeight;if(!w||!h)return null;const scale=(m.fit==='cover'?Math.max:Math.min)(r.width/w,r.height/h);return {r,bw:w*scale,bh:h*scale};}
 function paintScene(){const m=media[selected],scene=$('#vg-composer-visual').firstElementChild;if(!m||!scene)return;scene.style.objectFit=m.fit||'contain';scene.style.objectPosition=(m.position_x??50)+'% '+(m.position??50)+'%';scene.style.transform=(m.offset_x||m.offset_y?'translate('+(m.offset_x||0)+'%, '+(m.offset_y||0)+'%) ':'')+'scale('+(m.zoom??1)+')';scene.style.transformOrigin=(m.position_x??50)+'% '+(m.position??50)+'%';$('#vg-scene-out').disabled=uploading||saving||(m.zoom??1)<=1;$('#vg-scene-in').disabled=uploading||saving||(m.zoom??1)>=3;}
 function applyScene(values){if(uploading||saving||step!==0||!media[selected])return;Object.assign(media[selected],values);paintScene();$('#vg-scene-fit').textContent=media[selected].fit==='cover'?'Cena inteira':'Preencher';}
 function enableSceneGestures(){
 const layer=$('#vg-scene-gesture'),points=new Map();let base=null;
 const snapshot=()=>{const g=sceneGeometry(),m=media[selected],ps=[...points.values()];if(!g||!ps.length){base=null;return}const center=ps.length>1?{x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2}:ps[0];base={...g,m,center,z:m.zoom??1,x:m.position_x??50,y:m.position??50,ox:m.offset_x||0,oy:m.offset_y||0,distance:ps.length>1?Math.hypot(ps[1].x-ps[0].x,ps[1].y-ps[0].y):0};};
 cancelSceneGesture=()=>{points.clear();base=null;layer.classList.remove('vg-panning')};
 layer.onpointerdown=e=>{if(uploading||saving||step!==0||media[selected]?.kind!=='photo'||e.button!==undefined&&e.button!==0||points.size>=2)return;e.preventDefault();points.set(e.pointerId,{x:e.clientX,y:e.clientY});layer.setPointerCapture?.(e.pointerId);layer.classList.add('vg-panning');snapshot()};
 layer.onpointermove=e=>{if(!points.has(e.pointerId)||!base||uploading||saving)return;e.preventDefault();points.set(e.pointerId,{x:e.clientX,y:e.clientY});const ps=[...points.values()],pinch=ps.length===2&&base.distance>0,c=pinch?{x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2}:ps[0],z=pinch?clamp(base.z*Math.hypot(ps[1].x-ps[0].x,ps[1].y-ps[0].y)/base.distance,1,3):base.z;
 const offset=(size,extent,initial,shift,oldPoint,newPoint,edge)=>{const oldLeft=(size-extent*base.z)*initial/100+shift/100*size,anchor=(oldPoint-edge-oldLeft)/(extent*base.z),visible=Math.min(size/2,extent*z/2),left=clamp(newPoint-edge-anchor*extent*z,-extent*z+visible,size-visible);return Math.round(clamp((left-(size-extent*z)*initial/100)/size*100,-300,300)*10000)/10000};
 applyScene({zoom:z,offset_x:offset(base.r.width,base.bw,base.x,base.ox,base.center.x,c.x,base.r.left),offset_y:offset(base.r.height,base.bh,base.y,base.oy,base.center.y,c.y,base.r.top)});
 };
 const end=e=>{points.delete(e.pointerId);if(!points.size)cancelSceneGesture();else snapshot()};layer.onpointerup=end;layer.onpointercancel=end;layer.onlostpointercapture=end;layer.oncontextmenu=e=>e.preventDefault();
 layer.onkeydown=e=>{const m=media[selected];if(!m)return;const z=m.zoom??1;if(['+','=','-','0','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='0')applyScene({zoom:1,position_x:50,position:50,offset_x:0,offset_y:0});else if(['+','=','-'].includes(e.key))applyScene({zoom:clamp(z+(e.key==='-'?-.1:.1),1,3)});else applyScene(e.key==='ArrowLeft'||e.key==='ArrowRight'?{offset_x:clamp((m.offset_x||0)+(e.key==='ArrowLeft'?-5:5),-50,50)}:{offset_y:clamp((m.offset_y||0)+(e.key==='ArrowUp'?-5:5),-50,50)})}};
 $('#vg-scene-tools').onclick=e=>{const action=e.target.closest('[data-scene-action]')?.dataset.sceneAction,m=media[selected];if(!action||!m||uploading||saving||step!==0)return;cancelSceneGesture();if(action==='cover'){cover=selected;renderMedia()}else if(action==='fit')applyScene({fit:m.fit==='cover'?'contain':'cover'});else if(action==='reset')applyScene({zoom:1,position_x:50,position:50,offset_x:0,offset_y:0,fit:'contain'});else applyScene({zoom:clamp((m.zoom??1)+(action==='in'?.1:-.1),1,3)})};
 }
 const stepNames=['Mídia e capa','Legenda','Publicar'];
 function setStep(value,focus=false){cancelSceneGesture();step=value;f.querySelectorAll('[data-panel]').forEach(n=>n.hidden=Number(n.dataset.panel)!==step);f.querySelectorAll('[data-step]').forEach(b=>{if(Number(b.dataset.step)===step)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});$('#vg-step-back').hidden=step===0;$('#vg-step-next').hidden=step===2;$('#vg-step-status').textContent='Etapa '+(step+1)+' de 3 · '+stepNames[step];updateComposition();if(focus)f.querySelector('[data-panel="'+step+'"] h3').focus();}
 function validateThrough(target){if(uploading||saving){$('#vg-editor-message').textContent='Espere a operação terminar.';return false}if(target>0&&!media.length){setStep(0);$('#vg-editor-message').textContent='Escolha um vídeo ou uma foto para começar.';return false}if(target>1){for(const name of ['title','caption']){const field=f.elements[name];if(!field.value.trim()||!field.checkValidity()){setStep(1);$('#vg-editor-message').textContent='Informe o título e a legenda.';field.focus();field.reportValidity();return false}}}return true;}
 function validatePublication(status='published'){if(!validateThrough(2))return false;for(const field of [f.elements.display_order,f.elements.expires_at]){if(!field.checkValidity()){setStep(2);$('.vg-advanced').open=true;field.focus();field.reportValidity();return false}}if(fixedStay()){const v=stayValues();if(!f.elements.property_id.value||!v.check_in||!v.check_out||v.check_out<=v.check_in||!v.rate_code||status==='published'&&!stayQuote){setStep(2);$('#vg-editor-message').textContent='Escolha chalé, datas e tarifa; consulte o preço atual antes de salvar.';return false}}const required=new Set([f.elements.type.value,f.elements.cta.value]);if(fixedStay())required.delete('offer');for(const kind of ['property','experience','offer']){if(required.has(kind)&&!f.elements[kind+'_id'].value){setStep(2);$('#vg-editor-message').textContent='Escolha '+({property:'o chalé',experience:'a experiência',offer:'a estadia pronta'})[kind]+' para este reel.';f.elements[kind+'_id'].focus();return false}}return true;}
 function busy(){f.querySelectorAll('button,input,textarea,select,summary').forEach(n=>{if(n.tagName!=='SUMMARY')n.disabled=uploading||saving||n.hasAttribute('data-cover')&&Number(n.dataset.cover)===cover});$('#vg-new').disabled=uploading||saving;if(!uploading&&!saving)updateComposition();}
 function toggleLibrary(open){$('#vg-publications-library').hidden=!open;$('#vg-library-toggle').setAttribute('aria-expanded',String(open));if(open)$('#vg-filter').focus();else $('#vg-library-toggle').focus();}
 function updateComposition(rebuild=false){const m=media[selected],visual=$('#vg-composer-visual');if(rebuild){cancelSceneGesture();const old=visual.querySelector('video');if(old)old.pause();visual.innerHTML=m?(m.kind==='video'?'<video src="'+esc(m.url)+'" poster="'+esc(m.poster||'')+'" controls muted playsinline preload="metadata" aria-label="Prévia do vídeo"></video>':'<img src="'+esc(m.url)+'" alt="'+esc(m.alt||'Prévia da foto')+'">'):'';const video=visual.querySelector('video');if(video)video.onerror=()=>{$('#vg-editor-message').textContent='Não foi possível reproduzir esta mídia. Confira o arquivo ou use MP4/H.264 sem HDR antes de publicar.'};const img=visual.querySelector('img');if(img)img.onload=()=>updateComposition();if(video)video.onloadedmetadata=()=>updateComposition();if(img)img.onerror=()=>{$('#vg-editor-message').textContent='Não foi possível carregar esta foto. Confira a conexão ou escolha outra mídia.'};}
 paintScene();const editing=!!m&&step===0;$('#vg-scene-tools').hidden=!editing;$('#vg-scene-gesture').hidden=!editing||m.kind!=='photo';$('#vg-scene-fit').textContent=m?.fit==='cover'?'Cena inteira':'Preencher';$('#vg-scene-cover').textContent=selected===cover?'✓ Capa':'Usar como capa';$('#vg-scene-cover').disabled=uploading||saving||selected===cover;
 $('#vg-composer-empty').hidden=!!m;$('#vg-composer-overlay').hidden=!m||step===0;$('#vg-composer-title').textContent=f.elements.title.value||'Título do reel';$('#vg-composer-caption').textContent=f.elements.caption.value||'Sua legenda aparece aqui.';$('#vg-composer-cta').textContent=f.elements.cta.selectedOptions[0]?.textContent||'';$('#vg-caption-count').textContent=f.elements.caption.value.length+' / 3000';
 const type=f.elements.type.value,cta=f.elements.cta.value;const offerLabel=f.querySelector('[data-link=offer_id]');offerLabel.firstChild.textContent=fixedStay()?'Pacote da estadia (opcional)':'Estadia pronta';f.querySelector('[data-link=experience_id]').firstChild.textContent=fixedStay()?'Vínculo editorial de experiência (não adiciona à reserva)':'Experiência';f.elements.offer_id.options[0].textContent=fixedStay()?'Somente hospedagem':'Sem vínculo';$('#vg-stay-choice').hidden=cta!=='offer';$('#vg-stay-fields').hidden=!f.elements.stay_fixed.checked;$('#vg-stay-calendar-note').hidden=f.elements.stay_fixed.checked;f.querySelectorAll('[data-link]').forEach(n=>n.hidden=![type,cta,...(fixedStay()?['property','offer']:[])].includes(n.dataset.link.replace('_id',''))&&!f.elements[n.dataset.link].value);
 const rate=stayQuote?.rate_options?.find(r=>r.code===f.elements.stay_rate_code.value);$('#vg-composer-stay').hidden=!fixedStay()||!rate;$('#vg-composer-stay').innerHTML=rate?esc(f.elements.stay_check_in.value+' a '+f.elements.stay_check_out.value+' · '+f.elements.stay_guests.value+' hóspedes')+'<strong>'+money(rate.total_amount_cents)+'</strong>Hospedagem, limpeza e pacote escolhido':'';const field=f.elements[cta+'_id'],name=field?.value?field.selectedOptions[0]?.textContent:null;$('#vg-destination-summary').textContent=cta==='dates'?'Abre a escolha de datas, hóspedes e motivo para montar a reserva.':name?({property:'Abre a página do chalé: ',experience:'Abre os detalhes da experiência: ',offer:'Abre a revisão da reserva com chalé, datas e pacote: '})[cta]+name:'Escolha o vínculo para definir o destino do botão.';
 $('#vg-preview-note').textContent=step===0?(m?.kind==='photo'?'Na foto: use pinça para aproximar e arraste para reposicionar. Toque e arraste em qualquer direção. Use +/− se preferir.':'Use os controles sobre a prévia para enquadrar. O vídeo mantém os controles de reprodução.'):'Prévia da composição · use Ver como visitante para conferir inclusões e preços atuais.';
 }
 async function api(body){const fresh=await sb.auth.getSession();session=fresh.data.session;if(!session)throw Error('authentication_required');const r=await fetch(C.supabaseUrl+'/functions/v1/villegram-content',{method:'POST',headers:{'Content-Type':'application/json','X-Chalezinho-Env':'development',Authorization:'Bearer '+session.access_token},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error);return d;}
 const message=e=>({edit_conflict:'Outra pessoa alterou esta publicação. Reabra a versão atual antes de salvar.',link_required:'Vincule o chalé, a experiência ou a estadia correspondente ao tipo.',invalid_action:'A ação principal precisa do vínculo correspondente.',link_unavailable:'O vínculo está indisponível. Salve como rascunho ou escolha outra opção.',stay_unavailable:'Datas ou pacote indisponíveis. Consulte novamente ou salve como rascunho.',invalid_stay_selection:'Confira as datas, hóspedes e tarifa do reel.',invalid_publication:'Informe título, legenda e pelo menos uma mídia válida.',invalid_media_owner:'Esta mídia não pertence ao autor. Envie sua própria mídia.',media_upload_incomplete:'A mídia ainda não terminou de carregar.',authentication_required:'Sua sessão expirou. Entre novamente.'}[e.message]||'Não foi possível concluir. '+(e.message==='service_unavailable'?'O serviço está indisponível; tente novamente.':e.message));
 async function load(preserveEditor=false){data=await api({operation:'admin_list'});$('#vg-admin-root').hidden=false;$('#vg-admin-message').textContent='';renderList();links();automation();library();if(!current&&!preserveEditor)edit();await report();}
 function links(){for(const [name,rows] of [['property_id',data.properties],['experience_id',data.products],['offer_id',data.offers]]){const selected=f.elements[name].value;f.elements[name].innerHTML='<option value="">Sem vínculo</option>'+rows.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join('');f.elements[name].value=selected;}}
 function renderList(){const filter=$('#vg-filter').value;$('#vg-post-list').innerHTML=data.publications.filter(p=>filter==='all'||filter==='automatic'&&p.source==='automatic'||p.status===filter).map(p=>`<article class="vg-post-card">${p.media[p.cover_index]?.poster||p.media[p.cover_index]?.url?`<img src="${esc(p.media[p.cover_index].poster||p.media[p.cover_index].url)}" alt="Capa de ${esc(p.title)}">`:''}<h3>${esc(p.title)}</h3><p>${labels[p.type]} · ${states[p.status]}${p.featured?' · Destaque':''}</p><p>${p.source==='automatic'?'Gerada automaticamente':'Equipe'} · ordem ${p.display_order}</p><div class="vg-media-actions"><button type="button" data-preview-post="${p.id}">▷ Ver prévia</button><button type="button" data-edit="${p.id}">Editar</button></div></article>`).join('')||'<p>Nenhuma publicação nesta seleção.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-preview-post]').forEach(b=>b.onclick=async()=>{if(uploading||saving)return;b.disabled=true;$('#vg-library-message').textContent='Preparando prévia…';try{const p=data.publications.find(p=>p.id===b.dataset.previewPost);await openPublicationPreview(p,p.id);$('#vg-library-message').textContent=''}catch(e){$('#vg-library-message').textContent=message(e)}finally{b.disabled=false}});}
 function edit(id){if(uploading||saving)return;dragCancel?.();++stayVersion;clearTimeout(stayTimer);stayQuote=null;pendingUpload=null;$('#vg-upload-retry').hidden=true;current=data.publications.find(p=>p.id===id)||null;media=current?current.media.map(m=>({...m})):[];cover=current?.cover_index||0;$('#vg-editor-title').textContent=current?'Editar publicação':'Nova publicação';$('#vg-post-status').textContent=current?states[current.status]:'Ainda não salva';const published=current?.status==='published';f.querySelector('[name=draft]').hidden=published;f.querySelector('[name=published]').textContent=published?'Salvar alterações':'Publicar';const view=$('#vg-view-post');view.hidden=!published;if(published)view.href='index.html?publication='+encodeURIComponent(current.id);for(const key of ['type','property_id','experience_id','offer_id','title','caption','cta','display_order'])f.elements[key].value=current?.[key]??({type:'property',cta:'property',display_order:0}[key]||'');f.elements.stay_fixed.checked=!!current?.stay_selection||!current||current.source==='manual'&&current.cta!=='offer';const stay=current?.stay_selection||{};for(const [name,value] of Object.entries({stay_check_in:stay.check_in||'',stay_check_out:stay.check_out||'',stay_guests:stay.guests||2,stay_rate_code:stay.rate_code||''}))f.elements[name].value=value;renderStayRates();f.elements.featured.checked=!!current?.featured;f.elements.expires_at.value=current?.expires_at?new Date(Date.parse(current.expires_at)-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):'';$('#vg-archive').hidden=!current||current.status==='archived';$('#vg-editor-message').textContent='';$('#vg-upload-status').textContent='';$('#vg-upload-progress').hidden=true;selected=cover;renderMedia();setStep(current?2:0);$('#vg-publications-library').hidden=true;$('#vg-library-toggle').setAttribute('aria-expanded','false');if(id)f.scrollIntoView({block:'start',behavior:'smooth'});if(fixedStay())consultStay();}
 function library(){const photos=data.properties.flatMap(p=>(p.gallery?.length?p.gallery:[p.cover_image]).filter(Boolean).map(m=>({url:typeof m==='string'?m:m.url,name:p.name}))).concat(data.products.flatMap(p=>(p.experience_media||[]).map(m=>({url:m.media_url,name:p.name}))));$('#vg-library-photos').innerHTML=photos.map((p,i)=>'<button type="button" data-photo="'+i+'" aria-label="Adicionar foto de '+esc(p.name)+'"><img src="'+esc(p.url)+'" alt="'+esc(p.name)+'"></button>').join('');$('#vg-library-photos').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(uploading||saving)return;if(media.length>=8||media.some(m=>m.kind==='video')){$('#vg-editor-message').textContent='Use até 8 fotos, ou apenas um vídeo.';return}const p=photos[Number(b.dataset.photo)];media.push({kind:'photo',url:p.url,fit:'contain',position:50,alt:p.name});selected=media.length-1;renderMedia()});}
 function renderMedia(){selected=Math.max(0,Math.min(selected,media.length-1));updateComposition(true);dragCancel?.();if(!media.length){$('#vg-media-list').innerHTML='';return}const m=media[selected],i=selected;
 $('#vg-media-list').innerHTML='<div class="vg-media-strip" role="group" aria-label="Mídias da publicação">'+media.map((item,n)=>'<button type="button" title="Segure e arraste; Alt + setas para ordenar" data-select="'+n+'" aria-pressed="'+(n===selected)+'" aria-label="Ajustar '+(item.kind==='video'?'vídeo':'foto '+(n+1))+'"><span class="vg-media-grip" aria-hidden="true">⠿</span><img src="'+esc(item.poster||item.url)+'" alt=""><span>'+(n===cover?'Capa':n+1)+'</span></button>').join('')+'</div><p id="vg-reorder-status" role="status">Segure uma miniatura e arraste para ordenar. Com teclado, use Alt + setas.</p>'+`<article class="vg-media-card"><p>${m.kind==='video'?'Vídeo':'Foto '+(i+1)} · ${i===cover?'capa escolhida':'selecione como capa se preferir'}</p><div class="vg-media-actions"><button type="button" data-cover="${i}" ${i===cover?'disabled':''}>${i===cover?'✓ Capa escolhida':'Usar como capa'}</button>${i?`<button type="button" data-up="${i}">← Mover antes</button>`:''}<button type="button" data-remove="${i}">Remover</button></div>${m.kind==='video'?`<p>Pause o vídeo no quadro desejado.</p><button type="button" data-poster-save="${i}">Usar quadro atual como capa</button><p>A capa muda após salvar o instante escolhido.</p>`:''}</article>`;
 updateComposition();enableReordering();
 $('#vg-media-list').querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{if(uploading||saving)return;selected=Number(b.dataset.select);renderMedia()});
 $('#vg-media-list').querySelectorAll('[data-cover]').forEach(b=>b.onclick=()=>{if(uploading||saving)return;cover=Number(b.dataset.cover);renderMedia()});$('#vg-media-list').querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{if(uploading||saving)return;const i=Number(b.dataset.up);[media[i-1],media[i]]=[media[i],media[i-1]];if(cover===i)cover--;else if(cover===i-1)cover++;selected=i-1;renderMedia()});$('#vg-media-list').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(uploading||saving)return;const i=Number(b.dataset.remove);media.splice(i,1);cover=Math.max(0,Math.min(cover-(i<cover?1:0),media.length-1));renderMedia()});
 $('#vg-media-list').querySelectorAll('[data-poster-save]').forEach(b=>b.onclick=async()=>{if(uploading||saving)return;uploading=true;busy();try{const i=Number(b.dataset.posterSave),blob=await window.VillegramUpload.poster($('#vg-composer-visual video'),$('#vg-composer-visual video').currentTime||0.5),path=session.user.id+'/'+crypto.randomUUID()+'.webp';await window.VillegramUpload.upload(sb,blob,path);media[i].poster_path=path;media[i].poster=URL.createObjectURL(blob);renderMedia();$('#vg-editor-message').textContent='Capa atualizada. Salve a publicação para aplicar.'}catch(e){$('#vg-editor-message').textContent=message(e)}finally{uploading=false;busy()}});
 }
 function payload(status){return {stay_selection:fixedStay()?stayValues():null,type:f.elements.type.value,title:f.elements.title.value,caption:f.elements.caption.value,media,cover_index:cover,property_id:f.elements.property_id.value||null,experience_id:f.elements.experience_id.value||null,offer_id:f.elements.offer_id.value||null,cta:f.elements.cta.value,display_order:Number(f.elements.display_order.value),featured:f.elements.featured.checked,status,published_at:current?.published_at||null,expires_at:f.elements.expires_at.value?new Date(f.elements.expires_at.value).toISOString():null};}
 async function save(status){if(status==='draft'&&current?.status==='published')status='published';if(uploading||saving){$('#vg-editor-message').textContent='Espere a operação terminar.';return}if(status!=='archived'&&!validatePublication(status))return;saving=true;busy();try{const r=await api({operation:'save',id:current?.id,updated_at:current?.updated_at,publication:payload(status)});current=r.publication;data.publications=data.publications.filter(p=>p.id!==current.id).concat(current).sort((a,b)=>a.display_order-b.display_order);renderList();saving=false;edit(current.id);$('#vg-editor-message').textContent=current.status==='published'?'Publicação salva como publicada. Use Ver publicação no Villegram para conferir.':current.status==='archived'?'Publicação arquivada.':'Rascunho salvo. Use Publicar para colocar no feed.'}catch(e){$('#vg-editor-message').textContent=message(e)}finally{saving=false;busy()}}
 async function uploadFiles(files){if(!files?.length||uploading||saving)return;uploading=true;busy();$('#vg-upload-retry').hidden=true;$('#vg-upload-progress').hidden=false;$('#vg-upload-progress').value=0;$('#vg-upload-status').textContent='Preparando mídia…';try{
  for(const file of files){if(file.type.startsWith('video/')){if(files.length!==1||media.length)throw Error('Um vídeo deve ser publicado sozinho. Remova as fotos antes de enviar.');const inspected=await window.VillegramUpload.inspect(file),poster=await window.VillegramUpload.poster(inspected.video),path=session.user.id+'/'+crypto.randomUUID()+(file.type==='video/mp4'?'.mp4':'.webm'),poster_path=session.user.id+'/'+crypto.randomUUID()+'.webp';pendingUpload={file,path,poster,poster_path,info:{kind:'video',fit:'contain',position:50,duration:inspected.video.duration,bytes:file.size,alt:f.elements.title.value||'Vídeo do Chalezinho Ville',url:inspected.url,poster:URL.createObjectURL(poster)}};}
   else{if(media.length>=8||media.some(m=>m.kind==='video')||file.size>10*1024*1024)throw Error('Use até 8 fotos de no máximo 10 MB cada.');const blob=await window.VillegramMedia.transform(file);if(!blob)continue;pendingUpload={file:blob,path:session.user.id+'/'+crypto.randomUUID()+'.webp',info:{kind:'photo',fit:'contain',position:50,alt:f.elements.title.value||'Foto do Chalezinho Ville',url:URL.createObjectURL(blob)}};}
   await finishUpload();
  }$('#vg-upload-status').textContent='Mídia enviada. Confira a capa e o enquadramento; depois use Publicar para colocar no feed.';
 }catch(e){$('#vg-upload-status').textContent=e.message;$('#vg-upload-retry').hidden=!pendingUpload;}finally{uploading=false;busy();$('#vg-upload').value=''}}
 async function finishUpload(){const u=pendingUpload;if(!u)return;$('#vg-upload-status').textContent='Enviando mídia…';if(!u.fileUploaded){await window.VillegramUpload.upload(sb,u.file,u.path,n=>{$('#vg-upload-progress').value=n});u.fileUploaded=true;}if(u.poster)await window.VillegramUpload.upload(sb,u.poster,u.poster_path);media.push({...u.info,path:u.path,...(u.poster_path?{poster_path:u.poster_path}:{})});pendingUpload=null;selected=media.length-1;renderMedia();busy();}
 async function openPublicationPreview(publication,id){const r=await api({operation:'preview',id,publication}),p=r.publication,property=r.properties.find(x=>x.id===p.property_id),product=r.products.find(x=>x.id===p.experience_id);const card={...(p.stay_card||{}),preview:true,publication:p,publication_id:p.id,property_id:property?.id,property_name:property?.name||'Chalezinho Ville',property_code:property?.code,property_url:window.VillegramContent.propertyURL(property),product,experiences:p.stay_card?.experiences||[],guests:p.stay_card?.guests||2};window.Villegram.configurePublications([card],r.offers,r.properties);window.Villegram.open(card);}
 async function preview(){if(uploading||saving)return;if(!validatePublication())return;const video=$('#vg-composer-visual video');if(video)video.pause();$('#vg-editor-message').textContent='Preparando prévia…';try{await openPublicationPreview(payload('draft'),current?.id);$('#vg-editor-message').textContent='';}catch(e){$('#vg-editor-message').textContent=message(e)}}
 function automation(){const a=$('#vg-automation-form'),s=data.settings;a.elements.enabled.checked=s.enabled;a.elements.auto_publish.value=String(s.auto_publish);a.elements.frequency_hours.value=s.frequency_hours;a.elements.max_offers.value=s.max_offers;$('#vg-templates').innerHTML=Object.entries(s.templates).map(([type,t])=>`<fieldset data-template="${type}"><legend>${labels[type]}</legend><label class="vg-check"><input data-enabled type="checkbox" ${t.enabled?'checked':''}> Gerar este tipo</label><label>Título<input data-title value="${esc(t.title)}" maxlength="140" required></label><label>Legenda<textarea data-caption maxlength="3000" required>${esc(t.caption)}</textarea></label><label>Movimento<select data-motion>${['gentle','slow','romantic'].map(m=>'<option value="'+m+'" '+(m===t.motion?'selected':'')+'>'+({gentle:'Suave',slow:'Lento',romantic:'Romântico'}[m])+'</option>').join('')}</select></label></fieldset>`).join('');}
 async function report(){const node=$('#vg-report-data');node.textContent='Consultando resultados…';try{const d=await api({operation:'report',days:Number($('#vg-report-days').value)});node.innerHTML='<div class="vg-report-scroll"><table><thead><tr><th>Publicação</th><th>Visualizações</th><th>Visitantes</th><th>Sessões</th><th>Interesse</th><th>Cliques</th><th>Consultas de datas</th><th>Intenção de reserva</th><th>Reservas iniciadas</th><th>Reservas pagas</th></tr></thead><tbody>'+d.rows.map(r=>'<tr><th>'+esc(r.title)+'</th>'+['views','visitors','sessions','interest','clicks','date_queries','reservation_intent','reservations_started','reservations_paid'].map(k=>'<td>'+r[k]+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}catch(e){node.textContent='Não foi possível consultar as métricas. Os valores não foram tratados como zero.'}}
 async function boot(){const r=await sb.auth.getSession();session=r.data.session;if(!session){location.href='auth.html?mode=login&return=villegram-admin.html';return}try{await load()}catch(e){$('#vg-admin-message').textContent=message(e)}}
 $('#vg-new').onclick=()=>edit();$('#vg-filter').onchange=renderList;$('#vg-upload').onchange=e=>uploadFiles([...e.target.files]);$('#vg-upload-retry').onclick=async()=>{if(uploading||saving)return;uploading=true;busy();try{await finishUpload();$('#vg-upload-retry').hidden=true;$('#vg-upload-status').textContent='Upload concluído.'}catch(e){$('#vg-upload-status').textContent=e.message}finally{uploading=false;busy()}};f.onsubmit=e=>{e.preventDefault();save(e.submitter?.name==='published'||current?.status==='published'?'published':'draft')};f.elements.type.onchange=()=>{f.elements.cta.value=({property:'property',experience:'experience',offer:'offer',trust:'dates'})[f.elements.type.value];updateComposition();invalidateStay()};$('#vg-archive').onclick=()=>save('archived');$('#vg-preview').onclick=preview;$('#vg-report-days').onchange=report;
 $('#vg-stay-refresh').onclick=consultStay;for(const name of ['cta','property_id','offer_id','stay_fixed','stay_check_in','stay_check_out','stay_guests'])f.elements[name].addEventListener('change',invalidateStay);
 $('#vg-library-toggle').onclick=()=>toggleLibrary($('#vg-publications-library').hidden);$('#vg-library-close').onclick=()=>toggleLibrary(false);
 f.querySelectorAll('[data-panel] h3').forEach(h=>h.tabIndex=-1);f.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const next=Number(b.dataset.step);if(next<=step||validateThrough(next)){setStep(next,true);$('#vg-editor-message').textContent=''}});$('#vg-step-next').onclick=()=>{if(validateThrough(step+1)){setStep(step+1,true);$('#vg-editor-message').textContent=''}};$('#vg-step-back').onclick=()=>setStep(Math.max(0,step-1),true);f.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target===f.elements.title&&step<2){e.preventDefault();if(validateThrough(step+1))setStep(step+1,true)}});f.addEventListener('input',()=>updateComposition());f.addEventListener('change',()=>updateComposition());
 $('#vg-automation-form').onsubmit=async e=>{e.preventDefault();const a=e.currentTarget,templates={};a.querySelectorAll('[data-template]').forEach(n=>templates[n.dataset.template]={enabled:n.querySelector('[data-enabled]').checked,title:n.querySelector('[data-title]').value,caption:n.querySelector('[data-caption]').value,motion:n.querySelector('[data-motion]').value});try{const d=await api({operation:'save_settings',updated_at:data.settings.updated_at,settings:{enabled:a.elements.enabled.checked,auto_publish:a.elements.auto_publish.value==='true',frequency_hours:Number(a.elements.frequency_hours.value),max_offers:Number(a.elements.max_offers.value),templates}});data.settings=d.settings;$('#vg-automation-message').textContent='Configuração salva. Os modelos valem para os novos conteúdos.'}catch(e){$('#vg-automation-message').textContent=message(e)}};
 function showAutomatic(){if(!data)return;$('#vg-filter').value='automatic';renderList();toggleLibrary(true);$('#vg-publications-library').scrollIntoView({block:'start',behavior:'smooth'});}
 $('#vg-open-generated').onclick=showAutomatic;
 $('#vg-generate').onclick=async()=>{const b=$('#vg-generate');if(uploading||saving)return;b.disabled=true;const before=new Set(data.publications.map(p=>p.id));try{const result=await api({operation:'generate'});await load(true);const generated=data.publications.filter(p=>p.source==='automatic'),fresh=generated.filter(p=>!before.has(p.id)),drafts=fresh.filter(p=>p.status==='draft'||p.status==='pending_review').length;const message=result.created?result.created+' nova(s) publicação(ões). '+(drafts?drafts+' para revisar. ':'')+'Abra Ver prévia para conferir.':'Nenhuma publicação nova: os temas existentes foram preservados. Há '+generated.length+' publicação(ões) do motor automático para visualizar.';$('#vg-automation-message').textContent=message;showAutomatic();$('#vg-library-message').textContent=message;}catch(e){$('#vg-automation-message').textContent=message(e)}finally{b.disabled=false}};enableSceneGestures();boot();
})();
