(()=>{
 const filters={original:{label:'Original',css:'none'},warm:{label:'Aconchego',css:'sepia(.18) saturate(1.12) brightness(1.04)'},soft:{label:'Suave',css:'saturate(.8) contrast(.92) brightness(1.08)'},gold:{label:'Dourado',css:'sepia(.3) saturate(1.15) contrast(1.05)'},mono:{label:'P&B',css:'grayscale(1) contrast(1.08)'}};
 const templates={weekend:{label:'Fim de semana',text:'Nosso fim de semana',filter:'warm'},coffee:{label:'Café a dois',text:'Um café a dois',filter:'soft'},celebrate:{label:'Comemorar',text:'Nossa comemoração',filter:'gold'}};
 const css=m=>filters[m?.filter||'original']?.css||'none';
 function applyTemplate(m,key){const t=templates[key];if(!t)return;if((m.text_layers||[]).length>=5)throw Error('Não há espaço para outro texto. Remova um antes de aplicar o modelo.');m.text_layers=[...(m.text_layers||[]),{text:t.text,x:50,y:72,size:6,color:'#ffffff',background:'#17130f',bold:true,italic:false,strike:false}];m.filter=t.filter;}
 function controls(host,getMedia,changed,locked=()=>false){
 host.innerHTML='<button type="button" data-effects-toggle aria-expanded="false">✦ Editar estilo</button><div class="vg-effects-panel" hidden><div role="tablist" aria-label="Edição"><button type="button" role="tab" data-effects-tab="filter" aria-selected="true">Filtros</button><button type="button" role="tab" data-effects-tab="speed" aria-selected="false">Velocidade</button><button type="button" role="tab" data-effects-tab="template" aria-selected="false">Modelos</button></div><div data-effects-options></div><p data-effects-feedback role="status"></p></div>';
 let active='filter';const panel=host.querySelector('.vg-effects-panel'),toggle=host.querySelector('[data-effects-toggle]');
 function draw(){const m=getMedia();if(!m)return;host.hidden=false;const video=m.kind==='video';host.querySelector('[data-effects-tab=speed]').hidden=!video;if(!video&&active==='speed')active='filter';host.querySelectorAll('[data-effects-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.effectsTab===active)));
 const options=host.querySelector('[data-effects-options]');options.innerHTML=(active==='filter'?Object.entries(filters).map(([k,v])=>'<button type="button" data-filter="'+k+'" aria-pressed="'+((m.filter||'original')===k)+'">'+v.label+'</button>'):active==='speed'?[.5,.75,1].map(v=>'<button type="button" data-speed="'+v+'" aria-pressed="'+((m.speed||1)===v)+'">'+(v===1?'Normal':String(v).replace('.',',')+'×')+'</button>'):Object.entries(templates).map(([k,v])=>'<button type="button" data-template="'+k+'">'+v.label+'</button>')).join('');options.querySelectorAll('button').forEach(b=>{b.disabled=locked();b.onclick=()=>{if(locked())return;try{if(b.dataset.filter)m.filter=b.dataset.filter;if(b.dataset.speed)m.speed=Number(b.dataset.speed);if(b.dataset.template)applyTemplate(m,b.dataset.template);host.querySelector('[data-effects-feedback]').textContent=b.dataset.template?'Modelo aplicado. Toque no texto para personalizar.':'';changed();draw()}catch(e){host.querySelector('[data-effects-feedback]').textContent=e.message}}});}
 toggle.onclick=()=>{if(locked())return;panel.hidden=!panel.hidden;toggle.setAttribute('aria-expanded',String(!panel.hidden));draw()};host.querySelectorAll('[data-effects-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.effectsTab;draw()});return {render(){host.hidden=!getMedia();if(getMedia())draw()},close(){panel.hidden=true;toggle.setAttribute('aria-expanded','false')}};
 }
 // Share frame: only authored layers, media framing and a discreet brand handle.
 function watermark(layers=[]){const corners=[{x:6,y:90},{x:72,y:90},{x:6,y:10},{x:72,y:10}];return corners.find(c=>!layers.some(t=>Math.abs(t.y-c.y)<14&&Math.abs(t.x-(c.x+11))<32))||null;}
 function geometry(m,sw,sh,w,h){const scale=(m.fit==='contain'?Math.min:Math.max)(w/sw,h/sh)*(m.zoom||1),dw=sw*scale,dh=sh*scale;return {x:(w-dw)*(m.position_x??50)/100+w*(m.offset_x||0)/100,y:(h-dh)*(m.position??50)/100+h*(m.offset_y||0)/100,w:dw,h:dh};}
 function draw(ctx,source,m,layers){const w=ctx.canvas.width,h=ctx.canvas.height;ctx.fillStyle='#17130f';ctx.fillRect(0,0,w,h);const g=geometry(m,source.videoWidth||source.naturalWidth,source.videoHeight||source.naturalHeight,w,h);ctx.save();ctx.filter=css(m);ctx.drawImage(source,g.x,g.y,g.w,g.h);ctx.restore();
 for(const t of layers){const size=t.size*w/100,chars=[];const font=v=>(v.italic?'italic ':'')+(v.bold===false?'400 ':'600 ')+size+'px "DM Sans",sans-serif';for(const part of new Intl.Segmenter('pt-BR',{granularity:'grapheme'}).segment(t.text)){const i=part.index,c=part.segment,style={...t};for(const r of t.runs||[])if(i>=r.start&&i<r.end)Object.assign(style,r);ctx.font=font(style);chars.push({c,style,width:ctx.measureText(c).width,index:i});}
 const lines=[[]];let length=0;for(const ch of chars){if(ch.c==='\n'){lines.push([]);length=0;continue}if(length+ch.width>w*.9&&lines.at(-1).length){lines.push([]);length=0}lines.at(-1).push(ch);length+=ch.width;}
 let y=t.y*h/100-lines.length*size*.625;ctx.textBaseline='top';for(const line of lines){const total=line.reduce((a,c)=>a+c.width,0);let x=t.x*w/100-total/2;for(const ch of line){ctx.font=font(ch.style);if(ch.style.background!=='transparent'){ctx.fillStyle=ch.style.background||'#17130f';ctx.fillRect(x-1,y-2,ch.width+2,size*1.25)}ctx.fillStyle=ch.style.color||'#fff';ctx.fillText(ch.c,x,y);if(ch.style.strike){ctx.fillRect(x,y+size*.55,ch.width,Math.max(1,size/18))}x+=ch.width;}y+=size*1.25;}}
 const mark=watermark(layers);if(mark){ctx.font='500 18px "DM Sans",sans-serif';ctx.fillStyle='#ffffff';ctx.shadowColor='#000';ctx.shadowBlur=4;ctx.fillText('@chalezinhoville',mark.x*w/100,mark.y*h/100);ctx.shadowBlur=0;}
 }
 async function exportMedia(blob,m,{guest=true,progress=()=>{},signal}={}){
 const canvas=document.createElement('canvas');canvas.width=720;canvas.height=1280;const ctx=canvas.getContext('2d');if(!ctx)throw Error('export_unavailable');const layers=guest?(m.text_layers||[]):[],url=URL.createObjectURL(blob);let source,stream,recorder,audioContext,frame,timeout;
 const check=()=>{if(signal?.aborted)throw new DOMException('Cancelado','AbortError')};
 try{check();await document.fonts?.ready;
 source=document.createElement(m.kind==='video'?'video':'img');if(m.kind==='video'){source.playsInline=true;source.preload='auto';source.style.cssText='position:fixed;left:-2px;bottom:0;width:1px;height:1px;opacity:.01;pointer-events:none';document.body.append(source)}
 await new Promise((resolve,reject)=>{timeout=setTimeout(()=>reject(Error('media_timeout')),20000);source.addEventListener(m.kind==='video'?'loadeddata':'load',resolve,{once:true});source.addEventListener('error',()=>reject(Error('media_unavailable')),{once:true});source.src=url});clearTimeout(timeout);check();draw(ctx,source,m,layers);
 if(m.kind!=='video')return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('export_unavailable')),'image/jpeg',.92));
 if(!window.MediaRecorder||!canvas.captureStream)throw Error('export_unavailable');
 // MP4 is required for the Instagram export; never silently discard the edits.
 const mime=['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4'].find(v=>MediaRecorder.isTypeSupported(v));if(!mime)throw Error('mp4_unavailable');
 source.playbackRate=m.speed||1;source.preservesPitch=true;stream=canvas.captureStream(30);
 const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('audio_unavailable');audioContext=new AC();const audioSource=audioContext.createMediaElementSource(source),dest=audioContext.createMediaStreamDestination();audioSource.connect(dest);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));await audioContext.resume();
 const chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:4000000});
 return await new Promise((resolve,reject)=>{const stopError=e=>{if(recorder.state!=='inactive')recorder.stop();reject(e)};const abort=()=>stopError(new DOMException('Cancelado','AbortError'));signal?.addEventListener('abort',abort,{once:true});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=()=>stopError(Error('export_failed'));recorder.onstop=()=>{signal?.removeEventListener('abort',abort);const result=new Blob(chunks,{type:'video/mp4'});result.size?resolve(result):reject(Error('export_failed'))};source.onended=()=>recorder.stop();source.onerror=()=>stopError(Error('export_failed'));timeout=setTimeout(()=>stopError(Error('export_timeout')),(source.duration/(m.speed||1)+20)*1000);
 const paint=()=>{if(recorder.state==='inactive')return;draw(ctx,source,m,layers);progress(Math.min(99,Math.round(source.currentTime/source.duration*100)));frame=requestAnimationFrame(paint)};recorder.start(1000);source.play().then(paint).catch(stopError);});
 }finally{clearTimeout(timeout);cancelAnimationFrame(frame);source?.pause?.();source?.remove();stream?.getTracks().forEach(t=>t.stop());if(recorder&&recorder.state!=='inactive')recorder.stop();await audioContext?.close();URL.revokeObjectURL(url);}
 }
 window.VillegramEffects={filters,templates,css,applyTemplate,controls,geometry,watermark,exportMedia};
})();
