(()=>{
 const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
 function geometry(width,height,zoom=1,x=.5,y=.5){const side=Math.min(width,height)/clamp(zoom,1,4);return {side,x:clamp(x*width,side/2,width-side/2),y:clamp(y*height,side/2,height-side/2)}}
 async function crop(file){
  const prepared=await window.VillegramMedia.transform(file),url=URL.createObjectURL(prepared),dialog=document.createElement('dialog');dialog.className='vg-avatar-editor';dialog.innerHTML='<h2>Enquadre sua foto</h2><p>Arraste para centralizar. Use pinça ou os botões para aproximar.</p><div class="vg-avatar-crop" tabindex="0" role="group" aria-label="Recorte circular: arraste ou use as setas. Mais e menos ajustam o zoom."><img alt="Prévia circular da sua foto" draggable="false"></div><div class="vg-avatar-tools"><button type="button" data-zoom="-1" aria-label="Afastar">−</button><button type="button" data-center>Centralizar</button><button type="button" data-zoom="1" aria-label="Aproximar">+</button></div><p role="status"></p><div class="vg-avatar-tools"><button type="button" data-cancel>Cancelar</button><button type="button" data-confirm disabled>Usar este recorte</button></div>';document.body.append(dialog);dialog.showModal();
  const frame=dialog.querySelector('.vg-avatar-crop'),img=frame.querySelector('img'),confirm=dialog.querySelector('[data-confirm]');let w=0,h=0,z=1,x=.5,y=.5,base=null,done=false;const points=new Map();
  function paint(){if(!w)return;const g=geometry(w,h,z,x,y);x=g.x/w;y=g.y/h;Object.assign(img.style,{width:w/g.side*100+'%',height:h/g.side*100+'%',left:50-g.x/g.side*100+'%',top:50-g.y/g.side*100+'%'});dialog.querySelector('[data-zoom="-1"]').disabled=z<=1;dialog.querySelector('[data-zoom="1"]').disabled=z>=4;}
  function snapshot(){const p=[...points.values()],r=frame.getBoundingClientRect();if(!p.length||!r.width)return;base={x,y,z,side:geometry(w,h,z,x,y).side,size:r.width,cx:p.reduce((s,v)=>s+v.x,0)/p.length,cy:p.reduce((s,v)=>s+v.y,0)/p.length,d:p.length===2?Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y):0};}
  frame.onpointerdown=e=>{if(!w||points.size>=2||e.button>0)return;e.preventDefault();points.set(e.pointerId,{x:e.clientX,y:e.clientY});frame.setPointerCapture?.(e.pointerId);snapshot()};
  frame.onpointermove=e=>{if(!points.has(e.pointerId)||!base)return;e.preventDefault();points.set(e.pointerId,{x:e.clientX,y:e.clientY});const p=[...points.values()],cx=p.reduce((s,v)=>s+v.x,0)/p.length,cy=p.reduce((s,v)=>s+v.y,0)/p.length;z=clamp(base.z*(p.length===2&&base.d?Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y)/base.d:1),1,4);x=base.x-(cx-base.cx)/base.size*base.side/w;y=base.y-(cy-base.cy)/base.size*base.side/h;paint()};
  const end=e=>{points.delete(e.pointerId);base=null;snapshot()};frame.onpointerup=end;frame.onpointercancel=end;frame.onlostpointercapture=end;
  dialog.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>{z=clamp(z+Number(b.dataset.zoom)*.2,1,4);paint()});dialog.querySelector('[data-center]').onclick=()=>{x=y=.5;z=1;paint()};frame.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')x-=.025;else if(e.key==='ArrowRight')x+=.025;else if(e.key==='ArrowUp')y-=.025;else if(e.key==='ArrowDown')y+=.025;else z=clamp(z+(e.key==='-'?-.2:.2),1,4);paint()};
  return new Promise(resolve=>{const finish=b=>{if(done)return;done=true;URL.revokeObjectURL(url);dialog.close();dialog.remove();resolve(b)};dialog.querySelector('[data-cancel]').onclick=()=>finish(null);dialog.oncancel=e=>{e.preventDefault();finish(null)};img.onload=()=>{w=img.naturalWidth;h=img.naturalHeight;paint();confirm.disabled=false};img.onerror=()=>{dialog.querySelector('[role=status]').textContent='Não foi possível abrir esta foto. Cancele e escolha outra.'};img.src=url;
   confirm.onclick=()=>{confirm.disabled=true;const g=geometry(w,h,z,x,y),c=document.createElement('canvas');c.width=c.height=512;try{c.getContext('2d').drawImage(img,g.x-g.side/2,g.y-g.side/2,g.side,g.side,0,0,512,512);c.toBlob(b=>{if(b)finish(b);else{confirm.disabled=false;dialog.querySelector('[role=status]').textContent='Não foi possível recortar. Tente novamente.'}},'image/webp',.9)}catch{confirm.disabled=false;dialog.querySelector('[role=status]').textContent='Não foi possível recortar. Tente novamente.'}};
  });
 }
 window.VillegramAvatar={crop,geometry};
})();
