(()=>{
 const C=window.CHALEZINHO_CONFIG,endpoint=C.supabaseUrl+'/functions/v1/villegram-content',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let data=null,offerCards=[],busy=false,home=false,lastFeed=[],offersReady=false,offerWait=null;
 const pages={CH1:'chale-premium.html',CH2:'chale-com-hidro.html',CH3:'chale-romantico.html'};
 function propertyURL(p){return pages[p?.code]||'imovel.html?chalet='+encodeURIComponent(p?.code||'')}
 async function request(body={}){let s;try{s=(await window.villegramAuth?.auth.getSession())?.data?.session}catch{}const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-Chalezinho-Env':'development',...(s?{Authorization:'Bearer '+s.access_token}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok||!d.ok)throw Object.assign(Error(d.error),{status:r.status});return d;}
 function cards(){if(!data)return [];let count=0;return data.publications.map(p=>{const property=data.properties.find(x=>x.id===p.property_id),product=data.products.find(x=>x.id===p.experience_id);const preferred=window.VillegramSignals?.declared()||{},candidates=offerCards.filter(c=>c.offer_id===p.offer_id&&(!p.property_id||c.property_id===p.property_id));const live=p.stay_selection?p.stay_card||null:p.offer_id?[...candidates].sort((a,b)=>{const distance=c=>preferred.check_in?Math.abs(Date.parse(c.check_in)-Date.parse(preferred.check_in)):0;return distance(a)-distance(b)})[0]:null;
  if((p.type==='offer'||p.cta==='offer')&&!live)return null;if(p.type==='offer'&&!p.stay_selection&&count++>=data.max_offers)return null;
  return {...(live||{}),publication:p,publication_id:p.id,property_id:property?.id,property_code:property?.code,property_name:property?.name||'Chalezinho Ville',offer_name:p.title,image:p.media[p.cover_index]?.poster||p.media[p.cover_index]?.url,title:p.title,caption:p.caption,product,purposes:product?.travel_purposes||data.products.filter(x=>(data.offers.find(o=>o.id===p.offer_id)?.product_ids||[]).includes(x.id)).flatMap(x=>x.travel_purposes||[]),property_url:propertyURL(property),experiences:live?.experiences||[],guests:live?.guests||2};}).filter(Boolean);}
 function rank(pool,previous=null){const declared=window.VillegramSignals?.declared()||{},interest=window.VillegramSignals?.interest()||{};const targets=(data?.publications||[]).map(p=>({p,s:interest[p.id]||{}}));return [...pool].map((c,i)=>{const p=c.publication,s=interest[p?.id]||{};const explicit=(s.like||0)*2+(s.property_open||0)*3+(s.experience_open||0)*3+(s.reservation_start||0)*5;const related=targets.filter(x=>x.p.id!==p?.id&&(c.property_id&&x.p.property_id===c.property_id||p?.experience_id&&x.p.experience_id===p.experience_id)).reduce((n,x)=>n+(x.s.property_open||0)*2+(x.s.experience_open||0)*2+(x.s.like||0),0);return {c,i,score:Math.min(5,related)+(p?.featured?20:0)+(declared.purpose&&c.purposes?.includes(declared.purpose)?6:0)+(declared.check_in===c.check_in&&declared.check_out===c.check_out?10:0)+Math.min(8,explicit)-(previous?.property_id&&c.property_id===previous.property_id?7:0)-(previous?.publication?.type===p?.type?5:0)};}).sort((a,b)=>b.score-a.score||a.i-b.i).map(x=>x.c);}
 function mix(pool){const output=[];while(pool.length){const next=rank(pool,output.at(-1))[0];output.push(next);pool=pool.filter(x=>x!==next)}return output;}
 function saved(){try{return JSON.parse(sessionStorage.getItem('villegram-position')||'null')}catch{return null}}
 function refresh(){lastFeed=mix(cards());window.Villegram.configurePublications?.(lastFeed,data?.offers||[],data?.properties||[],{totalReady:offersReady||!(data?.publications||[]).some(p=>p.type==='offer'&&!p.stay_selection)});return lastFeed;}
 async function load(){if(busy)return;busy=true;try{data=await request({operation:'feed'});refresh();if(home&&!document.querySelector('#villegram'))enter();if(!offerWait)document.querySelector('#villegram-home-status')?.remove()}catch{const node=document.querySelector('#villegram-home-status');if(node)node.innerHTML='O Villegram não carregou. <button type="button" id="vg-retry">Tentar novamente</button> <a href="reservar.html">Escolher minhas datas</a> <a href="index.html?view=site">Site completo</a>';document.querySelector('#vg-retry')?.addEventListener('click',load);if(home){home=false;document.body.classList.remove('villegram-home-loading')}}finally{busy=false}}
 function enter(){if(!data){home=true;load();return}const shared=new URLSearchParams(location.search).get('publication');if(shared&&data.publications.some(p=>p.id===shared&&p.type==='offer'&&!p.stay_selection)&&!offersReady){if(!document.querySelector('#villegram-home-status')){const wait=document.createElement('div');wait.id='villegram-home-status';wait.setAttribute('role','status');wait.innerHTML='Consultando a estadia compartilhada… <a href="index.html?view=site">Site completo</a>';document.body.append(wait)}offerWait ||= setTimeout(()=>{offersReady=true;offerWait=null;enter()},16000);return}const feed=refresh(),position=saved(),chosen=feed.find(c=>c.publication_id===(shared||position?.id));if(!feed.length){home=false;document.body.classList.remove('villegram-home-loading');document.querySelector('#villegram-home-status')?.remove();let notice=document.querySelector('#villegram-empty-status');if(!notice){notice=document.createElement('p');notice.id='villegram-empty-status';notice.setAttribute('role','status');document.querySelector('main')?.prepend(notice)}notice.innerHTML='Ainda não há publicações disponíveis. Explore os chalés abaixo ou <a href="reservar.html">escolha suas datas</a>.';return}document.querySelector('#villegram-empty-status')?.remove();home=true;document.body.classList.remove('villegram-home-loading');document.querySelector('#villegram-home-status')?.remove();window.Villegram.openHome(chosen||feed[0],{restored:!!chosen});if(shared&&!chosen){const notice=document.querySelector('#villegram .vg-status');if(notice)notice.textContent='Esta publicação não está disponível agora. Explore outras experiências ou escolha suas datas.'}}
 function leave(){home=false;document.body.classList.remove('villegram-home-loading')}
 function mounted(){const mobile=matchMedia('(max-width:700px)');const q=new URLSearchParams(location.search);const conventional=q.get('view')==='site'||location.hash;const entry=document.createElement('button');entry.type='button';entry.className='villegram-home-entry';entry.innerHTML=window.Villegram.navLabel?window.Villegram.navLabel('feed','Villegram'):'Villegram';entry.onclick=()=>{home=true;enter()};document.querySelector('header nav')?.append(entry);
  const nav=document.createElement('nav');nav.className='villegram-mobile-nav';nav.setAttribute('aria-label','Navegação principal no celular');const label=(name,text)=>window.Villegram.navLabel?window.Villegram.navLabel(name,text):text;nav.innerHTML='<button type="button" data-feed>'+label('feed','Villegram')+'</button><a href="index.html?view=site#colecao">'+label('chalets','Chalés')+'</a><a href="reservar.html">'+label('dates','Escolher datas')+'</a><a href="conta.html">'+label('account','Minha conta')+'</a>';nav.querySelector('button').onclick=()=>{home=true;enter()};document.body.append(nav);
  if(mobile.matches&&!conventional||q.has('publication')){home=true;document.body.classList.add('villegram-home-loading');const status=document.createElement('div');status.id='villegram-home-status';status.setAttribute('role','status');status.innerHTML='<strong>VILLEGRAM</strong><p>Preparando suas próximas descobertas…</p><a href="index.html?view=site">Ver o site completo</a>';document.body.append(status)}
  load();mobile.addEventListener('change',e=>{if(!e.matches&&window.Villegram.isHome?.()){window.Villegram.close();leave()}});
 }
 window.VillegramContent={request,propertyURL,rank,enter,leave,setOffers(cards){offerCards=cards;offersReady=true;clearTimeout(offerWait);offerWait=null;refresh();if(home&&data&&!document.querySelector('#villegram'))enter()},saved,async datesSheet(body){body.innerHTML='<p>Carregando opções…</p>';try{const r=await fetch(C.bookingEngine+'?action=config',{headers:{'X-Chalezinho-Env':'development'},signal:AbortSignal.timeout(15000)}),d=await r.json();if(!r.ok||!d.ok)throw Error();body.innerHTML='<form class="vg-dates"><label>Entrada<input name="check_in" type="date" required></label><label>Saída<input name="check_out" type="date" required></label><label>Hóspedes<select name="guests"><option value="2">2 hóspedes</option><option value="1">1 hóspede</option></select></label><label>Motivo da viagem (opcional)<select name="purpose"><option value="">Sem preferência</option>'+d.purposes.map(p=>'<option value="'+esc(p.code)+'">'+esc(p.label)+'</option>').join('')+'</select></label><button type="submit">Consultar minhas datas</button><p role="status"></p></form>';const f=body.querySelector('form'),today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());f.elements.check_in.min=today;f.elements.check_out.min=today;f.elements.check_in.onchange=()=>{f.elements.check_out.min=f.elements.check_in.value};const preference=window.VillegramSignals?.declared()||{};for(const k of ['check_in','check_out','guests','purpose'])if(preference[k])f.elements[k].value=preference[k];f.onsubmit=e=>{e.preventDefault();if(f.elements.check_out.value<=f.elements.check_in.value){f.querySelector('[role=status]').textContent='Escolha uma saída depois da entrada.';return}const values=Object.fromEntries(new FormData(f));window.VillegramSignals?.declare(values);window.VillegramSignals?.mark('dates_query');window.Villegram.remember();location.href='reservar.html?'+new URLSearchParams({...values,from:'dates',mode:'stay'})};}catch{body.innerHTML='<p>Não foi possível consultar as opções agora.</p><a href="reservar.html">Escolher minhas datas na reserva</a>'}}};
 if(document.querySelector('.hero')&&!document.querySelector('main[data-property-code],#property-detail'))mounted();
})();
