(()=>{
 // Browsers decode EXIF orientation before drawing. Re-encoding removes the stale EXIF
 // tag, so saved rotations cannot be applied twice by another surface.
 async function decode(blob){if(window.createImageBitmap)return createImageBitmap(blob,{imageOrientation:'from-image'});return new Promise((resolve,reject)=>{const url=URL.createObjectURL(blob),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(Error('image_decode_failed'))};image.src=url})}
 async function transform(blob,turns=0,crop='full',position=50){const image=await decode(blob);if(image.width*image.height>40000000){image.close?.();throw Error('image_too_large')}const angle=((turns%4)+4)%4,w=image.width,h=image.height,canvas=document.createElement('canvas');canvas.width=angle%2?h:w;canvas.height=angle%2?w:h;const ctx=canvas.getContext('2d');ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(angle*Math.PI/2);ctx.drawImage(image,-w/2,-h/2);image.close?.();let output=canvas;if(crop!=='full'){const target=crop==='portrait'?9/16:4/3,sw=Math.min(canvas.width,canvas.height*target),sh=Math.min(canvas.height,canvas.width/target),c=document.createElement('canvas');c.width=Math.round(sw);c.height=Math.round(sh);c.getContext('2d').drawImage(canvas,(canvas.width-sw)*position/100,(canvas.height-sh)*position/100,sw,sh,0,0,c.width,c.height);output=c}if(output.width>1920||output.height>1920){const c=document.createElement('canvas'),scale=1920/Math.max(output.width,output.height);c.width=Math.round(output.width*scale);c.height=Math.round(output.height*scale);c.getContext('2d').drawImage(output,0,0,c.width,c.height);output=c}return new Promise((resolve,reject)=>output.toBlob(b=>b?resolve(b):reject(Error('image_encode_failed')),'image/webp',.9))}
 async function editor(blob){
 const dialog=document.createElement('dialog');dialog.className='vg-media-editor';dialog.innerHTML='<h2>Enquadre a foto</h2><p>Veja o recorte enquanto ajusta. A foto original é preservada até confirmar.</p><div class="vg-crop-frame"><img alt="Prévia do enquadramento" draggable="false"></div><div class="vg-crop-tools"><button type="button" data-left>↶ Girar</button><button type="button" data-right>↷ Girar</button></div><label>Formato<select><option value="full">Foto inteira</option><option value="portrait">Vertical · 9:16</option><option value="landscape">Horizontal · 4:3</option></select></label><label>Posição do recorte<input type="range" min="0" max="100" value="50"></label><p data-crop-note role="status"></p><div class="vg-crop-tools"><button type="button" data-save>Usar esta foto</button><button type="button" data-cancel>Cancelar</button></div>';document.body.append(dialog);dialog.showModal();let turns=0,url,version=0,closed=false;
 const image=dialog.querySelector('img'),frame=dialog.querySelector('.vg-crop-frame'),format=dialog.querySelector('select'),position=dialog.querySelector('input'),save=dialog.querySelector('[data-save]');
 function framePreview(){const crop=format.value,ratio=crop==='portrait'?9/16:crop==='landscape'?4/3:(image.naturalWidth/image.naturalHeight||1);frame.style.aspectRatio=String(ratio);frame.style.setProperty('--vg-crop-ratio',String(ratio));image.style.objectFit=crop==='full'?'contain':'cover';image.style.objectPosition=position.value+'% '+position.value+'%';position.disabled=crop==='full';dialog.querySelector('[data-crop-note]').textContent=crop==='full'?'A foto inteira está visível. Escolha um formato para recortar.':'O quadro mostra o recorte que será salvo.';}
 async function rotatedPreview(){save.disabled=true;const v=++version;try{const b=await transform(blob,turns,'full');if(closed||v!==version)return;URL.revokeObjectURL(url);url=URL.createObjectURL(b);image.onload=framePreview;image.src=url;framePreview();save.disabled=false}catch{dialog.querySelector('[data-crop-note]').textContent='Não foi possível preparar esta foto. Cancele e tente outro arquivo.'}}
 dialog.querySelector('[data-left]').onclick=()=>{turns--;rotatedPreview()};dialog.querySelector('[data-right]').onclick=()=>{turns++;rotatedPreview()};format.onchange=framePreview;position.oninput=framePreview;
 return new Promise(resolve=>{const done=b=>{closed=true;++version;URL.revokeObjectURL(url);dialog.close();dialog.remove();resolve(b)};save.onclick=async()=>{save.disabled=true;try{const b=await transform(blob,turns,format.value,Number(position.value));if(!closed)done(b)}catch{dialog.querySelector('[data-crop-note]').textContent='Não foi possível salvar o recorte. Tente novamente.';save.disabled=false}};dialog.querySelector('[data-cancel]').onclick=()=>done(null);dialog.oncancel=e=>{e.preventDefault();done(null)};rotatedPreview()});
 }
 window.VillegramMedia={transform,editor};
})();
