(()=>{
 const C=window.CHALEZINHO_CONFIG,endpoint=C.supabaseUrl+'/functions/v1/villegram-content',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let data=null,offerCards=[],busy=false,home=false,lastFeed=[];
 const pages={CH1:'chale-premium.html',CH2:'chale-com-hidro.html',CH3:'chale-romantico.html'};
 function propertyURL(p){return pages[p?.code]||'imovel.html?chalet='+encodeURIComponent(p?.code||'')}
 async function request(body={}){let s;try{s=(await window.villegramAuth?.auth.getSession())?.data?.session}catch{}const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-Chalezinho-Env':'development',...(s?{Authorization:'Bearer '+s.access_token}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok||!d.ok)throw Object.assign(Error(d.error),{status:r.status});return d;}
 function cards(){if(!data)return [];let count=0;return data.publications.map(p=>{const property=data.properties.find(x=>x.id===p.property_id),product=data.products.find(x=>x.id===p.experience_id);const live=p.offer_id?offerCards.find(c=>c.offer_id===p.offer_id&&(!p.property_id||c.property_id===p.property_id)):null;
  if(p.type==='offer'&&(!live||count++>=data.max_offers))return null;
  return {...(live||{}),publication:p,publication_id:p.id,property_id:property?.id,property_code:property?.code,property_name:property?.name||'Chalezinho Ville',offer_name:p.title,image:p.media[p.cover_index]?.poster||p.media[p.cover_index]?.url,title:p.title,caption:p.caption,product,purposes:product?.travel_purposes||[],property_url:propertyURL(property),experiences:live?.experiences||[],guests:live?.guests||2};}).filter(Boolean);}
 function rank(pool,previous=null){const declared=window.VillegramSignals?.declared()||{},interest=window.VillegramSignals?.interest()||{};return [...pool].map((c,i)=>{const p=c.publication,s=interest[p?.id]||{};const explicit=(s.like||0)*2+(s.property_open||0)*3+(s.experience_open||0)*3+(s.reservation_start||0)*5;return {c,i,score:(p?.featured?20:0)+(declared.purpose&&c.purposes?.includes(declared.purpose)?6:0)+(declared.check_in===c.check_in&&declared.check_out===c.check_out?10:0)+Math.min(8,explicit)-(previous?.property_id&&c.property_id===previous.property_id?7:0)-(previous?.publication?.type===p?.type?5:0)};}).sort((a,b)=>b.score-a.score||a.i-b.i).map(x=>x.c);}
 function mix(pool){const output=[];while(pool.length){const next=rank(pool,output.at(-1))[0];output.push(next);pool=pool.filter(x=>x!==next)}return output;}
 function saved(){try{return JSON.parse(sessionStorage.getItem('villegram-position')||'null')}catch{return null}}
 function refresh(){lastFeed=mix(cards());window.Villegram.configurePublications?.(lastFeed,data?.offers||[],data?.properties||[]);return lastFeed;}
 async function load(){if(busy)return;busy=true;try{data=await request({operation:'feed'});refresh();if(home&&!document.querySelector('#villegram'))enter();document.querySelector('#villegram-home-status')?.remove()}catch{const node=document.querySelector('#villegram-home-status');if(node)node.innerHTML='O Villegram não carregou. <button type="button" id="vg-retry">Tentar novamente</button> <a href="reservar.html">Escolher minhas datas</a>';document.querySelector('#vg-retry')?.addEventListener('click',load);if(home){home=false;document.body.classList.remove('villegram-home-loading')}}finally{busy=false}}
 function enter(){if(!data){home=true;load();return}const feed=refresh(),position=saved(),shared=new URLSearchParams(location.search).get('publication'),chosen=feed.find(c=>c.publication_id===(shared||position?.id));if(!feed.length){home=false;document.body.classList.remove('villegram-home-loading');document.querySelector('#villegram-home-status')?.remove();return}home=true;document.body.classList.remove('villegram-home-loading');window.Villegram.openHome(chosen||feed[0],{restored:!!chosen});}
 function leave(){home=false;document.body.classList.remove('villegram-home-loading')}
 function mounted(){const mobile=matchMedia('(max-width:700px)');const q=new URLSearchParams(location.search);const conventional=q.get('view')==='site'||location.hash;const entry=document.createElement('button');entry.type='button';entry.className='villegram-home-entry';entry.textContent='Villegram';entry.onclick=()=>{home=true;enter()};document.querySelector('header nav')?.append(entry);
  const nav=document.createElement('nav');nav.className='villegram-mobile-nav';nav.setAttribute('aria-label','Navegação principal no celular');nav.innerHTML='<button type="button" data-feed>Villegram</button><a href="index.html?view=site#colecao">Chalés</a><a href="reservar.html">Escolher datas</a><a href="conta.html">Minha conta</a>';nav.querySelector('button').onclick=()=>{home=true;enter()};document.body.append(nav);
  if(mobile.matches&&!conventional){home=true;document.body.classList.add('villegram-home-loading');const status=document.createElement('div');status.id='villegram-home-status';status.setAttribute('role','status');status.innerHTML='<strong>VILLEGRAM</strong><p>Preparando suas próximas descobertas…</p><a href="index.html?view=site">Ver o site completo</a>';document.body.append(status)}
  load();mobile.addEventListener('change',e=>{if(!e.matches&&window.Villegram.isHome?.()){window.Villegram.close();leave()}});
 }
 window.VillegramContent={request,propertyURL,rank,enter,leave,setOffers(cards){offerCards=cards;refresh()},saved,async datesSheet(body){body.innerHTML='<p>Carregando opções…</p>';try{const r=await fetch(C.bookingEngine+'?action=config',{headers:{'X-Chalezinho-Env':'development'},signal:AbortSignal.timeout(15000)}),d=await r.json();if(!r.ok||!d.ok)throw Error();body.innerHTML='<form class="vg-dates"><label>Entrada<input name="check_in" type="date" required></label><label>Saída<input name="check_out" type="date" required></label><label>Hóspedes<select name="guests"><option value="2">2 hóspedes</option><option value="1">1 hóspede</option></select></label><label>Motivo da viagem (opcional)<select name="purpose"><option value="">Sem preferência</option>'+d.purposes.map(p=>'<option value="'+esc(p.code)+'">'+esc(p.label)+'</option>').join('')+'</select></label><button type="submit">Consultar minhas datas</button><p role="status"></p></form>';const f=body.querySelector('form'),today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());f.elements.check_in.min=today;f.elements.check_out.min=today;f.elements.check_in.onchange=()=>{f.elements.check_out.min=f.elements.check_in.value};const preference=window.VillegramSignals?.declared()||{};for(const k of ['check_in','check_out','guests','purpose'])if(preference[k])f.elements[k].value=preference[k];f.onsubmit=e=>{e.preventDefault();if(f.elements.check_out.value<=f.elements.check_in.value){f.querySelector('[role=status]').textContent='Escolha uma saída depois da entrada.';return}const values=Object.fromEntries(new FormData(f));window.VillegramSignals?.declare(values);window.VillegramSignals?.mark('dates_query');window.Villegram.remember();location.href='reservar.html?'+new URLSearchParams({...values,from:'dates',mode:'stay'})};}catch{body.innerHTML='<p>Não foi possível consultar as opções agora.</p><a href="reservar.html">Escolher minhas datas na reserva</a>'}}};
 if(document.querySelector('.hero')&&!document.querySelector('main[data-property-code],#property-detail'))mounted();
})();
