(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n))),color=v=>/^#[\da-f]{6}$/i.test(v)?v:'#ffffff';
 const weight=t=>t.bold===false?400:600,plain=el=>el.innerText??el.textContent;
 function markup(layers=[]){return '<div class="vg-text-stage">'+layers.slice(0,5).map(t=>'<span class="vg-text-sticker" style="left:'+clamp(t.x??50,5,95)+'%;top:'+clamp(t.y??30,5,95)+'%;font-size:'+clamp(t.size??6,3,9)+'cqw;font-weight:'+weight(t)+';font-style:'+(t.italic===true?'italic':'normal')+';text-decoration:'+(t.strike===true?'line-through':'none')+';color:'+color(t.color)+';background:'+(t.background==='transparent'?'transparent':color(t.background||'#17130f'))+'">'+esc(t.text)+'</span>').join('')+'</div>'}
 const svg=path=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+path+'</svg>';
 function editor({screen,getMedia,onChange,isBusy}){
  const stage=document.createElement('div'),tools=document.createElement('div'),menu=document.createElement('div'),palette=document.createElement('div');
  stage.className='vg-text-stage vg-text-edit-stage';tools.className='vg-text-tools';tools.innerHTML='<button type="button" aria-label="Adicionar texto sobre a cena">Aa <span>Texto</span></button><button type="button" data-text-finish aria-label="Concluir texto" hidden>'+svg('<path d="m5 12 4 4L19 6"/>')+'</button>';
  menu.className='vg-text-orbit';menu.setAttribute('role','toolbar');menu.setAttribute('aria-label','Formatar texto');menu.hidden=true;
  menu.innerHTML='<button type="button" data-format="color" aria-label="Cor da fonte" title="Cor da fonte"><span class="vg-font-color">A</span></button><button type="button" data-format="background" aria-label="Fundo do texto" title="Fundo do texto">'+svg('<rect x="4" y="4" width="16" height="16" rx="4"/><path d="M8 16 16 8"/>')+'</button><button type="button" data-format="bold" aria-label="Negrito" title="Negrito"><b>N</b></button><button type="button" data-format="italic" aria-label="Itálico" title="Itálico"><i>I</i></button><button type="button" data-format="strike" aria-label="Tachado" title="Tachado"><s>S</s></button><button type="button" data-delete aria-label="Excluir texto" title="Excluir texto">'+svg('<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/>')+'</button><button type="button" data-text-edit aria-label="Digitar texto" title="Digitar texto">'+svg('<path d="m15 5 4 4M4 20l4-1L20 7a2.8 2.8 0 0 0-4-4L4 15z"/>')+'</button>';
  palette.className='vg-text-swatches';palette.hidden=true;palette.setAttribute('role','group');screen.append(stage,tools,menu,palette);
  let active=-1,typing=false,source=null,menuOpen=false,paletteKind=null;
  const list=()=>getMedia()?.text_layers||[],item=()=>list()[active],node=()=>stage.children[active];
  function confine(el,t){const r=stage.getBoundingClientRect(),b=el.getBoundingClientRect();if(!r.width||!r.height)return;t.x=clamp(t.x,Math.max(5,Math.min(50,b.width/r.width*50)),Math.min(95,Math.max(50,100-b.width/r.width*50)));t.y=clamp(t.y,Math.max(5,Math.min(50,b.height/r.height*50)),Math.min(95,Math.max(50,100-b.height/r.height*50)));el.style.left=t.x+'%';el.style.top=t.y+'%'}
  function paint(el,t){Object.assign(el.style,{left:t.x+'%',top:t.y+'%',fontSize:t.size+'cqw',fontWeight:weight(t),fontStyle:t.italic?'italic':'normal',textDecoration:t.strike?'line-through':'none',color:t.color,background:t.background});confine(el,t)}
  function positionMenu(){const el=node();menu.hidden=!menuOpen||!el;palette.hidden=!menuOpen||!paletteKind;if(!el||!menuOpen)return;const s=screen.getBoundingClientRect(),r=el.getBoundingClientRect(),width=Math.min(264,s.width-16),height=148;const x=clamp(r.left+r.width/2-s.left-width/2,8,Math.max(8,s.width-width-8));const above=r.top-s.top-height-8;const y=above>=8?above:clamp(r.bottom-s.top+8,8,Math.max(8,s.height-height-8));Object.assign(menu.style,{left:x+'px',top:y+'px',width:width+'px'});Object.assign(palette.style,{left:'8px',right:'8px',top:clamp(y+height+4,8,Math.max(8,s.height-100))+'px'});for(const key of ['bold','italic','strike'])menu.querySelector('[data-format='+key+']').setAttribute('aria-pressed',String(key==='bold'?weight(item())===600:item()[key]===true));menu.querySelector('.vg-font-color').style.borderColor=item().color}
  function notify(){onChange();render()}
  function closeMenu(){menuOpen=false;paletteKind=null;menu.hidden=true;palette.hidden=true}
  function finish(keepMenu=false){if(typing){const el=node(),t=item();if(t&&el){t.text=plain(el).slice(0,280);el.setAttribute('contenteditable','false');el.blur();if(!t.text.trim()){list().splice(active,1);active=-1}}typing=false;tools.querySelector('[data-text-finish]').hidden=true;notify()}if(!keepMenu)closeMenu()}
  function caretEnd(el){const selection=window.getSelection(),range=document.createRange();range.selectNodeContents(el);range.collapse(false);selection.removeAllRanges();selection.addRange(range)}
  function startTyping(index){if(isBusy())return;if(typing&&active!==index)finish();active=index;typing=true;closeMenu();const el=node();if(!el)return;el.setAttribute('contenteditable','true');el.setAttribute('role','textbox');el.setAttribute('aria-label','Texto sobre a cena');el.setAttribute('aria-multiline','true');tools.querySelector('[data-text-finish]').hidden=false;el.focus();caretEnd(el)}
  function showMenu(index){active=index;menuOpen=true;paletteKind=null;positionMenu()}
  function bind(el,t,index){
   let points=new Map(),snapshot=null,moved=false;
   const capture=()=>{const p=[...points.values()];snapshot={points:p.map(v=>({...v})),x:t.x,y:t.y,size:t.size,rect:stage.getBoundingClientRect(),distance:p.length===2?Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y):0}};
   el.onpointerdown=e=>{if(isBusy()||e.button>0||points.size>=2)return;e.stopPropagation();if(typing&&active!==index){finish();showMenu(index);return}if(points.size===0)moved=false;points.set(e.pointerId,{x:e.clientX,y:e.clientY});active=index;if(!typing||points.size===2)e.preventDefault();if(points.size===2){typing=false;el.setAttribute('contenteditable','false');el.blur();tools.querySelector('[data-text-finish]').hidden=true;closeMenu();moved=true}el.setPointerCapture?.(e.pointerId);capture()};
   el.onpointermove=e=>{if(!points.has(e.pointerId)||!snapshot)return;e.stopPropagation();points.set(e.pointerId,{x:e.clientX,y:e.clientY});const p=[...points.values()],r=snapshot.rect;if(!r.width||!r.height)return;const dx=p[0].x-snapshot.points[0].x,dy=p[0].y-snapshot.points[0].y;if(points.size===2){e.preventDefault();moved=true;t.size=clamp(snapshot.size*Math.hypot(p[1].x-p[0].x,p[1].y-p[0].y)/Math.max(1,snapshot.distance),3,9)}else{if(!moved&&Math.hypot(dx,dy)<6)return;e.preventDefault();moved=true;typing=false;el.setAttribute('contenteditable','false');el.blur();tools.querySelector('[data-text-finish]').hidden=true;t.x=clamp(snapshot.x+dx/r.width*100,5,95);t.y=clamp(snapshot.y+dy/r.height*100,5,95)}closeMenu();paint(el,t)};
   const end=e=>{if(!points.has(e.pointerId))return;e.stopPropagation();points.delete(e.pointerId);if(points.size){capture();return}snapshot=null;if(moved){typing=false;notify()}};
   el.onpointerup=end;el.onpointercancel=end;
   el.onclick=()=>{if(moved){moved=false;return}if(!isBusy())showMenu(index)};el.ondblclick=()=>startTyping(index);
   el.oninput=()=>{t.text=plain(el).slice(0,280);if(plain(el).length>280){el.textContent=t.text;caretEnd(el)}paint(el,t);positionMenu()};
   el.onpaste=e=>{e.preventDefault();const text=e.clipboardData?.getData('text/plain')||'',selection=window.getSelection();if(!selection.rangeCount)return;const range=selection.getRangeAt(0);if(!el.contains(range.commonAncestorContainer))return;range.deleteContents();const insert=document.createTextNode(text);range.insertNode(insert);range.setStartAfter(insert);range.collapse(true);selection.removeAllRanges();selection.addRange(range);el.dispatchEvent(new Event('input',{bubbles:true}))};
   el.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();finish();return}if(typing){if((e.ctrlKey||e.metaKey)&&['b','i'].includes(e.key.toLowerCase())){e.preventDefault();const key=e.key.toLowerCase()==='b'?'bold':'italic';t[key]=key==='bold'?weight(t)!==600:!t[key];paint(el,t);return}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();finish()}return}if(e.key==='Enter'||e.key===' '){e.preventDefault();startTyping(index);return}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();active=index;remove();return}if(e.key.startsWith('Arrow')||['+','-','='].includes(e.key)){e.preventDefault();e.stopPropagation();if(e.key==='ArrowLeft')t.x-=2;if(e.key==='ArrowRight')t.x+=2;if(e.key==='ArrowUp')t.y-=2;if(e.key==='ArrowDown')t.y+=2;if(e.key==='+'||e.key==='=')t.size=clamp(t.size+.5,3,9);if(e.key==='-')t.size=clamp(t.size-.5,3,9);paint(el,t);notify()}};
  }
  function render(){const media=getMedia();if(source!==media){typing=false;active=-1;closeMenu();source=media;tools.querySelector('[data-text-finish]').hidden=true}if(typing)return;tools.hidden=!media;stage.innerHTML='';list().forEach((t,i)=>{const el=document.createElement('div');el.className='vg-text-sticker';el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label','Editar texto: '+t.text);el.setAttribute('data-placeholder','Digite aqui');el.setAttribute('spellcheck','true');el.textContent=t.text;stage.append(el);paint(el,t);bind(el,t,i)});positionMenu()}
  function remove(){if(isBusy())return;typing=false;list().splice(active,1);active=-1;tools.querySelector('[data-text-finish]').hidden=true;closeMenu();notify();tools.querySelector('button').focus()}
  function showPalette(kind){paletteKind=paletteKind===kind?null:kind;palette.innerHTML='';if(!paletteKind){positionMenu();return}palette.setAttribute('aria-label',kind==='color'?'Cor da fonte':'Cor do fundo');const options=['#ffffff','#17130f','#e5cc97','#f29cbb','#e35454','#91c8e4','#96cba8'];if(kind==='background')options.unshift('transparent');for(const value of options){const b=document.createElement('button');b.type='button';b.className='vg-text-swatch';b.style.background=value==='transparent'?'repeating-linear-gradient(45deg,#aaa 0 5px,#fff 5px 10px)':value;b.setAttribute('aria-label',value==='transparent'?'Fundo transparente':value);b.onclick=()=>{if(isBusy())return;item()[kind]=value;paint(node(),item());notify()};palette.append(b)}const label=document.createElement('label');label.className='vg-text-custom';label.textContent='Outra cor';const input=document.createElement('input');input.type='color';input.setAttribute('aria-label',kind==='color'?'Cor personalizada da fonte':'Cor personalizada do fundo');input.value=item()[kind]==='transparent'?'#17130f':item()[kind];input.oninput=()=>{if(isBusy())return;item()[kind]=input.value;paint(node(),item());notify()};label.append(input);palette.append(label);positionMenu()}
  for(const surface of [menu,palette])surface.addEventListener('pointerdown',e=>{e.stopPropagation();if(e.target.closest('button'))e.preventDefault()});
  menu.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{if(isBusy())return;finish(true);if(!item())return;menuOpen=true;const key=b.dataset.format;if(key==='color'||key==='background'){showPalette(key);return}item()[key]=key==='bold'?weight(item())!==600:!item()[key];notify()});menu.querySelector('[data-delete]').onclick=remove;menu.querySelector('[data-text-edit]').onclick=()=>startTyping(active);
  tools.querySelector('[data-text-finish]').onclick=()=>finish();tools.querySelector('button').onclick=()=>{if(isBusy())return;finish();const media=getMedia();if(!media)return;media.text_layers ||= [];if(media.text_layers.length>=5){showMenu(0);return}media.text_layers.push({text:'',x:55,y:62,size:6,color:'#ffffff',background:'transparent',bold:false,italic:false,strike:false});render();startTyping(media.text_layers.length-1)};
  document.addEventListener('pointerdown',e=>{if(!screen.isConnected)return;if(!stage.contains(e.target)&&!menu.contains(e.target)&&!palette.contains(e.target)&&!tools.contains(e.target)){finish();closeMenu()}});
  return {render,commit:()=>finish(),isEditing:()=>typing};
 }
 window.VillegramText={markup,editor};
})();
