(()=>{
 // Browsers decode EXIF orientation before drawing. Re-encoding removes the stale EXIF
 // tag, so saved rotations cannot be applied twice by another surface.
 async function decode(blob){if(window.createImageBitmap)return createImageBitmap(blob,{imageOrientation:'from-image'});return new Promise((resolve,reject)=>{const url=URL.createObjectURL(blob),image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(Error('image_decode_failed'))};image.src=url})}
 async function transform(blob,turns=0,crop='full',position=50){const image=await decode(blob),angle=((turns%4)+4)%4,w=image.width,h=image.height,canvas=document.createElement('canvas');canvas.width=angle%2?h:w;canvas.height=angle%2?w:h;const ctx=canvas.getContext('2d');ctx.translate(canvas.width/2,canvas.height/2);ctx.rotate(angle*Math.PI/2);ctx.drawImage(image,-w/2,-h/2);image.close?.();let output=canvas;if(crop!=='full'){const target=crop==='portrait'?9/16:4/3,sw=Math.min(canvas.width,canvas.height*target),sh=Math.min(canvas.height,canvas.width/target),c=document.createElement('canvas');c.width=Math.round(sw);c.height=Math.round(sh);c.getContext('2d').drawImage(canvas,(canvas.width-sw)*position/100,(canvas.height-sh)*position/100,sw,sh,0,0,c.width,c.height);output=c}if(output.width>1920||output.height>1920){const c=document.createElement('canvas'),scale=1920/Math.max(output.width,output.height);c.width=Math.round(output.width*scale);c.height=Math.round(output.height*scale);c.getContext('2d').drawImage(output,0,0,c.width,c.height);output=c}return new Promise((resolve,reject)=>output.toBlob(b=>b?resolve(b):reject(Error('image_encode_failed')),'image/webp',.9))}
 async function editor(blob){const dialog=document.createElement('dialog');dialog.className='vg-media-editor';dialog.innerHTML='<h2>Orientação e enquadramento</h2><p>A orientação EXIF é aplicada ao carregar. Confira a cena antes de salvar.</p><img alt="Prévia do enquadramento"><div><button type="button" data-left>↶ Girar à esquerda</button><button type="button" data-right>↷ Girar à direita</button></div><label>Enquadramento<select><option value="full">Foto inteira (recomendado)</option><option value="portrait">Vertical · 9:16</option><option value="landscape">Horizontal · 4:3</option></select></label><label>Posição do recorte<input type="range" min="0" max="100" value="50"></label><button type="button" data-save>Usar esta foto</button><button type="button" data-cancel>Cancelar</button>';document.body.append(dialog);dialog.showModal();let turns=0,url,previewVersion=0;
 async function preview(){const v=++previewVersion,b=await transform(blob,turns,dialog.querySelector('select').value,Number(dialog.querySelector('input').value));if(v!==previewVersion)return;URL.revokeObjectURL(url);url=URL.createObjectURL(b);dialog.querySelector('img').src=url;dialog.result=b}
 dialog.querySelector('[data-left]').onclick=()=>{turns--;preview()};dialog.querySelector('[data-right]').onclick=()=>{turns++;preview()};dialog.querySelector('select').onchange=preview;dialog.querySelector('input').oninput=preview;await preview();return new Promise(resolve=>{const done=b=>{URL.revokeObjectURL(url);dialog.close();dialog.remove();resolve(b)};dialog.querySelector('[data-save]').onclick=()=>done(dialog.result);dialog.querySelector('[data-cancel]').onclick=()=>done(null);dialog.oncancel=e=>{e.preventDefault();done(null)}})}
 window.VillegramMedia={transform,editor};
})();
