(()=>{
 const guest=new URLSearchParams(location.search).get('mode')==='guest';
 const C=window.CHALEZINHO_CONFIG,sb=window.supabase.createClient(C.supabaseUrl,C.supabaseKey,C.authOptions),$=s=>document.querySelector(s),f=$('#vg-post-form'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={property:'Chalé',experience:'Experiência',offer:'Estadia pronta',trust:'Dúvidas e confiança'},states={draft:'Rascunho',published:'Publicada',archived:'Arquivada',pending_review:'Aguardando aprovação'};
 let textEditor,effectsEditor;let data,current=null,media=[],cover=0,uploading=false,pendingUpload=null,session,step=0,selected=0,saving=false,stayQuote=null,stayVersion=0,stayTimer=null,dragCancel=null,suppressMediaClickUntil=0;

 const money=c=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const fixedStay=()=>f.elements.cta.value==='offer'&&f.elements.stay_fixed.checked;
 const stayValues=()=>({check_in:f.elements.stay_check_in.value,check_out:f.elements.stay_check_out.value,guests:Number(f.elements.stay_guests.value),rate_code:f.elements.stay_rate_code.value});
 function invalidateStay(){++stayVersion;clearTimeout(stayTimer);stayQuote=null;$('#vg-stay-rates').innerHTML='';$('#vg-stay-message').textContent='';updateComposition();if(fixedStay())stayTimer=setTimeout(()=>consultStay(),450);}
 function renderStayRates(){const rates=stayQuote?.rate_options||[];$('#vg-stay-rates').innerHTML=rates.map(r=>'<button type="button" class="vg-stay-rate" data-stay-rate="'+esc(r.code)+'" aria-pressed="'+(r.code===f.elements.stay_rate_code.value)+'"><span>'+esc(r.name)+'</span><strong>'+money(r.total_amount_cents)+'</strong><span>Hospedagem '+money(r.accommodation_amount_cents)+' · limpeza '+money(r.cleaning_fee_cents)+' · pacote '+money(r.experience_amount_cents||0)+'</span><small>'+(r.code===f.elements.stay_rate_code.value?'Tarifa apresentada no Trip':'Escolher esta tarifa para apresentar')+'</small></button>').join('');$('#vg-stay-rates').querySelectorAll('[data-stay-rate]').forEach(b=>b.onclick=()=>{f.elements.stay_rate_code.value=b.dataset.stayRate;renderStayRates();updateComposition()});}
 async function consultStay(){clearTimeout(stayTimer);if(!fixedStay())return;const values=stayValues();if(!f.elements.property_id.value||!values.check_in||!values.check_out||values.check_out<=values.check_in){$('#vg-stay-message').textContent='Escolha chalé, entrada e saída para consultar.';return}const version=++stayVersion;stayQuote=null;renderStayRates();updateComposition();$('#vg-stay-message').textContent='Consultando calendário e preço atual…';try{const r=await fetch(C.bookingEngine,{method:'POST',headers:{'Content-Type':'application/json','X-Chalezinho-Env':'development'},body:JSON.stringify({action:'villegram_quote',property_id:Number(f.elements.property_id.value),offer_id:f.elements.offer_id.value||null,...values}),signal:AbortSignal.timeout(30000)}),d=await r.json();if(version!==stayVersion)return;if(!r.ok||!d.ok)throw Error(d.error);stayQuote=d;renderStayRates();updateComposition();$('#vg-stay-message').textContent='Preços completos consultados agora. Escolha a tarifa que será apresentada. O hóspede confirma sua tarifa na revisão.'}catch(e){if(version!==stayVersion)return;stayQuote=null;renderStayRates();updateComposition();$('#vg-stay-message').textContent='Não foi possível calcular estes dias. '+(e.message==='dates_unavailable'?'Chalé indisponível nessas datas.':e.message?.startsWith('minimum_stay')?'Confira o mínimo de noites.':message(e))}}
 function moveMedia(from,to){if(from===to||from<0||to<0||to>=media.length||uploading||saving)return;const chosen=media[selected],cap=media[cover];media.splice(to,0,media.splice(from,1)[0]);selected=media.indexOf(chosen);cover=media.indexOf(cap);renderMedia();$('#vg-reorder-status').textContent='Foto movida para a posição '+(to+1)+'. A capa foi preservada.';$('#vg-media-list [data-select="'+to+'"]').focus();}
 function enableReordering(){
 const strip=$('.vg-media-strip');if(!strip||media.length<2)return;
 const marker=document.createElement('span');marker.className='vg-insertion-marker';marker.hidden=true;marker.setAttribute('aria-hidden','true');strip.append(marker);
 strip.addEventListener('click',e=>{if(Date.now()<suppressMediaClickUntil){e.preventDefault();e.stopImmediatePropagation()}},true);
 const buttons=[...strip.querySelectorAll('[data-select]')];let positions=[];const rectFor=n=>positions[buttons.indexOf(n)]||n.getBoundingClientRect();
 buttons.forEach(b=>{let timer=null,active=false,slot=Number(b.dataset.select),origin=null,ghost=null,grab=null,scrollFrame=0,lastPoint=null,scrolling=false,lastScrollX=0;
 const clear=()=>{clearTimeout(timer);cancelAnimationFrame(scrollFrame);ghost?.remove();ghost=null;marker.hidden=true;buttons.forEach(n=>{n.classList.remove('vg-dragging');n.style.transform=''});active=false;dragCancel=null};
 const indicate=x=>{const rect=strip.getBoundingClientRect();slot=buttons.findIndex(n=>{const r=rectFor(n);return x<r.left-strip.scrollLeft+r.width/2});if(slot<0)slot=buttons.length;const edge=slot===buttons.length?rectFor(buttons.at(-1)).right-strip.scrollLeft+4:rectFor(buttons[slot]).left-strip.scrollLeft-4;marker.style.left=(edge-rect.left+strip.scrollLeft)+'px';marker.hidden=false;buttons.forEach((n,i)=>{n.style.transform=n===b?'':(i>=slot?'translateX(8px)':'translateX(-8px)')});$('#vg-reorder-status').textContent='Solte na posição '+(slot>Number(b.dataset.select)?slot:slot+1)+'.'};
 b.onpointerdown=e=>{if(e.button!==undefined&&e.button!==0||uploading||saving)return;dragCancel?.();scrolling=false;lastScrollX=e.clientX;origin={x:e.clientX,y:e.clientY};positions=buttons.map(n=>{const r=n.getBoundingClientRect();return {left:r.left+strip.scrollLeft,right:r.right+strip.scrollLeft,width:r.width}});timer=setTimeout(()=>{active=true;const r=b.getBoundingClientRect();grab={x:e.clientX-r.left,y:e.clientY-r.top};ghost=b.cloneNode(true);ghost.removeAttribute('data-select');ghost.removeAttribute('id');ghost.tabIndex=-1;ghost.setAttribute('aria-hidden','true');ghost.className='vg-drag-ghost';ghost.style.width=r.width+'px';ghost.style.height=r.height+'px';document.body.append(ghost);lastPoint={x:e.clientX,y:e.clientY};ghost.style.transform='translate3d('+(e.clientX-grab.x)+'px,'+(e.clientY-grab.y-14)+'px,0) scale(1.1)';b.classList.add('vg-dragging');b.setPointerCapture?.(e.pointerId);indicate(e.clientX);const scroll=()=>{if(!active)return;const r=strip.getBoundingClientRect(),speed=lastPoint.x<r.left+28?-5:lastPoint.x>r.right-28?5:0;if(speed){strip.scrollLeft=clamp(strip.scrollLeft+speed,0,Math.max(0,strip.scrollWidth-strip.clientWidth));indicate(lastPoint.x)}scrollFrame=requestAnimationFrame(scroll)};scrollFrame=requestAnimationFrame(scroll)},320);dragCancel=clear};
 b.onpointermove=e=>{if(!active){if(origin&&Math.abs(e.clientX-origin.x)>8&&Math.abs(e.clientX-origin.x)>Math.abs(e.clientY-origin.y)){clearTimeout(timer);scrolling=true;e.preventDefault();strip.scrollLeft+=lastScrollX-e.clientX;lastScrollX=e.clientX;}else if(origin&&Math.abs(e.clientY-origin.y)>8)clear();return}e.preventDefault();lastPoint={x:e.clientX,y:e.clientY};ghost.style.transform='translate3d('+(e.clientX-grab.x)+'px,'+(e.clientY-grab.y-14)+'px,0) scale(1.1)';indicate(e.clientX)};
 b.onpointerup=()=>{const from=Number(b.dataset.select),drop=active,to=slot>from?slot-1:slot;if(scrolling)suppressMediaClickUntil=Date.now()+300;clear();if(drop){suppressMediaClickUntil=Date.now()+450;moveMedia(from,to)}};b.onpointercancel=clear;b.onlostpointercapture=clear;b.oncontextmenu=e=>e.preventDefault();
 b.onkeydown=e=>{if(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();moveMedia(Number(b.dataset.select),Number(b.dataset.select)+(e.key==='ArrowLeft'?-1:1))}};
 });
 }
 const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
 let cancelSceneGesture=()=>{};
 let uploadNoticeTimer=null,holdTimer=null,holdOrigin=null,heldMedia=null,heldPointers=new Set();
 function hideMediaMenu(){clearTimeout(holdTimer);holdTimer=null;heldMedia=null;$('#vg-media-menu').hidden=true;$('#vg-media-options').setAttribute('aria-expanded','false')}
 function showMediaMenu(){if(uploading||saving||step!==0||!media[selected])return;textEditor?.commit();heldMedia=media[selected];$('#vg-composer-visual video')?.pause();$('#vg-media-delete span').textContent=heldMedia.kind==='video'?'Remover vídeo':'Remover foto';$('#vg-media-menu').hidden=false;$('#vg-media-options').setAttribute('aria-expanded','true')}
 function removeSelectedMedia(){if(uploading||saving||step!==0||!heldMedia||heldMedia!==media[selected])return;const i=selected;textEditor?.commit();cancelSceneGesture();media.splice(i,1);cover=Math.max(0,Math.min(cover-(i<cover?1:0),media.length-1));hideMediaMenu();renderMedia();(media.length?$('#vg-media-options'):$('#vg-composer-empty')).focus()}
 function uploadNotice(text,state='busy'){clearTimeout(uploadNoticeTimer);uploadNoticeTimer=null;const box=$('#vg-upload-feedback');box.hidden=!text;box.dataset.state=state;$('#vg-upload-status').textContent=text;$('#vg-upload-progress').hidden=state!=='busy';$('#vg-upload-spinner').hidden=state!=='busy';$('#vg-composer-screen').classList.toggle('is-uploading',state==='busy');if(state==='success')uploadNoticeTimer=setTimeout(()=>{box.hidden=true;$('#vg-upload-status').textContent=''},2500)}
 function chooseMedia(){if(uploading||saving)return;hideMediaMenu();$('#vg-upload').click()}
 function enableMediaSurface(){
 const effectsHost=document.createElement('div');effectsHost.className='vg-effects';$('#vg-composer-screen').append(effectsHost);effectsEditor=window.VillegramEffects?.controls(effectsHost,()=>step===0?media[selected]:null,()=>{const text=(media[selected]?.text_layers||[]).map(t=>t.text).join('\n');if(text&&!f.elements.title.value)f.elements.title.value=text.slice(0,140);if(text&&!f.elements.caption.value)f.elements.caption.value=text;updateComposition()},()=>uploading||saving,()=>media);
 const screen=$('#vg-composer-screen');$('#vg-composer-empty').onclick=chooseMedia;$('#vg-media-add').onclick=chooseMedia;$('#vg-media-options').onclick=()=>$('#vg-media-menu').hidden?showMediaMenu():hideMediaMenu();$('#vg-media-delete').onclick=removeSelectedMedia;$('#vg-scene-library').onclick=()=>{if(!uploading&&!saving)$('#vg-source-library').showModal()};$('#vg-source-close').onclick=()=>$('#vg-source-library').close();
 const excluded=target=>target.closest('button,input,.vg-text-stage,.vg-text-tools,.vg-text-orbit,.vg-text-swatches,#vg-scene-tools,#vg-scene-notices,#vg-media-list');
 screen.addEventListener('pointerdown',e=>{if(e.target.closest('#vg-scene-gesture'))return;if(excluded(e.target)||uploading||saving||step!==0||!media[selected]||e.button>0)return;heldPointers.add(e.pointerId);hideMediaMenu();if(heldPointers.size!==1)return;const r=e.target.getBoundingClientRect();if(e.target.tagName==='VIDEO'&&e.clientY>r.bottom-56)return;holdOrigin={x:e.clientX,y:e.clientY,media:media[selected]};holdTimer=setTimeout(()=>{if(heldPointers.size===1&&holdOrigin?.media===media[selected])showMediaMenu()},550)},true);
 screen.addEventListener('pointermove',e=>{if(holdOrigin&&Math.hypot(e.clientX-holdOrigin.x,e.clientY-holdOrigin.y)>10){hideMediaMenu();holdOrigin=null}},true);
 const end=e=>{clearTimeout(holdTimer);heldPointers.delete(e.pointerId);if(!heldPointers.size)holdOrigin=null};for(const type of ['pointerup','pointercancel','lostpointercapture'])screen.addEventListener(type,end,true);
 screen.addEventListener('click',e=>{if(!$('#vg-media-menu').hidden&&!excluded(e.target)){e.preventDefault();e.stopPropagation()}},true);
 screen.addEventListener('contextmenu',e=>{if(step===0&&media[selected]&&!excluded(e.target))e.preventDefault()});
 screen.addEventListener('keydown',e=>{if(e.key==='Escape'){hideMediaMenu();$('#vg-media-options').focus()}if(e.target.id==='vg-scene-gesture'&&['Delete','Backspace','ContextMenu'].includes(e.key)){e.preventDefault();showMediaMenu();$('#vg-media-delete').focus()}});
 document.addEventListener('pointerdown',e=>{if(!screen.contains(e.target))hideMediaMenu()});
 }
 function sceneGeometry(){const scene=$('#vg-composer-visual').firstElementChild,m=media[selected],r=$('#vg-composer-visual').getBoundingClientRect();if(!scene||!m||!r.width||!r.height)return null;const w=scene.naturalWidth||scene.videoWidth,h=scene.naturalHeight||scene.videoHeight;if(!w||!h)return null;const scale=(m.fit==='cover'?Math.max:Math.min)(r.width/w,r.height/h);return {r,bw:w*scale,bh:h*scale};}
 function paintScene(){const m=media[selected],scene=$('#vg-composer-visual').firstElementChild;if(!m||!scene)return;scene.dataset.mode=m.mode||'original';scene.style.setProperty('--vg-mode-duration',(window.VillegramEffects?.modes[m.mode]?.duration||6500)+'ms');scene.style.filter=window.VillegramEffects?.css(m)||'none';if(scene.tagName==='VIDEO')scene.playbackRate=m.speed||1;scene.style.objectFit=m.fit||'contain';scene.style.objectPosition=(m.position_x??50)+'% '+(m.position??50)+'%';scene.style.transform=(m.offset_x||m.offset_y?'translate('+(m.offset_x||0)+'%, '+(m.offset_y||0)+'%) ':'')+'scale('+(m.zoom??1)+')';scene.style.transformOrigin=(m.position_x??50)+'% '+(m.position??50)+'%';$('#vg-scene-out').disabled=uploading||saving||(m.zoom??1)<=1;$('#vg-scene-in').disabled=uploading||saving||(m.zoom??1)>=3;}
 function isSceneFilled(m){return !!m&&m.fit==='cover'&&(m.zoom??1)===1&&!(m.offset_x||m.offset_y)&&(m.position_x??50)===50&&(m.position??50)===50;}
 function paintFitControl(){const button=$('#vg-scene-fit'),filled=isSceneFilled(media[selected]),label=filled?'Mostrar foto inteira':'Preencher a cena';button.setAttribute('aria-label',label);button.title=label;button.dataset.fit=filled?'cover':'contain';}
 function applyScene(values){if(uploading||saving||step!==0||!media[selected])return;Object.assign(media[selected],values);paintScene();paintFitControl();}
 let filterToastTimer;function cycleFilter(direction){const m=media[selected],effects=window.VillegramEffects;if(!m||!effects||uploading||saving)return;const keys=Object.keys(effects.filters),i=Math.max(0,keys.indexOf(m.filter||'original'));m.filter=keys[(i+direction+keys.length)%keys.length];paintScene();effectsEditor?.render();let toast=$('#vg-filter-toast');if(!toast){toast=document.createElement('span');toast.id='vg-filter-toast';toast.setAttribute('role','status');$('#vg-composer-screen').append(toast)}toast.textContent=effects.filters[m.filter].label;toast.hidden=false;toast.dataset.direction=direction>0?'next':'previous';clearTimeout(filterToastTimer);filterToastTimer=setTimeout(()=>toast.hidden=true,1100)}
 function enableSceneGestures(){
 const layer=$('#vg-scene-gesture'),points=new Map();let base=null,panReady=false,panTimer=null,origin=null,swiping=false;
 const snapshot=()=>{const g=sceneGeometry(),m=media[selected],ps=[...points.values()];if(!g||!ps.length){base=null;return}const center=ps.length>1?{x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2}:ps[0];base={...g,m,center,z:m.zoom??1,x:m.position_x??50,y:m.position??50,ox:m.offset_x||0,oy:m.offset_y||0,distance:ps.length>1?Math.hypot(ps[1].x-ps[0].x,ps[1].y-ps[0].y):0};};
 cancelSceneGesture=()=>{clearTimeout(panTimer);points.clear();base=null;panReady=false;origin=null;swiping=false;layer.classList.remove('vg-panning')};
 layer.onpointerdown=e=>{if(uploading||saving||step!==0||media[selected]?.kind!=='photo'||e.button!==undefined&&e.button!==0||points.size>=2)return;points.set(e.pointerId,{x:e.clientX,y:e.clientY});layer.setPointerCapture?.(e.pointerId);snapshot();if(points.size===2){clearTimeout(panTimer);panReady=true;layer.classList.add('vg-panning')}else{origin={x:e.clientX,y:e.clientY};panTimer=setTimeout(()=>{if(points.size===1&&!swiping){panReady=true;hideMediaMenu();effectsEditor?.open();snapshot()}},500)}};
 layer.onpointermove=e=>{if(!points.has(e.pointerId)||!base||uploading||saving)return;points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!panReady&&points.size===1){if(origin&&Math.hypot(e.clientX-origin.x,e.clientY-origin.y)>10){clearTimeout(panTimer);swiping=true;}return;}e.preventDefault();effectsEditor?.close();layer.classList.add('vg-panning');const ps=[...points.values()],pinch=ps.length===2&&base.distance>0,c=pinch?{x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2}:ps[0],z=pinch?clamp(base.z*Math.hypot(ps[1].x-ps[0].x,ps[1].y-ps[0].y)/base.distance,1,3):base.z;
 const offset=(size,extent,initial,shift,oldPoint,newPoint,edge)=>{const oldLeft=(size-extent*base.z)*initial/100+shift/100*size,anchor=(oldPoint-edge-oldLeft)/(extent*base.z),visible=Math.min(size/2,extent*z/2),left=clamp(newPoint-edge-anchor*extent*z,-extent*z+visible,size-visible);return Math.round(clamp((left-(size-extent*z)*initial/100)/size*100,-300,300)*10000)/10000};
 applyScene({zoom:z,offset_x:offset(base.r.width,base.bw,base.x,base.ox,base.center.x,c.x,base.r.left),offset_y:offset(base.r.height,base.bh,base.y,base.oy,base.center.y,c.y,base.r.top)});
 };
 const end=e=>{if(e.type==='pointerup'&&points.size===1&&!panReady&&origin&&Math.abs(e.clientX-origin.x)>45&&Math.abs(e.clientX-origin.x)>Math.abs(e.clientY-origin.y)*1.3){cycleFilter(e.clientX<origin.x?1:-1);}points.delete(e.pointerId);if(!points.size)cancelSceneGesture();else snapshot()};layer.onpointerup=end;layer.onpointercancel=end;layer.onlostpointercapture=end;layer.oncontextmenu=e=>e.preventDefault();
 layer.onkeydown=e=>{const m=media[selected];if(!m)return;const z=m.zoom??1;if(['+','=','-','0','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();if(e.key==='0')applyScene({zoom:1,position_x:50,position:50,offset_x:0,offset_y:0});else if(['+','=','-'].includes(e.key))applyScene({zoom:clamp(z+(e.key==='-'?-.1:.1),1,3)});else applyScene(e.key==='ArrowLeft'||e.key==='ArrowRight'?{offset_x:clamp((m.offset_x||0)+(e.key==='ArrowLeft'?-5:5),-50,50)}:{offset_y:clamp((m.offset_y||0)+(e.key==='ArrowUp'?-5:5),-50,50)})}};
 $('#vg-scene-fit').onclick=$('#vg-scene-tools').onclick=e=>{const action=e.target.closest('[data-scene-action]')?.dataset.sceneAction,m=media[selected];if(!action||!m||uploading||saving||step!==0)return;cancelSceneGesture();if(action==='cover'){cover=selected;renderMedia()}else if(action==='fit')applyScene({fit:isSceneFilled(m)?'contain':'cover',zoom:1,position_x:50,position:50,offset_x:0,offset_y:0});else if(action==='reset')applyScene({zoom:1,position_x:50,position:50,offset_x:0,offset_y:0,fit:'contain'});else applyScene({zoom:clamp((m.zoom??1)+(action==='in'?.1:-.1),1,3)})};
 }
 const stepNames=['Mídia e capa','Legenda','Publicar'];
 function setStep(value,focus=false){textEditor?.commit();cancelSceneGesture();effectsEditor?.close();hideMediaMenu();step=value;f.classList.toggle('vg-canvas-step',step===0);(step===0?$('#vg-scene-next-slot'):$('.vg-composer-footer')).append($('#vg-step-next'));(step===0?$('#vg-scene-notices'):f).append($('#vg-editor-message'));$('#vg-step-next').setAttribute('aria-label',step===0?'Avançar para legenda':'Avançar para publicar');$('.vg-composer-footer').hidden=step===0;$('#vg-scene-library').hidden=guest||step!==0;$('.vg-composer-workspace').classList.toggle('is-media-stage',step===0);f.querySelectorAll('[data-panel]').forEach(n=>n.hidden=Number(n.dataset.panel)!==step);f.querySelectorAll('[data-step]').forEach(b=>{if(Number(b.dataset.step)===step)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});$('#vg-step-back').hidden=step===0;$('#vg-step-next').hidden=step===2;$('#vg-step-status').textContent='Etapa '+(step+1)+' de 3 · '+stepNames[step];updateComposition();if(focus)(step===0?(media.length?$('#vg-step-next'):$('#vg-composer-empty')):f.querySelector('[data-panel="'+step+'"] h3')).focus();}
 function validateThrough(target){textEditor?.commit();if(uploading||saving){$('#vg-editor-message').textContent='Espere a operação terminar.';return false}if(target>0&&!media.length){setStep(0);$('#vg-editor-message').textContent='Escolha um vídeo ou uma foto para começar.';return false}if(target>1){for(const name of ['title','caption']){const field=f.elements[name];if(!field.value.trim()||!field.checkValidity()){setStep(1);$('#vg-description-fields').open=true;$('#vg-editor-message').textContent='Adicione texto na foto pelo botão Aa ou informe o título e a descrição.';field.focus();field.reportValidity();return false}}}return true;}
 function validatePublication(status='published'){if(!validateThrough(2))return false;for(const field of [f.elements.display_order,f.elements.expires_at]){if(!field.checkValidity()){setStep(2);$('.vg-advanced').open=true;field.focus();field.reportValidity();return false}}if(fixedStay()){const v=stayValues();if(!f.elements.property_id.value||!v.check_in||!v.check_out||v.check_out<=v.check_in||!v.rate_code||status==='published'&&!stayQuote){setStep(2);$('#vg-editor-message').textContent='Escolha chalé, datas e tarifa; consulte o preço atual antes de salvar.';return false}}const required=new Set([f.elements.type.value,f.elements.cta.value]);if(fixedStay())required.delete('offer');for(const kind of ['property','experience','offer']){if(required.has(kind)&&!f.elements[kind+'_id'].value){setStep(2);$('#vg-editor-message').textContent='Escolha '+({property:'o chalé',experience:'a experiência',offer:'a estadia pronta'})[kind]+' para este Trip.';f.elements[kind+'_id'].focus();return false}}return true;}
 function busy(){f.querySelectorAll('button,input,textarea,select,summary').forEach(n=>{if(n.tagName!=='SUMMARY')n.disabled=uploading||saving||n.hasAttribute('data-cover')&&Number(n.dataset.cover)===cover});$('#vg-new').disabled=uploading||saving;if(!uploading&&!saving)updateComposition();}
 function toggleLibrary(open){$('#vg-publications-library').hidden=!open;$('#vg-library-toggle').setAttribute('aria-expanded',String(open));if(open)$('#vg-filter').focus();else $('#vg-library-toggle').focus();}
 function updateComposition(rebuild=false){if(guest){f.elements.type.value=f.elements.property_id.value?'property':'trust';f.elements.cta.value=f.elements.property_id.value?'property':'dates';}const m=media[selected],visual=$('#vg-composer-visual');if(rebuild){hideMediaMenu();heldPointers.clear();cancelSceneGesture();const old=visual.querySelector('video');if(old)old.pause();visual.innerHTML=m?(m.kind==='video'?'<video src="'+esc(m.url)+'" poster="'+esc(m.poster||'')+'" controls muted playsinline preload="metadata" aria-label="Prévia do vídeo"></video>':'<img src="'+esc(m.url)+'" alt="'+esc(m.alt||'Prévia da foto')+'">'):'';const video=visual.querySelector('video');if(video)video.onerror=()=>{$('#vg-editor-message').textContent='Não foi possível reproduzir esta mídia. Confira o arquivo ou use MP4/H.264 sem HDR antes de publicar.'};const img=visual.querySelector('img');if(img)img.onload=()=>updateComposition();if(video)video.onloadedmetadata=()=>updateComposition();if(img)img.onerror=()=>{$('#vg-editor-message').textContent='Não foi possível carregar esta foto. Confira a conexão ou escolha outra mídia.'};}
 effectsEditor?.render();textEditor?.render();$('#vg-composer-screen').classList.toggle('has-text',!!media[selected]?.text_layers?.length);paintScene();const editing=!!m&&step===0;$('#vg-scene-tools').hidden=!editing;$('#vg-scene-gesture').hidden=!editing||m.kind!=='photo';$('#vg-scene-fit').hidden=!editing;paintFitControl();$('#vg-scene-cover').textContent=selected===cover?'✓ Capa':'Usar como capa';$('#vg-scene-cover').disabled=uploading||saving||selected===cover;
 $('#vg-composer-empty').hidden=!!m;$('#vg-media-list').hidden=!m||step!==0;$('#vg-scene-next-slot').hidden=!m||step!==0;$('.vg-composer-steps').hidden=!m;$('#vg-composer-screen').classList.toggle('has-media',!!m);$('#vg-media-controls').hidden=!m||step!==0;$('#vg-media-add').hidden=m?.kind==='video'||media.length>=8;$('#vg-composer-screen').classList.toggle('is-video',m?.kind==='video');$('#vg-composer-overlay').hidden=!m||step===0;$('#vg-composer-title').textContent=f.elements.title.value||'Título do Trip';$('#vg-composer-caption').textContent=f.elements.caption.value||'Sua legenda aparece aqui.';$('#vg-composer-cta').textContent=f.elements.cta.selectedOptions[0]?.textContent||'';$('#vg-caption-count').textContent=f.elements.caption.value.length+' / 3000';
 const type=f.elements.type.value,cta=f.elements.cta.value;const offerLabel=f.querySelector('[data-link=offer_id]');offerLabel.firstChild.textContent=fixedStay()?'Pacote da estadia (opcional)':'Estadia pronta';f.querySelector('[data-link=experience_id]').firstChild.textContent=fixedStay()?'Vínculo editorial de experiência (não adiciona à reserva)':'Experiência';f.elements.offer_id.options[0].textContent=fixedStay()?'Somente hospedagem':'Sem vínculo';$('#vg-stay-choice').hidden=cta!=='offer';$('#vg-stay-fields').hidden=!f.elements.stay_fixed.checked;$('#vg-stay-calendar-note').hidden=f.elements.stay_fixed.checked;f.querySelectorAll('[data-link]').forEach(n=>n.hidden=![type,cta,...(fixedStay()?['property','offer']:[])].includes(n.dataset.link.replace('_id',''))&&!f.elements[n.dataset.link].value);
 const rate=stayQuote?.rate_options?.find(r=>r.code===f.elements.stay_rate_code.value);$('#vg-composer-stay').hidden=!fixedStay()||!rate;$('#vg-composer-stay').innerHTML=rate?esc(f.elements.stay_check_in.value+' a '+f.elements.stay_check_out.value+' · '+f.elements.stay_guests.value+' hóspedes')+'<strong>'+money(rate.total_amount_cents)+'</strong>Hospedagem, limpeza e pacote escolhido':'';const field=f.elements[cta+'_id'],name=field?.value?field.selectedOptions[0]?.textContent:null;$('#vg-destination-summary').textContent=cta==='dates'?'Abre a escolha de datas, hóspedes e motivo para montar a reserva.':name?({property:'Abre a página do chalé: ',experience:'Abre os detalhes da experiência: ',offer:'Abre a revisão da reserva com chalé, datas e pacote: '})[cta]+name:'Escolha o vínculo para definir o destino do botão.';
 if(guest){f.querySelector('[data-link=property_id]').hidden=false;f.querySelector('[name=published]').textContent='Enviar para aprovação';}
 $('#vg-preview-note').hidden=!m||step===0;$('#vg-preview-note').textContent=step===0?(m?.kind==='photo'?'Arraste e use pinça para enquadrar. Aa adiciona texto. Segure a foto para remover.':'Aa adiciona texto. Segure o vídeo para remover.'):'Prévia da composição · use Ver como visitante para conferir inclusões e preços atuais.';
 }
 async function api(body){if(guest){body={...body,operation:({admin_list:'guest_list',save:'guest_save',preview:'guest_preview'})[body.operation]||body.operation};if(body.operation==='guest_save')body.mentions=(f.elements.mentions.value||'').split(/[\s,]+/).filter(Boolean);}const fresh=await sb.auth.getSession();session=fresh.data.session;if(!session)throw Error('authentication_required');const r=await fetch(C.supabaseUrl+'/functions/v1/villegram-content',{method:'POST',headers:{'Content-Type':'application/json','X-Chalezinho-Env':'development',Authorization:'Bearer '+session.access_token},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const d=await r.json();if(!r.ok||!d.ok)throw Error(d.error);return d;}
 const message=e=>({public_profile_required:'Crie seu perfil público no Meu Ville Moments para começar.',guest_required:'Para postar, é preciso uma reserva confirmada ou um convite de acompanhante.',guest_profile_required:'Confira seu perfil e sua estadia no Meu Ville Moments.',mention_profile_unavailable:'Uma das pessoas marcadas não tem um perfil público. Confira o @nome.',post_limit:'Você já enviou dez momentos hoje. Continue amanhã.',edit_conflict:'Outra pessoa alterou esta publicação. Reabra a versão atual antes de salvar.',link_required:'Vincule o chalé, a experiência ou a estadia correspondente ao tipo.',invalid_action:'A ação principal precisa do vínculo correspondente.',link_unavailable:'O vínculo está indisponível. Salve como rascunho ou escolha outra opção.',stay_unavailable:'Datas ou pacote indisponíveis. Consulte novamente ou salve como rascunho.',invalid_stay_selection:'Confira as datas, hóspedes e tarifa do Trip.',invalid_publication:'Informe título, legenda e pelo menos uma mídia válida.',invalid_media_owner:'Esta mídia não pertence ao autor. Envie sua própria mídia.',media_upload_incomplete:'A mídia ainda não terminou de carregar.',authentication_required:'Sua sessão expirou. Entre novamente.'}[e.message]||'Não foi possível concluir. '+(e.message==='service_unavailable'?'O serviço está indisponível; tente novamente.':e.message));
 async function load(preserveEditor=false){data=await api({operation:'admin_list'});$('#vg-admin-root').hidden=false;$('#vg-admin-message').textContent='';renderList();links();if(!guest){automation();library()}else{$('.vg-author-line strong').textContent=data.profile.display_name;$('#vg-composer-overlay>span').textContent=data.profile.display_name}if(!current&&!preserveEditor)edit();if(!guest)await report();else if(!preserveEditor&&new URLSearchParams(location.search).get('edit'))edit(new URLSearchParams(location.search).get('edit'));}
 function links(){for(const [name,rows] of [['property_id',data.properties],['experience_id',data.products],['offer_id',data.offers]]){const selected=f.elements[name].value;f.elements[name].innerHTML='<option value="">Sem vínculo</option>'+rows.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join('');f.elements[name].value=selected;}}
 function renderList(){const filter=$('#vg-filter').value;$('#vg-post-list').innerHTML=(filter==='pending_review'&&reviewRows?reviewRows:data.publications).filter(p=>filter==='all'||filter==='automatic'&&p.source==='automatic'||p.status===filter).map(p=>`<article class="vg-post-card">${p.media[p.cover_index]?.poster||p.media[p.cover_index]?.url?`<img src="${esc(p.media[p.cover_index].poster||p.media[p.cover_index].url)}" alt="Capa de ${esc(p.title)}">`:''}<h3>${esc(p.title)}</h3><p>${p.source==='guest_submission'?'Momento':labels[p.type]} · ${states[p.status]}${p.featured?' · Destaque':''}</p><p>${p.source==='automatic'?'Gerada automaticamente':p.source==='guest_submission'?'Momento de '+esc(p.author_name):'Equipe'} · ordem ${p.display_order}</p><div class="vg-media-actions"><button type="button" data-preview-post="${p.id}">▷ Ver prévia</button>${!guest&&p.source==='guest_submission'?`<button type="button" data-review="${p.id}">Revisar momento</button>`:`<button type="button" data-edit="${p.id}">Editar</button>`}</div></article>`).join('')||'<p>Nenhuma publicação nesta seleção.</p>';document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>moderate(data.publications.find(p=>p.id===b.dataset.review)));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-preview-post]').forEach(b=>b.onclick=async()=>{if(uploading||saving)return;b.disabled=true;$('#vg-library-message').textContent='Preparando prévia…';try{const p=data.publications.find(p=>p.id===b.dataset.previewPost);await openPublicationPreview(p,p.id);$('#vg-library-message').textContent=''}catch(e){$('#vg-library-message').textContent=message(e)}finally{b.disabled=false}});}
 function edit(id){if(uploading||saving)return;dragCancel?.();++stayVersion;clearTimeout(stayTimer);stayQuote=null;pendingUpload=null;$('#vg-upload-retry').hidden=true;current=data.publications.find(p=>p.id===id)||null;media=current?current.media.map(m=>({...m,text_layers:(m.text_layers||[]).map(t=>({...t,...(t.runs?{runs:t.runs.map(r=>({...r}))}:{})}))})):[];cover=current?.cover_index||0;$('#vg-editor-title').textContent=current?'Editar publicação':'Nova publicação';$('#vg-post-status').textContent=current?states[current.status]:'Ainda não salva';const published=current?.status==='published';f.querySelector('[name=draft]').hidden=published;f.querySelector('[name=published]').textContent=published?'Salvar alterações':'Publicar';const view=$('#vg-view-post');view.hidden=!published;if(published)view.href='index.html?publication='+encodeURIComponent(current.id);for(const key of ['type','property_id','experience_id','offer_id','title','caption','cta','display_order'])f.elements[key].value=current?.[key]??({type:'property',cta:'property',display_order:0}[key]||'');f.elements.stay_fixed.checked=!!current?.stay_selection||!current||current.source==='manual'&&current.cta!=='offer';const stay=current?.stay_selection||{};for(const [name,value] of Object.entries({stay_check_in:stay.check_in||'',stay_check_out:stay.check_out||'',stay_guests:stay.guests||2,stay_rate_code:stay.rate_code||''}))f.elements[name].value=value;renderStayRates();f.elements.featured.checked=!!current?.featured;f.elements.expires_at.value=current?.expires_at?new Date(Date.parse(current.expires_at)-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):'';$('#vg-archive').hidden=!current||current.status==='archived';$('#vg-editor-message').textContent='';uploadNotice('','idle');selected=cover;renderMedia();setStep(current?2:0);$('#vg-publications-library').hidden=true;$('#vg-library-toggle').setAttribute('aria-expanded','false');if(guest){f.elements.mentions.value=(current?.mention_handles||[]).map(h=>'@'+h).join(' ');if(!current&&data.suggested_property_id){f.elements.property_id.value=data.suggested_property_id;updateComposition();$('#vg-editor-message').textContent=''}}if(id)f.scrollIntoView({block:'start',behavior:'smooth'});if(fixedStay())consultStay();}
 function library(){const photos=data.properties.flatMap(p=>(p.gallery?.length?p.gallery:[p.cover_image]).filter(Boolean).map(m=>({url:typeof m==='string'?m:m.url,name:p.name}))).concat(data.products.flatMap(p=>(p.experience_media||[]).map(m=>({url:m.media_url,name:p.name}))));$('#vg-library-photos').innerHTML=photos.map((p,i)=>'<button type="button" data-photo="'+i+'" aria-label="Adicionar foto de '+esc(p.name)+'"><img src="'+esc(p.url)+'" alt="'+esc(p.name)+'"></button>').join('');$('#vg-library-photos').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(uploading||saving)return;if(media.length>=8||media.some(m=>m.kind==='video')){$('#vg-editor-message').textContent='Use até 8 fotos, ou apenas um vídeo.';return}const p=photos[Number(b.dataset.photo)];media.push({kind:'photo',url:p.url,fit:'cover',position:50,alt:p.name});selected=media.length-1;renderMedia()});}
 function renderMedia(){const previousScroll=$('.vg-media-strip')?.scrollLeft||0;selected=Math.max(0,Math.min(selected,media.length-1));updateComposition(true);dragCancel?.();if(!media.length){$('#vg-media-list').innerHTML='';$('#vg-scene-extra').innerHTML='';return}const m=media[selected],i=selected;
 $('#vg-media-list').innerHTML='<div class="vg-media-strip" role="group" aria-label="Mídias da publicação">'+media.map((item,n)=>'<button type="button" title="Segure e arraste; Alt + setas para ordenar" data-select="'+n+'" aria-pressed="'+(n===selected)+'" aria-label="Ajustar '+(item.kind==='video'?'vídeo':'foto '+(n+1))+'"><span class="vg-media-grip" aria-hidden="true">⠿</span><img src="'+esc(item.poster||item.url)+'" alt=""><span>'+(n===cover?'Capa':n+1)+'</span></button>').join('')+'</div><div class="vg-strip-scroll"><button type="button" data-strip-prev aria-label="Ver fotos anteriores">‹</button><button type="button" data-strip-next aria-label="Ver próximas fotos">›</button></div><p id="vg-reorder-status" role="status">'+(media.length>1?'Segure e arraste para ordenar · Alt + setas no teclado.':'')+'</p>'+`<details class="vg-media-card"><summary>Opções da cena</summary><p>${m.kind==='video'?'Vídeo':'Foto '+(i+1)} · ${i===cover?'capa escolhida':'selecione como capa se preferir'}</p><div class="vg-media-actions"><button type="button" data-cover="${i}" ${i===cover?'disabled':''}>${i===cover?'✓ Capa escolhida':'Usar como capa'}</button>${i?`<button type="button" data-up="${i}">← Mover antes</button>`:''}</div>${m.kind==='video'?`<p>Pause o vídeo no quadro desejado.</p><button type="button" data-poster-save="${i}">Usar quadro atual como capa</button><p>A capa muda após salvar o instante escolhido.</p>`:''}</details>`;
 $('#vg-media-list [data-strip-prev]').onclick=()=>$('.vg-media-strip').scrollBy({left:-150,behavior:'smooth'});$('#vg-media-list [data-strip-next]').onclick=()=>$('.vg-media-strip').scrollBy({left:150,behavior:'smooth'});const extra=$('#vg-media-list .vg-media-card');$('#vg-scene-extra').replaceChildren(...extra.querySelectorAll('button'));extra.remove();$('#vg-reorder-status').classList.add('vg-visually-hidden');updateComposition();const strip=$('.vg-media-strip');strip.scrollLeft=previousScroll;const chosen=strip.querySelector('[aria-pressed=true]');if(chosen){const left=chosen.offsetLeft,right=left+chosen.offsetWidth;if(left<strip.scrollLeft)strip.scrollLeft=left;else if(right>strip.scrollLeft+strip.clientWidth)strip.scrollLeft=right-strip.clientWidth;}enableReordering();
 $('#vg-media-list').querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{if(uploading||saving)return;selected=Number(b.dataset.select);renderMedia()});
 $('#vg-scene-extra').querySelectorAll('[data-cover]').forEach(b=>b.onclick=()=>{if(uploading||saving)return;cover=Number(b.dataset.cover);renderMedia()});$('#vg-scene-extra').querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{if(uploading||saving)return;const i=Number(b.dataset.up);[media[i-1],media[i]]=[media[i],media[i-1]];if(cover===i)cover--;else if(cover===i-1)cover++;selected=i-1;renderMedia()});
 $('#vg-scene-extra').querySelectorAll('[data-poster-save]').forEach(b=>b.onclick=async()=>{if(uploading||saving)return;uploading=true;busy();try{const i=Number(b.dataset.posterSave),blob=await window.VillegramUpload.poster($('#vg-composer-visual video'),$('#vg-composer-visual video').currentTime||0.5),path=session.user.id+'/'+crypto.randomUUID()+'.webp';await window.VillegramUpload.upload(sb,blob,path);media[i].poster_path=path;media[i].poster=URL.createObjectURL(blob);renderMedia();$('#vg-editor-message').textContent='Capa atualizada. Salve a publicação para aplicar.'}catch(e){$('#vg-editor-message').textContent=message(e)}finally{uploading=false;busy()}});
 }
 function payload(status){return {stay_selection:fixedStay()?stayValues():null,type:f.elements.type.value,title:f.elements.title.value,caption:f.elements.caption.value,media,cover_index:cover,property_id:f.elements.property_id.value||null,experience_id:f.elements.experience_id.value||null,offer_id:f.elements.offer_id.value||null,cta:f.elements.cta.value,display_order:Number(f.elements.display_order.value),featured:f.elements.featured.checked,status,published_at:current?.published_at||null,expires_at:f.elements.expires_at.value?new Date(f.elements.expires_at.value).toISOString():null};}
 async function save(status){if(status==='draft'&&current?.status==='published')status='published';if(uploading||saving){$('#vg-editor-message').textContent='Espere a operação terminar.';return}if(status!=='archived'&&!validatePublication(status))return;saving=true;busy();try{const r=await api({operation:'save',id:current?.id,updated_at:current?.updated_at,publication:payload(status)});current=r.publication;data.publications=data.publications.filter(p=>p.id!==current.id).concat(current).sort((a,b)=>a.display_order-b.display_order);renderList();saving=false;edit(current.id);$('#vg-editor-message').textContent=current.status==='published'?'Publicação salva como publicada. Use Ver publicação no Ville Moments para conferir.':current.status==='archived'?'Publicação arquivada.':current.status==='pending_review'?'Momento enviado! A equipe vai revisar antes de aparecer no Ville Moments.':'Rascunho salvo.'}catch(e){$('#vg-editor-message').textContent=message(e)}finally{saving=false;busy()}}
 async function uploadFiles(files){if(!files?.length||uploading||saving)return;uploading=true;hideMediaMenu();busy();$('#vg-upload-retry').hidden=true;$('#vg-upload-progress').value=0;uploadNotice('Preparando mídia…');try{
  for(const file of files){if(file.type.startsWith('video/')){if(files.length!==1||media.length)throw Error('Um vídeo deve ser publicado sozinho. Remova as fotos antes de enviar.');const inspected=await window.VillegramUpload.inspect(file),poster=await window.VillegramUpload.poster(inspected.video),path=session.user.id+'/'+crypto.randomUUID()+(file.type==='video/mp4'?'.mp4':'.webm'),poster_path=session.user.id+'/'+crypto.randomUUID()+'.webp';pendingUpload={file,path,poster,poster_path,info:{kind:'video',fit:'contain',position:50,duration:inspected.video.duration,bytes:file.size,alt:f.elements.title.value||'Vídeo do Chalezinho Ville',url:inspected.url,poster:URL.createObjectURL(poster)}};}
   else{if(media.length>=8||media.some(m=>m.kind==='video')||file.size>10*1024*1024)throw Error('Use até 8 fotos de no máximo 10 MB cada.');const blob=await window.VillegramMedia.transform(file);if(!blob)continue;pendingUpload={file:blob,path:session.user.id+'/'+crypto.randomUUID()+'.webp',info:{kind:'photo',fit:'cover',position:50,alt:f.elements.title.value||'Foto do Chalezinho Ville',url:URL.createObjectURL(blob)}};}
   await finishUpload();
  }uploadNotice('Mídia enviada.','success');
 }catch(e){uploadNotice(e.message,'error');$('#vg-upload-retry').hidden=!pendingUpload;}finally{uploading=false;busy();$('#vg-upload').value=''}}
 async function finishUpload(){const u=pendingUpload;if(!u)return;uploadNotice('Enviando mídia…');$('#vg-upload-progress').value=0;if(!u.fileUploaded){await window.VillegramUpload.upload(sb,u.file,u.path,n=>{$('#vg-upload-progress').value=n});u.fileUploaded=true;}if(u.poster)await window.VillegramUpload.upload(sb,u.poster,u.poster_path);media.push({...u.info,path:u.path,...(u.poster_path?{poster_path:u.poster_path}:{})});pendingUpload=null;selected=media.length-1;renderMedia();busy();}
 async function openPublicationPreview(publication,id){const r=await api({operation:'preview',id,publication}),p=r.publication,property=r.properties.find(x=>x.id===p.property_id),product=r.products.find(x=>x.id===p.experience_id);const card={...(p.stay_card||{}),preview:true,publication:p,publication_id:p.id,property_id:property?.id,property_name:property?.name||'Chalezinho Ville',property_code:property?.code,property_url:window.VillegramContent.propertyURL(property),product,experiences:p.stay_card?.experiences||[],guests:p.stay_card?.guests||2};window.Villegram.configurePublications([card],r.offers,r.properties);window.Villegram.open(card);}
 async function preview(){if(uploading||saving)return;if(!validatePublication())return;const video=$('#vg-composer-visual video');if(video)video.pause();$('#vg-editor-message').textContent='Preparando prévia…';try{await openPublicationPreview(payload('draft'),current?.id);$('#vg-editor-message').textContent='';}catch(e){$('#vg-editor-message').textContent=message(e)}}
 function automation(){const a=$('#vg-automation-form'),s=data.settings;a.elements.enabled.checked=s.enabled;a.elements.auto_publish.value=String(s.auto_publish);a.elements.frequency_hours.value=s.frequency_hours;a.elements.max_offers.value=s.max_offers;$('#vg-templates').innerHTML=Object.entries(s.templates).map(([type,t])=>`<fieldset data-template="${type}"><legend>${labels[type]}</legend><label class="vg-check"><input data-enabled type="checkbox" ${t.enabled?'checked':''}> Gerar este tipo</label><label>Título<input data-title value="${esc(t.title)}" maxlength="140" required></label><label>Legenda<textarea data-caption maxlength="3000" required>${esc(t.caption)}</textarea></label><label>Movimento<select data-motion>${['gentle','slow','romantic'].map(m=>'<option value="'+m+'" '+(m===t.motion?'selected':'')+'>'+({gentle:'Suave',slow:'Lento',romantic:'Romântico'}[m])+'</option>').join('')}</select></label></fieldset>`).join('');}
 async function report(){const node=$('#vg-report-data');node.textContent='Consultando resultados…';try{const d=await api({operation:'report',days:Number($('#vg-report-days').value)});node.innerHTML='<div class="vg-report-scroll"><table><thead><tr><th>Publicação</th><th>Visualizações</th><th>Visitantes</th><th>Sessões</th><th>Interesse</th><th>Cliques</th><th>Consultas de datas</th><th>Intenção de reserva</th><th>Reservas iniciadas</th><th>Reservas pagas</th></tr></thead><tbody>'+d.rows.map(r=>'<tr><th>'+esc(r.title)+'</th>'+['views','visitors','sessions','interest','clicks','date_queries','reservation_intent','reservations_started','reservations_paid'].map(k=>'<td>'+r[k]+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}catch(e){node.textContent='Não foi possível consultar as métricas. Os valores não foram tratados como zero.'}}
 let reviewPage=0,reviewRows=null,reviewLoading=false;
 async function openReviewQueue(page=0){
  if(guest||!data||reviewLoading)return;reviewLoading=true;toggleLibrary(true);$('#vg-filter').value='pending_review';$('#vg-library-message').textContent='Carregando aprovações…';
  try{const r=await api({operation:'community_review_queue',page});if(page>0&&!r.publications.length){reviewLoading=false;return openReviewQueue(0)}reviewPage=r.page;reviewRows=r.publications;data.publications=data.publications.filter(p=>!r.publications.some(n=>n.id===p.id)).concat(r.publications);renderList();$('#vg-library-message').textContent=r.total?r.total+' momento(s) aguardando aprovação.':'Nenhum momento aguardando aprovação.';$('#vg-review-pagination').hidden=r.total<=50;$('#vg-review-page').textContent='Página '+(page+1)+' de '+Math.max(1,Math.ceil(r.total/50));$('#vg-review-prev').disabled=page===0;$('#vg-review-next').disabled=(page+1)*50>=r.total;}
  catch(e){$('#vg-library-message').textContent=message(e)}finally{reviewLoading=false}
 }
 document.addEventListener('villegram-review-open',e=>{if(!guest&&data){e.preventDefault();openReviewQueue()}});
 $('#vg-review-prev').onclick=()=>openReviewQueue(reviewPage-1);$('#vg-review-next').onclick=()=>openReviewQueue(reviewPage+1);
 async function boot(){const r=await sb.auth.getSession();session=r.data.session;if(!session){location.href='auth.html?mode=login&return='+encodeURIComponent('villegram-admin.html'+location.search);return}try{await load();if(!new URLSearchParams(location.search).get('edit'))centerComposer();if(!guest&&new URLSearchParams(location.search).get('review')==='pending')await openReviewQueue()}catch(e){$('#vg-admin-message').textContent=message(e);if(guest){const a=document.createElement('a');a.href='conta.html';a.textContent='Abrir Meu Ville Moments para configurar o perfil';$('#vg-admin-message').append(document.createElement('br'),a)}}}

 function moderate(p){const panel=document.createElement('dialog');panel.className='vg-review-dialog';panel.innerHTML='<h2>Momento de '+esc(p.author_name)+'</h2><p>'+esc(p.title)+'</p><p>'+esc(p.caption)+'</p><p>A aprovação torna a mídia e a legenda públicas. Confira a prévia antes de aprovar.</p><button type="button" data-look>Ver prévia</button><label>Motivo para devolver ao hóspede<textarea maxlength="500"></textarea></label><p role="status"></p><div><button type="button" data-approve '+(p.status!=='pending_review'?'disabled':'')+'>Aprovar e publicar</button><button type="button" data-reject>Devolver / arquivar</button><button type="button" data-close>Fechar</button></div>';document.body.append(panel);panel.showModal();panel.querySelector('[data-close]').onclick=()=>panel.close();panel.onclose=()=>panel.remove();panel.querySelector('[data-look]').onclick=async()=>{panel.close();try{await openPublicationPreview(p,p.id)}catch(e){$('#vg-library-message').textContent=message(e)}};for(const [selector,status] of [['[data-approve]','published'],['[data-reject]','archived']])panel.querySelector(selector).onclick=async()=>{try{await api({operation:'community_moderate',id:p.id,updated_at:p.updated_at,status,reason:panel.querySelector('textarea').value});panel.close();await api({operation:'admin_list'}).then(r=>{data.publications=r.publications}).catch(()=>{data.publications=data.publications.filter(row=>row.id!==p.id)});await openReviewQueue(reviewPage);document.dispatchEvent(new Event('villegram-review-changed'))}catch(e){panel.querySelector('[role=status]').textContent=message(e)}};}
 function guestSetup(){if(!guest)return;document.body.classList.add('vg-guest-editor');document.title='Seu momento | Ville Moments';$('.vg-admin-nav').innerHTML='<a href="conta.html">← Meu Ville Moments</a><a href="index.html">Descobrir</a>';$('.vg-admin-head small').textContent='SUAS MEMÓRIAS NO VILLE';$('.vg-admin-head h1').textContent='Compartilhe seu momento';$('.vg-admin-head p').textContent='Um mergulho, um café, uma paisagem. Conte a experiência do seu jeito.';$('[data-panel="1"] .vg-step-intro').textContent='Toque em Aa sobre a foto para escrever, escolher cores e arrastar o texto. O título e a descrição abaixo são opcionais quando a cena já tem texto.';$('.vg-automation').hidden=true;$('.vg-report').hidden=true;$('.vg-admin-media details').hidden=true;$('.vg-advanced').hidden=true;f.elements.type.closest('label').hidden=true;f.elements.cta.closest('label').hidden=true;$('#vg-publish-heading').textContent='Pronto para compartilhar?';$('[data-panel="2"] .vg-step-intro').textContent='A equipe revisa seu momento antes de publicar. Suas datas e dados de reserva não aparecem.';const label=document.createElement('label');label.textContent='Marcar pessoas (opcional)';const input=document.createElement('input');input.name='mentions';input.placeholder='@nome @outrapessoa';input.maxLength=250;label.append(input);$('[data-panel="1"]').append(label);const note=document.createElement('p');note.textContent='Use o @nome do perfil. A marcação só aparece depois que a pessoa aceitar.';label.after(note);$('#vg-filter option[value=automatic]').remove();}
 guestSetup();
 textEditor=window.VillegramText?.editor({screen:$('#vg-composer-screen'),getMedia:()=>media[selected],isBusy:()=>uploading||saving,onChange:()=>{const text=media.flatMap(m=>(m.text_layers||[]).map(t=>t.text)).join('\n');if(text&&!f.elements.title.value)f.elements.title.value=text.slice(0,140);if(text&&!f.elements.caption.value)f.elements.caption.value=text;updateComposition();}});
 function centerComposer(){requestAnimationFrame(()=>$('#vg-composer-screen').scrollIntoView({behavior:window.matchMedia?.('(prefers-reduced-motion: reduce)')?.matches?'auto':'smooth',block:'center'}))}$('#vg-new').onclick=()=>{if(uploading||saving)return;edit();centerComposer()};$('#vg-filter').onchange=()=>{if(!guest&&$('#vg-filter').value==='pending_review')openReviewQueue();else{reviewRows=null;$('#vg-review-pagination').hidden=true;renderList()}};$('#vg-upload').onchange=e=>uploadFiles([...e.target.files]);$('#vg-upload-retry').onclick=async()=>{if(uploading||saving)return;uploading=true;hideMediaMenu();busy();$('#vg-upload-retry').hidden=true;try{await finishUpload();uploadNotice('Upload concluído.','success')}catch(e){uploadNotice(e.message,'error');$('#vg-upload-retry').hidden=!pendingUpload;}finally{uploading=false;busy()}};f.onsubmit=e=>{e.preventDefault();save(e.submitter?.name==='published'||current?.status==='published'?'published':'draft')};f.elements.type.onchange=()=>{f.elements.cta.value=({property:'property',experience:'experience',offer:'offer',trust:'dates'})[f.elements.type.value];updateComposition();invalidateStay()};$('#vg-archive').onclick=()=>save('archived');$('#vg-preview').onclick=preview;$('#vg-report-days').onchange=report;
 $('#vg-stay-refresh').onclick=consultStay;for(const name of ['cta','property_id','offer_id','stay_fixed','stay_check_in','stay_check_out','stay_guests'])f.elements[name].addEventListener('change',invalidateStay);
 $('#vg-library-toggle').onclick=()=>toggleLibrary($('#vg-publications-library').hidden);$('#vg-library-close').onclick=()=>toggleLibrary(false);
 f.querySelectorAll('[data-panel] h3').forEach(h=>h.tabIndex=-1);f.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const next=Number(b.dataset.step);if(next<=step||validateThrough(next)){setStep(next,true);$('#vg-editor-message').textContent=''}});$('#vg-step-next').onclick=()=>{if(validateThrough(step+1)){setStep(step+1,true);$('#vg-editor-message').textContent=''}};$('#vg-step-back').onclick=()=>setStep(Math.max(0,step-1),true);f.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target===f.elements.title&&step<2){e.preventDefault();if(validateThrough(step+1))setStep(step+1,true)}});f.addEventListener('input',()=>updateComposition());f.addEventListener('change',()=>updateComposition());
 $('#vg-automation-form').onsubmit=async e=>{e.preventDefault();const a=e.currentTarget,templates={};a.querySelectorAll('[data-template]').forEach(n=>templates[n.dataset.template]={enabled:n.querySelector('[data-enabled]').checked,title:n.querySelector('[data-title]').value,caption:n.querySelector('[data-caption]').value,motion:n.querySelector('[data-motion]').value});try{const d=await api({operation:'save_settings',updated_at:data.settings.updated_at,settings:{enabled:a.elements.enabled.checked,auto_publish:a.elements.auto_publish.value==='true',frequency_hours:Number(a.elements.frequency_hours.value),max_offers:Number(a.elements.max_offers.value),templates}});data.settings=d.settings;$('#vg-automation-message').textContent='Configuração salva. Os modelos valem para os novos conteúdos.'}catch(e){$('#vg-automation-message').textContent=message(e)}};
 function showAutomatic(){if(!data)return;$('#vg-filter').value='automatic';renderList();toggleLibrary(true);$('#vg-publications-library').scrollIntoView({block:'start',behavior:'smooth'});}
 $('#vg-open-generated').onclick=showAutomatic;
 $('#vg-generate').onclick=async()=>{const b=$('#vg-generate');if(uploading||saving)return;b.disabled=true;const before=new Set(data.publications.map(p=>p.id));try{const result=await api({operation:'generate'});await load(true);const generated=data.publications.filter(p=>p.source==='automatic'),fresh=generated.filter(p=>!before.has(p.id)),drafts=fresh.filter(p=>p.status==='draft'||p.status==='pending_review').length;const message=result.created?result.created+' nova(s) publicação(ões). '+(drafts?drafts+' para revisar. ':'')+'Abra Ver prévia para conferir.':'Nenhuma publicação nova: os temas existentes foram preservados. Há '+generated.length+' publicação(ões) do motor automático para visualizar.';$('#vg-automation-message').textContent=message;showAutomatic();$('#vg-library-message').textContent=message;}catch(e){$('#vg-automation-message').textContent=message(e)}finally{b.disabled=false}};$('#vg-composer-screen').append($('#vg-upload-feedback'));enableSceneGestures();enableMediaSurface();boot();
})();
