import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {JSDOM} from 'jsdom';
function setup(){const dom=new JSDOM('',{runScripts:'outside-only'});dom.window.eval(readFileSync('image-manifest.js','utf8'));dom.window.eval(readFileSync('responsive-images.js','utf8'));return dom.window}
test('every local variant exists and original gallery images resolve',()=>{const w=setup();for(const [url,variants] of Object.entries(w.VILLE_IMAGE_MANIFEST)){assert.ok(variants.length);for(const v of variants)assert.ok(existsSync(v.url),v.url);assert.equal(w.VilleImages.variants(url+'?v=2').length,variants.length)}});
test('hidden carousel photos have no request URL until activated',()=>{const w=setup(),img=w.document.createElement('img');w.VilleImages.set(img,'assets/hero-signature.webp',{defer:true});assert.equal(img.getAttribute('src'),null);assert.equal(img.getAttribute('srcset'),null);w.VilleImages.activate(img);assert.match(img.src,/opt-w1600/);assert.match(img.srcset,/640w/);assert.equal(img.dataset.src,undefined)});
test('new uploads resolve both variants; legacy photos retain their original URL',()=>{const w=setup();const url='https://example.test/responsive-abcd-1234-w1200.webp';const v=w.VilleImages.variants(url);assert.equal(v[0].width,640);assert.equal(v[1].width,1200);assert.equal(w.VilleImages.variants('https://example.test/old.webp').length,0);assert.equal(w.VilleImages.variants('https://example.test/responsive-abcd-w400.webp').length,1)});
test('upload compressor preserves aspect ratio, caps width and closes the bitmap',async()=>{const w=setup(),sizes=[];let closed=false;w.createImageBitmap=async()=>({width:2400,height:1800,close(){closed=true}});w.HTMLCanvasElement.prototype.getContext=function(){return{drawImage(){}}};w.HTMLCanvasElement.prototype.toBlob=function(cb,type){sizes.push([this.width,this.height]);cb(new w.Blob(['test'],{type}))};const variants=await w.VilleImages.compress({});assert.deepEqual(sizes,[[640,480],[1600,1200]]);assert.equal(variants.length,2);assert.equal(closed,true)});
test('small uploads are not enlarged and failed encodes are rejected',async()=>{const w=setup();w.createImageBitmap=async()=>({width:400,height:300,close(){}});w.HTMLCanvasElement.prototype.getContext=()=>({drawImage(){}});w.HTMLCanvasElement.prototype.toBlob=function(cb,type){assert.equal(this.width,400);cb(new w.Blob(['test'],{type}))};assert.equal((await w.VilleImages.compress({})).length,1);w.HTMLCanvasElement.prototype.toBlob=cb=>cb(null);await assert.rejects(w.VilleImages.compress({}),/converter/)});
