import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {JSDOM} from 'jsdom';
const wait=async(p)=>{for(let i=0;i<100;i++){if(p())return;await new Promise(r=>setTimeout(r,3))}assert.fail('UI did not settle')};
test('guest sees approval warning and sends a request without invoking payment',async()=>{
 const w=new JSDOM('<input id="book-in" value="2026-10-03"><input id="book-out" value="2026-10-05"><input id="book-guests" value="2">',{runScripts:'outside-only',url:'https://qa.example/reservar.html'}).window;
 const calls=[];w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.api=async(a,b)=>{calls.push([a,b]);return {ok:true}};
 try{w.eval(`const $=s=>document.querySelector(s),esc=s=>String(s),state={session:{},search:[{id:1,name:'QA'}]};`+readFileSync('booking.js','utf8').split('async function openSameDayRequest')[1].split('async function restoreSameDay')[0].replace(/^/,'async function openSameDayRequest')+';window.openRequest=openSameDayRequest;');await w.openRequest(1);assert.match(w.document.body.textContent,/passará por aprovação/);const f=w.document.querySelector('form');f.elements.guest_name.value='QA Pessoa';f.elements.guest_phone.value='27999990000';f.dispatchEvent(new w.Event('submit',{cancelable:true,bubbles:true}));await wait(()=>w.document.body.textContent.includes('Pedido recebido'));assert.equal(calls.length,1);assert.equal(calls[0][0],'same_day_request');assert.equal(calls[0][1].operation,'create');}finally{w.close()}
});
test('admin opens urgent request and approves explicitly, without charging',async()=>{
 const w=new JSDOM('<div id="admin-modal-content"></div>',{runScripts:'outside-only'}).window;const calls=[];let status='pending';w.api=async(a,b)=>{calls.push(b.operation);if(b.operation==='approve')status='approved';return {request:{id:'r',property_id:1,guest_name:'QA',guest_phone:'27999990000',check_in:'2026-10-03',check_out:'2026-10-05',guests:2,status,expires_at:'2026-10-03T23:00:00Z'}}};
 try{const s=readFileSync('admin.js','utf8'),body=s.slice(s.indexOf('async function openSameDayReview'),s.indexOf('function renderNotifications'));
 w.eval(`const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s||''),prop=()=>({name:'QA'}),date=s=>s,dateTime=s=>s,openModal=()=>{},load=async()=>{};`+body+';window.review=openSameDayReview');await w.review('r');assert.deepEqual(calls,['get']);w.document.querySelector('#approve-same-day').click();await wait(()=>w.document.body.textContent.includes('Aprovado para pagamento'));assert.deepEqual(calls,['get','approve','get']);}finally{w.close()}
});
