import {test} from 'node:test';import assert from 'node:assert/strict';import {sameDayRequests,approvedSameDayRequest,requestActive} from '../supabase/functions/_shared/same-day-requests.ts';
const now=new Date('2026-10-03T19:00Z'),id='11111111-1111-4111-8111-111111111111',user={id:'guest'},manager={id:'admin'};
function db(){const rows=[];return {rows,from(){let fs=[],mode='get',data,one=false,head=false;const q={select(_,opts){head=!!opts?.head;return q},order(){return q},limit(){return q},eq(k,v){fs.push(r=>r[k]===v);return q},gt(k,v){fs.push(r=>r[k]>v);return q},maybeSingle(){one=true;return q},single(){one=true;return q},insert(v){mode='insert';data=v;return q},update(v){mode='update';data=v;return q},then(resolve){let result=rows.filter(r=>fs.every(f=>f(r)));if(mode==='insert'){const r={...data,id,status:'pending'};rows.push(r);result=[r]}if(mode==='update')result.forEach(r=>Object.assign(r,data));return Promise.resolve({data:head?null:one?result[0]||null:result.map(x=>({...x})),count:result.length}).then(resolve)}};return q}}}
const input={operation:'create',property_id:1,check_in:'2026-10-03',check_out:'2026-10-05',guests:2,guest_name:'Pessoa QA',guest_phone:'27999991234',estimated_arrival_time:'18:30'},available=async()=>({available:true,same_day_approval_required:true});
test('request is idempotent, requires availability, cannot be created for tomorrow',async()=>{const d=db();await sameDayRequests(d,input,user,false,available,now);await sameDayRequests(d,input,user,false,available,now);assert.equal(d.rows.length,1);assert.equal(d.rows[0].status,'pending');await assert.rejects(()=>sameDayRequests(db(),{...input,check_in:'2026-10-04'},user,false,available,now),/invalid_request/);await assert.rejects(()=>sameDayRequests(db(),input,user,false,async()=>({available:false}),now),/dates_unavailable/)});
test('guest cannot approve or read another guest request; approval expires in one hour',async()=>{const d=db();await sameDayRequests(d,input,user,false,available,now);await assert.rejects(()=>sameDayRequests(d,{operation:'approve',id},user,false,available,now),/admin_required/);await assert.rejects(()=>sameDayRequests(d,{operation:'get',id},{id:'other'},false,available,now),/request_not_found/);await sameDayRequests(d,{operation:'approve',id},manager,true,available,now);assert.equal(d.rows[0].expires_at,'2026-10-03T20:00:00.000Z');await approvedSameDayRequest(d,id,'guest',input,now);await assert.rejects(()=>approvedSameDayRequest(d,id,'other',input,now));await assert.rejects(()=>approvedSameDayRequest(d,id,'guest',{...input,guests:3},now));await assert.rejects(()=>approvedSameDayRequest(d,id,'guest',input,new Date('2026-10-03T20:00Z')));});
test('approval rechecks occupied dates and repeated decision cannot change rejection',async()=>{const d=db();await sameDayRequests(d,input,user,false,available,now);await assert.rejects(()=>sameDayRequests(d,{operation:'approve',id},manager,true,async()=>({available:false}),now),/dates_unavailable/);assert.equal(d.rows[0].status,'pending');await sameDayRequests(d,{operation:'reject',id},manager,true,available,now);assert.equal(d.rows[0].status,'rejected');await assert.rejects(()=>sameDayRequests(d,{operation:'approve',id},manager,true,available,now));});
test('Brazil midnight expires pending requests without permitting checkout',()=>{assert.equal(requestActive({status:'pending',check_in:'2026-10-03',expires_at:'2026-10-04T02:59:59Z'},new Date('2026-10-04T03:00Z')),false)});

test('arrival time is required and valid, preserved for review',async()=>{for(const time of ['', '24:00','18:75'])await assert.rejects(()=>sameDayRequests(db(),{...input,estimated_arrival_time:time},user,false,available,now),/invalid_request/);const d=db();await sameDayRequests(d,input,user,false,available,now);assert.equal(d.rows[0].estimated_arrival_time,'18:30');});
