import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';import ts from 'typescript';
import * as publications from '../supabase/functions/_shared/villegram-publications.ts';
import {commentText} from '../supabase/functions/_shared/villegram.ts';
const id='4069a585-7cc6-48ad-9263-567358a45c0c',dev='https://pxfqmnhqodqyaaqeyjgr.supabase.co';
async function handler({project=dev,logged=false,role='guest'}={}){
 let serve,writes=0;const db={auth:{getUser:async()=>({data:{user:logged?{id}:null},error:logged?null:Error('invalid token')})},from(table){const data=table==='profiles'?{role,pms_access_status:'active'}:table==='villegram_publications'?{id,status:'published'}:null;const query={select(){return this},eq(){return this},maybeSingle:async()=>({data,error:null}),insert(){writes++;return this},upsert(){writes++;return this},update(){writes++;return this}};return query;}};
 const source=await readFile(new URL('../supabase/functions/villegram-content/index.ts',import.meta.url),'utf8'),compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 vm.runInNewContext(compiled,{exports:{},require(name){return name.startsWith('npm:')?{createClient:()=>db}:name.includes('villegram-publications')?publications:{commentText}},Deno:{env:{get:k=>k==='SUPABASE_URL'?project:'test-key'},serve:fn=>serve=fn},Response,URL,console});
 return {request:body=>serve(new Request(dev+'/functions/v1/villegram-content',{method:'POST',headers:{'Content-Type':'application/json',...(logged?{authorization:'Bearer test'}:{})},body:JSON.stringify(body)})),writes:()=>writes};
}
test('DEV-only service rejects another project before touching the database',async()=>{const s=await handler({project:'https://other.supabase.co',logged:true,role:'admin'}),r=await s.request({operation:'save'});assert.equal(r.status,403);assert.equal((await r.json()).error,'development_only');assert.equal(s.writes(),0)});
test('anonymous interactions and guest publication writes require the correct authentication/role',async()=>{const anon=await handler(),like=await anon.request({operation:'like',publication_id:id,liked:true});assert.equal(like.status,401);assert.equal(anon.writes(),0);const guest=await handler({logged:true}),save=await guest.request({operation:'save',publication:{status:'published'}});assert.equal(save.status,403);assert.equal(guest.writes(),0)});
test('public telemetry cannot confirm payment and unauthenticated callers cannot claim a reservation',async()=>{const s=await handler();let r=await s.request({operation:'signals',events:[{event_id:id,publication_id:id,visitor_id:id,session_id:id,view_id:id,kind:'payment_confirmed'}]});assert.equal(r.status,400);r=await s.request({operation:'attribute',reservation_id:id});assert.equal(r.status,401);assert.equal(s.writes(),0)});
