import {guestInput} from '../supabase/functions/_shared/villegram-community.ts';
import {publicationInput} from '../supabase/functions/_shared/villegram-publications.ts';
import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';
const uid='4069a585-7cc6-48ad-9263-567358a45c0c',url='https://pxfqmnhqodqyaaqeyjgr.supabase.co';
const tick=()=>new Promise(r=>setTimeout(r,10));
test('TUS resumes a failed second chunk from the server offset without duplicating the file',async()=>{
 const d=new JSDOM('',{url,runScripts:'outside-only'}),w=d.window;w.CHALEZINHO_CONFIG={supabaseUrl:url,supabaseKey:'public-key'};w.AbortSignal.timeout=()=>undefined;
 let offset=0,creates=0,fail=true;const offsets=[];w.fetch=async(_url,r)=>{if(r.method==='POST'){creates++;return {ok:true,headers:new Headers({Location:url+'/storage/v1/upload/resumable/test'})}}if(r.method==='HEAD')return {ok:true,headers:new Headers({'Upload-Offset':String(offset)})};offsets.push(Number(r.headers['Upload-Offset']));if(offset>0&&fail){fail=false;return {ok:false}}offset+=r.body.size;return {ok:true,headers:new Headers({'Upload-Offset':String(offset)})}};
 w.eval(await readFile(new URL('../villegram-upload.js',import.meta.url),'utf8'));const sb={auth:{getSession:async()=>({data:{session:{access_token:'test'}}})}},file=new Blob([new Uint8Array(7*1024*1024)],{type:'video/mp4'});
 await assert.rejects(w.VillegramUpload.upload(sb,file,uid+'/test.mp4'),/interrompido/);assert.equal(offset,6*1024*1024);
 await w.VillegramUpload.upload(sb,file,uid+'/test.mp4');assert.equal(offset,file.size);assert.equal(creates,1);assert.deepEqual(offsets,[0,6*1024*1024,6*1024*1024]);d.window.close();
});
async function editor({quoteResponder,initialRows=[],generatedRows=[],guest=false}={}){const d=new JSDOM(await readFile(new URL('../villegram-admin.html',import.meta.url),'utf8'),{url:url+'/villegram-admin.html'+(guest?'?mode=guest':''),runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;const rows=[...initialRows],saved=[],quotes=[],previews=[];w.CHALEZINHO_CONFIG={supabaseUrl:url,supabaseKey:'public-key'};w.AbortSignal.timeout=()=>undefined;w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLMediaElement.prototype.pause=function(){};w.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:'test',user:{id:uid}}}})}})};
 w.fetch=async(_url,opts)=>{const b=JSON.parse(opts.body);if(b.action==='villegram_quote'){quotes.push(b);return response(await quoteResponder?.(b)||{rate_options:[]})}if(['admin_list','guest_list'].includes(b.operation))return response({profile:{display_name:'Hóspede público'},suggested_property_id:1,publications:rows,properties:[{id:1,name:'Ville',gallery:['assets/photo.webp']}],products:[],offers:[{id:'a8116a6a-66e2-471f-8a6a-d35daa690887',name:'Escapada a dois'}],settings:{enabled:true,auto_publish:false,frequency_hours:24,max_offers:3,templates:{}}});if(b.operation==='generate'){rows.push(...generatedRows);return response({created:generatedRows.length})}if(b.operation==='preview'){previews.push(b);let checked;try{checked=publicationInput(b.publication,url)}catch(e){return {ok:false,json:async()=>({ok:false,error:e.message})}}return response({publication:{...checked,id:b.id},properties:[{id:1,name:'Ville',code:'CH1'}],products:[],offers:[]})}if(b.operation==='report')return response({rows:[]});if(b.operation==='community_review_queue'){const pending=rows.filter(p=>p.status==='pending_review'&&p.source==='guest_submission');return response({publications:pending.slice((b.page||0)*50,(b.page||0)*50+50),total:pending.length,page:b.page||0})}if(b.operation==='community_moderate'){rows.find(p=>p.id===b.id).status=b.status;return response({})}if(['save','guest_save'].includes(b.operation)){saved.push(b);const p={...(guest?guestInput(b.publication,url,uid):b.publication),id:b.id||uid,updated_at:'revision-'+saved.length,author_name:'Equipe'};rows.splice(0,rows.length,p);return response({publication:p})}return response({})};function response(data){return {ok:true,json:async()=>({ok:true,...data})}}
 w.VillegramMedia={transform:async()=>new Blob(['photo'],{type:'image/webp'})};w.URL.createObjectURL=()=>url+'/preview.webp';w.eval(await readFile(new URL('../villegram-text.js',import.meta.url),'utf8'));w.eval(await readFile(new URL('../villegram-effects.js',import.meta.url),'utf8'));w.eval(await readFile(new URL('../villegram-admin.js',import.meta.url),'utf8'));await tick();return {d,w,rows,saved,quotes,previews};}
test('manual editor saves draft, retains identity during edit, publishes and archives',async()=>{
 const {d,w,saved}=await editor(),f=w.document.querySelector('#vg-post-form');f.elements.property_id.value='1';f.elements.title.value='Manual';f.elements.caption.value='Foto real';w.document.querySelector('[data-photo]').click();
 f.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:f.querySelector('[name=draft]')}));await tick();assert.equal(saved[0].publication.status,'draft');assert.match(w.document.querySelector('#vg-editor-message').textContent,/Rascunho salvo/);
 f.elements.caption.value='Legenda editada';f.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:f.querySelector('[name=published]')}));await tick();assert.equal(saved[1].id,uid);assert.equal(saved[1].updated_at,'revision-1');assert.equal(saved[1].publication.status,'published');assert.equal(saved[1].publication.caption,'Legenda editada');
 w.document.querySelector('#vg-archive').click();await tick();assert.equal(saved[2].publication.status,'archived');assert.equal(saved[2].id,uid);d.window.close();
});
test('retrying a failed video poster upload preserves the already uploaded video',async()=>{
 const {d,w}=await editor();let videoUploads=0,posterUploads=0,fail=true;w.VillegramUpload={inspect:async()=>({url:'blob:video',video:{duration:4}}),poster:async()=>new Blob(['poster']),upload:async(_sb,_file,path)=>{if(path.endsWith('.mp4'))videoUploads++;else{posterUploads++;if(fail){fail=false;throw Error('upload failed')}}}};
 const input=w.document.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['video'],'real.mp4',{type:'video/mp4'})]});input.dispatchEvent(new w.Event('change'));await tick();assert.equal(w.document.querySelector('#vg-upload-retry').hidden,false);assert.equal(videoUploads,1);
 w.document.querySelector('#vg-upload-retry').click();await tick();assert.equal(videoUploads,1);assert.equal(posterUploads,2);assert.equal(w.document.querySelectorAll('#vg-composer-visual video').length,1);d.window.close();
});

test('native publication clicks and Enter preserve published status during subsequent edits',async()=>{
 const {d,w,saved}=await editor(),f=w.document.querySelector('#vg-post-form');f.elements.property_id.value='1';f.elements.title.value='Publicação';f.elements.caption.value='Cena real';w.document.querySelector('[data-photo]').click();
 f.querySelector('[name=published]').click();await tick();assert.equal(saved[0].publication.status,'published');assert.equal(w.document.querySelector('#vg-post-status').textContent,'Publicada');assert.equal(f.querySelector('[name=draft]').hidden,true);assert.equal(f.querySelector('[name=published]').textContent,'Salvar alterações');
 const link=w.document.querySelector('#vg-view-post');assert.equal(link.hidden,false);assert.equal(new URL(link.href).searchParams.get('publication'),uid);
 f.elements.caption.value='Legenda corrigida';f.requestSubmit();await tick();assert.equal(saved[1].publication.status,'published');assert.equal(saved[1].publication.caption,'Legenda corrigida');assert.equal(saved[1].id,uid);assert.equal(saved[1].updated_at,'revision-1');
 // A stale caller selecting the old draft action must also preserve publication.
 f.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:f.querySelector('[name=draft]')}));await tick();assert.equal(saved[2].publication.status,'published');
 w.document.querySelector('#vg-archive').click();await tick();assert.equal(saved[3].publication.status,'archived');assert.equal(link.hidden,true);assert.equal(w.document.querySelector('#vg-post-status').textContent,'Arquivada');d.window.close();
});
test('uploaded video can be published by clicking the actual button and saved edits keep the file identity',async()=>{
 const {d,w,saved}=await editor(),f=w.document.querySelector('#vg-post-form');w.VillegramUpload={inspect:async()=>({url:'blob:video',video:{duration:9.7}}),poster:async()=>new Blob(['poster'],{type:'image/webp'}),upload:async()=>{}};
 f.elements.property_id.value='1';f.elements.title.value='Vinho no SPA aquecido?';f.elements.caption.value='Vídeo real do imóvel';const input=w.document.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['video'],'real.mp4',{type:'video/mp4'})]});input.dispatchEvent(new w.Event('change'));await tick();
 assert.match(w.document.querySelector('#vg-upload-status').textContent,/Mídia enviada/);assert.equal(saved.length,0);f.querySelector('[name=published]').click();await tick();assert.equal(saved[0].publication.status,'published');const file=saved[0].publication.media[0];assert.equal(file.kind,'video');assert.ok(file.path.endsWith('.mp4'));assert.ok(file.poster_path.endsWith('.webp'));
 f.elements.caption.value='Nova legenda';f.querySelector('[name=published]').click();await tick();assert.equal(saved[1].publication.status,'published');assert.equal(saved[1].publication.media[0].path,file.path);d.window.close();
});

test('cover generation seeks a decoded frame and rejects a black canvas instead of uploading it',async()=>{
 const d=new JSDOM('',{url,runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;let dark=false;
 w.HTMLCanvasElement.prototype.getContext=()=>({drawImage(){},getImageData(){return {data:Uint8ClampedArray.from([dark?0:50,0,0,255])}}});w.HTMLCanvasElement.prototype.toBlob=function(callback){callback(new w.Blob(['cover'],{type:'image/webp'}))};w.eval(await readFile(new URL('../villegram-upload.js',import.meta.url),'utf8'));
 const video=w.document.createElement('video');let time=0;Object.defineProperties(video,{readyState:{value:2},duration:{value:9.7},videoWidth:{value:2160},videoHeight:{value:3840},currentTime:{get:()=>time,set:value=>{time=value;Promise.resolve().then(()=>video.dispatchEvent(new w.Event('seeked')))}}});
 const cover=await w.VillegramUpload.poster(video);assert.equal(time,.5);assert.equal(cover.type,'image/webp');dark=true;await assert.rejects(w.VillegramUpload.poster(video,1),/capa ficou preta/);assert.equal(time,1);d.window.close();
});

test('visual composer gates empty steps and keeps media, cover, crop and text when returning',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');const click=s=>doc.querySelector(s).click(),change=(n,v)=>{n.value=v;n.dispatchEvent(new w.Event('input',{bubbles:true}))};
 assert.equal(doc.querySelector('[data-panel="0"]').hidden,false);assert.equal(doc.querySelector('[data-panel="1"]').hidden,true);assert.equal(doc.querySelector('#vg-composer-empty').hidden,false);
 click('#vg-step-next');assert.equal(doc.querySelector('[data-panel="0"]').hidden,false);assert.match(doc.querySelector('#vg-editor-message').textContent,/Escolha um vídeo/);
 click('[data-photo]');click('[data-photo]');assert.equal(doc.querySelectorAll('[data-select]').length,2);click('[data-cover="1"]');
 doc.querySelector('#vg-scene-gesture').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowUp',bubbles:true}));assert.equal(doc.querySelector('#vg-composer-visual img').style.transform,'translate(0%, -5%) scale(1)');assert.equal(doc.querySelector('#vg-composer-visual img').style.objectFit,'cover');
 click('#vg-step-next');assert.equal(doc.querySelector('[data-panel="1"]').hidden,false);click('#vg-step-next');assert.equal(doc.querySelector('[data-panel="1"]').hidden,false);assert.equal(doc.activeElement,f.elements.title);
 change(f.elements.title,'Minha cena');change(f.elements.caption,'Minha legenda');assert.equal(doc.querySelector('#vg-composer-title').textContent,'Minha cena');assert.equal(doc.querySelector('#vg-composer-caption').textContent,'Minha legenda');
 click('#vg-step-next');assert.equal(doc.querySelector('[data-panel="2"]').hidden,false);click('[name=published]');await tick();assert.equal(saved.length,0);assert.match(doc.querySelector('#vg-editor-message').textContent,/Escolha o chalé/);
 change(f.elements.property_id,'1');assert.match(doc.querySelector('#vg-destination-summary').textContent,/página do chalé: Ville/);
 click('#vg-step-back');click('#vg-step-back');assert.equal(f.elements.caption.value,'Minha legenda');assert.equal(doc.querySelector('[data-select="1"]').getAttribute('aria-pressed'),'true');assert.equal(doc.querySelector('[data-cover="1"]').disabled,true);
 click('[data-up="1"]');assert.equal(doc.querySelector('[data-select="0"]').getAttribute('aria-pressed'),'true');click('[data-step="2"]');click('[name=draft]');await tick();assert.equal(saved[0].publication.cover_index,0);assert.equal(saved[0].publication.media[0].fit,'cover');assert.equal(saved[0].publication.media[0].offset_y,-5);assert.equal(saved[0].publication.caption,'Minha legenda');d.window.close();
});

test('composer opens its library, edits published posts, and does not restart video while typing or switching steps',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');w.VillegramUpload={inspect:async()=>({url:'blob:video',video:{duration:9.7}}),poster:async()=>new Blob(['poster']),upload:async()=>{}};
 const input=doc.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['video'],'real.mp4',{type:'video/mp4'})]});input.dispatchEvent(new w.Event('change'));await tick();const video=doc.querySelector('#vg-composer-visual video');video.currentTime=3;
 doc.querySelector('#vg-step-next').click();f.elements.title.value='Vídeo';f.elements.caption.value='Texto';f.elements.caption.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(doc.querySelector('#vg-composer-visual video'),video);assert.equal(video.currentTime,3);
 f.elements.title.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));assert.equal(doc.querySelector('[data-panel="2"]').hidden,false);assert.equal(saved.length,0);assert.equal(doc.querySelector('#vg-composer-visual video'),video);
 f.elements.property_id.value='1';f.querySelector('[name=published]').click();await tick();doc.querySelector('#vg-library-toggle').click();assert.equal(doc.querySelector('#vg-publications-library').hidden,false);assert.equal(doc.querySelector('#vg-library-toggle').getAttribute('aria-expanded'),'true');doc.querySelector('[data-edit]').click();assert.equal(doc.querySelector('#vg-publications-library').hidden,true);assert.equal(doc.querySelector('#vg-post-status').textContent,'Publicada');assert.equal(f.querySelector('[name=draft]').hidden,true);assert.equal(saved.length,1);d.window.close();
});

test('slow media upload locks the composer, recovers after failure, and reports preview media errors',async()=>{
 const {d,w}=await editor(),doc=w.document;let finish;const pending=new Promise(r=>finish=r);w.VillegramUpload={inspect:async()=>({url:'blob:video',video:{duration:9}}),poster:async()=>new Blob(['poster']),upload:async()=>pending};
 const input=doc.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['video'],'real.mp4',{type:'video/mp4'})]});input.dispatchEvent(new w.Event('change'));await tick();assert.equal(doc.querySelector('#vg-step-next').disabled,true);assert.equal(doc.querySelector('#vg-new').disabled,true);assert.equal(doc.querySelector('[data-photo]').disabled,true);finish();await tick();assert.equal(doc.querySelector('#vg-step-next').disabled,false);assert.equal(doc.querySelector('#vg-new').disabled,false);
 doc.querySelector('#vg-composer-visual video').dispatchEvent(new w.Event('error'));assert.match(doc.querySelector('#vg-editor-message').textContent,/MP4\/H.264/);doc.querySelector('#vg-media-options').click();doc.querySelector('#vg-media-delete').click();assert.equal(doc.querySelector('#vg-composer-empty').hidden,false);assert.equal(doc.querySelectorAll('[data-select]').length,0);d.window.close();
});

test('scene controls remain on the photo with no framing sliders',async()=>{
 const {d,w}=await editor(),doc=w.document;doc.querySelector('[data-photo]').click();const image=doc.querySelector('#vg-composer-visual img');assert.equal(doc.querySelectorAll('#vg-post-form input[type=range]').length,0);doc.querySelector('#vg-scene-in').click();doc.querySelector('#vg-scene-gesture').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true,cancelable:true}));assert.equal(doc.querySelector('#vg-composer-visual img'),image);assert.equal(image.style.transform,'translate(5%, 0%) scale(1.1)');d.window.close();
});

test('holding and dragging photo thumbnails changes order while retaining the selected cover; keyboard also works',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();doc.querySelector('[data-photo]').click();doc.querySelector('[data-cover="1"]').click();
 const thumb=doc.querySelector('[data-select="1"]'),target=doc.querySelector('[data-select="0"]');doc.elementFromPoint=()=>target;target.getBoundingClientRect=()=>({left:4,right:64,width:60});thumb.getBoundingClientRect=()=>({left:72,right:132,width:60});doc.querySelector('.vg-media-strip').getBoundingClientRect=()=>({left:0,right:160,width:160});
 thumb.dispatchEvent(new w.MouseEvent('pointerdown',{bubbles:true,button:0}));await new Promise(r=>setTimeout(r,340));assert.ok(thumb.classList.contains('vg-dragging'));thumb.dispatchEvent(new w.MouseEvent('pointermove',{bubbles:true,cancelable:true,clientX:1,clientY:1}));thumb.dispatchEvent(new w.MouseEvent('pointerup',{bubbles:true}));assert.equal(doc.querySelector('[data-cover]').dataset.cover,'0');assert.equal(doc.querySelector('[data-select="0"]').getAttribute('aria-pressed'),'true');assert.match(doc.querySelector('#vg-reorder-status').textContent,/capa foi preservada/);
 doc.querySelector('[data-select="0"]').dispatchEvent(new w.KeyboardEvent('keydown',{altKey:true,key:'ArrowRight',bubbles:true,cancelable:true}));assert.equal(doc.querySelector('[data-cover]').dataset.cover,'1');f.elements.property_id.value='1';f.elements.title.value='Ordem';f.elements.caption.value='Fotos';f.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.cover_index,1);d.window.close();
});

test('Quero estes dias quotes both tariffs, reprices packages, and saves only explicit dates and rate',async()=>{
 const {d,w,saved,quotes}=await editor({quoteResponder:async b=>({rate_options:['refundable','non_refundable'].map((code,i)=>({code,name:i?'Não reembolsável':'Reembolsável',selectable:true,total_amount_cents:100000-i*10000+(b.offer_id?20000:0),accommodation_amount_cents:85000-i*10000,cleaning_fee_cents:15000,experience_amount_cents:b.offer_id?20000:0})),experiences:[]})}),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();f.elements.title.value='Dias no Ville';f.elements.caption.value='Sua estadia';const change=(name,value)=>{f.elements[name].value=value;f.elements[name].dispatchEvent(new w.Event('change',{bubbles:true}))};change('property_id','1');change('cta','offer');assert.equal(doc.querySelector('#vg-stay-choice').hidden,false);assert.match(f.elements.offer_id.selectedOptions[0].textContent,/Somente hospedagem/);change('stay_check_in','2026-11-16');change('stay_check_out','2026-11-19');doc.querySelector('#vg-stay-refresh').click();await tick();assert.equal(doc.querySelectorAll('[data-stay-rate]').length,2);assert.equal(f.elements.stay_rate_code.value,'');assert.equal(doc.querySelector('#vg-composer-stay').hidden,true);f.querySelector('[name=published]').click();await tick();assert.equal(saved.length,0);
 doc.querySelector('[data-stay-rate="refundable"]').click();assert.match(doc.querySelector('#vg-composer-stay').textContent,/1.000,00/);change('offer_id','a8116a6a-66e2-471f-8a6a-d35daa690887');assert.equal(doc.querySelector('#vg-composer-stay').hidden,true);doc.querySelector('#vg-stay-refresh').click();await tick();assert.match(doc.querySelector('#vg-composer-stay').textContent,/1.200,00/);assert.match(doc.querySelector('[data-stay-rate="refundable"]').textContent,/pacote R\$\s*200,00/);
 f.querySelector('[name=published]').click();await tick();assert.deepEqual(JSON.parse(JSON.stringify(saved[0].publication.stay_selection)),{check_in:'2026-11-16',check_out:'2026-11-19',guests:2,rate_code:'refundable'});assert.equal(saved[0].publication.total_cents,undefined);assert.equal(saved[0].publication.offer_id,quotes.at(-1).offer_id);d.window.close();
});

test('photo crop dialog moves its preview immediately and encodes only on rotate or confirmation',async()=>{
 const d=new JSDOM('',{url,runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;let encoded=0;w.createImageBitmap=async()=>({width:2000,height:1000,close(){}});w.HTMLDialogElement.prototype.showModal=function(){};w.HTMLDialogElement.prototype.close=function(){};w.HTMLCanvasElement.prototype.getContext=()=>({translate(){},rotate(){},drawImage(){}});w.HTMLCanvasElement.prototype.toBlob=function(done){encoded++;done(new w.Blob(['frame'],{type:'image/webp'}))};w.URL.createObjectURL=()=>url+'/crop.webp';w.URL.revokeObjectURL=()=>{};Object.defineProperties(w.HTMLImageElement.prototype,{naturalWidth:{get:()=>2000},naturalHeight:{get:()=>1000}});w.eval(await readFile(new URL('../villegram-media.js',import.meta.url),'utf8'));
 const result=w.VillegramMedia.editor(new w.Blob(['photo']));await tick();const dialog=w.document.querySelector('dialog'),image=dialog.querySelector('img'),format=dialog.querySelector('select'),position=dialog.querySelector('input'),initial=encoded;assert.equal(position.disabled,true);format.value='portrait';format.dispatchEvent(new w.Event('change'));assert.equal(position.disabled,false);assert.equal(dialog.querySelector('.vg-crop-frame').style.aspectRatio,String(9/16));position.value='0';position.dispatchEvent(new w.Event('input'));assert.equal(image.style.objectPosition,'0% 0%');position.value='100';position.dispatchEvent(new w.Event('input'));assert.equal(image.style.objectPosition,'100% 100%');assert.equal(encoded,initial);dialog.querySelector('[data-save]').click();const saved=await result;assert.equal(saved.type,'image/webp');assert.ok(encoded>initial);assert.equal(w.document.querySelector('dialog'),null);d.window.close();
});

test('changing dates while a quote is pending cannot show the old total or publish it',async()=>{
 let finish;const held=new Promise(r=>finish=r);const {d,w,saved}=await editor({quoteResponder:async()=>held}),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();f.elements.title.value='Datas';f.elements.caption.value='Texto';f.elements.property_id.value='1';f.elements.cta.value='offer';f.elements.cta.dispatchEvent(new w.Event('change',{bubbles:true}));f.elements.stay_check_in.value='2026-11-16';f.elements.stay_check_out.value='2026-11-19';doc.querySelector('#vg-stay-refresh').click();await tick();f.elements.stay_check_in.value='2026-11-17';f.elements.stay_check_in.dispatchEvent(new w.Event('change',{bubbles:true}));finish({rate_options:[{code:'refundable',total_amount_cents:1}]});await tick();assert.equal(doc.querySelectorAll('[data-stay-rate]').length,0);assert.equal(doc.querySelector('#vg-composer-stay').hidden,true);f.querySelector('[name=published]').click();await tick();assert.equal(saved.length,0);d.window.close();
});

function pointer(w,node,type,id,x,y){const e=new w.MouseEvent(type,{bubbles:true,cancelable:true,button:0,clientX:x,clientY:y});Object.defineProperty(e,'pointerId',{value:id});node.dispatchEvent(e);}
test('direct photo pinch and drag preserve the live element and save bounded framing',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();const scene=doc.querySelector('#vg-composer-visual img'),layer=doc.querySelector('#vg-scene-gesture');Object.defineProperties(scene,{naturalWidth:{value:1000},naturalHeight:{value:1600}});doc.querySelector('#vg-composer-visual').getBoundingClientRect=()=>({left:0,top:0,width:200,height:320});scene.dispatchEvent(new w.Event('load'));
 assert.equal(layer.hidden,false);assert.equal(doc.querySelector('.vg-precise-controls'),null);
 pointer(w,layer,'pointerdown',1,50,160);pointer(w,layer,'pointerdown',2,150,160);pointer(w,layer,'pointermove',1,0,160);pointer(w,layer,'pointermove',2,200,160);assert.equal(scene.style.transform,'scale(2)');assert.equal(scene.style.objectPosition,'50% 50%');
 pointer(w,layer,'pointerup',2,200,160);pointer(w,layer,'pointermove',1,50,192);assert.equal(scene.style.transform,'translate(25%, 10%) scale(2)');pointer(w,layer,'pointerup',1,50,192);assert.equal(doc.querySelector('#vg-composer-visual img'),scene);
 f.elements.title.value='Gesto';f.elements.caption.value='Cena';f.elements.property_id.value='1';doc.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.media[0].zoom,2);assert.equal(saved[0].publication.media[0].offset_x,25);assert.equal(saved[0].publication.media[0].offset_y,10);d.window.close();
});
test('photo gestures clamp zoom, cancel between scenes, and overlay controls work without touch',async()=>{
 const {d,w}=await editor(),doc=w.document;doc.querySelector('[data-photo]').click();let scene=doc.querySelector('#vg-composer-visual img');Object.defineProperties(scene,{naturalWidth:{value:1000},naturalHeight:{value:1600}});doc.querySelector('#vg-composer-visual').getBoundingClientRect=()=>({left:0,top:0,width:200,height:320});const layer=doc.querySelector('#vg-scene-gesture');pointer(w,layer,'pointerdown',1,50,100);pointer(w,layer,'pointerdown',2,100,100);pointer(w,layer,'pointermove',2,1000,100);assert.match(scene.style.transform,/scale\(3\)/);pointer(w,layer,'pointermove',2,51,100);assert.match(scene.style.transform,/scale\(1\)/);
 doc.querySelector('[data-photo]').click();const next=doc.querySelector('#vg-composer-visual img');pointer(w,layer,'pointermove',1,500,500);assert.equal(next.style.transform,'scale(1)');doc.querySelector('#vg-scene-in').click();assert.equal(next.style.transform,'scale(1.1)');doc.querySelector('#vg-scene-fit').click();assert.equal(next.style.objectFit,'cover');assert.equal(next.style.transform,'scale(1)');doc.querySelector('[data-scene-action=reset]').click();assert.equal(next.style.transform,'scale(1)');assert.equal(next.style.objectFit,'contain');assert.equal(next.style.objectPosition,'50% 50%');layer.dispatchEvent(new w.KeyboardEvent('keydown',{key:'+',bubbles:true,cancelable:true}));assert.equal(next.style.transform,'scale(1.1)');doc.querySelector('#vg-scene-cover').click();assert.equal(doc.querySelector('[data-cover]').dataset.cover,'1');doc.querySelector('[data-step="1"]').click();assert.equal(layer.hidden,true);assert.equal(doc.querySelector('#vg-scene-tools').hidden,true);d.window.close();
});
test('white insertion marker follows before/after slots and cancelling a drag preserves order',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');for(let n=0;n<3;n++)doc.querySelector('[data-photo]').click();const strip=doc.querySelector('.vg-media-strip'),buttons=[...strip.querySelectorAll('button')];strip.getBoundingClientRect=()=>({left:0,right:250,width:250});buttons.forEach((b,i)=>b.getBoundingClientRect=()=>({left:4+i*70,right:64+i*70,width:60,top:0,height:84}));const marker=strip.querySelector('.vg-insertion-marker');
 pointer(w,buttons[0],'pointerdown',1,20,20);await new Promise(r=>setTimeout(r,340));pointer(w,buttons[0],'pointermove',1,100,20);assert.equal(marker.hidden,false);const ghost=doc.querySelector('.vg-drag-ghost');assert.ok(ghost);assert.match(ghost.style.transform,/translate3d\(84px/);assert.equal(marker.style.left,'70px');pointer(w,buttons[0],'pointermove',1,120,20);assert.equal(marker.style.left,'140px');pointer(w,buttons[0],'pointercancel',1,120,20);assert.equal(marker.hidden,true);assert.equal(doc.querySelector('.vg-drag-ghost'),null);assert.equal(doc.querySelector('[data-select="2"]').getAttribute('aria-pressed'),'true');
 pointer(w,buttons[0],'pointerdown',2,20,20);await new Promise(r=>setTimeout(r,340));pointer(w,buttons[0],'pointermove',2,230,20);assert.equal(marker.style.left,'208px');pointer(w,buttons[0],'pointerup',2,230,20);assert.equal(doc.querySelector('[data-cover]').dataset.cover,'1');assert.equal(doc.querySelector('[data-select="2"]').textContent.includes('Capa'),true);f.elements.title.value='Ordem';f.elements.caption.value='Fotos';f.elements.property_id.value='1';doc.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.cover_index,2);d.window.close();
});

test('photo moves freely on both axes even at original zoom and cannot be lost outside canvas',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();const scene=doc.querySelector('#vg-composer-visual img'),layer=doc.querySelector('#vg-scene-gesture');Object.defineProperties(scene,{naturalWidth:{value:1000},naturalHeight:{value:1600}});doc.querySelector('#vg-composer-visual').getBoundingClientRect=()=>({left:0,top:0,width:200,height:320});pointer(w,layer,'pointerdown',1,100,160);await new Promise(r=>setTimeout(r,520));pointer(w,layer,'pointermove',1,140,128);assert.equal(scene.style.transform,'translate(20%, -10%) scale(1)');pointer(w,layer,'pointermove',1,2000,2000);assert.equal(scene.style.transform,'translate(50%, 50%) scale(1)');pointer(w,layer,'pointerup',1,2000,2000);f.elements.title.value='Movimento';f.elements.caption.value='Foto';f.elements.property_id.value='1';doc.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.media[0].offset_x,50);assert.equal(saved[0].publication.media[0].offset_y,50);d.window.close();
});
test('automatic generation opens its library and previews without replacing unsaved composition',async()=>{
 const automatic={id:'automatic-1',source:'automatic',type:'property',title:'Ville automático',caption:'Apresentação',status:'draft',property_id:1,cta:'property',cover_index:0,media:[{kind:'photo',url:'assets/photo.webp'}]},manual={...automatic,id:'manual-1',source:'manual',title:'Manual'};
 const {d,w,saved,previews}=await editor({initialRows:[manual],generatedRows:[automatic]}),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();f.elements.title.value='Minha edição ainda não salva';f.elements.caption.value='Texto em andamento';let opened;w.VillegramContent={propertyURL:()=>'/ville-signature.html'};w.Villegram={configurePublications(){},open:c=>opened=c};doc.querySelector('#vg-generate').click();await tick();await tick();assert.equal(doc.querySelector('#vg-publications-library').hidden,false);assert.equal(doc.querySelector('#vg-filter').value,'automatic');assert.equal(doc.querySelectorAll('[data-preview-post]').length,1);assert.match(doc.querySelector('#vg-library-message').textContent,/1 para revisar/);doc.querySelector('[data-preview-post]').click();await tick();assert.equal(previews[0].id,automatic.id);assert.equal(opened.preview,true);assert.equal(opened.publication.title,automatic.title);assert.equal(f.elements.title.value,'Minha edição ainda não salva');assert.equal(f.elements.caption.value,'Texto em andamento');assert.equal(saved.length,0);d.window.close();
});
test('generating zero new posts exposes existing automatic previews with a clear explanation',async()=>{
 const p={id:'auto-existing',source:'automatic',type:'property',title:'Ville',caption:'Apresentação',status:'published',property_id:1,cta:'property',cover_index:0,media:[{kind:'photo',url:'assets/photo.webp'}]};const {d,w}=await editor({initialRows:[p]}),doc=w.document;doc.querySelector('#vg-generate').click();await tick();await tick();assert.equal(doc.querySelector('#vg-publications-library').hidden,false);assert.match(doc.querySelector('#vg-library-message').textContent,/Nenhuma publicação nova/);assert.match(doc.querySelector('#vg-library-message').textContent,/1 publicação/);assert.equal(doc.querySelectorAll('[data-preview-post]').length,1);doc.querySelector('#vg-library-close').click();doc.querySelector('#vg-open-generated').click();assert.equal(doc.querySelector('#vg-filter').value,'automatic');assert.equal(doc.querySelector('#vg-publications-library').hidden,false);d.window.close();
});

test('automatic library preview accepts the real Signature versioned cover through server validation',async()=>{
 const p={id:uid,source:'automatic',type:'property',title:'Ville Signature',caption:'Piscina e SPA',status:'published',property_id:1,cta:'property',cover_index:0,media:[{kind:'photo',url:'assets/ch1-capa-casal-spa.webp?v=2',fit:'contain',position:50}]};const {d,w,saved}=await editor({initialRows:[p]}),doc=w.document;let opened;w.VillegramContent={propertyURL:()=>'/chale-premium.html'};w.Villegram={configurePublications(){},open:c=>opened=c};doc.querySelector('#vg-open-generated').click();doc.querySelector('[data-preview-post]').click();await tick();assert.ok(opened);assert.equal(opened.publication.media[0].url,p.media[0].url);assert.equal(doc.querySelector('#vg-library-message').textContent,'');assert.equal(saved.length,0);d.window.close();
});

test('guest composer reuses photo upload and framing but sends moderation without exposing commercial controls',async()=>{
 const {d,w,saved}=await editor({guest:true}),doc=w.document,f=doc.querySelector('#vg-post-form');
 assert.equal(doc.querySelector('.vg-automation').hidden,true);assert.equal(f.elements.cta.closest('label').hidden,true);assert.equal(doc.querySelector('.vg-admin-media details').hidden,true);assert.match(doc.querySelector('.vg-author-line').textContent,/Hóspede público/);assert.equal(f.elements.property_id.value,'1');
 w.VillegramUpload={upload:async()=>{}};const upload=doc.querySelector('#vg-upload');Object.defineProperty(upload,'files',{value:[new w.File(['photo'],'moment.jpg',{type:'image/jpeg'})]});upload.dispatchEvent(new w.Event('change'));await tick();
 f.elements.title.value='Meu café';f.elements.caption.value='Uma manhã tranquila';f.elements.mentions.value='@amiga';doc.querySelector('[data-step="2"]').click();assert.equal(f.querySelector('[name=published]').textContent,'Enviar para aprovação');f.querySelector('[name=published]').click();await tick();
 assert.equal(saved.length,1);assert.equal(saved[0].operation,'guest_save');assert.deepEqual([...saved[0].mentions],['@amiga']);assert.equal(doc.querySelector('#vg-post-status').textContent,'Aguardando aprovação');assert.match(doc.querySelector('#vg-editor-message').textContent,/equipe vai revisar/);assert.equal(doc.querySelector('#vg-view-post').hidden,true);d.window.close();
});

test('text on scene supports color, transparent background, keyboard positioning and survives save/edit',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');f.elements.property_id.value='1';doc.querySelector('[data-photo]').click();doc.querySelector('.vg-text-tools button').click();
 const input=doc.querySelector('[contenteditable=true]');assert.equal(doc.activeElement,input);assert.equal(doc.querySelector('.vg-text-panel'),null);input.textContent='Café na piscina';input.dispatchEvent(new w.Event('input'));doc.querySelector('[data-text-finish]').click();
 doc.querySelector('.vg-text-edit-stage .vg-text-sticker').click();doc.querySelector('[data-format=color]').click();const fg=doc.querySelector('.vg-text-custom input');fg.value='#ffcc00';fg.dispatchEvent(new w.Event('input'));doc.querySelector('[data-format=background]').click();doc.querySelector('.vg-text-swatches [aria-label="#17130f"]').click();doc.querySelector('[data-format=bold]').click();doc.querySelector('[data-format=italic]').click();doc.querySelector('[data-format=strike]').click();
 assert.equal(f.elements.title.value,'Café na piscina');assert.equal(f.elements.caption.value,'Café na piscina');const sticker=doc.querySelector('.vg-text-edit-stage .vg-text-sticker');sticker.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));
 f.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:f.querySelector('[name=draft]')}));await tick();const layer=saved[0].publication.media[0].text_layers[0];assert.equal(layer.text,'Café na piscina');assert.equal(layer.x,57);assert.equal(layer.color,'#ffcc00');assert.equal(layer.background,'#17130f');assert.equal(layer.bold,true);assert.equal(layer.italic,true);assert.equal(layer.strike,true);assert.equal(doc.querySelector('.vg-text-edit-stage .vg-text-sticker').textContent,'Café na piscina');
 doc.querySelector('.vg-text-edit-stage .vg-text-sticker').click();doc.querySelector('[data-delete]').click();f.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:f.querySelector('[name=draft]')}));await tick();assert.equal(saved[1].publication.media[0].text_layers.length,0);d.window.close();
});

test('empty scene opens the file picker; progress disappears after success and new uploads cancel the old notice',async()=>{
 const {d,w}=await editor({guest:true}),doc=w.document,input=doc.querySelector('#vg-upload');let chosen=0,complete;input.click=()=>chosen++;doc.querySelector('#vg-composer-empty').click();assert.equal(chosen,1);assert.equal(doc.querySelector('.vg-upload-button'),null);
 const timeouts=new Map(),nativeSet=w.setTimeout.bind(w),nativeClear=w.clearTimeout.bind(w);let id=9000;w.setTimeout=(cb,ms,...args)=>ms===2500?(timeouts.set(++id,cb),id):nativeSet(cb,ms,...args);w.clearTimeout=n=>{timeouts.delete(n);nativeClear(n)};
 w.VillegramUpload={upload:async(_sb,_file,_path,progress)=>{progress?.(45);await new Promise(r=>complete=r)}};
 Object.defineProperty(input,'files',{configurable:true,value:[new w.File(['photo'],'one.jpg',{type:'image/jpeg'})]});input.dispatchEvent(new w.Event('change'));await tick();assert.equal(doc.querySelector('#vg-upload-feedback').hidden,false);assert.equal(doc.querySelector('#vg-upload-progress').hidden,false);assert.equal(doc.querySelector('#vg-upload-progress').value,45);assert.equal(doc.querySelector('#vg-upload-spinner').hidden,false);assert.equal(doc.querySelector('#vg-upload-feedback').parentNode,doc.querySelector('#vg-composer-screen'));assert.equal(doc.querySelector('#vg-composer-screen').classList.contains('is-uploading'),true);assert.equal(doc.querySelector('#vg-composer-empty').disabled,true);
 complete();await tick();assert.equal(doc.querySelector('#vg-upload-progress').hidden,true);assert.equal(doc.querySelector('#vg-upload-spinner').hidden,true);assert.equal(doc.querySelector('#vg-composer-screen').classList.contains('is-uploading'),false);assert.equal(timeouts.size,1);assert.match(doc.querySelector('#vg-upload-status').textContent,/Mídia enviada/);assert.equal(doc.querySelector('#vg-composer-empty').hidden,true);doc.querySelector('#vg-media-add').click();assert.equal(chosen,2);
 input.dispatchEvent(new w.Event('change'));await tick();assert.equal(timeouts.size,0);assert.equal(doc.querySelector('#vg-upload-progress').hidden,false);complete();await tick();assert.equal(doc.querySelectorAll('[data-select]').length,2);for(const cb of timeouts.values())cb();assert.equal(doc.querySelector('#vg-upload-feedback').hidden,true);assert.equal(doc.querySelector('#vg-upload-status').textContent,'');d.window.close();
});

test('failed upload stays actionable and retry hides progress only after success',async()=>{
 const {d,w}=await editor(),doc=w.document;let fail=true;w.VillegramUpload={upload:async()=>{if(fail)throw Error('Falha de conexão')}};const input=doc.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['photo'],'one.jpg',{type:'image/jpeg'})]});input.dispatchEvent(new w.Event('change'));await tick();assert.equal(doc.querySelector('#vg-upload-feedback').hidden,false);assert.equal(doc.querySelector('#vg-upload-feedback').dataset.state,'error');assert.equal(doc.querySelector('#vg-upload-spinner').hidden,true);assert.equal(doc.querySelector('#vg-upload-progress').hidden,true);assert.equal(doc.querySelector('#vg-upload-retry').hidden,false);assert.match(doc.querySelector('#vg-upload-status').textContent,/Falha/);
 fail=false;doc.querySelector('#vg-upload-retry').click();await tick();assert.equal(doc.querySelector('#vg-upload-feedback').dataset.state,'success');assert.equal(doc.querySelector('#vg-upload-progress').hidden,true);assert.equal(doc.querySelector('#vg-upload-retry').hidden,true);assert.equal(doc.querySelectorAll('[data-select]').length,1);doc.querySelector('#vg-new').click();assert.equal(doc.querySelector('#vg-upload-feedback').hidden,true);d.window.close();
});

test('holding enables photo pan while explicit media options preserve trash and remaining cover',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();doc.querySelector('[data-photo]').click();doc.querySelector('[data-cover="1"]').click();doc.querySelector('[data-select="0"]').click();const layer=doc.querySelector('#vg-scene-gesture');pointer(w,layer,'pointerdown',1,80,130);await new Promise(r=>setTimeout(r,580));assert.equal(doc.querySelector('#vg-media-menu').hidden,true);assert.equal(doc.querySelector('.vg-wheel').hidden,false);assert.equal(doc.querySelectorAll('[data-select]').length,2);pointer(w,layer,'pointerup',1,80,130);doc.querySelector('#vg-media-options').click();assert.equal(doc.querySelector('#vg-media-menu').hidden,false);doc.querySelector('#vg-media-delete').click();assert.equal(doc.querySelectorAll('[data-select]').length,1);assert.match(doc.querySelector('[data-select="0"]').textContent,/Capa/);
 f.elements.title.value='Cena';f.elements.caption.value='Preservada';f.elements.property_id.value='1';doc.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.cover_index,0);assert.equal(saved[0].publication.media.length,1);
 doc.querySelector('[data-step="0"]').click();layer.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Delete',bubbles:true}));assert.equal(doc.activeElement,doc.querySelector('#vg-media-delete'));doc.querySelector('#vg-media-delete').click();assert.equal(doc.querySelector('#vg-composer-empty').hidden,false);assert.equal(doc.activeElement,doc.querySelector('#vg-composer-empty'));assert.equal(doc.querySelector('#vg-scene-next-slot').hidden,true);assert.equal(doc.querySelector('.vg-composer-steps').hidden,true);assert.equal(doc.querySelector('.vg-text-tools').hidden,true);d.window.close();
});

test('pan, pinch, text tools and cancelled touches never open the media trash',async()=>{
 const {d,w}=await editor(),doc=w.document;doc.querySelector('[data-photo]').click();const layer=doc.querySelector('#vg-scene-gesture'),menu=doc.querySelector('#vg-media-menu');pointer(w,layer,'pointerdown',1,80,130);pointer(w,layer,'pointermove',1,100,150);await new Promise(r=>setTimeout(r,580));assert.equal(menu.hidden,true);pointer(w,layer,'pointerup',1,100,150);
 pointer(w,layer,'pointerdown',1,80,130);pointer(w,layer,'pointerdown',2,110,150);await new Promise(r=>setTimeout(r,580));assert.equal(menu.hidden,true);pointer(w,layer,'pointercancel',1,80,130);pointer(w,layer,'pointercancel',2,110,150);
 pointer(w,layer,'pointerdown',3,80,130);pointer(w,layer,'pointercancel',3,80,130);await new Promise(r=>setTimeout(r,580));assert.equal(menu.hidden,true);const add=doc.querySelector('.vg-text-tools button');pointer(w,add,'pointerdown',4,80,130);await new Promise(r=>setTimeout(r,580));assert.equal(menu.hidden,true);d.window.close();
});

test('video keeps native controls; hold exposes removal and switching scenes dismisses trash',async()=>{
 const {d,w}=await editor(),doc=w.document;w.VillegramUpload={inspect:async()=>({url:'blob:video',video:{duration:9}}),poster:async()=>new Blob(['poster']),upload:async()=>{}};const input=doc.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['video'],'scene.mp4',{type:'video/mp4'})]});input.dispatchEvent(new w.Event('change'));await tick();const video=doc.querySelector('#vg-composer-visual video');video.getBoundingClientRect=()=>({bottom:600});assert.equal(video.controls,true);assert.equal(doc.querySelector('#vg-media-add').hidden,true);
 pointer(w,video,'pointerdown',1,80,580);await new Promise(r=>setTimeout(r,580));assert.equal(doc.querySelector('#vg-media-menu').hidden,true);pointer(w,video,'pointerup',1,80,580);
 pointer(w,video,'pointerdown',2,80,130);await new Promise(r=>setTimeout(r,580));pointer(w,video,'pointerup',2,80,130);assert.equal(doc.querySelector('#vg-media-menu').hidden,false);assert.match(doc.querySelector('#vg-media-delete').textContent,/vídeo/);doc.querySelector('#vg-step-next').click();assert.equal(doc.querySelector('#vg-media-menu').hidden,true);doc.querySelector('#vg-step-back').click();doc.querySelector('#vg-media-options').click();doc.querySelector('#vg-media-delete').click();assert.equal(doc.querySelector('#vg-composer-empty').hidden,false);assert.equal(doc.querySelector('#vg-composer-visual video'),null);d.window.close();
});

test('canvas navigation preserves thumbnails, text and cover when advancing and returning',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form'),screen=doc.querySelector('#vg-composer-screen'),next=doc.querySelector('#vg-step-next'),footer=doc.querySelector('.vg-composer-footer');
 assert.equal(screen.contains(next),true);assert.equal(footer.hidden,true);assert.equal(next.parentNode.hidden,true);assert.equal(doc.querySelector('.vg-composer-steps').hidden,true);assert.equal(doc.querySelector('.vg-text-tools').hidden,true);assert.equal(doc.querySelector('#vg-media-controls').hidden,true);assert.equal(doc.querySelector('#vg-scene-library').textContent.trim(),'');assert.equal(doc.querySelector('#vg-scene-library').getAttribute('aria-label'),'Abrir biblioteca de fotos');next.click();assert.equal(screen.contains(doc.querySelector('#vg-editor-message')),true);assert.match(doc.querySelector('#vg-editor-message').textContent,/Escolha/);
 const dialog=doc.querySelector('#vg-source-library');dialog.showModal=()=>dialog.setAttribute('open','');dialog.close=()=>dialog.removeAttribute('open');doc.querySelector('#vg-scene-library').click();assert.equal(dialog.open,true);doc.querySelector('[data-photo]').click();doc.querySelector('[data-photo]').click();doc.querySelector('#vg-source-close').click();assert.equal(dialog.open,false);
 assert.equal(next.parentNode.hidden,false);assert.equal(doc.querySelector('.vg-composer-steps').hidden,false);assert.equal(screen.contains(doc.querySelector('[data-select]')),true);doc.querySelector('#vg-media-options').click();assert.equal(doc.querySelector('#vg-media-menu').contains(doc.querySelector('[data-cover]')),true);doc.querySelector('[data-cover="1"]').click();f.elements.property_id.value='1';f.elements.title.value='Na cena';f.elements.caption.value='Composição preservada';next.click();assert.equal(footer.contains(next),true);assert.equal(footer.hidden,false);assert.equal(doc.querySelector('#vg-media-list').hidden,true);assert.equal(doc.querySelector('#vg-editor-message').parentNode,f);
 doc.querySelector('#vg-step-back').click();assert.equal(screen.contains(next),true);assert.equal(footer.hidden,true);assert.equal(doc.querySelector('#vg-preview-note').hidden,true);assert.equal(doc.querySelector('#vg-media-list').hidden,false);assert.match(doc.querySelector('[data-select="1"]').textContent,/Capa/);
 next.click();next.click();f.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.cover_index,1);assert.equal(saved[0].publication.media.length,2);assert.equal(saved[0].publication.caption,'Composição preservada');d.window.close();
});


test('new photos fill the scene; the standalone framing icon toggles and preserves saved framing',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form'),fit=doc.querySelector('#vg-scene-fit');
 assert.equal(fit.hidden,true);assert.equal(doc.querySelector('#vg-media-menu').contains(fit),false);
 doc.querySelector('[data-photo]').click();assert.equal(fit.hidden,false);assert.equal(doc.querySelector('#vg-composer-visual img').style.objectFit,'cover');assert.equal(fit.getAttribute('aria-label'),'Mostrar foto inteira');
 fit.click();assert.equal(doc.querySelector('#vg-composer-visual img').style.objectFit,'contain');assert.equal(fit.getAttribute('aria-label'),'Preencher a cena');assert.ok(fit.querySelector('svg'));assert.equal(doc.querySelector('#vg-media-menu').hidden,true);
 f.elements.property_id.value='1';f.elements.title.value='Enquadramento';f.elements.caption.value='Foto inteira';doc.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.media[0].fit,'contain');doc.querySelector('[data-edit]').click();assert.equal(doc.querySelector('#vg-composer-visual img').style.objectFit,'contain');
 doc.querySelector('[data-step="0"]').click();doc.querySelector('#vg-step-next').click();assert.equal(fit.hidden,true);doc.querySelector('#vg-step-back').click();assert.equal(fit.hidden,false);
 w.VillegramUpload={upload:async()=>{}};const input=doc.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['photo'],'scene.jpg',{type:'image/jpeg'})]});input.dispatchEvent(new w.Event('change'));await tick();assert.equal(doc.querySelector('#vg-composer-visual img').style.objectFit,'cover');
 doc.querySelector('#vg-media-options').click();doc.querySelector('#vg-media-delete').click();assert.equal(doc.querySelector('#vg-composer-visual img').style.objectFit,'contain');doc.querySelector('#vg-media-options').click();doc.querySelector('#vg-media-delete').click();assert.equal(fit.hidden,true);d.window.close();
});


test('fill removes dragged gaps and stale zoom in one click, persists it and can show the whole photo',async()=>{
 const post={id:uid,source:'manual',type:'property',title:'Cena deslocada',caption:'Foto do chalé',status:'draft',property_id:1,cta:'property',cover_index:0,media:[{kind:'photo',url:'assets/photo.webp',fit:'cover',zoom:1.4,position_x:25,position:70,offset_x:8,offset_y:12}]};
 const {d,w,saved}=await editor({initialRows:[post]}),doc=w.document;doc.querySelector('[data-edit]').click();doc.querySelector('[data-step="0"]').click();const fit=doc.querySelector('#vg-scene-fit'),img=doc.querySelector('#vg-composer-visual img');assert.match(img.style.transform,/translate/);assert.equal(fit.getAttribute('aria-label'),'Preencher a cena');fit.click();assert.equal(img.style.objectFit,'cover');assert.equal(img.style.transform,'scale(1)');assert.equal(img.style.objectPosition,'50% 50%');assert.equal(img.style.transformOrigin,'50% 50%');assert.equal(fit.getAttribute('aria-label'),'Mostrar foto inteira');
 doc.querySelector('[name=draft]').click();await tick();const m=saved[0].publication.media[0];assert.equal(m.fit,'cover');assert.equal(m.zoom,1);assert.equal(m.offset_x,0);assert.equal(m.offset_y,0);assert.equal(m.position_x,50);assert.equal(m.position,50);
 doc.querySelector('[data-edit]').click();doc.querySelector('[data-step="0"]').click();fit.click();assert.equal(doc.querySelector('#vg-composer-visual img').style.objectFit,'contain');doc.querySelector('#vg-scene-gesture').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));fit.click();assert.equal(doc.querySelector('#vg-composer-visual img').style.objectFit,'cover');assert.equal(doc.querySelector('#vg-composer-visual img').style.transform,'scale(1)');d.window.close();
});


test('approver alert opens the pending queue without discarding a composition; approving clears the queue',async()=>{
 const post={id:uid,source:'guest_submission',status:'pending_review',title:'Momento do hóspede',caption:'Café',author_name:'Hóspede',media:[{kind:'photo',url:'assets/photo.webp'}],cover_index:0};const {d,w}=await editor({initialRows:[post]}),doc=w.document;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};
 doc.querySelector('[data-photo]').click();doc.querySelector('#vg-post-form').elements.title.value='Composição em andamento';const event=new w.CustomEvent('villegram-review-open',{cancelable:true});assert.equal(doc.dispatchEvent(event),false);await tick();assert.equal(doc.querySelector('#vg-filter').value,'pending_review');assert.equal(doc.querySelectorAll('[data-review]').length,1);assert.equal(doc.querySelector('#vg-post-form').elements.title.value,'Composição em andamento');let changed=0;doc.addEventListener('villegram-review-changed',()=>changed++);doc.querySelector('[data-review]').click();doc.querySelector('[data-approve]').click();await tick();assert.equal(changed,1);assert.equal(doc.querySelectorAll('[data-review]').length,0);assert.match(doc.querySelector('#vg-library-message').textContent,/Nenhum momento/);d.window.close();
});

test('horizontal swipe rolls filters without moving photo; held drag pans and cancellation does not select filter',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();const scene=doc.querySelector('#vg-composer-visual img'),layer=doc.querySelector('#vg-scene-gesture');Object.defineProperties(scene,{naturalWidth:{value:1000},naturalHeight:{value:1600}});doc.querySelector('#vg-composer-visual').getBoundingClientRect=()=>({left:0,top:0,width:200,height:320});
 pointer(w,layer,'pointerdown',1,150,160);pointer(w,layer,'pointermove',1,60,160);pointer(w,layer,'pointerup',1,60,160);assert.match(scene.style.filter,/sepia/);assert.equal(scene.style.transform,'scale(1)');assert.equal(doc.querySelector('#vg-filter-toast').textContent,'Aconchego');
 pointer(w,layer,'pointerdown',2,60,160);pointer(w,layer,'pointermove',2,150,160);pointer(w,layer,'pointerup',2,150,160);assert.equal(scene.style.filter,'none');
 pointer(w,layer,'pointerdown',3,150,160);pointer(w,layer,'pointermove',3,60,160);pointer(w,layer,'pointercancel',3,60,160);assert.equal(scene.style.filter,'none');
 pointer(w,layer,'pointerdown',4,100,160);await new Promise(r=>setTimeout(r,520));pointer(w,layer,'pointermove',4,140,128);pointer(w,layer,'pointerup',4,140,128);assert.equal(scene.style.transform,'translate(20%, -10%) scale(1)');assert.equal(scene.style.filter,'none');
 f.elements.title.value='Gestos';f.elements.caption.value='Foto';f.elements.property_id.value='1';doc.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.media[0].offset_x,20);d.window.close();
});

test('new moment centers upload canvas and vertical photo movement stays scrollable',async()=>{const {d,w}=await editor(),doc=w.document;let target,options;w.HTMLElement.prototype.scrollIntoView=function(o){target=this;options=o};doc.querySelector('#vg-new').click();await new Promise(r=>setTimeout(r,30));assert.equal(target.id,'vg-composer-screen');assert.equal(options.block,'center');doc.querySelector('[data-photo]').click();const layer=doc.querySelector('#vg-scene-gesture'),scene=doc.querySelector('#vg-composer-visual img');Object.defineProperties(scene,{naturalWidth:{value:1000},naturalHeight:{value:1600}});doc.querySelector('#vg-composer-visual').getBoundingClientRect=()=>({left:0,top:0,width:200,height:320});const fire=(type,x,y)=>{const e=new w.MouseEvent(type,{bubbles:true,cancelable:true,clientX:x,clientY:y,button:0});Object.defineProperty(e,'pointerId',{value:1});layer.dispatchEvent(e);return e};assert.equal(fire('pointerdown',100,100).defaultPrevented,false);assert.equal(fire('pointermove',100,170).defaultPrevented,false);fire('pointercancel',100,170);await new Promise(r=>setTimeout(r,520));assert.equal(doc.querySelector('.vg-wheel').hidden,true);d.window.close()});

test('six photos can be scrolled to the last and reordered with cover identity preserved',async()=>{const {d,w,saved}=await editor(),doc=w.document;for(let i=0;i<6;i++)doc.querySelector('[data-photo]').click();let strip=doc.querySelector('.vg-media-strip');assert.equal(strip.querySelectorAll('[data-select]').length,6);let requested;strip.scrollBy=o=>{requested=o.left;strip.scrollLeft+=o.left};doc.querySelector('[data-strip-next]').click();assert.equal(requested,150);const last=doc.querySelector('[data-select="5"]');pointer(w,last,'pointerdown',1,160,30);pointer(w,last,'pointermove',1,60,30);assert.equal(strip.scrollLeft,250);pointer(w,last,'pointerup',1,60,30);await new Promise(r=>setTimeout(r,320));last.click();doc.querySelector('#vg-scene-extra [data-up]').click();const f=doc.querySelector('#vg-post-form');f.elements.title.value='Seis fotos';f.elements.caption.value='Ordem';f.elements.property_id.value='1';doc.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.media.length,6);assert.equal(saved[0].publication.cover_index,0);d.window.close()});
