import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';
import {publicationInput,automationInput,eligiblePublication,generatePublications,signalInput,summarizePublications,recordVillegramBooking} from '../supabase/functions/_shared/villegram-publications.ts';
const id='4069a585-7cc6-48ad-9263-567358a45c0c',other='4fe5af08-361d-441c-a8e1-6fbb871df3e9',url='https://dev.supabase.co',media=[{kind:'photo',url:'assets/photo.webp',fit:'contain'}];
const post={id,type:'property',property_id:1,title:'Ville',caption:'Fotos reais',media,cta:'property',status:'published',published_at:'2026-10-01T00:00:00Z'};
test('independent posts validate status, links, bounded media and safe destinations',()=>{const p=publicationInput(post,url);assert.equal(p.property_id,1);assert.equal(p.media[0].fit,'contain');for(const update of [{media:[{kind:'photo',url:'javascript:alert(1)'}]},{cta:'offer'},{property_id:null},{title:''},{cover_index:2},{status:'unrestricted'},{expires_at:'bad'}])assert.throws(()=>publicationInput({...post,...update},url));});
test('video requires private owner path, a separate poster, known duration and format',()=>{const video={kind:'video',path:id+'/'+other+'.mp4',poster_path:id+'/'+id+'.webp',duration:25,bytes:1024,fit:'contain'};assert.equal(publicationInput({...post,media:[video]},url).media[0].duration,25);assert.throws(()=>publicationInput({...post,media:[{...video,duration:121}]},url));assert.throws(()=>publicationInput({...post,media:[video,...media]},url));assert.throws(()=>publicationInput({...post,media:[{...video,poster_path:null}]},url));});
test('eligibility removes archived, future, expired and unavailable catalog links',()=>{const props=[{id:1,active:true}],now=Date.parse('2026-10-06');assert.ok(eligiblePublication(post,props,[],[],now));for(const update of [{status:'archived'},{published_at:'2026-10-07'},{expires_at:'2026-10-02'},{property_id:2},{offer_id:other},{experience_id:other}])assert.equal(eligiblePublication({...post,...update},props,[],[],now),false);});
test('generation uses registered photos, stable identities, real descriptions and no variable prices',()=>{const s=automationInput({auto_publish:false}),properties=[{id:1,name:'Ville',summary:'Piscina',cover_image:'assets/photo.webp',gallery:['assets/photo.webp']}],products=[{id:other,name:'Café',description:'Café cadastrado',status:'active',price_cents:99999,experience_media:[{media_url:'assets/cafe.webp',display_order:0}]}],offers=[{id,name:'Dias livres',description:'Descrição existente',status:'active',property_ids:[1]}];const a=generatePublications(properties,products,offers,s),b=generatePublications(properties,products,offers,s);assert.deepEqual(a.map(p=>p.source_key),b.map(p=>p.source_key));assert.equal(new Set(a.map(p=>p.source_key)).size,a.length);assert.deepEqual(a.map(p=>p.type),['property','experience','offer','trust']);assert.ok(a.every(p=>p.status==='draft'));assert.ok(!JSON.stringify(a).includes('99999'));assert.equal(a[0].caption,'Piscina');});
test('automation settings bound publication frequency and disable categories explicitly',()=>{const s=automationInput({templates:{offer:{enabled:false}},auto_publish:true});const p=generatePublications([{id:1,name:'Ville',summary:'Real',cover_image:'assets/photo.webp'}],[],[{id,status:'active',property_ids:[1]}],s);assert.ok(!p.some(p=>p.type==='offer'));assert.ok(p.every(p=>p.status==='published'));assert.throws(()=>automationInput({frequency_hours:1}));assert.throws(()=>automationInput({max_offers:100}));});
test('signals reject forged payments and invalid identity/time',()=>{const e={event_id:id,publication_id:id,visitor_id:other,session_id:id,view_id:other,kind:'view'};assert.equal(signalInput(e).publication_id,id);for(const update of [{kind:'payment_confirmed'},{active_ms:-1},{active_ms:0.5},{sequence:999999},{visitor_id:'IP address'}])assert.throws(()=>signalInput({...e,...update}));});
test('funnel deduplicates view IDs and derives paid reservations from finance, not browser',()=>{const views=[{publication_id:id,visitor_id:other,session_id:id,view_id:id,kind:'view',active_ms:1000},{publication_id:id,visitor_id:other,session_id:id,view_id:id,kind:'view',active_ms:1000},{publication_id:id,visitor_id:other,session_id:id,view_id:id,kind:'progress',active_ms:5000}];const attrs=[{publication_id:id,reservation_id:'r'}];let r=summarizePublications([post],views,attrs,[{id:'r',status:'confirmed',source:'direct',payments:[{provider:'pagbank_sandbox',status:'paid'}]}])[0];assert.equal(r.views,1);assert.equal(r.visitors,1);assert.equal(r.active_ms,5000);assert.equal(r.reservations_started,1);assert.equal(r.reservations_paid,1);for(const reservation of [{id:'r',status:'hold',source:'direct',payments:[{provider:'pagbank_sandbox',status:'paid'}]},{id:'r',status:'confirmed',source:'direct',payments:[{provider:'mock',status:'paid'}]}])assert.equal(summarizePublications([post],views,attrs,[reservation])[0].reservations_paid,0);});
test('server attribution requires matching recent view and is optional to checkout',async()=>{const calls=[];let matching=true;const query={select(){return this},eq(){return this},gte(){return this},maybeSingle:async()=>({data:matching?{id}:null,error:null})};const db={from(table){return table==='villegram_signals'?query:{upsert:async(row)=>{calls.push(row);return {error:null}}}}};const a={publication_id:id,visitor_id:other,session_id:id,view_id:other};await recordVillegramBooking(db,'r',a,'u');assert.equal(calls.length,1);matching=false;await recordVillegramBooking(db,'r2',a,'u');assert.equal(calls.length,1);await recordVillegramBooking({from(){throw Error('unavailable')}},'r3',a,'u');});
async function dom(html='<div></div>'){const d=new JSDOM(html,{url:'https://dev.local/index.html',runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;w.CHALEZINHO_CONFIG={supabaseUrl:url,bookingEngine:url+'/engine'};w.matchMedia=()=>({matches:false,addEventListener(){}});w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};w.VilleOffers={label:i=>i.name};w.fetch=async()=>({ok:true,json:async()=>({ok:true,likes:0,liked:false,comments:[]})});w.AbortSignal.timeout=()=>undefined;return d;}
test('recommendation uses explicit interest/declarations, diversifies and never uses dwell time',async()=>{const d=await dom(),w=d.window;w.VillegramSignals={declared:()=>({purpose:'romance'}),interest:()=>({[id]:{progress:900000},[other]:{like:1}})};w.eval(await readFile(new URL('../villegram-content.js',import.meta.url),'utf8'));const a={publication:{id,type:'property'},property_id:1},b={publication:{id:other,type:'experience'},property_id:2,purposes:['romance']};assert.equal(w.VillegramContent.rank([a,b],a)[0],b);d.window.close();});
test('mobile publication preserves a single main action, reading pauses and explicit navigation',async()=>{const d=await dom(),w=d.window;let active=false;w.VillegramSignals={begin(){},active(v){active=v},mark(){},end(){},flush(){}};w.VillegramContent={request:async()=>({ok:true,likes:0,liked:false,comments:[]}),rank:a=>a,leave(){}};w.eval(await readFile(new URL('../villegram.js',import.meta.url),'utf8'));const c={publication:post,publication_id:id,property_id:1,property_name:'Ville',property_url:'chale-premium.html',experiences:[]};w.Villegram.configurePublications([c,{...c,publication_id:other,publication:{...post,id:other,title:'Other'}}],[],[]);w.Villegram.openHome(c);assert.equal(w.document.querySelectorAll('.vg-primary').length,1);assert.equal(w.document.querySelector('.vg-primary').textContent,'Conhecer este chalé');assert.equal(w.document.querySelector('.vg-bottom-nav').children.length,4);assert.equal(active,true);w.document.querySelector('[data-action=caption]').click();assert.equal(active,false);w.document.querySelector('[data-action=next]').click();assert.equal(w.document.querySelector('h2').textContent,'Ville');w.document.querySelector('[data-sheet-close]').click();assert.equal(active,true);w.Villegram.close();assert.ok(w.sessionStorage.getItem('villegram-position'));d.window.close();});
test('signals persist a view through reload, exclude pause/hidden time, retry idempotent events',async()=>{const d=await dom(),w=d.window;const callbacks=[];let time=0;Object.defineProperty(w.performance,'now',{value:()=>time});w.setInterval=fn=>{callbacks.push(fn);return callbacks.length};let batches=[];w.fetch=async(_u,opts)=>{batches.push(JSON.parse(opts.body));return{ok:true}};const source=await readFile(new URL('../villegram-signals.js',import.meta.url),'utf8');w.eval(source);w.VillegramSignals.begin(post);w.VillegramSignals.active(true);time=1000;callbacks[0]();await new Promise(r=>setTimeout(r,0));w.VillegramSignals.active(false);time=11000;assert.equal(w.VillegramSignals.snapshot().active_ms,1000);w.VillegramSignals.mark('property_open');const first=w.VillegramSignals.snapshot().view_id;w.eval(source);w.VillegramSignals.begin(post,true);assert.equal(w.VillegramSignals.snapshot().view_id,first);assert.ok(w.VillegramSignals.attribution());d.window.close();});
test('privacy opt-out blocks viewer telemetry',async()=>{const d=await dom(),w=d.window;Object.defineProperty(w.navigator,'globalPrivacyControl',{value:true});let calls=0;w.fetch=async()=>{calls++;return {ok:true}};w.eval(await readFile(new URL('../villegram-signals.js',import.meta.url),'utf8'));w.VillegramSignals.begin(post);w.VillegramSignals.mark('reservation_start');await w.VillegramSignals.flush();assert.equal(calls,0);assert.equal(w.VillegramSignals.attribution(),null);d.window.close();});
test('sharing an independent publication pauses the scene and preserves its unique link',async()=>{const d=await dom('<main><button id="background">Home</button></main>'),w=d.window;let active=false;w.VillegramSignals={begin(){},active(v){active=v},mark(){},end(){},flush(){}};w.VillegramContent={request:async()=>({likes:0,comments:[]}),rank:a=>a,leave(){}};w.eval(await readFile(new URL('../villegram.js',import.meta.url),'utf8'));const c={publication:post,publication_id:id,property_url:'chale-premium.html',property_name:'Ville',offer_name:'Ville'};w.Villegram.configurePublications([c],[],[]);w.Villegram.openHome(c);assert.equal(w.document.querySelector('main').inert,true);w.document.querySelector('[data-action=share]').click();assert.equal(w.document.querySelector('.vg-sheet').hidden,false);assert.equal(active,false);assert.ok(w.document.querySelector('.vg-sheet input').value.endsWith('?publication='+id));w.Villegram.close();assert.notEqual(w.document.querySelector('main').inert,true);d.window.close();});
test('old showcase cards still open the exact offer dates after publications are loaded',async()=>{const d=await dom(),w=d.window;w.VillegramSignals={begin(){},active(){},end(){},flush(){}};w.VillegramContent={leave(){}};w.eval(await readFile(new URL('../villegram.js',import.meta.url),'utf8'));w.Villegram.configurePublications([{publication:post,publication_id:id}],[],[]);const c={offer_id:other,property_id:1,property_code:'CH1',property_name:'Ville',offer_name:'Dias prontos',check_in:'2026-11-16',check_out:'2026-11-19',guests:2,nights:3,total_cents:100000,experiences:[],rate_code:'refundable'};w.Villegram.open(c);assert.match(w.document.querySelector('.vg-primary').href,/check_in=2026-11-16/);assert.match(w.document.querySelector('.vg-primary').href,/stay_offer=/);w.Villegram.close();d.window.close();});
test('empty feed exposes the existing site and dates instead of a blank screen',async()=>{const d=await dom('<header><nav></nav></header><main><div class="hero"></div></main>'),w=d.window;w.matchMedia=()=>({matches:true,addEventListener(){}});w.fetch=async()=>({ok:true,json:async()=>({ok:true,publications:[],properties:[],products:[],offers:[],max_offers:3})});w.Villegram={configurePublications(){},isHome:()=>false,openHome(){throw Error('empty feed must not open')}};w.eval(await readFile(new URL('../villegram-content.js',import.meta.url),'utf8'));await new Promise(r=>setTimeout(r,10));assert.match(w.document.querySelector('#villegram-empty-status').textContent,/Ainda não há publicações/);assert.equal(w.document.querySelector('#villegram-home-status'),null);assert.ok(w.document.querySelector('.villegram-mobile-nav'));d.window.close();});
test('video metadata cannot omit duration/size or disguise video as a photo',()=>{const video={kind:'video',path:id+'/'+other+'.mp4',poster_path:id+'/'+id+'.webp',duration:4,bytes:100};for(const update of [{duration:undefined},{bytes:undefined},{bytes:0},{bytes:0.5},{poster_path:id+'/'+id+'.mp4'},{kind:'photo'}])assert.throws(()=>publicationInput({...post,media:[{...video,...update}]},url));});
test('return restores a lazy photo and scrolling beyond the first reel preserves active tracking',async()=>{const d=await dom(),w=d.window;let ends=0;w.VillegramSignals={begin(){},active(){},end(){ends++},flush(){}};w.VillegramContent={leave(){},request:async()=>({likes:0}),saved:()=>({photo:2,scroll:40})};w.eval(await readFile(new URL('../villegram.js',import.meta.url),'utf8'));const p={...post,media:['one','two','three'].map(n=>({kind:'photo',url:'assets/'+n+'.webp'}))},c={publication:p,publication_id:id,property_url:'chale-premium.html'};w.Villegram.configurePublications([c],[],[]);w.Villegram.openHome(c,{restored:true});assert.ok(w.document.querySelector('.vg-scene.is-visible img').src.endsWith('three.webp'));w.document.querySelector('#villegram').dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowUp',bubbles:true}));assert.equal(ends,0);w.Villegram.close();d.window.close();});
test('a shared offer waits for current offer data and opens the same publication on desktop',async()=>{const d=await dom('<header><nav></nav></header><main><div class="hero"></div></main>'),w=d.window;w.history.replaceState(null,'','index.html?publication='+id);const offer={...post,type:'offer',offer_id:other,cta:'offer'};w.fetch=async()=>({ok:true,json:async()=>({ok:true,publications:[offer],properties:[{id:1,code:'CH1',name:'Ville'}],products:[],offers:[{id:other}],max_offers:3})});let opened=null;w.Villegram={configurePublications(){},isHome:()=>false,openHome(c){opened=c}};w.eval(await readFile(new URL('../villegram-content.js',import.meta.url),'utf8'));await new Promise(r=>setTimeout(r,10));assert.equal(opened,null);w.VillegramContent.setOffers([{offer_id:other,property_id:1,check_in:'2026-11-16',check_out:'2026-11-19'}]);assert.equal(opened.publication_id,id);assert.equal(opened.check_in,'2026-11-16');d.window.close();});

test('delayed live offers update the current reel counter without resetting playback or reading',async()=>{
 const d=await dom('<header><nav></nav></header><main><div class="hero"></div></main>'),w=d.window;let begins=0,active=false;
 w.matchMedia=q=>({matches:q.includes('max-width'),addEventListener(){}});w.VillegramSignals={begin(){begins++},active(v){active=v},end(){},flush(){},declared:()=>({}),interest:()=>({}),mark(){}};
 const introductions=Array.from({length:6},(_,i)=>({...post,id:'intro-'+i,title:'Introdução '+i})),specials=Array.from({length:3},(_,i)=>({...post,id:'offer-'+i,type:'offer',offer_id:'live-'+i,cta:'offer'}));
 const quotes=specials.map(p=>({offer_id:p.offer_id,property_id:1,property_code:'CH1',check_in:'2026-11-16',check_out:'2026-11-19',guests:2,nights:3,rate_code:'refundable',total_cents:100000}));
 w.fetch=async(_url,options)=>({ok:true,json:async()=>JSON.parse(options.body).operation==='feed'?{ok:true,publications:[...introductions,...specials],properties:[{id:1,code:'CH1',name:'Ville'}],products:[],offers:[],max_offers:3}:{ok:true,likes:0,comments:[]}});
 w.eval(await readFile(new URL('../villegram.js',import.meta.url),'utf8'));w.eval(await readFile(new URL('../villegram-content.js',import.meta.url),'utf8'));await new Promise(r=>setTimeout(r,20));
 const label=()=>w.document.querySelector('.vg-progress>span').textContent;assert.equal(label(),'Reel 1');const reel=w.document.querySelector('.vg-reel'),picture=w.document.querySelector('.vg-scene.is-visible'),purchase=w.document.querySelector('.vg-purchase');purchase.scrollTop=25;
 w.document.querySelector('[data-action=caption]').click();const panel=w.document.querySelector('.vg-sheet');assert.equal(active,false);
 w.VillegramContent.setOffers(quotes);assert.equal(label(),'1 de 9');assert.equal(w.document.querySelector('.vg-reel'),reel);assert.equal(w.document.querySelector('.vg-scene.is-visible'),picture);assert.equal(w.document.querySelector('.vg-sheet'),panel);assert.equal(panel.hidden,false);assert.equal(purchase.scrollTop,25);assert.equal(active,false);assert.equal(begins,1);
 w.document.querySelector('[data-sheet-close]').click();w.document.querySelector('[data-action=next]').click();assert.equal(label(),'2 de 9');w.Villegram.close();d.window.close();
});
test('an updated feed immediately enables or disables the next control without rerendering the current post',async()=>{
 const d=await dom(),w=d.window;w.VillegramContent={request:async()=>({likes:0,comments:[]}),leave(){},rank:cards=>cards};w.eval(await readFile(new URL('../villegram.js',import.meta.url),'utf8'));
 const first={publication:post,publication_id:id,property_url:'chale-premium.html'},second={...first,publication_id:other,publication:{...post,id:other,title:'Outra publicação'}};
 w.Villegram.configurePublications([first],[],[]);w.Villegram.openHome(first);const reel=w.document.querySelector('.vg-reel'),next=w.document.querySelector('[data-action=next]');assert.equal(next.disabled,true);
 w.Villegram.configurePublications([first,second],[],[]);assert.equal(next.disabled,false);assert.equal(w.document.querySelector('.vg-progress>span').textContent,'1 de 2');assert.equal(w.document.querySelector('.vg-reel'),reel);
 w.Villegram.configurePublications([first],[],[]);assert.equal(next.disabled,true);assert.equal(w.document.querySelector('.vg-progress>span').textContent,'1 de 1');w.Villegram.close();d.window.close();
});
