import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';
import {publicationInput} from '../supabase/functions/_shared/villegram-publications.ts';import {guestInput} from '../supabase/functions/_shared/villegram-community.ts';
const id='4069a585-7cc6-48ad-9263-567358a45c0c',project='https://pxfqmnhqodqyaaqeyjgr.supabase.co';
const video={kind:'video',path:id+'/'+id+'.mp4',poster_path:id+'/'+id+'.webp',duration:8,bytes:10000,speed:.5,trim_start:1,trim_end:5,original_volume:.5,transition:'slide',sound:{id:'coffee',offset:2,source_start:0,length:3,volume:.3}};
const photo={kind:'photo',url:'assets/photo.webp',clip_duration:4,mode:'feelings',transition:'fade'};
const post=media=>({type:'trust',title:'Feelings',caption:'Nossa estadia',media});
test('mixed timeline validates and persists trims, transitions and synchronized sound, while guest ownership stays enforced',()=>{const saved=publicationInput(post([photo,video]),project);assert.equal(saved.media.length,2);assert.equal(saved.media[1].trim_start,1);assert.deepEqual(saved.media[1].sound,video.sound);assert.equal(saved.media[0].mode,'feelings');const owned={...photo,path:id+'/'+id+'.webp',url:undefined};assert.equal(guestInput(post([owned,video]),project,id).status,'pending_review');assert.throws(()=>guestInput(post([owned,{...video,path:'00000000-0000-0000-0000-000000000000/'+id+'.mp4'}]),project,id),/invalid_media_owner/)});
test('invalid timeline edits and arbitrary audio URLs cannot enter saved publications',()=>{for(const updates of [{trim_start:9},{trim_start:4,trim_end:4},{transition:'<script>'},{original_volume:2},{clip_duration:3},{sound:{...video.sound,id:'https://example.com/a.mp3'}},{sound:{...video.sound,offset:9}},{sound:{...video.sound,length:99}},{sound:{...video.sound,volume:NaN}}])assert.throws(()=>publicationInput(post([{...video,...updates}]),project),/invalid_media_(timeline|sound)/);for(const clip_duration of [0,21,'6',NaN])assert.throws(()=>publicationInput(post([{...photo,clip_duration}]),project),/invalid_media_timeline/)});
test('legacy publications remain valid and have no generated sound or timeline values',()=>{const m=publicationInput(post([{kind:'photo',url:'assets/photo.webp'}]),project).media[0];assert.equal(m.sound,undefined);assert.equal(m.clip_duration,undefined);assert.equal(m.mode,undefined)});
test('mixed sequence uses displayed seconds after speed and locates every scene across a boundary',async()=>{const d=new JSDOM('',{runScripts:'outside-only'}),w=d.window;w.eval(await readFile(new URL('../villegram-timeline.js',import.meta.url),'utf8'));const T=w.VillegramTimeline,clips=T.sequence([photo,video,photo]);assert.deepEqual(Array.from(clips,c=>[c.start,c.end]),[[0,4],[4,12],[12,16]]);assert.equal(T.locate(clips,4).index,1);assert.equal(T.locate(clips,7).local,3);assert.equal(T.locate(clips,999).index,2);assert.equal(T.enabled([photo,video]),true);d.window.close()});
test('visual suggestions require a recognized subject with sufficient confidence, without filename heuristics',async()=>{const d=new JSDOM('',{runScripts:'outside-only'});d.window.eval(await readFile(new URL('../villegram-feelings.js',import.meta.url),'utf8'));const suggest=d.window.VillegramFeelings.suggestion;assert.equal(suggest([{label:'espresso',probability:.75},{label:'cup',probability:.1}]).id,'coffee');assert.equal(suggest([{label:'bathtub',probability:.6}]).id,'bubbles');assert.equal(suggest([{label:'bed',probability:.98}]),null);assert.equal(suggest([{label:'espresso',probability:.15}]),null);assert.equal(suggest([{label:'cup',probability:.4},{label:'goblet',probability:.35}]),null);d.window.close()});

test('changing speed or photo duration keeps the selected sound inside the shortened scene',async()=>{const d=new JSDOM('',{runScripts:'outside-only'});d.window.eval(await readFile(new URL('../villegram-timeline.js',import.meta.url),'utf8'));const m={kind:'photo',clip_duration:1,sound:{id:'coffee',offset:2,length:3,source_start:0,volume:.5}};d.window.VillegramTimeline.fitSound(m);assert.equal(m.sound.offset,.9);assert.equal(m.sound.length,.1);const v={...video,speed:1,sound:{...video.sound}};d.window.VillegramTimeline.fitSound(v);assert.equal(v.sound.offset,2);assert.equal(v.sound.length,2);d.window.close()});
