import {test} from 'node:test';
import assert from 'node:assert/strict';
import '../villegram-audio-dsp.js';
import {mediaTimelineInput} from '../supabase/functions/_shared/villegram-timeline.ts';
const {Cleaner}=globalThis.VillegramAudioDSP;
const base={version:2,enabled:true,gain_db:0,highpass_hz:0,hum_hz:0,compress:false,fade_ms:80,status:'ready',waveform:[.1,.2],noise_db:Array(12).fill(-42),reduction_db:Array(12).fill(6),dereverb_db:1.5,cleanup:'gentle'};
function render(fn,p=base,rate=48000){const dsp=new Cleaner(rate,p,2),input=new Float64Array(2),before=[],after=[];for(let i=0;i<rate*2;i++){input[0]=fn(i/rate,i);input[1]=-input[0];const y=dsp.sample(input);assert.ok(Number.isFinite(y[0]));assert.ok(Math.abs(y[0]+y[1])<1e-12,'linked gains preserve stereo polarity');before.push(input[0]);after.push(y[0]);}return {before,after,dsp};}
const rms=a=>Math.sqrt(a.reduce((s,v)=>s+v*v,0)/a.length);
test('unity cleanup reconstructs sample-exact without added latency at phone sample rates',()=>{for(const rate of [8000,44100,48000]){const r=render((t,i)=>Math.sin(t*720)*.3+(i===5?.5:0),{...base,reduction_db:Array(12).fill(0),dereverb_db:0},rate);assert.ok(Math.max(...r.before.map((v,i)=>Math.abs(v-r.after[i])))<1e-12);}});
test('steady low noise is reduced and stronger cleanup is reversible',()=>{const fn=t=>.01*Math.sin(2*Math.PI*180*t)+.001*Math.sin(2*Math.PI*890*t),gentle=render(fn),strong=render(fn,{...base,cleanup:'strong'});assert.ok(rms(gentle.after.slice(24000))<rms(gentle.before.slice(24000))*.7);assert.ok(rms(strong.after.slice(24000))<rms(gentle.after.slice(24000)));strong.dsp.reset();assert.deepEqual(Array.from(strong.dsp.fast),Array(12).fill(0));});
test('tail attenuation preserves the transient and cannot alter a stationary tone',()=>{const fn=t=>t<.5?0:Math.sin(2*Math.PI*1400*t)*.3*Math.exp(-(t-.5)*12),plain=render(fn,{...base,reduction_db:Array(12).fill(0),dereverb_db:0}),treated=render(fn,{...base,reduction_db:Array(12).fill(0),dereverb_db:3});assert.ok(rms(treated.after.slice(24000,26000))/rms(plain.after.slice(24000,26000))>.98);assert.ok(rms(treated.after.slice(36000,42000))/rms(plain.after.slice(36000,42000))<.95);const steady=render(t=>.1*Math.sin(2*Math.PI*1000*t),{...base,reduction_db:Array(12).fill(0),dereverb_db:3});assert.ok(rms(steady.after)/rms(steady.before)>.999);});
test('v2 parameters survive persistence; malformed DSP data and future versions fail closed',()=>{assert.deepEqual(mediaTimelineInput({kind:'video',duration:4,audio_treatment:base}).audio_treatment,base);for(const change of [{version:3},{noise_db:Array(11).fill(-40)},{noise_db:Array(12).fill(Infinity)},{reduction_db:Array(12).fill(10)},{dereverb_db:4},{cleanup:'extreme'}])assert.throws(()=>mediaTimelineInput({kind:'video',duration:4,audio_treatment:{...base,...change}}),/invalid_media_treatment/);});
