import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';import {textLayersInput,publicationInput} from '../supabase/functions/_shared/villegram-publications.ts';
const layer={text:'Um café',x:50,y:30,size:6,color:'#ffffff',background:'transparent'};
test('text layers validate bounds, reject CSS injection and retain only public presentation fields',()=>{
 assert.deepEqual(textLayersInput([{...layer,private:'secret'}]),[layer]);for(const value of [[{...layer,color:'red;display:none'}],[{...layer,text:'x'.repeat(281)}],[{...layer,x:Infinity}],[{...layer,y:0}],[{...layer,size:10}],Array(6).fill(layer),{}])assert.throws(()=>textLayersInput(value),/invalid_text_layers/);
 const p=publicationInput({type:'trust',title:'Teste',caption:'Teste',media:[{kind:'photo',url:'assets/test.webp',text_layers:[layer]}]},'https://dev.supabase.co');assert.deepEqual(p.media[0].text_layers,[layer]);
});
test('avatar crop geometry covers circle, clamps edges, preserves proportions and supports portrait/landscape',async()=>{
 const d=new JSDOM('',{runScripts:'outside-only'});d.window.eval(await readFile(new URL('../villegram-avatar.js',import.meta.url),'utf8'));const g=d.window.VillegramAvatar.geometry;for(const [w,h] of [[800,1200],[1200,800]]){const a=g(w,h,1,0,1);assert.equal(a.side,800);assert.ok(a.x-a.side/2>=0);assert.ok(a.y+a.side/2<=h);const b=g(w,h,4,.5,.5);assert.equal(b.side,200);assert.equal(b.x,w/2);assert.equal(b.y,h/2)}d.window.close();
});
test('visitor text is escaped and remains a separate layer from cropped media',async()=>{
 const d=new JSDOM('',{runScripts:'outside-only'});d.window.eval(await readFile(new URL('../villegram-text.js',import.meta.url),'utf8'));d.window.document.body.innerHTML=d.window.VillegramText.markup([{...layer,text:'<img src=x onerror=alert(1)>'}]);assert.equal(d.window.document.querySelector('img'),null);assert.equal(d.window.document.querySelector('.vg-text-sticker').textContent,'<img src=x onerror=alert(1)>');d.window.close();
});
async function inlineEditor(){const d=new JSDOM('<div id="screen"></div><button id="outside">Avançar</button>',{runScripts:'outside-only',pretendToBeVisual:true}),w=d.window,screen=w.document.querySelector('#screen'),media={text_layers:[]};w.eval(await readFile(new URL('../villegram-text.js',import.meta.url),'utf8'));let changes=0;const editor=w.VillegramText.editor({screen,getMedia:()=>media,isBusy:()=>false,onChange:()=>changes++});editor.render();screen.getBoundingClientRect=()=>({left:0,top:0,width:360,height:640});screen.querySelector('.vg-text-stage').getBoundingClientRect=()=>({left:18,top:83,width:295,height:384});const pointer=(el,type,id,x,y)=>{const e=new w.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{pointerId:id,clientX:x,clientY:y,button:0});el.dispatchEvent(e);};return {d,w,screen,media,editor,pointer,changes:()=>changes}}
test('inline text begins focused, commits on outside click and never creates a full image panel',async()=>{const q=await inlineEditor(),{w,screen,media}=q;screen.querySelector('.vg-text-tools button').click();const input=screen.querySelector('[contenteditable=true]');assert.equal(w.document.activeElement,input);assert.equal(media.text_layers[0].text,'');assert.equal(screen.querySelector('.vg-text-panel'),null);input.textContent='À beira da piscina';input.dispatchEvent(new w.Event('input'));q.pointer(w.document.querySelector('#outside'),'pointerdown',1,500,500);assert.equal(q.editor.isEditing(),false);assert.equal(media.text_layers[0].text,'À beira da piscina');assert.ok(q.changes()>0);q.d.window.close()});
test('pinch resizes text and one pointer drags it without bubbling to photo gestures',async()=>{const q=await inlineEditor(),{screen,media,w}=q;screen.querySelector('.vg-text-tools button').click();let n=screen.querySelector('[contenteditable=true]');n.textContent='Momento';n.dispatchEvent(new w.Event('input'));screen.querySelector('[data-text-finish]').click();n=screen.querySelector('.vg-text-sticker');let photoEvents=0;screen.addEventListener('pointermove',()=>photoEvents++);q.pointer(n,'pointerdown',1,100,200);q.pointer(n,'pointerdown',2,200,200);q.pointer(n,'pointermove',2,250,200);assert.equal(media.text_layers[0].size,9);q.pointer(n,'pointermove',2,150,200);assert.equal(media.text_layers[0].size,3);q.pointer(n,'pointerup',2,150,200);q.pointer(n,'pointerup',1,100,200);n=screen.querySelector('.vg-text-sticker');const before={...media.text_layers[0]};q.pointer(n,'pointerdown',3,100,200);q.pointer(n,'pointermove',3,129,238);q.pointer(n,'pointerup',3,129,238);assert.ok(media.text_layers[0].x>before.x);assert.ok(media.text_layers[0].y>before.y);assert.equal(photoEvents,0);q.d.window.close()});
test('formatting flags survive server validation and the visitor renderer; invalid flags are rejected',async()=>{const rich={...layer,bold:true,italic:true,strike:true};assert.deepEqual(textLayersInput([rich]),[rich]);for(const k of ['bold','italic','strike'])assert.throws(()=>textLayersInput([{...rich,[k]:'true'}]),/invalid_text_layers/);const q=await inlineEditor();q.screen.innerHTML=q.w.VillegramText.markup([rich]);const style=q.screen.querySelector('.vg-text-sticker').style;assert.equal(style.fontWeight,'600');assert.equal(style.fontStyle,'italic');assert.equal(style.textDecoration,'line-through');q.d.window.close()});
test('empty text is discarded, pasted markup remains plain text and delete removes the whole block',async()=>{const q=await inlineEditor(),{screen,media,w}=q;screen.querySelector('.vg-text-tools button').click();q.editor.commit();assert.equal(media.text_layers.length,0);screen.querySelector('.vg-text-tools button').click();const n=screen.querySelector('[contenteditable=true]'),event=new w.Event('paste',{bubbles:true,cancelable:true});Object.defineProperty(event,'clipboardData',{value:{getData:()=>'<b>Um momento</b>'}});n.dispatchEvent(event);q.editor.commit();assert.equal(media.text_layers[0].text,'<b>Um momento</b>');assert.equal(screen.querySelector('.vg-text-sticker b'),null);screen.querySelector('.vg-text-sticker').click();assert.equal(screen.querySelector('.vg-text-orbit').hidden,false);screen.querySelector('[data-delete]').click();assert.equal(media.text_layers.length,0);q.d.window.close()});
function selectText(q,el,start,end){const walker=q.w.document.createTreeWalker(el,q.w.NodeFilter.SHOW_TEXT);let n,offset=0,a,b;while(n=walker.nextNode()){if(!a&&start<=offset+n.length)a=[n,start-offset];if(end<=offset+n.length){b=[n,end-offset];break}offset+=n.length}const range=q.w.document.createRange();range.setStart(...a);range.setEnd(...b);const sel=q.w.getSelection();sel.removeAllRanges();sel.addRange(range);q.w.document.dispatchEvent(new q.w.Event('selectionchange'))}
function addText(q,text){q.screen.querySelector('.vg-text-tools button').click();const n=q.screen.querySelector('[contenteditable=true]');n.textContent=text;n.dispatchEvent(new q.w.Event('input'));return n}
test('formatting follows selected words across blur and color controls without touching another box',async()=>{const q=await inlineEditor();addText(q,'Outra caixa');q.editor.commit();let n=addText(q,'Lindo momento a dois');selectText(q,n,6,13);q.screen.querySelector('[data-format=bold]').click();assert.equal(q.media.text_layers[0].bold,false);assert.equal(q.media.text_layers[1].bold,false);assert.deepEqual(JSON.parse(JSON.stringify(q.media.text_layers[1].runs)),[{start:6,end:13,bold:true}]);q.screen.querySelector('[data-format=italic]').click();q.screen.querySelector('[data-format=strike]').click();q.screen.querySelector('[data-format=color]').click();q.screen.querySelector('.vg-text-swatches [aria-label="#e35454"]').click();q.screen.querySelector('[data-format=background]').click();q.screen.querySelector('.vg-text-swatches [aria-label="#e5cc97"]').click();const t=q.media.text_layers[1];assert.equal(t.color,'#ffffff');assert.equal(t.background,'transparent');assert.deepEqual(JSON.parse(JSON.stringify(t.runs)),[{start:6,end:13,color:'#e35454',background:'#e5cc97',bold:true,italic:true,strike:true}]);const result=q.w.document.createElement('div');result.innerHTML=q.w.VillegramText.markup([t]);assert.equal(result.querySelectorAll('.vg-text-run')[1].textContent,'momento');assert.equal(result.querySelectorAll('.vg-text-run')[0].style.fontWeight,'400');assert.equal(result.querySelectorAll('.vg-text-run')[1].style.fontWeight,'600');assert.match(q.screen.querySelector('.vg-text-scope').textContent,/Trecho/);assert.deepEqual(textLayersInput(JSON.parse(JSON.stringify([t]))),JSON.parse(JSON.stringify([t])));q.d.window.close()});
test('switching boxes clears old word selection and applies style only to the active box',async()=>{const q=await inlineEditor();let n=addText(q,'Primeiro momento');selectText(q,n,0,8);q.screen.querySelector('[data-format=bold]').click();q.editor.commit();addText(q,'Segundo');q.editor.commit();q.screen.querySelectorAll('.vg-text-sticker')[1].click();q.screen.querySelector('[data-format=italic]').click();assert.equal(q.media.text_layers[0].italic,false);assert.equal(q.media.text_layers[1].italic,true);assert.equal(q.media.text_layers[1].runs,undefined);assert.equal(q.media.text_layers[0].runs[0].bold,true);q.d.window.close()});
test('editing text rebases selected-word formatting instead of moving it to another word',async()=>{const q=await inlineEditor();let n=addText(q,'Bom café');selectText(q,n,4,8);q.screen.querySelector('[data-format=bold]').click();q.screen.querySelector('[data-text-edit]').click();n=q.screen.querySelector('[contenteditable=true]');n.textContent='Um Bom café';n.dispatchEvent(new q.w.Event('input'));q.editor.commit();assert.deepEqual(JSON.parse(JSON.stringify(q.media.text_layers[0].runs)),[{start:7,end:11,bold:true}]);q.d.window.close()});
test('server rejects overlapping or malicious ranges and preserves whitespace offsets',()=>{const t={...layer,text:' Um café ',runs:[{start:4,end:8,bold:true,color:'#fefefe',unknown:'discard'}]};assert.deepEqual(textLayersInput([t])[0].runs,[{start:4,end:8,bold:true,color:'#fefefe'}]);assert.equal(textLayersInput([t])[0].text,' Um café ');for(const runs of [[{start:0,end:999,bold:true}],[{start:0,end:3,bold:true},{start:2,end:4,italic:true}],[{start:0,end:3,color:'red;display:none'}],[{start:0,end:3,bold:'yes'}]])assert.throws(()=>textLayersInput([{...layer,runs}]),/invalid_text_layers/)});
