import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';import {textLayersInput,publicationInput} from '../supabase/functions/_shared/villegram-publications.ts';
const layer={text:'Um café',x:50,y:30,size:6,color:'#ffffff',background:'transparent'};
test('text layers validate bounds, reject CSS injection and retain only public presentation fields',()=>{
 assert.deepEqual(textLayersInput([{...layer,private:'secret'}]),[layer]);for(const value of [[{...layer,color:'red;display:none'}],[{...layer,text:'x'.repeat(281)}],[{...layer,x:Infinity}],[{...layer,y:0}],[{...layer,size:10}],Array(6).fill(layer),{}])assert.throws(()=>textLayersInput(value),/invalid_text_layers/);
 const p=publicationInput({type:'trust',title:'Teste',caption:'Teste',media:[{kind:'photo',url:'assets/test.webp',text_layers:[layer]}]},'https://dev.supabase.co');assert.deepEqual(p.media[0].text_layers,[layer]);
});
test('avatar crop geometry covers circle, clamps edges, preserves proportions and supports portrait/landscape',async()=>{
 const d=new JSDOM('',{runScripts:'outside-only'});d.window.eval(await readFile(new URL('../villegram-avatar.js',import.meta.url),'utf8'));const g=d.window.VillegramAvatar.geometry;for(const [w,h] of [[800,1200],[1200,800]]){const a=g(w,h,1,0,1);assert.equal(a.side,800);assert.ok(a.x-a.side/2>=0);assert.ok(a.y+a.side/2<=h);const b=g(w,h,4,.5,.5);assert.equal(b.side,200);assert.equal(b.x,w/2);assert.equal(b.y,h/2)}d.window.close();
});
test('visitor text is escaped and remains a separate layer from cropped media',async()=>{
 const d=new JSDOM('',{runScripts:'outside-only'});d.window.eval(await readFile(new URL('../villegram-text.js',import.meta.url),'utf8'));d.window.document.body.innerHTML=d.window.VillegramText.markup([{...layer,text:'<img src=x onerror=alert(1)>'}]);assert.equal(d.window.document.querySelector('img'),null);assert.equal(d.window.document.querySelector('.vg-text-sticker').textContent,'<img src=x onerror=alert(1)>');d.window.close();
});
async function inlineEditor(){const d=new JSDOM('<div id="screen"></div><button id="outside">Avançar</button>',{runScripts:'outside-only',pretendToBeVisual:true}),w=d.window,screen=w.document.querySelector('#screen'),media={text_layers:[]};w.eval(await readFile(new URL('../villegram-text.js',import.meta.url),'utf8'));let changes=0;const editor=w.VillegramText.editor({screen,getMedia:()=>media,isBusy:()=>false,onChange:()=>changes++});editor.render();screen.getBoundingClientRect=()=>({left:0,top:0,width:360,height:640});screen.querySelector('.vg-text-stage').getBoundingClientRect=()=>({left:18,top:83,width:295,height:384});const pointer=(el,type,id,x,y)=>{const e=new w.Event(type,{bubbles:true,cancelable:true});Object.assign(e,{pointerId:id,clientX:x,clientY:y,button:0});el.dispatchEvent(e);};return {d,w,screen,media,editor,pointer,changes:()=>changes}}
test('inline text begins focused, commits on outside click and never creates a full image panel',async()=>{const q=await inlineEditor(),{w,screen,media}=q;screen.querySelector('.vg-text-tools button').click();const input=screen.querySelector('[contenteditable=true]');assert.equal(w.document.activeElement,input);assert.equal(media.text_layers[0].text,'');assert.equal(screen.querySelector('.vg-text-panel'),null);input.textContent='À beira da piscina';input.dispatchEvent(new w.Event('input'));q.pointer(w.document.querySelector('#outside'),'pointerdown',1,500,500);assert.equal(q.editor.isEditing(),false);assert.equal(media.text_layers[0].text,'À beira da piscina');assert.ok(q.changes()>0);q.d.window.close()});
test('pinch resizes text and one pointer drags it without bubbling to photo gestures',async()=>{const q=await inlineEditor(),{screen,media,w}=q;screen.querySelector('.vg-text-tools button').click();let n=screen.querySelector('[contenteditable=true]');n.textContent='Momento';n.dispatchEvent(new w.Event('input'));screen.querySelector('[data-text-finish]').click();n=screen.querySelector('.vg-text-sticker');let photoEvents=0;screen.addEventListener('pointermove',()=>photoEvents++);q.pointer(n,'pointerdown',1,100,200);q.pointer(n,'pointerdown',2,200,200);q.pointer(n,'pointermove',2,250,200);assert.equal(media.text_layers[0].size,9);q.pointer(n,'pointermove',2,150,200);assert.equal(media.text_layers[0].size,3);q.pointer(n,'pointerup',2,150,200);q.pointer(n,'pointerup',1,100,200);n=screen.querySelector('.vg-text-sticker');const before={...media.text_layers[0]};q.pointer(n,'pointerdown',3,100,200);q.pointer(n,'pointermove',3,129,238);q.pointer(n,'pointerup',3,129,238);assert.ok(media.text_layers[0].x>before.x);assert.ok(media.text_layers[0].y>before.y);assert.equal(photoEvents,0);q.d.window.close()});
test('formatting flags survive server validation and the visitor renderer; invalid flags are rejected',async()=>{const rich={...layer,bold:true,italic:true,strike:true};assert.deepEqual(textLayersInput([rich]),[rich]);for(const k of ['bold','italic','strike'])assert.throws(()=>textLayersInput([{...rich,[k]:'true'}]),/invalid_text_layers/);const q=await inlineEditor();q.screen.innerHTML=q.w.VillegramText.markup([rich]);const style=q.screen.querySelector('.vg-text-sticker').style;assert.equal(style.fontWeight,'600');assert.equal(style.fontStyle,'italic');assert.equal(style.textDecoration,'line-through');q.d.window.close()});
test('empty text is discarded, pasted markup remains plain text and delete removes the whole block',async()=>{const q=await inlineEditor(),{screen,media,w}=q;screen.querySelector('.vg-text-tools button').click();q.editor.commit();assert.equal(media.text_layers.length,0);screen.querySelector('.vg-text-tools button').click();const n=screen.querySelector('[contenteditable=true]'),event=new w.Event('paste',{bubbles:true,cancelable:true});Object.defineProperty(event,'clipboardData',{value:{getData:()=>'<b>Um momento</b>'}});n.dispatchEvent(event);q.editor.commit();assert.equal(media.text_layers[0].text,'<b>Um momento</b>');assert.equal(screen.querySelector('.vg-text-sticker b'),null);screen.querySelector('.vg-text-sticker').click();assert.equal(screen.querySelector('.vg-text-orbit').hidden,false);screen.querySelector('[data-delete]').click();assert.equal(media.text_layers.length,0);q.d.window.close()});
