import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {JSDOM} from 'jsdom';
const uid='4069a585-7cc6-48ad-9263-567358a45c0c',url='https://pxfqmnhqodqyaaqeyjgr.supabase.co';
const tick=()=>new Promise(r=>setTimeout(r,10));
test('TUS resumes a failed second chunk from the server offset without duplicating the file',async()=>{
 const d=new JSDOM('',{url,runScripts:'outside-only'}),w=d.window;w.CHALEZINHO_CONFIG={supabaseUrl:url,supabaseKey:'public-key'};w.AbortSignal.timeout=()=>undefined;
 let offset=0,creates=0,fail=true;const offsets=[];w.fetch=async(_url,r)=>{if(r.method==='POST'){creates++;return {ok:true,headers:new Headers({Location:url+'/storage/v1/upload/resumable/test'})}}if(r.method==='HEAD')return {ok:true,headers:new Headers({'Upload-Offset':String(offset)})};offsets.push(Number(r.headers['Upload-Offset']));if(offset>0&&fail){fail=false;return {ok:false}}offset+=r.body.size;return {ok:true,headers:new Headers({'Upload-Offset':String(offset)})}};
 w.eval(await readFile(new URL('../villegram-upload.js',import.meta.url),'utf8'));const sb={auth:{getSession:async()=>({data:{session:{access_token:'test'}}})}},file=new Blob([new Uint8Array(7*1024*1024)],{type:'video/mp4'});
 await assert.rejects(w.VillegramUpload.upload(sb,file,uid+'/test.mp4'),/interrompido/);assert.equal(offset,6*1024*1024);
 await w.VillegramUpload.upload(sb,file,uid+'/test.mp4');assert.equal(offset,file.size);assert.equal(creates,1);assert.deepEqual(offsets,[0,6*1024*1024,6*1024*1024]);d.window.close();
});
async function editor({quoteResponder}={}){const d=new JSDOM(await readFile(new URL('../villegram-admin.html',import.meta.url),'utf8'),{url:url+'/villegram-admin.html',runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;const rows=[],saved=[],quotes=[];w.CHALEZINHO_CONFIG={supabaseUrl:url,supabaseKey:'public-key'};w.AbortSignal.timeout=()=>undefined;w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLMediaElement.prototype.pause=function(){};w.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:'test',user:{id:uid}}}})}})};
 w.fetch=async(_url,opts)=>{const b=JSON.parse(opts.body);if(b.action==='villegram_quote'){quotes.push(b);return response(await quoteResponder?.(b)||{rate_options:[]})}if(b.operation==='admin_list')return response({publications:rows,properties:[{id:1,name:'Ville',gallery:['assets/photo.webp']}],products:[],offers:[{id:'a8116a6a-66e2-471f-8a6a-d35daa690887',name:'Escapada a dois'}],settings:{enabled:true,auto_publish:false,frequency_hours:24,max_offers:3,templates:{}}});if(b.operation==='report')return response({rows:[]});if(b.operation==='save'){saved.push(b);const p={...b.publication,id:b.id||uid,updated_at:'revision-'+saved.length,author_name:'Equipe'};rows.splice(0,rows.length,p);return response({publication:p})}return response({})};function response(data){return {ok:true,json:async()=>({ok:true,...data})}}
 w.VillegramMedia={editor:async()=>new Blob(['photo'],{type:'image/webp'})};w.URL.createObjectURL=()=>url+'/preview.webp';w.eval(await readFile(new URL('../villegram-admin.js',import.meta.url),'utf8'));await tick();return {d,w,rows,saved,quotes};}
test('manual editor saves draft, retains identity during edit, publishes and archives',async()=>{
 const {d,w,saved}=await editor(),f=w.document.querySelector('#vg-post-form');f.elements.property_id.value='1';f.elements.title.value='Manual';f.elements.caption.value='Foto real';w.document.querySelector('[data-photo]').click();
 f.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:f.querySelector('[name=draft]')}));await tick();assert.equal(saved[0].publication.status,'draft');assert.match(w.document.querySelector('#vg-editor-message').textContent,/Rascunho salvo/);
 f.elements.caption.value='Legenda editada';f.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:f.querySelector('[name=published]')}));await tick();assert.equal(saved[1].id,uid);assert.equal(saved[1].updated_at,'revision-1');assert.equal(saved[1].publication.status,'published');assert.equal(saved[1].publication.caption,'Legenda editada');
 w.document.querySelector('#vg-archive').click();await tick();assert.equal(saved[2].publication.status,'archived');assert.equal(saved[2].id,uid);d.window.close();
});
test('retrying a failed video poster upload preserves the already uploaded video',async()=>{
 const {d,w}=await editor();let videoUploads=0,posterUploads=0,fail=true;w.VillegramUpload={inspect:async()=>({url:'blob:video',video:{duration:4}}),poster:async()=>new Blob(['poster']),upload:async(_sb,_file,path)=>{if(path.endsWith('.mp4'))videoUploads++;else{posterUploads++;if(fail){fail=false;throw Error('upload failed')}}}};
 const input=w.document.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['video'],'real.mp4',{type:'video/mp4'})]});input.dispatchEvent(new w.Event('change'));await tick();assert.equal(w.document.querySelector('#vg-upload-retry').hidden,false);assert.equal(videoUploads,1);
 w.document.querySelector('#vg-upload-retry').click();await tick();assert.equal(videoUploads,1);assert.equal(posterUploads,2);assert.equal(w.document.querySelectorAll('#vg-composer-visual video').length,1);d.window.close();
});

test('native publication clicks and Enter preserve published status during subsequent edits',async()=>{
 const {d,w,saved}=await editor(),f=w.document.querySelector('#vg-post-form');f.elements.property_id.value='1';f.elements.title.value='Publicação';f.elements.caption.value='Cena real';w.document.querySelector('[data-photo]').click();
 f.querySelector('[name=published]').click();await tick();assert.equal(saved[0].publication.status,'published');assert.equal(w.document.querySelector('#vg-post-status').textContent,'Publicada');assert.equal(f.querySelector('[name=draft]').hidden,true);assert.equal(f.querySelector('[name=published]').textContent,'Salvar alterações');
 const link=w.document.querySelector('#vg-view-post');assert.equal(link.hidden,false);assert.equal(new URL(link.href).searchParams.get('publication'),uid);
 f.elements.caption.value='Legenda corrigida';f.requestSubmit();await tick();assert.equal(saved[1].publication.status,'published');assert.equal(saved[1].publication.caption,'Legenda corrigida');assert.equal(saved[1].id,uid);assert.equal(saved[1].updated_at,'revision-1');
 // A stale caller selecting the old draft action must also preserve publication.
 f.dispatchEvent(new w.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:f.querySelector('[name=draft]')}));await tick();assert.equal(saved[2].publication.status,'published');
 w.document.querySelector('#vg-archive').click();await tick();assert.equal(saved[3].publication.status,'archived');assert.equal(link.hidden,true);assert.equal(w.document.querySelector('#vg-post-status').textContent,'Arquivada');d.window.close();
});
test('uploaded video can be published by clicking the actual button and saved edits keep the file identity',async()=>{
 const {d,w,saved}=await editor(),f=w.document.querySelector('#vg-post-form');w.VillegramUpload={inspect:async()=>({url:'blob:video',video:{duration:9.7}}),poster:async()=>new Blob(['poster'],{type:'image/webp'}),upload:async()=>{}};
 f.elements.property_id.value='1';f.elements.title.value='Vinho no SPA aquecido?';f.elements.caption.value='Vídeo real do imóvel';const input=w.document.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['video'],'real.mp4',{type:'video/mp4'})]});input.dispatchEvent(new w.Event('change'));await tick();
 assert.match(w.document.querySelector('#vg-upload-status').textContent,/Mídia enviada/);assert.equal(saved.length,0);f.querySelector('[name=published]').click();await tick();assert.equal(saved[0].publication.status,'published');const file=saved[0].publication.media[0];assert.equal(file.kind,'video');assert.ok(file.path.endsWith('.mp4'));assert.ok(file.poster_path.endsWith('.webp'));
 f.elements.caption.value='Nova legenda';f.querySelector('[name=published]').click();await tick();assert.equal(saved[1].publication.status,'published');assert.equal(saved[1].publication.media[0].path,file.path);d.window.close();
});

test('cover generation seeks a decoded frame and rejects a black canvas instead of uploading it',async()=>{
 const d=new JSDOM('',{url,runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;let dark=false;
 w.HTMLCanvasElement.prototype.getContext=()=>({drawImage(){},getImageData(){return {data:Uint8ClampedArray.from([dark?0:50,0,0,255])}}});w.HTMLCanvasElement.prototype.toBlob=function(callback){callback(new w.Blob(['cover'],{type:'image/webp'}))};w.eval(await readFile(new URL('../villegram-upload.js',import.meta.url),'utf8'));
 const video=w.document.createElement('video');let time=0;Object.defineProperties(video,{readyState:{value:2},duration:{value:9.7},videoWidth:{value:2160},videoHeight:{value:3840},currentTime:{get:()=>time,set:value=>{time=value;Promise.resolve().then(()=>video.dispatchEvent(new w.Event('seeked')))}}});
 const cover=await w.VillegramUpload.poster(video);assert.equal(time,.5);assert.equal(cover.type,'image/webp');dark=true;await assert.rejects(w.VillegramUpload.poster(video,1),/capa ficou preta/);assert.equal(time,1);d.window.close();
});

test('visual composer gates empty steps and keeps media, cover, crop and text when returning',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');const click=s=>doc.querySelector(s).click(),change=(n,v)=>{n.value=v;n.dispatchEvent(new w.Event('input',{bubbles:true}))};
 assert.equal(doc.querySelector('[data-panel="0"]').hidden,false);assert.equal(doc.querySelector('[data-panel="1"]').hidden,true);assert.equal(doc.querySelector('#vg-composer-empty').hidden,false);
 click('#vg-step-next');assert.equal(doc.querySelector('[data-panel="0"]').hidden,false);assert.match(doc.querySelector('#vg-editor-message').textContent,/Escolha um vídeo/);
 click('[data-photo]');click('[data-photo]');assert.equal(doc.querySelectorAll('[data-select]').length,2);click('[data-cover="1"]');
 const fit=doc.querySelector('[data-fit]');fit.value='cover';fit.dispatchEvent(new w.Event('change',{bubbles:true}));change(doc.querySelector('[data-position]'),'0');assert.equal(doc.querySelector('#vg-composer-visual img').style.objectPosition,'50% 0%');assert.equal(doc.querySelector('#vg-composer-visual img').style.objectFit,'cover');
 click('#vg-step-next');assert.equal(doc.querySelector('[data-panel="1"]').hidden,false);click('#vg-step-next');assert.equal(doc.querySelector('[data-panel="1"]').hidden,false);assert.equal(doc.activeElement,f.elements.title);
 change(f.elements.title,'Minha cena');change(f.elements.caption,'Minha legenda');assert.equal(doc.querySelector('#vg-composer-title').textContent,'Minha cena');assert.equal(doc.querySelector('#vg-composer-caption').textContent,'Minha legenda');
 click('#vg-step-next');assert.equal(doc.querySelector('[data-panel="2"]').hidden,false);click('[name=published]');await tick();assert.equal(saved.length,0);assert.match(doc.querySelector('#vg-editor-message').textContent,/Escolha o chalé/);
 change(f.elements.property_id,'1');assert.match(doc.querySelector('#vg-destination-summary').textContent,/página do chalé: Ville/);
 click('#vg-step-back');click('#vg-step-back');assert.equal(f.elements.caption.value,'Minha legenda');assert.equal(doc.querySelector('[data-select="1"]').getAttribute('aria-pressed'),'true');assert.equal(doc.querySelector('[data-cover="1"]').disabled,true);
 click('[data-up="1"]');assert.equal(doc.querySelector('[data-select="0"]').getAttribute('aria-pressed'),'true');click('[data-step="2"]');click('[name=draft]');await tick();assert.equal(saved[0].publication.cover_index,0);assert.equal(saved[0].publication.media[0].fit,'cover');assert.equal(saved[0].publication.media[0].position,0);assert.equal(saved[0].publication.caption,'Minha legenda');d.window.close();
});

test('composer opens its library, edits published posts, and does not restart video while typing or switching steps',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');w.VillegramUpload={inspect:async()=>({url:'blob:video',video:{duration:9.7}}),poster:async()=>new Blob(['poster']),upload:async()=>{}};
 const input=doc.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['video'],'real.mp4',{type:'video/mp4'})]});input.dispatchEvent(new w.Event('change'));await tick();const video=doc.querySelector('#vg-composer-visual video');video.currentTime=3;
 doc.querySelector('#vg-step-next').click();f.elements.title.value='Vídeo';f.elements.caption.value='Texto';f.elements.caption.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(doc.querySelector('#vg-composer-visual video'),video);assert.equal(video.currentTime,3);
 f.elements.title.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}));assert.equal(doc.querySelector('[data-panel="2"]').hidden,false);assert.equal(saved.length,0);assert.equal(doc.querySelector('#vg-composer-visual video'),video);
 f.elements.property_id.value='1';f.querySelector('[name=published]').click();await tick();doc.querySelector('#vg-library-toggle').click();assert.equal(doc.querySelector('#vg-publications-library').hidden,false);assert.equal(doc.querySelector('#vg-library-toggle').getAttribute('aria-expanded'),'true');doc.querySelector('[data-edit]').click();assert.equal(doc.querySelector('#vg-publications-library').hidden,true);assert.equal(doc.querySelector('#vg-post-status').textContent,'Publicada');assert.equal(f.querySelector('[name=draft]').hidden,true);assert.equal(saved.length,1);d.window.close();
});

test('slow media upload locks the composer, recovers after failure, and reports preview media errors',async()=>{
 const {d,w}=await editor(),doc=w.document;let finish;const pending=new Promise(r=>finish=r);w.VillegramUpload={inspect:async()=>({url:'blob:video',video:{duration:9}}),poster:async()=>new Blob(['poster']),upload:async()=>pending};
 const input=doc.querySelector('#vg-upload');Object.defineProperty(input,'files',{value:[new w.File(['video'],'real.mp4',{type:'video/mp4'})]});input.dispatchEvent(new w.Event('change'));await tick();assert.equal(doc.querySelector('#vg-step-next').disabled,true);assert.equal(doc.querySelector('#vg-new').disabled,true);assert.equal(doc.querySelector('[data-photo]').disabled,true);finish();await tick();assert.equal(doc.querySelector('#vg-step-next').disabled,false);assert.equal(doc.querySelector('#vg-new').disabled,false);
 doc.querySelector('#vg-composer-visual video').dispatchEvent(new w.Event('error'));assert.match(doc.querySelector('#vg-editor-message').textContent,/MP4\/H.264/);doc.querySelector('[data-remove]').click();assert.equal(doc.querySelector('#vg-composer-empty').hidden,false);assert.equal(doc.querySelectorAll('[data-select]').length,0);d.window.close();
});

test('zoom and two-axis position update the same live image and are saved with it',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();const image=doc.querySelector('#vg-composer-visual img');Object.defineProperties(image,{naturalWidth:{value:900},naturalHeight:{value:1600}});image.dispatchEvent(new w.Event('load'));assert.equal(doc.querySelector('[data-position]').disabled,true);
 for(const [selector,value] of [['[data-zoom]','1.5'],['[data-position-x]','0'],['[data-position]','100']]){const n=doc.querySelector(selector);n.value=value;n.dispatchEvent(new w.Event('input',{bubbles:true}))}
 assert.equal(doc.querySelector('#vg-composer-visual img'),image);assert.equal(image.style.transform,'scale(1.5)');assert.equal(image.style.transformOrigin,'0% 100%');assert.equal(image.style.objectPosition,'0% 100%');assert.equal(doc.querySelector('[data-position]').disabled,false);f.elements.title.value='Minha foto';f.elements.caption.value='Texto';f.elements.property_id.value='1';f.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.media[0].zoom,1.5);assert.equal(saved[0].publication.media[0].position_x,0);assert.equal(saved[0].publication.media[0].position,100);d.window.close();
});

test('holding and dragging photo thumbnails changes order while retaining the selected cover; keyboard also works',async()=>{
 const {d,w,saved}=await editor(),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();doc.querySelector('[data-photo]').click();doc.querySelector('[data-cover="1"]').click();
 const thumb=doc.querySelector('[data-select="1"]'),target=doc.querySelector('[data-select="0"]');doc.elementFromPoint=()=>target;
 thumb.dispatchEvent(new w.MouseEvent('pointerdown',{bubbles:true,button:0}));await new Promise(r=>setTimeout(r,340));assert.ok(thumb.classList.contains('vg-dragging'));thumb.dispatchEvent(new w.MouseEvent('pointermove',{bubbles:true,cancelable:true,clientX:1,clientY:1}));thumb.dispatchEvent(new w.MouseEvent('pointerup',{bubbles:true}));assert.equal(doc.querySelector('[data-cover]').dataset.cover,'0');assert.equal(doc.querySelector('[data-select="0"]').getAttribute('aria-pressed'),'true');assert.match(doc.querySelector('#vg-reorder-status').textContent,/capa foi preservada/);
 doc.querySelector('[data-select="0"]').dispatchEvent(new w.KeyboardEvent('keydown',{altKey:true,key:'ArrowRight',bubbles:true,cancelable:true}));assert.equal(doc.querySelector('[data-cover]').dataset.cover,'1');f.elements.property_id.value='1';f.elements.title.value='Ordem';f.elements.caption.value='Fotos';f.querySelector('[name=draft]').click();await tick();assert.equal(saved[0].publication.cover_index,1);d.window.close();
});

test('Quero estes dias quotes both tariffs, reprices packages, and saves only explicit dates and rate',async()=>{
 const {d,w,saved,quotes}=await editor({quoteResponder:async b=>({rate_options:['refundable','non_refundable'].map((code,i)=>({code,name:i?'Não reembolsável':'Reembolsável',selectable:true,total_amount_cents:100000-i*10000+(b.offer_id?20000:0),accommodation_amount_cents:85000-i*10000,cleaning_fee_cents:15000,experience_amount_cents:b.offer_id?20000:0})),experiences:[]})}),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();f.elements.title.value='Dias no Ville';f.elements.caption.value='Sua estadia';const change=(name,value)=>{f.elements[name].value=value;f.elements[name].dispatchEvent(new w.Event('change',{bubbles:true}))};change('property_id','1');change('cta','offer');assert.equal(doc.querySelector('#vg-stay-choice').hidden,false);assert.match(f.elements.offer_id.selectedOptions[0].textContent,/Somente hospedagem/);change('stay_check_in','2026-11-16');change('stay_check_out','2026-11-19');doc.querySelector('#vg-stay-refresh').click();await tick();assert.equal(doc.querySelectorAll('[data-stay-rate]').length,2);assert.equal(f.elements.stay_rate_code.value,'');assert.equal(doc.querySelector('#vg-composer-stay').hidden,true);f.querySelector('[name=published]').click();await tick();assert.equal(saved.length,0);
 doc.querySelector('[data-stay-rate="refundable"]').click();assert.match(doc.querySelector('#vg-composer-stay').textContent,/1.000,00/);change('offer_id','a8116a6a-66e2-471f-8a6a-d35daa690887');assert.equal(doc.querySelector('#vg-composer-stay').hidden,true);doc.querySelector('#vg-stay-refresh').click();await tick();assert.match(doc.querySelector('#vg-composer-stay').textContent,/1.200,00/);assert.match(doc.querySelector('[data-stay-rate="refundable"]').textContent,/pacote R\$\s*200,00/);
 f.querySelector('[name=published]').click();await tick();assert.deepEqual(JSON.parse(JSON.stringify(saved[0].publication.stay_selection)),{check_in:'2026-11-16',check_out:'2026-11-19',guests:2,rate_code:'refundable'});assert.equal(saved[0].publication.total_cents,undefined);assert.equal(saved[0].publication.offer_id,quotes.at(-1).offer_id);d.window.close();
});

test('photo crop dialog moves its preview immediately and encodes only on rotate or confirmation',async()=>{
 const d=new JSDOM('',{url,runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;let encoded=0;w.createImageBitmap=async()=>({width:2000,height:1000,close(){}});w.HTMLDialogElement.prototype.showModal=function(){};w.HTMLDialogElement.prototype.close=function(){};w.HTMLCanvasElement.prototype.getContext=()=>({translate(){},rotate(){},drawImage(){}});w.HTMLCanvasElement.prototype.toBlob=function(done){encoded++;done(new w.Blob(['frame'],{type:'image/webp'}))};w.URL.createObjectURL=()=>url+'/crop.webp';w.URL.revokeObjectURL=()=>{};Object.defineProperties(w.HTMLImageElement.prototype,{naturalWidth:{get:()=>2000},naturalHeight:{get:()=>1000}});w.eval(await readFile(new URL('../villegram-media.js',import.meta.url),'utf8'));
 const result=w.VillegramMedia.editor(new w.Blob(['photo']));await tick();const dialog=w.document.querySelector('dialog'),image=dialog.querySelector('img'),format=dialog.querySelector('select'),position=dialog.querySelector('input'),initial=encoded;assert.equal(position.disabled,true);format.value='portrait';format.dispatchEvent(new w.Event('change'));assert.equal(position.disabled,false);assert.equal(dialog.querySelector('.vg-crop-frame').style.aspectRatio,String(9/16));position.value='0';position.dispatchEvent(new w.Event('input'));assert.equal(image.style.objectPosition,'0% 0%');position.value='100';position.dispatchEvent(new w.Event('input'));assert.equal(image.style.objectPosition,'100% 100%');assert.equal(encoded,initial);dialog.querySelector('[data-save]').click();const saved=await result;assert.equal(saved.type,'image/webp');assert.ok(encoded>initial);assert.equal(w.document.querySelector('dialog'),null);d.window.close();
});

test('changing dates while a quote is pending cannot show the old total or publish it',async()=>{
 let finish;const held=new Promise(r=>finish=r);const {d,w,saved}=await editor({quoteResponder:async()=>held}),doc=w.document,f=doc.querySelector('#vg-post-form');doc.querySelector('[data-photo]').click();f.elements.title.value='Datas';f.elements.caption.value='Texto';f.elements.property_id.value='1';f.elements.cta.value='offer';f.elements.cta.dispatchEvent(new w.Event('change',{bubbles:true}));f.elements.stay_check_in.value='2026-11-16';f.elements.stay_check_out.value='2026-11-19';doc.querySelector('#vg-stay-refresh').click();await tick();f.elements.stay_check_in.value='2026-11-17';f.elements.stay_check_in.dispatchEvent(new w.Event('change',{bubbles:true}));finish({rate_options:[{code:'refundable',total_amount_cents:1}]});await tick();assert.equal(doc.querySelectorAll('[data-stay-rate]').length,0);assert.equal(doc.querySelector('#vg-composer-stay').hidden,true);f.querySelector('[name=published]').click();await tick();assert.equal(saved.length,0);d.window.close();
});
