-- CHALEZINHO VILLE — FASE 1
-- Snapshot idempotente da estrutura alvo em 2026-09-23.
-- Não executa remoção de dados existentes.

create schema if not exists private;
create schema if not exists extensions;

-- Properties: catálogo data-driven
alter table public.properties add column if not exists slug text;
alter table public.properties add column if not exists property_type text not null default 'chalet';
alter table public.properties add column if not exists tagline text;
alter table public.properties add column if not exists summary text;
alter table public.properties add column if not exists cover_image text;
alter table public.properties add column if not exists gallery jsonb not null default '[]'::jsonb;
alter table public.properties add column if not exists features jsonb not null default '[]'::jsonb;
alter table public.properties add column if not exists guarantee_amount_cents integer not null default 50000;
alter table public.properties add column if not exists updated_at timestamptz not null default now();
create unique index if not exists properties_slug_key on public.properties(slug);

create table if not exists public.property_integrations(
 id bigint generated by default as identity primary key,
 property_id bigint not null references public.properties(id) on delete cascade,
 provider text not null check(provider in ('pricelabs','airbnb','booking')),
 external_listing_id text,pms text,environment_key text,active boolean not null default true,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 unique(property_id,provider)
);

-- Auth/perfis
create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 role text not null default 'guest' check(role in ('guest','admin','host','staff','service_provider')),
 full_name text,phone text,marketing_consent boolean not null default false,
 deletion_requested_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);

-- Documentos/políticas/tarifas
create table if not exists public.policy_documents(
 id uuid primary key default gen_random_uuid(),
 document_type text not null check(document_type in ('hosting_terms','cancellation_policy','property_rules','privacy_policy')),
 code text not null,version text not null,title text not null,body text not null,
 status text not null default 'draft' check(status in ('draft','active','archived')),
 effective_at timestamptz,created_at timestamptz not null default now(),unique(code,version)
);
create table if not exists public.rate_plans(
 id bigint generated by default as identity primary key,code text not null unique,name text not null,
 multiplier_bps integer not null check(multiplier_bps>0),selectable boolean not null default true,
 cancellation_policy_id uuid references public.policy_documents(id),active boolean not null default true,
 display_order integer not null default 0,created_at timestamptz not null default now()
);

-- Quotes server-side
create table if not exists public.quotes(
 id uuid primary key default gen_random_uuid(),property_id bigint not null references public.properties(id),
 user_id uuid references auth.users(id) on delete set null,client_token_hash text not null,
 check_in date not null,check_out date not null,guests integer not null check(guests>0),
 base_amount_cents bigint not null check(base_amount_cents>=0),cleaning_fee_cents bigint not null check(cleaning_fee_cents>=0),
 pricing_snapshot jsonb not null default '{}'::jsonb,rules_version text not null default '2026-09-v1',
 status text not null default 'active' check(status in ('active','expired','consumed','cancelled')),
 created_at timestamptz not null default now(),expires_at timestamptz not null,check(check_out>check_in)
);
create table if not exists public.quote_options(
 id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete cascade,
 rate_plan_id bigint not null references public.rate_plans(id),
 accommodation_amount_cents bigint not null check(accommodation_amount_cents>=0),
 cleaning_fee_cents bigint not null check(cleaning_fee_cents>=0),total_amount_cents bigint not null check(total_amount_cents>=0),
 cancellation_policy_id uuid references public.policy_documents(id),created_at timestamptz not null default now(),
 unique(quote_id,rate_plan_id)
);
create table if not exists public.quote_experience_items(
 id uuid primary key default gen_random_uuid(),quote_id uuid not null references public.quotes(id) on delete cascade,
 product_id uuid not null,variant_id uuid not null,product_name_snapshot text not null,variant_name_snapshot text not null,
 unit_price_cents bigint not null check(unit_price_cents>=0),quantity integer not null default 1 check(quantity>0),
 created_at timestamptz not null default now(),unique(quote_id,variant_id)
);

-- Reserva existente: extensões da Fase 1
alter table public.reservations add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.reservations add column if not exists quote_id uuid references public.quotes(id);
alter table public.reservations add column if not exists quote_option_id uuid references public.quote_options(id);
alter table public.reservations add column if not exists rate_plan_code text;
alter table public.reservations add column if not exists travel_purpose_code text;
alter table public.reservations add column if not exists confirmation_code text;
alter table public.reservations add column if not exists cancelled_at timestamptz;
alter table public.reservations add column if not exists confirmed_at timestamptz;
create unique index if not exists reservations_confirmation_code_key on public.reservations(confirmation_code) where confirmation_code is not null;
create index if not exists reservations_user_idx on public.reservations(user_id,created_at desc);

create table if not exists public.reservation_policy_acceptances(
 id uuid primary key default gen_random_uuid(),reservation_id uuid not null references public.reservations(id) on delete cascade,
 user_id uuid references auth.users(id) on delete set null,document_id uuid not null references public.policy_documents(id),
 document_code text not null,document_version text not null,accepted_at timestamptz not null default now(),
 unique(reservation_id,document_id)
);

-- Viagem e experiências
create table if not exists public.travel_purposes(code text primary key,label text not null,active boolean not null default true,display_order integer not null default 0);
create table if not exists public.experience_products(
 id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,description text,
 status text not null default 'draft' check(status in ('draft','active','inactive','archived')),
 minimum_lead_hours integer not null default 0 check(minimum_lead_hours>=0),daily_capacity integer,inventory integer,
 cancellation_policy_id uuid references public.policy_documents(id),travel_purposes text[] not null default '{}',
 display_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.experience_variants(
 id uuid primary key default gen_random_uuid(),product_id uuid not null references public.experience_products(id) on delete cascade,
 code text not null,name text not null,price_cents bigint not null check(price_cents>=0),active boolean not null default true,
 display_order integer not null default 0,created_at timestamptz not null default now(),unique(product_id,code)
);
create table if not exists public.experience_property_eligibility(
 product_id uuid not null references public.experience_products(id) on delete cascade,
 property_id bigint not null references public.properties(id) on delete cascade,primary key(product_id,property_id)
);
alter table public.quote_experience_items
 drop constraint if exists quote_experience_items_product_id_fkey,
 add constraint quote_experience_items_product_id_fkey foreign key(product_id) references public.experience_products(id);
alter table public.quote_experience_items
 drop constraint if exists quote_experience_items_variant_id_fkey,
 add constraint quote_experience_items_variant_id_fkey foreign key(variant_id) references public.experience_variants(id);

create table if not exists public.experience_orders(
 id uuid primary key default gen_random_uuid(),reservation_id uuid not null references public.reservations(id) on delete cascade,
 user_id uuid references auth.users(id) on delete set null,status text not null default 'pending' check(status in ('pending','active','cancelled','refunded')),
 created_at timestamptz not null default now()
);
create table if not exists public.experience_order_items(
 id uuid primary key default gen_random_uuid(),order_id uuid not null references public.experience_orders(id) on delete cascade,
 product_id uuid not null references public.experience_products(id),variant_id uuid references public.experience_variants(id),
 product_name_snapshot text not null,variant_name_snapshot text,unit_price_cents bigint not null check(unit_price_cents>=0),
 quantity integer not null default 1 check(quantity>0),status text not null default 'active' check(status in ('active','upgraded','cancelled','refunded')),
 created_at timestamptz not null default now()
);

-- Pagamentos/ledger
create table if not exists public.payment_settings(
 id smallint primary key default 1 check(id=1),active_provider text not null default 'mock',
 charge_percent integer not null default 100 check(charge_percent between 1 and 100),
 pix_expiration_minutes integer not null default 15 check(pix_expiration_minutes between 1 and 1440),
 max_card_installments integer not null default 1 check(max_card_installments between 1 and 24),
 updated_at timestamptz not null default now()
);
create table if not exists public.payments(
 id uuid primary key default gen_random_uuid(),reservation_id uuid references public.reservations(id) on delete set null,
 user_id uuid references auth.users(id) on delete set null,provider text not null,provider_payment_id text,
 method text check(method in ('pix','card','mock')),installments integer,amount_cents bigint not null check(amount_cents>=0),
 status text not null check(status in ('awaiting_payment','processing','under_review','paid','refused','cancelled','expired','refunded')),
 idempotency_key text not null unique,metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.financial_entries(
 id uuid primary key default gen_random_uuid(),reservation_id uuid references public.reservations(id) on delete set null,
 payment_id uuid references public.payments(id) on delete set null,experience_order_item_id uuid references public.experience_order_items(id) on delete set null,
 entry_type text not null check(entry_type in ('accommodation','cleaning','experience','upgrade','refund','adjustment','additional_charge','guarantee_capture')),
 amount_cents bigint not null,currency char(3) not null default 'BRL',description text,created_at timestamptz not null default now()
);

-- Garantia
create table if not exists public.guarantees(
 id uuid primary key default gen_random_uuid(),reservation_id uuid not null references public.reservations(id) on delete cascade,
 provider text,provider_authorization_id text,amount_cents bigint not null check(amount_cents>=0),
 captured_amount_cents bigint not null default 0 check(captured_amount_cents>=0),
 status text not null default 'pending' check(status in ('pending','guaranteed','released','incident_reported','capture_requested','captured','disputed','resolved')),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.incidents(
 id uuid primary key default gen_random_uuid(),guarantee_id uuid not null references public.guarantees(id) on delete cascade,
 description text not null,requested_capture_cents bigint check(requested_capture_cents>=0),
 evidence jsonb not null default '[]'::jsonb,status text not null default 'open' check(status in ('open','capture_requested','resolved','rejected')),
 created_at timestamptz not null default now(),resolved_at timestamptz
);

-- Alterações pós-reserva
create table if not exists public.modification_requests(
 id uuid primary key default gen_random_uuid(),reservation_id uuid not null references public.reservations(id) on delete cascade,
 user_id uuid references auth.users(id) on delete set null,request_type text not null check(request_type in ('dates','property')),
 requested_check_in date,requested_check_out date,requested_property_id bigint references public.properties(id),
 reference_quote_id uuid references public.quotes(id),admin_additional_amount_cents bigint,
 status text not null default 'requested' check(status in ('requested','quoted','awaiting_guest_acceptance','accepted','rejected','applied','cancelled')),
 guest_accepted_at timestamptz,applied_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 original_amount_cents bigint,reference_amount_cents bigint,admin_note text,decided_at timestamptz
);
create table if not exists public.reservation_change_events(
 id uuid primary key default gen_random_uuid(),reservation_id uuid not null references public.reservations(id) on delete cascade,
 modification_request_id uuid references public.modification_requests(id) on delete set null,
 event_type text not null check(event_type in ('requested','quoted','admin_decision','guest_accepted','additional_payment','applied','rejected','cancelled')),
 before_snapshot jsonb,after_snapshot jsonb,amount_cents bigint,actor_user_id uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now()
);

create table if not exists public.account_deletion_requests(
 id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete set null,
 status text not null default 'requested' check(status in ('requested','processing','completed','rejected')),
 requested_at timestamptz not null default now(),completed_at timestamptz
);
create table if not exists public.analytics_events(
 id bigint generated by default as identity primary key,event_name text not null,anonymous_id text,user_id uuid references auth.users(id) on delete set null,
 reservation_id uuid references public.reservations(id) on delete set null,property_id bigint references public.properties(id) on delete set null,
 metadata jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now()
);
create table if not exists public.audit_events(
 id bigint generated by default as identity primary key,actor_user_id uuid references auth.users(id) on delete set null,
 action text not null,entity_type text not null,entity_id text,old_value jsonb,new_value jsonb,created_at timestamptz not null default now()
);

-- RLS permanece obrigatório em todas as tabelas expostas.
alter table public.properties enable row level security;
alter table public.profiles enable row level security;
alter table public.reservations enable row level security;
alter table public.policy_documents enable row level security;
alter table public.rate_plans enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_options enable row level security;
alter table public.quote_experience_items enable row level security;
alter table public.reservation_policy_acceptances enable row level security;
alter table public.travel_purposes enable row level security;
alter table public.experience_products enable row level security;
alter table public.experience_variants enable row level security;
alter table public.experience_property_eligibility enable row level security;
alter table public.experience_orders enable row level security;
alter table public.experience_order_items enable row level security;
alter table public.payments enable row level security;
alter table public.financial_entries enable row level security;
alter table public.guarantees enable row level security;
alter table public.incidents enable row level security;
alter table public.modification_requests enable row level security;
alter table public.reservation_change_events enable row level security;
alter table public.account_deletion_requests enable row level security;
alter table public.analytics_events enable row level security;
alter table public.audit_events enable row level security;
alter table public.property_integrations enable row level security;
alter table public.payment_settings enable row level security;

-- As policies, funções transacionais, triggers e jobs estão versionadas no histórico
-- do projeto Supabase listado no README deste diretório. Este snapshot é deliberadamente
-- não destrutivo e serve para revisão/recuperação da estrutura da Fase 1.
