create schema if not exists extensions;
create extension if not exists btree_gist with schema public;
create extension if not exists pg_cron;
create table public.properties(
 id bigint generated by default as identity primary key,code text not null unique,name text not null,
 active boolean not null default true,cleaning_fee numeric not null default 290,max_guests integer not null default 2,
 created_at timestamptz not null default now());
create table public.reservations(
 id uuid primary key default gen_random_uuid(),property_id bigint not null references public.properties,
 check_in date not null,check_out date not null,status text not null,
 source text not null default 'direct' check(source in('direct','airbnb','booking','manual')),
 guests integer not null default 2,guest_name text,guest_email text,guest_phone text,
 accommodation_amount numeric,cleaning_fee numeric,total_amount numeric,payment_id text,hold_expires_at timestamptz,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
 constraint valid_dates check(check_out>check_in),
 constraint reservations_status_check check(status in('hold','pending_payment','confirmed','cancelled','expired')),
 constraint no_overlapping_active_reservations exclude using gist(property_id with =,daterange(check_in,check_out,'[)') with &&)
 where(status in('hold','pending_payment','confirmed')));
alter table public.properties enable row level security;
alter table public.reservations enable row level security;
insert into public.properties(code,name) values('CH1','Ville Signature'),('CH2','Ville Essenza'),('CH3','Ville Amore');

-- Historical: 20260923230511 phase1_foundation

-- Fase 1 foundation: additive, no destructive data changes.

create schema if not exists private;

-- Common timestamp helper.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Extend existing properties into a data-driven catalog.
alter table public.properties
  add column if not exists slug text,
  add column if not exists property_type text not null default 'chalet',
  add column if not exists tagline text,
  add column if not exists summary text,
  add column if not exists cover_image text,
  add column if not exists gallery jsonb not null default '[]'::jsonb,
  add column if not exists features jsonb not null default '[]'::jsonb,
  add column if not exists guarantee_amount_cents integer not null default 50000,
  add column if not exists updated_at timestamptz not null default now();

update public.properties
set slug = case code
  when 'CH1' then 'ville-signature'
  when 'CH2' then 'ville-essenza'
  when 'CH3' then 'ville-amore'
  else lower(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g'))
end
where slug is null;

update public.properties
set
  tagline = case code
    when 'CH1' then 'Piscina aquecida privativa + Spa'
    when 'CH2' then 'Hidromassagem + Deck privativo'
    when 'CH3' then 'Hidromassagem + Pergolado privativo'
    else tagline end,
  summary = case code
    when 'CH1' then 'Piscina aquecida, spa e terreno exclusivo para uma experiência completa a dois.'
    when 'CH2' then 'Hidromassagem privativa, deck só de vocês e natureza ao redor.'
    when 'CH3' then 'Madeira, luz quente, hidromassagem e pergolado privativo para dois.'
    else summary end,
  cover_image = case code
    when 'CH1' then 'assets/ch1-capa-casal-spa.webp?v=2'
    when 'CH2' then 'assets/04-banheira-petalas.webp'
    when 'CH3' then 'assets/04-experiencia-compartilhada.webp'
    else cover_image end,
  gallery = case code
    when 'CH1' then '["assets/ch1-capa-casal-spa.webp?v=2","assets/01-piscina.webp","assets/02-interior.webp","assets/03-banheiro.webp","assets/04-decoracao.webp","assets/05-spa-experiencia.webp"]'::jsonb
    when 'CH2' then '["assets/04-banheira-petalas.webp","assets/01-pergolado-dia.webp","assets/02-pergolado-noite.webp","assets/03-banheira-cama.webp","assets/05-experiencia.webp","assets/06-mesa-cozinha.webp"]'::jsonb
    when 'CH3' then '["assets/04-experiencia-compartilhada.webp","assets/01-cantinho-cafe.webp","assets/02-lavabo-led.webp","assets/03-banheira-petalas-compartilhada.webp","assets/05-mesa-cozinha.webp","assets/experiencia-vinho-deck-1.webp"]'::jsonb
    else gallery end,
  features = case code
    when 'CH1' then '["Piscina aquecida","Spa","Terreno exclusivo","2 hóspedes"]'::jsonb
    when 'CH2' then '["Hidromassagem","Deck privativo","2 hóspedes"]'::jsonb
    when 'CH3' then '["Hidromassagem","Pergolado privativo","2 hóspedes"]'::jsonb
    else features end;

create unique index if not exists properties_slug_key on public.properties(slug);

drop trigger if exists properties_set_updated_at on public.properties;
create trigger properties_set_updated_at before update on public.properties
for each row execute function public.set_updated_at();

-- Provider/integration metadata. Secrets themselves remain server-side.
create table if not exists public.property_integrations (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  provider text not null check (provider in ('pricelabs','airbnb','booking')),
  external_listing_id text,
  pms text,
  environment_key text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(property_id, provider)
);

insert into public.property_integrations(property_id,provider,external_listing_id,pms,environment_key)
select id,'pricelabs',
  case code
    when 'CH1' then '1526341230074666349'
    when 'CH2' then '1547126637360310141'
    when 'CH3' then '1745999870058886727'
  end,
  'airbnb',
  null
from public.properties
where code in ('CH1','CH2','CH3')
on conflict(property_id,provider) do update set
 external_listing_id=excluded.external_listing_id,pms=excluded.pms,active=true;

insert into public.property_integrations(property_id,provider,external_listing_id,pms,environment_key)
select id,'airbnb',null,null,'ICAL_AIRBNB_'||code
from public.properties
where code in ('CH1','CH2','CH3')
on conflict(property_id,provider) do update set
 environment_key=excluded.environment_key,active=true;

drop trigger if exists property_integrations_set_updated_at on public.property_integrations;
create trigger property_integrations_set_updated_at before update on public.property_integrations
for each row execute function public.set_updated_at();

-- Auth profiles and roles.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'guest' check (role in ('guest','admin','host','staff','service_provider')),
  full_name text,
  phone text,
  marketing_consent boolean not null default false,
  deletion_requested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles(id,full_name,phone)
  values(new.id,new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'phone')
  on conflict(id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles where id=(select auth.uid()) and role='admin');
$$;

-- Versioned policies / terms.
create table if not exists public.policy_documents (
  id uuid primary key default gen_random_uuid(),
  document_type text not null check (document_type in ('hosting_terms','cancellation_policy','property_rules','privacy_policy')),
  code text not null,
  version text not null,
  title text not null,
  body text not null,
  status text not null default 'draft' check (status in ('draft','active','archived')),
  effective_at timestamptz,
  created_at timestamptz not null default now(),
  unique(code,version)
);

-- User-approved cancellation rules, versioned.
insert into public.policy_documents(document_type,code,version,title,body,status,effective_at)
values
('cancellation_policy','refundable_v1','1.0','Tarifa reembolsável',
 'Cancelamento gratuito durante as primeiras 24 horas após a contratação, observadas as regras aplicáveis. Após essa janela inicial, há reembolso integral para cancelamentos realizados até 20 dias antes do check-in.',
 'active',now()),
('cancellation_policy','non_refundable_v1','1.0','Tarifa não reembolsável',
 'Cancelamento gratuito durante as primeiras 24 horas após a contratação, observadas as regras aplicáveis. Após essa janela inicial de 24 horas, não há reembolso por cancelamento.',
 'active',now()),
('hosting_terms','hosting_terms_draft','0.1','Termos de Hospedagem — rascunho de desenvolvimento',
 'Documento em desenvolvimento. O conteúdo jurídico final deverá ser aprovado antes do GO-LIVE.',
 'draft',null),
('property_rules','property_rules_draft','0.1','Regras da Propriedade — rascunho de desenvolvimento',
 'Documento em desenvolvimento. As regras finais por propriedade serão apresentadas antes do GO-LIVE.',
 'draft',null),
('privacy_policy','privacy_policy_draft','0.1','Política de Privacidade — rascunho de desenvolvimento',
 'Documento em desenvolvimento. O conteúdo final de privacidade/LGPD deverá ser aprovado antes do GO-LIVE.',
 'draft',null)
on conflict(code,version) do nothing;

-- Configurable rate plans. Amounts are always calculated server-side.
create table if not exists public.rate_plans (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  multiplier_bps integer not null check (multiplier_bps > 0),
  selectable boolean not null default true,
  cancellation_policy_id uuid references public.policy_documents(id),
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

insert into public.rate_plans(code,name,multiplier_bps,selectable,cancellation_policy_id,display_order)
select 'reference','Referência',12800,false,null,0
where not exists(select 1 from public.rate_plans where code='reference');

insert into public.rate_plans(code,name,multiplier_bps,selectable,cancellation_policy_id,display_order)
select 'refundable','Reembolsável',12000,true,id,10
from public.policy_documents
where code='refundable_v1' and version='1.0'
on conflict(code) do update set multiplier_bps=excluded.multiplier_bps,cancellation_policy_id=excluded.cancellation_policy_id,active=true;

insert into public.rate_plans(code,name,multiplier_bps,selectable,cancellation_policy_id,display_order)
select 'non_refundable','Não reembolsável',11000,true,id,20
from public.policy_documents
where code='non_refundable_v1' and version='1.0'
on conflict(code) do update set multiplier_bps=excluded.multiplier_bps,cancellation_policy_id=excluded.cancellation_policy_id,active=true;

-- Server-side price quotes; no inventory lock.
create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  property_id bigint not null references public.properties(id),
  user_id uuid references auth.users(id) on delete set null,
  client_token_hash text not null,
  check_in date not null,
  check_out date not null,
  guests integer not null check (guests > 0),
  base_amount_cents bigint not null check (base_amount_cents >= 0),
  cleaning_fee_cents bigint not null check (cleaning_fee_cents >= 0),
  pricing_snapshot jsonb not null default '{}'::jsonb,
  rules_version text not null default '2026-09-v1',
  status text not null default 'active' check(status in ('active','expired','consumed','cancelled')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  check (check_out > check_in)
);
create index if not exists quotes_expires_idx on public.quotes(expires_at);
create index if not exists quotes_user_idx on public.quotes(user_id,created_at desc);

create table if not exists public.quote_options (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  rate_plan_id bigint not null references public.rate_plans(id),
  accommodation_amount_cents bigint not null check(accommodation_amount_cents >= 0),
  cleaning_fee_cents bigint not null check(cleaning_fee_cents >= 0),
  total_amount_cents bigint not null check(total_amount_cents >= 0),
  cancellation_policy_id uuid references public.policy_documents(id),
  created_at timestamptz not null default now(),
  unique(quote_id,rate_plan_id)
);

-- Extend existing reservations without rewriting history.
alter table public.reservations
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists quote_id uuid references public.quotes(id),
  add column if not exists quote_option_id uuid references public.quote_options(id),
  add column if not exists rate_plan_code text,
  add column if not exists travel_purpose_code text,
  add column if not exists confirmation_code text,
  add column if not exists cancelled_at timestamptz,
  add column if not exists confirmed_at timestamptz;

create unique index if not exists reservations_confirmation_code_key
on public.reservations(confirmation_code) where confirmation_code is not null;
create index if not exists reservations_user_idx on public.reservations(user_id,created_at desc);

-- Acceptance records preserve document/version history.
create table if not exists public.reservation_policy_acceptances (
  id uuid primary key default gen_random_uuid(),
  reservation_id uuid not null references public.reservations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  document_id uuid not null references public.policy_documents(id),
  document_code text not null,
  document_version text not null,
  accepted_at timestamptz not null default now(),
  unique(reservation_id,document_id)
);

-- Configurable trip purpose taxonomy.
create table if not exists public.travel_purposes (
  code text primary key,
  label text not null,
  active boolean not null default true,
  display_order integer not null default 0
);
insert into public.travel_purposes(code,label,display_order) values
('vacation','Férias',10),('honeymoon','Lua de mel',20),('birthday','Aniversário',30),
('romantic','Romântico',40),('rest','Descanso',50),('beach','Praia',60)
on conflict(code) do nothing;

-- Experience catalog and variants.
create table if not exists public.experience_products (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  status text not null default 'draft' check(status in ('draft','active','inactive','archived')),
  minimum_lead_hours integer not null default 0 check(minimum_lead_hours >= 0),
  daily_capacity integer,
  inventory integer,
  cancellation_policy_id uuid references public.policy_documents(id),
  travel_purposes text[] not null default '{}',
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.experience_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.experience_products(id) on delete cascade,
  code text not null,
  name text not null,
  price_cents bigint not null check(price_cents >= 0),
  active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(product_id,code)
);

create table if not exists public.experience_property_eligibility (
  product_id uuid not null references public.experience_products(id) on delete cascade,
  property_id bigint not null references public.properties(id) on delete cascade,
  primary key(product_id,property_id)
);

drop trigger if exists experience_products_set_updated_at on public.experience_products;
create trigger experience_products_set_updated_at before update on public.experience_products
for each row execute function public.set_updated_at();

-- Reservation-linked experience orders preserve history.
create table if not exists public.experience_orders (
  id uuid primary key default gen_random_uuid(),
  reservation_id uuid not null references public.reservations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'pending' check(status in ('pending','active','cancelled','refunded')),
  created_at timestamptz not null default now()
);
create table if not exists public.experience_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.experience_orders(id) on delete cascade,
  product_id uuid not null references public.experience_products(id),
  variant_id uuid references public.experience_variants(id),
  product_name_snapshot text not null,
  variant_name_snapshot text,
  unit_price_cents bigint not null check(unit_price_cents >= 0),
  quantity integer not null default 1 check(quantity > 0),
  status text not null default 'active' check(status in ('active','upgraded','cancelled','refunded')),
  created_at timestamptz not null default now()
);

-- Gateway-independent payments.
create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  reservation_id uuid references public.reservations(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  provider text not null,
  provider_payment_id text,
  method text check(method in ('pix','card','mock')),
  installments integer,
  amount_cents bigint not null check(amount_cents >= 0),
  status text not null check(status in ('awaiting_payment','processing','under_review','paid','refused','cancelled','expired','refunded')),
  idempotency_key text not null unique,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists payments_set_updated_at on public.payments;
create trigger payments_set_updated_at before update on public.payments
for each row execute function public.set_updated_at();

-- Financial ledger uses integer cents; historical entries are append-only at application level.
create table if not exists public.financial_entries (
  id uuid primary key default gen_random_uuid(),
  reservation_id uuid references public.reservations(id) on delete set null,
  payment_id uuid references public.payments(id) on delete set null,
  experience_order_item_id uuid references public.experience_order_items(id) on delete set null,
  entry_type text not null check(entry_type in ('accommodation','cleaning','experience','upgrade','refund','adjustment','additional_charge','guarantee_capture')),
  amount_cents bigint not null,
  currency char(3) not null default 'BRL',
  description text,
  created_at timestamptz not null default now()
);
create index if not exists financial_entries_reservation_idx on public.financial_entries(reservation_id,created_at);

-- Hospitality guarantee / incident architecture.
create table if not exists public.guarantees (
  id uuid primary key default gen_random_uuid(),
  reservation_id uuid not null references public.reservations(id) on delete cascade,
  provider text,
  provider_authorization_id text,
  amount_cents bigint not null check(amount_cents >= 0),
  captured_amount_cents bigint not null default 0 check(captured_amount_cents >= 0),
  status text not null default 'pending' check(status in ('pending','guaranteed','released','incident_reported','capture_requested','captured','disputed','resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists guarantees_set_updated_at on public.guarantees;
create trigger guarantees_set_updated_at before update on public.guarantees
for each row execute function public.set_updated_at();

create table if not exists public.incidents (
  id uuid primary key default gen_random_uuid(),
  guarantee_id uuid not null references public.guarantees(id) on delete cascade,
  description text not null,
  requested_capture_cents bigint check(requested_capture_cents >= 0),
  evidence jsonb not null default '[]'::jsonb,
  status text not null default 'open' check(status in ('open','capture_requested','resolved','rejected')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

-- Guest-requested booking changes.
create table if not exists public.modification_requests (
  id uuid primary key default gen_random_uuid(),
  reservation_id uuid not null references public.reservations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  request_type text not null check(request_type in ('dates','property')),
  requested_check_in date,
  requested_check_out date,
  requested_property_id bigint references public.properties(id),
  reference_quote_id uuid references public.quotes(id),
  admin_additional_amount_cents bigint,
  status text not null default 'requested' check(status in ('requested','quoted','awaiting_guest_acceptance','accepted','rejected','applied','cancelled')),
  guest_accepted_at timestamptz,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
drop trigger if exists modification_requests_set_updated_at on public.modification_requests;
create trigger modification_requests_set_updated_at before update on public.modification_requests
for each row execute function public.set_updated_at();

-- Account deletion requests keep a compliance trail.
create table if not exists public.account_deletion_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  status text not null default 'requested' check(status in ('requested','processing','completed','rejected')),
  requested_at timestamptz not null default now(),
  completed_at timestamptz
);

-- Analytics event sink; no unnecessary PII.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  anonymous_id text,
  user_id uuid references auth.users(id) on delete set null,
  reservation_id uuid references public.reservations(id) on delete set null,
  property_id bigint references public.properties(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);
create index if not exists analytics_events_name_time_idx on public.analytics_events(event_name,occurred_at desc);

-- Audit events.
create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  old_value jsonb,
  new_value jsonb,
  created_at timestamptz not null default now()
);

-- Expire stale payment holds before any new blocking operation.
create or replace function public.expire_stale_reservations()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare v_count integer;
begin
  update public.reservations
     set status='expired', updated_at=now()
   where status in ('hold','pending_payment')
     and hold_expires_at is not null
     and hold_expires_at <= now();
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- Transactional direct-booking hold. Only called after payment starts.
create or replace function public.start_payment_hold(
  p_quote_id uuid,
  p_quote_option_id uuid,
  p_user_id uuid,
  p_guest_name text,
  p_guest_email text,
  p_guest_phone text,
  p_guests integer
)
returns table(reservation_id uuid, confirmation_code text, hold_expires_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  q public.quotes%rowtype;
  o public.quote_options%rowtype;
  v_id uuid;
  v_code text;
  v_expires timestamptz;
begin
  perform public.expire_stale_reservations();

  select * into q from public.quotes
   where id=p_quote_id and status='active' and expires_at>now()
   for update;
  if not found then raise exception 'quote_expired'; end if;

  select * into o from public.quote_options
   where id=p_quote_option_id and quote_id=q.id;
  if not found then raise exception 'invalid_quote_option'; end if;

  v_code := upper(substr(replace(gen_random_uuid()::text,'-',''),1,10));
  v_expires := now() + interval '15 minutes';

  insert into public.reservations(
    property_id,check_in,check_out,status,source,guests,guest_name,guest_email,guest_phone,
    accommodation_amount,cleaning_fee,total_amount,hold_expires_at,user_id,quote_id,quote_option_id,
    rate_plan_code,confirmation_code
  )
  select q.property_id,q.check_in,q.check_out,'pending_payment','direct',p_guests,p_guest_name,p_guest_email,p_guest_phone,
    o.accommodation_amount_cents/100.0,o.cleaning_fee_cents/100.0,o.total_amount_cents/100.0,v_expires,p_user_id,q.id,o.id,
    rp.code,v_code
  from public.rate_plans rp where rp.id=o.rate_plan_id
  returning id into v_id;

  update public.quotes set status='consumed' where id=q.id;

  return query select v_id,v_code,v_expires;
exception
  when exclusion_violation then
    raise exception 'dates_unavailable';
end;
$$;

revoke all on function public.expire_stale_reservations() from public,anon,authenticated;
grant execute on function public.expire_stale_reservations() to service_role;
revoke all on function public.start_payment_hold(uuid,uuid,uuid,text,text,text,integer) from public,anon,authenticated;
grant execute on function public.start_payment_hold(uuid,uuid,uuid,text,text,text,integer) to service_role;

-- RLS.
alter table public.properties enable row level security;
alter table public.property_integrations enable row level security;
alter table public.profiles enable row level security;
alter table public.policy_documents enable row level security;
alter table public.rate_plans enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_options enable row level security;
alter table public.reservations enable row level security;
alter table public.reservation_policy_acceptances enable row level security;
alter table public.travel_purposes enable row level security;
alter table public.experience_products enable row level security;
alter table public.experience_variants enable row level security;
alter table public.experience_property_eligibility enable row level security;
alter table public.experience_orders enable row level security;
alter table public.experience_order_items enable row level security;
alter table public.payments enable row level security;
alter table public.financial_entries enable row level security;
alter table public.guarantees enable row level security;
alter table public.incidents enable row level security;
alter table public.modification_requests enable row level security;
alter table public.account_deletion_requests enable row level security;
alter table public.analytics_events enable row level security;
alter table public.audit_events enable row level security;

-- Drop only project policies with our controlled names, making migration rerunnable.
drop policy if exists "properties_public_read" on public.properties;
create policy "properties_public_read" on public.properties for select to anon,authenticated using(active);

drop policy if exists "profiles_self_read" on public.profiles;
create policy "profiles_self_read" on public.profiles for select to authenticated using(id=(select auth.uid()) or public.current_user_is_admin());
drop policy if exists "profiles_self_update" on public.profiles;
create policy "profiles_self_update" on public.profiles for update to authenticated
using(id=(select auth.uid()) or public.current_user_is_admin())
with check(id=(select auth.uid()) or public.current_user_is_admin());

drop policy if exists "policies_active_read" on public.policy_documents;
create policy "policies_active_read" on public.policy_documents for select to anon,authenticated using(status='active' or public.current_user_is_admin());

drop policy if exists "rate_plans_public_read" on public.rate_plans;
create policy "rate_plans_public_read" on public.rate_plans for select to anon,authenticated using(active);

drop policy if exists "travel_purposes_public_read" on public.travel_purposes;
create policy "travel_purposes_public_read" on public.travel_purposes for select to anon,authenticated using(active);

drop policy if exists "experiences_public_read" on public.experience_products;
create policy "experiences_public_read" on public.experience_products for select to anon,authenticated using(status='active' or public.current_user_is_admin());
drop policy if exists "experience_variants_public_read" on public.experience_variants;
create policy "experience_variants_public_read" on public.experience_variants for select to anon,authenticated
using(active and exists(select 1 from public.experience_products p where p.id=product_id and p.status='active'));
drop policy if exists "experience_eligibility_public_read" on public.experience_property_eligibility;
create policy "experience_eligibility_public_read" on public.experience_property_eligibility for select to anon,authenticated using(true);

drop policy if exists "reservations_own_read" on public.reservations;
create policy "reservations_own_read" on public.reservations for select to authenticated
using(user_id=(select auth.uid()) or public.current_user_is_admin());

drop policy if exists "acceptances_own_read" on public.reservation_policy_acceptances;
create policy "acceptances_own_read" on public.reservation_policy_acceptances for select to authenticated
using(user_id=(select auth.uid()) or public.current_user_is_admin());

drop policy if exists "experience_orders_own_read" on public.experience_orders;
create policy "experience_orders_own_read" on public.experience_orders for select to authenticated
using(user_id=(select auth.uid()) or public.current_user_is_admin());
drop policy if exists "experience_items_own_read" on public.experience_order_items;
create policy "experience_items_own_read" on public.experience_order_items for select to authenticated
using(exists(select 1 from public.experience_orders o where o.id=order_id and (o.user_id=(select auth.uid()) or public.current_user_is_admin())));

drop policy if exists "payments_own_read" on public.payments;
create policy "payments_own_read" on public.payments for select to authenticated
using(user_id=(select auth.uid()) or public.current_user_is_admin());

drop policy if exists "ledger_own_read" on public.financial_entries;
create policy "ledger_own_read" on public.financial_entries for select to authenticated
using(exists(select 1 from public.reservations r where r.id=reservation_id and (r.user_id=(select auth.uid()) or public.current_user_is_admin())));

drop policy if exists "guarantees_own_read" on public.guarantees;
create policy "guarantees_own_read" on public.guarantees for select to authenticated
using(exists(select 1 from public.reservations r where r.id=reservation_id and (r.user_id=(select auth.uid()) or public.current_user_is_admin())));

drop policy if exists "incidents_own_read" on public.incidents;
create policy "incidents_own_read" on public.incidents for select to authenticated
using(exists(select 1 from public.guarantees g join public.reservations r on r.id=g.reservation_id
            where g.id=guarantee_id and (r.user_id=(select auth.uid()) or public.current_user_is_admin())));

drop policy if exists "modifications_own_read" on public.modification_requests;
create policy "modifications_own_read" on public.modification_requests for select to authenticated
using(user_id=(select auth.uid()) or public.current_user_is_admin());
drop policy if exists "modifications_own_insert" on public.modification_requests;
create policy "modifications_own_insert" on public.modification_requests for insert to authenticated
with check(user_id=(select auth.uid()));

drop policy if exists "deletion_requests_own_read" on public.account_deletion_requests;
create policy "deletion_requests_own_read" on public.account_deletion_requests for select to authenticated
using(user_id=(select auth.uid()) or public.current_user_is_admin());
drop policy if exists "deletion_requests_own_insert" on public.account_deletion_requests;
create policy "deletion_requests_own_insert" on public.account_deletion_requests for insert to authenticated
with check(user_id=(select auth.uid()));

-- No direct client access to internal server-side tables.
-- service_role bypasses RLS; anon/authenticated receive only explicit policies above.

-- Explicit grants for client-readable tables.
grant select on public.properties,public.policy_documents,public.rate_plans,public.travel_purposes,
  public.experience_products,public.experience_variants,public.experience_property_eligibility to anon,authenticated;
grant select,update on public.profiles to authenticated;
grant select on public.reservations,public.reservation_policy_acceptances,public.experience_orders,
  public.experience_order_items,public.payments,public.financial_entries,public.guarantees,public.incidents,
  public.modification_requests,public.account_deletion_requests to authenticated;
grant insert on public.modification_requests,public.account_deletion_requests to authenticated;

-- Block direct access to server-only internals.
revoke all on public.property_integrations,public.quotes,public.quote_options,public.analytics_events,public.audit_events from anon,authenticated;

-- Historical: 20260923230605 phase1_foundation_hardening

-- Harden security-definer functions.
revoke all on function public.handle_new_user() from public,anon,authenticated;
revoke all on function public.current_user_is_admin() from public,anon,authenticated;
grant execute on function public.current_user_is_admin() to authenticated,service_role;

-- Explicitly revoke server-only table privileges.
revoke all on public.property_integrations,public.quotes,public.quote_options,public.analytics_events,public.audit_events from anon,authenticated;

-- Cover frequent foreign keys and guest-area queries.
create index if not exists reservations_quote_idx on public.reservations(quote_id);
create index if not exists reservations_quote_option_idx on public.reservations(quote_option_id);
create index if not exists quote_options_rate_plan_idx on public.quote_options(rate_plan_id);
create index if not exists quote_options_policy_idx on public.quote_options(cancellation_policy_id);
create index if not exists rate_plans_policy_idx on public.rate_plans(cancellation_policy_id);
create index if not exists payments_reservation_idx on public.payments(reservation_id);
create index if not exists payments_user_idx on public.payments(user_id);
create index if not exists guarantees_reservation_idx on public.guarantees(reservation_id);
create index if not exists incidents_guarantee_idx on public.incidents(guarantee_id);
create index if not exists experience_orders_reservation_idx on public.experience_orders(reservation_id);
create index if not exists experience_orders_user_idx on public.experience_orders(user_id);
create index if not exists experience_order_items_order_idx on public.experience_order_items(order_id);
create index if not exists modification_requests_reservation_idx on public.modification_requests(reservation_id);
create index if not exists modification_requests_user_idx on public.modification_requests(user_id);
create index if not exists account_deletion_requests_user_idx on public.account_deletion_requests(user_id);
create index if not exists acceptances_user_idx on public.reservation_policy_acceptances(user_id);
create index if not exists acceptances_document_idx on public.reservation_policy_acceptances(document_id);
create index if not exists experience_eligibility_property_idx on public.experience_property_eligibility(property_id);

-- Historical: 20260923230736 phase1_quote_experiences

create table if not exists public.quote_experience_items (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  product_id uuid not null references public.experience_products(id),
  variant_id uuid not null references public.experience_variants(id),
  product_name_snapshot text not null,
  variant_name_snapshot text not null,
  unit_price_cents bigint not null check(unit_price_cents >= 0),
  quantity integer not null default 1 check(quantity > 0),
  created_at timestamptz not null default now(),
  unique(quote_id,variant_id)
);
alter table public.quote_experience_items enable row level security;
revoke all on public.quote_experience_items from anon,authenticated;
create index if not exists quote_experience_items_quote_idx on public.quote_experience_items(quote_id);

-- DEV-only catalog records: draft status means they are never offered by production/public rules.
insert into public.experience_products(code,name,description,status,minimum_lead_hours,travel_purposes,display_order)
values
('dev_romantic','[DEV] Experiência romântica','Item de teste do funil. Não publicar.','draft',24,array['romantic','honeymoon','birthday'],10),
('dev_breakfast','[DEV] Café da manhã','Item de teste do funil. Não publicar.','draft',12,array['vacation','rest','romantic'],20)
on conflict(code) do nothing;

insert into public.experience_variants(product_id,code,name,price_cents,display_order)
select id,'essential','Essencial',100,10 from public.experience_products where code='dev_romantic'
on conflict(product_id,code) do nothing;
insert into public.experience_variants(product_id,code,name,price_cents,display_order)
select id,'comfort','Comfort',150,20 from public.experience_products where code='dev_romantic'
on conflict(product_id,code) do nothing;
insert into public.experience_variants(product_id,code,name,price_cents,display_order)
select id,'test','Teste',100,10 from public.experience_products where code='dev_breakfast'
on conflict(product_id,code) do nothing;

insert into public.experience_property_eligibility(product_id,property_id)
select ep.id,p.id from public.experience_products ep cross join public.properties p
where ep.code in ('dev_romantic','dev_breakfast')
on conflict do nothing;

-- Historical: 20260923230825 phase1_payment_settings

create table if not exists public.payment_settings (
  id smallint primary key default 1 check(id=1),
  active_provider text not null default 'mock',
  charge_percent integer not null default 100 check(charge_percent between 1 and 100),
  pix_expiration_minutes integer not null default 15 check(pix_expiration_minutes between 1 and 1440),
  max_card_installments integer not null default 1 check(max_card_installments between 1 and 24),
  updated_at timestamptz not null default now()
);
insert into public.payment_settings(id,active_provider,charge_percent,pix_expiration_minutes,max_card_installments)
values(1,'mock',100,15,1)
on conflict(id) do nothing;
alter table public.payment_settings enable row level security;
revoke all on public.payment_settings from anon,authenticated;
drop trigger if exists payment_settings_set_updated_at on public.payment_settings;
create trigger payment_settings_set_updated_at before update on public.payment_settings
for each row execute function public.set_updated_at();

-- Historical: 20260923231619 enable_pg_net_for_internal_qa
create extension if not exists pg_net with schema extensions;
-- Historical: 20260923231817 grant_service_role_phase1

grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;
grant execute on all functions in schema public to service_role;

alter default privileges for role postgres in schema public
grant all privileges on tables to service_role;
alter default privileges for role postgres in schema public
grant all privileges on sequences to service_role;
alter default privileges for role postgres in schema public
grant execute on functions to service_role;

-- Historical: 20260923232040 schedule_hold_expiration

create extension if not exists pg_cron;
do $$
declare j bigint;
begin
  for j in select jobid from cron.job where jobname='expire-stale-reservations' loop
    perform cron.unschedule(j);
  end loop;
  perform cron.schedule('expire-stale-reservations','*/5 * * * *','select public.expire_stale_reservations();');
end $$;

-- Historical: 20260923232247 move_btree_gist_extension
create schema if not exists extensions; alter extension btree_gist set schema extensions;
-- Historical: 20260923232327 move_admin_helper_private

create or replace function private.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.profiles where id=(select auth.uid()) and role='admin');
$$;
revoke all on function private.current_user_is_admin() from public,anon;
grant execute on function private.current_user_is_admin() to authenticated,service_role;

drop policy if exists "profiles_self_read" on public.profiles;
create policy "profiles_self_read" on public.profiles for select to authenticated using(id=(select auth.uid()) or private.current_user_is_admin());
drop policy if exists "profiles_self_update" on public.profiles;
create policy "profiles_self_update" on public.profiles for update to authenticated
using(id=(select auth.uid()) or private.current_user_is_admin())
with check(id=(select auth.uid()) or private.current_user_is_admin());

drop policy if exists "policies_active_read" on public.policy_documents;
create policy "policies_active_read" on public.policy_documents for select to anon,authenticated using(status='active' or private.current_user_is_admin());

drop policy if exists "experiences_public_read" on public.experience_products;
create policy "experiences_public_read" on public.experience_products for select to anon,authenticated using(status='active' or private.current_user_is_admin());

drop policy if exists "reservations_own_read" on public.reservations;
create policy "reservations_own_read" on public.reservations for select to authenticated
using(user_id=(select auth.uid()) or private.current_user_is_admin());

drop policy if exists "acceptances_own_read" on public.reservation_policy_acceptances;
create policy "acceptances_own_read" on public.reservation_policy_acceptances for select to authenticated
using(user_id=(select auth.uid()) or private.current_user_is_admin());

drop policy if exists "experience_orders_own_read" on public.experience_orders;
create policy "experience_orders_own_read" on public.experience_orders for select to authenticated
using(user_id=(select auth.uid()) or private.current_user_is_admin());

drop policy if exists "experience_items_own_read" on public.experience_order_items;
create policy "experience_items_own_read" on public.experience_order_items for select to authenticated
using(exists(select 1 from public.experience_orders o where o.id=order_id and (o.user_id=(select auth.uid()) or private.current_user_is_admin())));

drop policy if exists "payments_own_read" on public.payments;
create policy "payments_own_read" on public.payments for select to authenticated
using(user_id=(select auth.uid()) or private.current_user_is_admin());

drop policy if exists "ledger_own_read" on public.financial_entries;
create policy "ledger_own_read" on public.financial_entries for select to authenticated
using(exists(select 1 from public.reservations r where r.id=reservation_id and (r.user_id=(select auth.uid()) or private.current_user_is_admin())));

drop policy if exists "guarantees_own_read" on public.guarantees;
create policy "guarantees_own_read" on public.guarantees for select to authenticated
using(exists(select 1 from public.reservations r where r.id=reservation_id and (r.user_id=(select auth.uid()) or private.current_user_is_admin())));

drop policy if exists "incidents_own_read" on public.incidents;
create policy "incidents_own_read" on public.incidents for select to authenticated
using(exists(select 1 from public.guarantees g join public.reservations r on r.id=g.reservation_id
            where g.id=guarantee_id and (r.user_id=(select auth.uid()) or private.current_user_is_admin())));

drop policy if exists "modifications_own_read" on public.modification_requests;
create policy "modifications_own_read" on public.modification_requests for select to authenticated
using(user_id=(select auth.uid()) or private.current_user_is_admin());

drop policy if exists "deletion_requests_own_read" on public.account_deletion_requests;
create policy "deletion_requests_own_read" on public.account_deletion_requests for select to authenticated
using(user_id=(select auth.uid()) or private.current_user_is_admin());

drop function if exists public.current_user_is_admin();

-- Historical: 20260923232417 phase1_post_booking_history

alter table public.modification_requests
  add column if not exists original_amount_cents bigint,
  add column if not exists reference_amount_cents bigint,
  add column if not exists admin_note text,
  add column if not exists decided_at timestamptz;

create table if not exists public.reservation_change_events (
  id uuid primary key default gen_random_uuid(),
  reservation_id uuid not null references public.reservations(id) on delete cascade,
  modification_request_id uuid references public.modification_requests(id) on delete set null,
  event_type text not null check(event_type in ('requested','quoted','admin_decision','guest_accepted','additional_payment','applied','rejected','cancelled')),
  before_snapshot jsonb,
  after_snapshot jsonb,
  amount_cents bigint,
  actor_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists reservation_change_events_reservation_idx on public.reservation_change_events(reservation_id,created_at);
alter table public.reservation_change_events enable row level security;
drop policy if exists "reservation_changes_own_read" on public.reservation_change_events;
create policy "reservation_changes_own_read" on public.reservation_change_events for select to authenticated
using(exists(select 1 from public.reservations r where r.id=reservation_id and (r.user_id=(select auth.uid()) or private.current_user_is_admin())));
grant select on public.reservation_change_events to authenticated;
grant all on public.reservation_change_events to service_role;

