const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export default async function handler(req,res){
 const host=String(req.headers.host||'');if(req.method!=='GET'||process.env.VERCEL_ENV!=='preview'||!(host==='chalezinho-ville-git-feature-romantic-fdde70-roldneicosta-4140.vercel.app'||/^chalezinho-ville-[a-z0-9]{9}-roldneicosta-4140\.vercel\.app$/.test(host)))return res.status(404).end();
 const input=new URL(req.url,'https://'+host),q=input.searchParams,id=q.get('villegram'),code=q.get('chalet');
 if(!/^[a-f0-9-]{36}$/i.test(id||'')||!/^[A-Z0-9_-]{1,32}$/.test(code||''))return res.status(400).end('Link inválido');
 const safe=new URLSearchParams({villegram:id,chalet:code});for(const field of ['check_in','check_out'])if(/^\d{4}-\d{2}-\d{2}$/.test(q.get(field)||''))safe.set(field,q.get(field));
 const target='/index.html?'+safe;let title='Villegram · Chalezinho Ville',description='Conheça a experiência e consulte as datas disponíveis.',image='/assets/hero-signature.webp';
 try{const endpoint='https://pxfqmnhqodqyaaqeyjgr.supabase.co/functions/v1/booking-engine';const headers={'X-Chalezinho-Env':'development',Origin:'https://'+host};const [catalog,media]=await Promise.all(['stay_offers','property_media'].map(async action=>{const r=await fetch(endpoint+'?action='+action,{headers,signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('unavailable');return r.json()}));const offer=catalog.offers.find(o=>o.id===id),property=media.properties.find(p=>p.code===code);if(offer&&property&&offer.property_ids.includes(property.id)){title=offer.name+' · '+property.name;description=offer.villegram?.title||offer.description;image=offer.villegram?.photos?.find(p=>p.property_id===property.id)?.url||property.cover_image;if(safe.get('check_in'))description+=' · '+safe.get('check_in')+' a '+safe.get('check_out')+'. Preço e disponibilidade sujeitos à nova consulta.'}}catch{res.setHeader('Cache-Control','no-store')}
 const absolute=new URL(image,'https://'+host+'/').href;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('X-Robots-Tag','noindex');res.status(200).send(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${esc(title)}</title><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${esc(absolute)}"><meta property="og:type" content="website"><meta name="twitter:card" content="summary_large_image"><meta http-equiv="refresh" content="0;url=${esc(target)}"></head><body><a href="${esc(target)}">Abrir esta experiência no Villegram</a></body></html>`);
}
